### ISSUE TITLE
How to search in multiple stores ?

### ISSUE THREAD

**Issue by ahmedfekry** [algolia/algoliasearch-magento#1004]
I have a 2 stores one in English and One in Arabic, how to search in both Arabic and English if i am in English store and vice versa.

**Comment by tomekjordan** [comment]
you need to change website and search in desired store. if Algolia would show results from many websites/stores - searching would be totally irrelevant - different products, different languages. so there is no option to mix it together. and it should stay as IS. which is correct for 99.9999% stores and users

**Comment by damcou** [comment]
Hi, I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
