### ISSUE TITLE
Prevent searching for default "Search for products, categories, ..." phrase

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#1007]
HI. I see many times users are submitting "Search for products, categories, ..." phrase. As this is default "placeholder" for search field - its probably by accidental on mobile or something.

Is there any option to block such behavior where in the script? maybe this is related to touch mode on mobile.

thanks
Tomek

**Comment by JanPetr** [comment]
Hello Tomek,

no, there is no option to prevent that.
I'll take a look on this issue and let you know. Thanks for bringing it up!

**Comment by damcou** [comment]
Added to the features list in our roadmap.
