### ISSUE TITLE
products not indexed

### ISSUE THREAD

**Issue by fyov** [algolia/algoliasearch-magento#1013]
I just installed algolia and the problems is that it does not index the products. Also, only some categories are indexed. Is there a solution?

**Comment by steveperrycreative** [comment]
@fyov I was having the same issue with v1.13. Try the steps [here](https://community.algolia.com/magento/doc/faq-support-data/). If that doesn't work (which it didn't for me) then try truncating your algoliasearch_queue table in the database (back-up first) and then re-build your indexes. That last step worked for me.

**Comment by steveperrycreative** [comment]
This is still an issue, see: https://discourse.algolia.com/t/magento-index-queue-not-running/

**Comment by damcou** [comment]
Hi @fyov , I don't know if you have still the issue. I'll close this ticket but feel free to create a topic on our [discourse forum](https://discourse.algolia.com/tags/magento) if you're still experiencing it.
