### ISSUE TITLE
saving configuration return 404 @custom

### ISSUE THREAD

**Issue by egyprotech** [algolia/algoliasearch-magento#1017]
When ever we try to save the configuration and redirect domain/@custom 404 page

**Comment by JanPetr** [comment]
Hello @egyprotech,
can you check your logs to see if it logs any errors during the configuration save?

**Comment by egyprotech** [comment]
Yes I checked the system.log, but there is nothing related to algolia
configuration save, please note that it was working before.
ᐧ

**Comment by damcou** [comment]
Hi, I don't know if you have still the issue. I'll close this ticket but feel free to create a topic on our [discourse forum](https://discourse.algolia.com/tags/magento) if you're still experiencing it.
