### ISSUE TITLE
ClickAnalytics support?

### ISSUE THREAD

**Issue by bmartus** [algolia/algoliasearch-magento#1018]
Are there any plans to add Click Analytics support to this extension?  It looks like it was added to the Magento 2 plugin [a couple weeks ago](https://github.com/algolia/algoliasearch-magento-2/pull/435).

We just recently upgraded to the Business plan and are interested in using the data provided by click analytics, but don't want to implement this on our own if it's being added to this plugin in the near future.

Thanks!

**Comment by JanPetr** [comment]
Hello @bmartus,

thanks for raising it up! We have plans to deliver click & conversion analytics to M1 extension as well. It on our roadmap, but I cannot give you any ETA for now. But I can ensure you we are working on it :)

Thanks for understanding!

**Comment by bmartus** [comment]
Looks like this made it to 1.14.0.  Thanks @damcou and @JanPetr !
