### ISSUE TITLE
exclude products

### ISSUE THREAD

**Issue by egyprotech** [algolia/algoliasearch-magento#1023]
I need to exclude some products from the results with specific attribute value, how to achieve this ?

**Comment by JanPetr** [comment]
Hello @egyprotech,

you cannot do that with configuration.
To achieve that you'll need to use [backend events](https://community.algolia.com/magento/doc/m1/getting-started/backend/), write listener and modify the collection of products so the products with specific attribute values are not fetched and indexed. Is that something you can do?

You can learn how to write listeners here: https://community.algolia.com/magento/doc/m1/customize-extension/
