### ISSUE TITLE
autocomplete menu auto close.

### ISSUE THREAD

**Issue by egyprotech** [algolia/algoliasearch-magento#1024]
A select box has been added in the product template in the autocomplete menu, but it's not working at all it's always disabled only here in autocomplete menu, so used js liberary to override the select box and replace it with some div and ul. The issue now is that when try to select option the menu is auto closed and removed from the html dom,
So the question is, in which file in the extension have the code/event to close the autocomplete menu when the user clicked on anything?

**Comment by egyprotech** [comment]
Here is a link to the issue: http://uat.dakakyn.com/en
try to enter the word "tomatt" and under the price of the third product there is a select box. This select box is not opening just here in the autocomplete wrapper, but it's working every where else.

Please reply ASAP

**Comment by JanPetr** [comment]
Hello @egyprotech,

you can turn on Debug mode for autocomplete menu and it'll stay open:
<img width="819" alt="screen shot 2018-06-19 at 10 17 23" src="https://user-images.githubusercontent.com/1058144/41585335-0cc3a88e-73aa-11e8-8fb4-42ea3505025c.png">

**Comment by egyprotech** [comment]
Are you kidding? :)
Ofcourse I know this option and this is just for debug, and this means that once the autocomplete menu appear it won't disappear unless the page changed. This is not what I'm asking for.
Anyway I had work around on the issue and made it work as I need (kind of)
