### ISSUE TITLE
 Algolia for Magento 1: Custom attribute with only numerical values getting indexed as a number value and removes zeros in front of it Give Feedback indexing customattributes numbers magento1 string

### ISSUE THREAD

**Issue by alexbogias** [algolia/algoliasearch-magento#1036]
I am using Algolia 1.13.0 extension for a Magento 1 store and we noticed that we cant search products with a value of a custom attributes starting with 0. If you check the latest screenshot you can notice that product_code attribute getting indexed without double-quotes like the rest attributes that has non-numeric characters. This product on magento of course has the 0 in-front of the code and I want to ask you if there is anyway to customiize the extension so it will not convert this attribute

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

![2f746c39-5167-43b9-afb0-a1c8860395bc](https://user-images.githubusercontent.com/1313467/41350660-8ecc52b4-6f1c-11e8-8e14-4fb3863a3914.png)
![c17c9e54-782a-450d-af65-096af582226f](https://user-images.githubusercontent.com/1313467/41350665-91796966-6f1c-11e8-90db-4870e3692403.png)
![ca72b6fe-8405-408a-9a04-06bb510e5fb9](https://user-images.githubusercontent.com/1313467/41350668-92c44462-6f1c-11e8-95b6-7157e3406d16.png)

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 1.9.3.8
Algolia 1.13.0

**Comment by alexbogias** [comment]
I found out that the function castProductObject on app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php#L55 alter the values. 
https://github.com/algolia/algoliasearch-magento/blob/5cb22d350b47cd02583dcaddfce217c00b44e142/app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php#L55

So I created a custom extension that overrides this function and added my custom attribute in the beginning of the function like this:
$nonCastableAttributes = array('sku', 'name', 'description', 'product_code');
and now everything looks good. 
Would be great if you can give the option to users to add their custom attributes to this list :P

**Comment by JanPetr** [comment]
Hey @alexbogias,

thank you for the report and great job on identifying the issue.
Actually right now we are working on configuration directive and you'll be able to specify "non castable attributes" directly in Advanced configuration in Algolia. I'll keep you posted :)

Cheers!

**Comment by alexbogias** [comment]
@JanPetr That's great! Thanks a lot for letting me know
