### ISSUE TITLE
Magento 2 auto suggest search not working Properly on the  Home Page

### ISSUE THREAD

**Issue by haniffas** [algolia/algoliasearch-magento#1042]
Our version of Magento is 2.2.5 and Algolia version is 1.7.0

Algolia search was working perfectly on the base /Luma themes. As soon as we installed a custom theme from a third party, the auto-complete search box disappeared.

After an investigation, we have changed the DOM id on Algolia advanced property to #search and the search box came back  (not sure why we had to do it because as per the algolia documentation it should be an issue as long as the custom theme uses top.search )

Now the issue is , on the Home page, search results (drop down box)  not being displayed properly (the structure is collapsed) while the same search results being displayed properly on all other pages (Ex. Customer Login)

We have also checked the page source on Home Page for the search box it has additional elements but these tags are not on other pages which are working ok.

Any help would be much apprciated.

<span class="aa-dropdown-menu" role="listbox" id="algolia-autocomplete-listbox-0" style="position: absolute; top: 0px; left: 0px; z-index: 100; display: none; right: auto;">
    <div class="autocomplete-wrapper">
        <div class="col9">
            <div class="aa-dataset-products"></div>
        </div>
        <div class="col3">
            <div class="other-sections">
                <div class="aa-dataset-suggestions"></div>
                                    <div class="aa-dataset-0"></div>
                                    <div class="aa-dataset-1"></div>
                                    <div class="aa-dataset-2"></div>
                                    <div class="aa-dataset-3"></div>
                                    <div class="aa-dataset-4"></div>
                                    <div class="aa-dataset-5"></div>
                                    <div class="aa-dataset-6"></div>
                                    <div class="aa-dataset-7"></div>
                                    <div class="aa-dataset-8"></div>
                                    <div class="aa-dataset-9"></div>
                            </div>
        </div>
    </div>
<div class="footer_algolia"><a href="https://www.algolia.com/?utm_source=magento&amp;utm_medium=link&amp;utm_campaign=magento_autocompletion_menu" title="Search by Algolia" target="_blank"><img src="http://192.168.0.55/pub/static/version1530390991/frontend/Mgs/mgsblank/en_GB/Algolia_AlgoliaSearch/images/search-by-algolia.svg" alt="Search by Algolia"></a></div></span></span>

**Comment by haniffas** [comment]
Additional tags on the home page 

![image](https://user-images.githubusercontent.com/32969173/42129294-13dcb9cc-7cb9-11e8-93cb-45d87e382070.png)

**Comment by haniffas** [comment]
![image](https://user-images.githubusercontent.com/32969173/42129347-4ce22706-7cba-11e8-86ad-cccc4827586f.png)

![image](https://user-images.githubusercontent.com/32969173/42129351-67fd3b7a-7cba-11e8-8e68-7579d80afa06.png)

**Comment by damcou** [comment]
Hi @haniffas ,

Thanks for reaching us.

Do you have any environment where we can reproduce this issue ?
Have you noticed any differences in the DOM between the HP and the other pages ?
Is the class "algolia-search-input" still applied on the search input ?

Thanks in advance.

Best regards.

**Comment by damcou** [comment]
Hi @haniffas , 

As this issue is related to Magento2, we will continue our talk on the algoliasearch-magento-2 repository : https://github.com/algolia/algoliasearch-magento-2/issues/517

Thanks agin
