### ISSUE TITLE
Configurable prices are wrong after #978

### ISSUE THREAD

**Issue by rbrown** [algolia/algoliasearch-magento#1043]
Hello, Pull #978 doesn't 'fix' configurable pricing. I guess the previous behaviour was that configurable products didn't show a range of prices, but the code in #978 doesn't work correctly. 

#978 iterates through all the simple products attached to the configurable, and uses min/max on their prices, but that's not how configurable products are priced. 

Configurable products attribute values are assigned a modifier to the price (percent of absolute value) that is combined for each configurable attribute. You can see in `Mage_Catalog_Block_Product_View_Type_Configurable->getJsonConfig()` how the prices for each individual attribute value are sent to the frontend.

Because configurables are priced this way, it's entirely possible for the simple product pricing to not be the same as the price of the same product when presented as a child of a configurable product.

Please accept my apologies for not including a pull request to calculate the correct configurable price, but configurable pricing code always gives me a headache anytime I look at it.

**Comment by damcou** [comment]
Hi @rbrown ,

Thanks for reaching us and for you interest on this issue.
I will try to have a look at it ASAP.
In the meanwhile, it could be super useful if you could give me some concrete examples of what the calculation is currently versus what it should be.

Thanks in advance.

Best regards.

**Comment by rbrown** [comment]
Hi @damcou, I hope this image bomb is ok. In this example `Algolia_Algoliasearch_Helper_Entity_Producthelper->handlePrice` will set min and max to the same (£10) because that's the `price` of the configurable and associated products. But you can see that the configurable has price adjustments set on the `Associated Products` tab, and that the prices range from £10-£13.
<img width="887" alt="screen shot 2018-07-04 at 14 54 18" src="https://user-images.githubusercontent.com/233384/42281006-3db28036-7f9a-11e8-8a73-cd4eda977e50.png">
<img width="897" alt="screen shot 2018-07-04 at 14 20 54" src="https://user-images.githubusercontent.com/233384/42279569-1688ca3c-7f96-11e8-8a6e-4cf9e9d0acd3.png">
<img width="567" alt="screen shot 2018-07-04 at 14 18 13" src="https://user-images.githubusercontent.com/233384/42279534-f62f2470-7f95-11e8-833d-56cd9510b2fb.png">
<img width="573" alt="screen shot 2018-07-04 at 14 18 24" src="https://user-images.githubusercontent.com/233384/42279537-f7571f74-7f95-11e8-8de1-8f02e835423a.png">
<img width="562" alt="screen shot 2018-07-04 at 14 18 57" src="https://user-images.githubusercontent.com/233384/42279540-f8809042-7f95-11e8-9085-0406125da5c4.png">
<img width="346" alt="screen shot 2018-07-04 at 14 49 22" src="https://user-images.githubusercontent.com/233384/42280821-b95b62e4-7f99-11e8-9025-1fe53a77e171.png">

<hr>
If I change it around, so there are no price adjustments for the various options, but one of the simple products has a different price like this:
<img width="896" alt="screen shot 2018-07-04 at 14 46 31" src="https://user-images.githubusercontent.com/233384/42280872-d7d8bf78-7f99-11e8-8aff-122ac3a640c3.png">
Then the helper is now incorrectly thinking the price ranges from £10-£20
<img width="355" alt="screen shot 2018-07-04 at 14 50 08" src="https://user-images.githubusercontent.com/233384/42280887-e85ff834-7f99-11e8-856b-10e0fab9c093.png">
<hr>
`Mage_Catalog_Block_Product_View_Type_Configurable->getJsonConfig()` is the method/block that creates the JSON that is used on the product view page to calculate the ± prices

**Comment by damcou** [comment]
Added to our roadmap.
