### ISSUE TITLE
x-frame-options deny for third party iframes

### ISSUE THREAD

**Issue by alamzaib** [algolia/algoliasearch-magento#1044]
We have implement algolia and working perfect but a payment module installed then it is blocking

The payment module loads in an iframe and loads inside that frame but algolia block that third party url in iframe and giving following error in browser console

“Load denied by X-Frame-Options: https://checkout.paymentwebsite.com/API/paymentPage does not permit framing.”

**Comment by damcou** [comment]
Hi @alamzaib , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
