### ISSUE TITLE
Event to tie into a search result for autocomplete

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#1046]
**Do you want to request a *feature* or report a *bug*?**
Feature

**Feature: What is your use case for such a feature?**
When a use is doing a search in the autocomplete search box, I'd like algolia to fire off an event after a predetermined set of time (say 3 seconds) which would include the result count and the search term. This would allow us to tie more easily into things like Google analytics.

Not sure if this already exists. I found it difficult to follow through the code since most of the relevant javascript has been minified and obscured. 

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**
- The user performs a search in the autocomplete search box
- After X seconds of inactivity, Algolia fires off an event for each index which provides the result count, the index, and the search term performed.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento version 1.9.3.1
Algolia 1.12.0

**Comment by JanPetr** [comment]
Hello @greatwitenorth,

the event itself doesn't exist, but the feature you're looking for - integration with GA is already there offering you this delay configuration: https://community.algolia.com/magento/doc/m1/analytics/

Would that work for you? :)
