### ISSUE TITLE
disjunctiveFacetRefinements not populating with a value

### ISSUE THREAD

**Issue by venglar** [algolia/algoliasearch-magento#1047]
Magento version: 1.7.2.0
Algolia version: 1.14.0

Bug: When a disjunctive facet is applied (in this case, the price slider), it doesn't actually show up as an applied disjunctive filter.

<img width="482" alt="screen shot 2018-07-26 at 10 40 40 am" src="https://user-images.githubusercontent.com/8823177/43278584-5e22923e-90c0-11e8-8e16-ab6d39af60f2.png">

Note how there is a price filter applied (and another facet filter that ISN'T disjunctive, which shows in the data object fine), but Algolia still thinks there aren't any disjunctive facet filters applied.

Expected behavior: I would expect to see that the price slider has been applied as a filter to my current results.

I am attempting to author some logic that conditionally shows/hides a page element based on whether or not any filters have been applied. It works fine, with everything except the price slider.

**Comment by JanPetr** [comment]
Hello @venglar,

by it's nature the price filter is applied as numericFilter and not disjunctive filter:
<img width="685" alt="screenshot 2018-08-13 16 42 40" src="https://user-images.githubusercontent.com/1058144/44038873-0a6d5dac-9f18-11e8-9bbd-72941ba1fcfb.png">

Is your issue that the products are not refined by the price? Or are they refined in a wrong way?
