### ISSUE TITLE
Algolia 1.14 - showing notification "One or more of the Indexes are not up to date: Algolia Search - Delete inactive products. 

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#1052]
HI. Just updated to latest version for M1.
The problem is that it shows notification in admin area - and this message cannot be removed.
"One or more of the Indexes are not up to date: Algolia Search - Delete inactive products. Click here to go to Index Management and rebuild required indexes."

- Its annoying, cannot be removed, and nobody will delete inactive products because Algolia says.
- Inactive products are inactive - because of 10000 other reasons. temporary disabled, out of stock, temp redirected to another product with promotions, or product is just to be validated, content is not yet finished. waiting for approval, etc. no matter.

- BIG NO, I dont plan to delete products, and later setup all the things, all attributes, all descriptions - just because Algolia plugin say so

This annoying message should be removed - because it gives nothing for store admin.

Thanks a lot
Tomek

**Comment by JanPetr** [comment]
Hey @tomekjordan,

I'm super grateful I see this report, thanks!
The name of the indexer is misleading /o\ It won't remove / delete inactive products from Magento, it won't touch your DB. It only removes inactive products from Algolia so it doesn't appear in search.

I'll improve the name so it's understandable what it does and that it won't touch your DB and mess with your products. Sorry about that 🙏

**Comment by JanPetr** [comment]
@tomekjordan Would change in PR #1054 help you understand what it does?

**Comment by tomekjordan** [comment]
Hi.
thanks. now I know what it does

**Comment by tomekjordan** [comment]
Hi. its been 2 months, and I cannot get rid of this annoying notification at every admin page.
It takes space, its annoying, its just for nothing. Cron is working, indexing is 100% correct

Please remove this "One or more of the Indexes are not up to date: Algolia Search - Delete inactive products. Click here to go to Index Management and rebuild required indexes."
from showing at admin area. Its not giving any value for store admin, besides is showing forever.
We dont need such trash at admin area, and notifications are for more important things, than this "spammy message" showing forever

Thanks

**Comment by JanPetr** [comment]
Hello @tomekjordan,

simple reindexing the indexer would remove the message.

Is it still an issue on your side? Let me know.

In a meantime, I'm closing the issue. Feel free to re-open.

**Comment by tomekjordan** [comment]
https://github.com/algolia/algoliasearch-magento/pull/1101
I have some stores that are disabled. Can it be related to this above?
