### ISSUE TITLE
Algolia docs - Emptying the queue - wrong info

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#1053]
I just tried to read indexing related guide in Algolia docs and see something like this:

> Emptying the queue
> If you want to clear the queue in one instance, you will need to bypass the cron and process the entire queue in one pass. You do this with by setting the variable EMPTY_QUEUE=1:
> 
> EMPTY_QUEUE=1 php path/to/magento/bin/magento indexer:reindex algolia_queue_runner
> If you want to process the entire queue in one pass you can run:
> 
> EMPTY_QUEUE=1 php -f /absolute/path/to/magento/shell/indexer.php -- -reindex algolia_queue_runner

Looks like somebody attached wrong code for M1 - there are no magento/bin in M1....
Anybody could fix the docs and add correct line for emptying queue. I'd like to just empty/remove all jobs it or truncate queue from db.

Thanks

**Comment by JanPetr** [comment]
Hello @tomekjordan,

thank you for the report!
This command is the correct one:
```
EMPTY_QUEUE=1 php -f /absolute/path/to/magento/shell/indexer.php -- -reindex algolia_queue_runner
```

I'm fixing the docs as I'm writing this message. Thanks again 💯
