### ISSUE TITLE
Got an Error Record at the position 18 objectID=20 is too big size=19248 bytes and You have some records which are too big to be indexed in Algolia when reindexing

### ISSUE THREAD

**Issue by darmayantiPuteri** [algolia/algoliasearch-magento#1055]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When Reindex got this error 
"You have some records which are too big to be indexed in Algolia.."

On the Category Page got this error
"Error Record at the position 18 objectID=20 is too big size=19248 bytes..."
and the page is broken, something like PHP error, the CSS no loaded.

**Bug: What is the expected behavior?**
The Category Page displayed properly and when reindexing no error.

**Bug: What is the proposed solution?**
I have configurable product, bundle and giftcard product, I think this is related to this.
Please fix the code.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento Cloud Commerce 2.2.3
Algolia 1.7.2

Can't wait to see the updates. Thanks.

**Comment by JanPetr** [comment]
Hello @darmayantiPuteri,

thank you for the report.
The error you see is due to Algolia limitation. It allows to only accepts records below 10kb size on some plans. In order to make the error go away, please make your records smaller or [upgrade to higher plan](https://www.algolia.com/pricing).
