### ISSUE TITLE
Missing search results after 1.13.0 update

### ISSUE THREAD

**Issue by L9Nick** [algolia/algoliasearch-magento#1059]
Hoping someone can give us some advice on how to resolve an issue we are seeing with our search results. We have a lot of items that are missing and are not being pushed into the Algolia indices. We do not see anything built up in the queue or can think of anything that would cause these items to not display. 

We are running Magento 1.9.1 with 1.13.0 version of the extension. We have the cron sync setup and do not see anything built up in the queue to be sent. IF we disable one of our items that is not showing up, and then re-enable (then manually run the standard Magento search index) we can temporarily get an item to so on the results. But then it will disappear again over time. Are there any known bugs, or advice on how to fix this? This issue is causing us sales with missed search results.

**Comment by JanPetr** [comment]
Hello @L9Nick,

sorry for the late reply.
Could you try to upgrade to 1.15.0 and reindex your all catalog? It should fix the issue.

If you still experience troubles, feel free to re-open the issue. Thank you!
