### ISSUE TITLE
Connect algolia with firestore ?

### ISSUE THREAD

**Issue by Omar-Qalei** [algolia/algoliasearch-magento#1062]
```
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';
admin.initializeApp();
const env = functions.config();

import * as algoliasearch from 'algoliasearch';

// Initialize the Algolia Client
const client = algoliasearch(env.algolia.appid, env.algolia.apikey);
const index = client.initIndex('AddListData');

exports.indexAnimal = functions.firestore
  .document('AddListData/{id}')
  .onCreate((snap, context) => {
    const data = snap.data();
    const objectID = snap.id;

    // Add the data to the algolia index
    return index.addObject({
      objectID,
      ...data
    });
});

exports.unindexAnimal = functions.firestore
  .document('AddListData/{id}')
  .onDelete((snap, context) => {
    const objectId = snap.id;

    // Delete an ID from the index
    return index.deleteObject(objectId);
});
```
![2018-10-13 2](https://user-images.githubusercontent.com/40803042/46904273-7b3c0400-ceea-11e8-8730-feec13554320.png)

**Note: my problem can't show this documents in algolia** 

![2018-10-13 3](https://user-images.githubusercontent.com/40803042/46904294-b807fb00-ceea-11e8-8240-d6e662c4d8ea.png)

**Comment by jafsparrow** [comment]
What plan do you have in firestore? Spark plan does not have option of doing outbound networking which is what the algolia function does in firestore.. check the function logs, if it has failed, then that means it is coz the plan

**Comment by JanPetr** [comment]
Hello @Omar-Qalei,

it's more Firestore related then Algolia Magento related. Could I advise you to ask Firestore support? Thank you!
