### ISSUE TITLE
No index update, only tmp index

### ISSUE THREAD

**Issue by jeremydevos** [algolia/algoliasearch-magento#1063]
Hello,

My product index goes back nothing, only on the index tmp.

Yet I have in database when indexing the line moveProductTmp on the good shop.

How else to move the products of tmp to the normal index?

Thank you

**Comment by JanPetr** [comment]
Hello @jeremydevos,

the extension will automatically move the TMP index to production once all products are indexed in TMP index. Does it happen for you?

I'm closing the issue as it's been a while since it was reported. If you still experience the issue, feel free to re-open.
