### ISSUE TITLE
Custom attributes (EAN-13 Code) of child products of configurable products not showing

### ISSUE THREAD

**Issue by simonmaass** [algolia/algoliasearch-magento#1067]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Custom attribute of child products of configurable products not showing! Used to work before version 1.8.0...

**Bug: What is the expected behavior?**
In Update 1.8.0 you added an update:
Values of skus and colors are now correctly index within record of main configurable product

The the custom attributes of the child product is kinda like the skus of the child products i am guessing the problem might come from there.

**Bug: What is the proposed solution?**
List all the attributes of the child products...

**Feature: What is your use case for such a feature?**
We are mantaining the EAN-13 code of all products - it would be great if you could search for the EAN!

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Using magento 2.2.6 and algolia seach 1.8.2

This is how it used to look:
![image](https://user-images.githubusercontent.com/32599710/47284091-457fd500-d5e6-11e8-9fcb-c068a8f8f95c.png)
Now the attribute EAN is not present...

**Comment by alexgran** [comment]
I had similar issue, with all other fields. Went on to index all simple products separately, see https://discourse.algolia.com/t/configurable-products-where-we-are-and-where-to-go/6641/2

**Comment by simonmaass** [comment]
wow - thanks so much - will look into this and give update!

**Comment by JanPetr** [comment]
Hello @simonmaass,

did you manage to figure it out?

I'm closing the issue now, feel free to re-open.
