### ISSUE TITLE
How to disable auotocomplete results dropdown when type in search box

### ISSUE THREAD

**Issue by praveentyagiutsav** [algolia/algoliasearch-magento#1068]
Hello,

I set up Algolia1.14.0  on Magento 1.9.3.9 and its working fine. Now, I want to disable autocomplete results dropdown which appears when customer type any character in search box. I want result page only when customer clicks over search button.
Kindly suggest the solution.

With Thanks!

**Comment by JanPetr** [comment]
Hello @praveentyagiutsav,

you can simply disable Autocomplete menu feature in Algolia configuration in Magento.

**Comment by praveentyagiutsav** [comment]
Thanks @JanPetr
