### ISSUE TITLE
Wrong price range for configurable with out of stock subs

### ISSUE THREAD

**Issue by Interghost** [algolia/algoliasearch-magento#1074]
Fix configurable products' prices #978 includes sub products that are not salable (out of stock for example) in price range calculation.
This by itself is possibly a desired behavior but a further bug happens here when the subproducts are setup with special prices... for example we have a configurable with 2 sub products.
All are priced $100, with special price without end date $50.
When all the products are in stock the price calculation gives the $50 value. (which is correct)
When one of the subs goes out of stock the getFinalPrice call on him returns the full price value, and in the end the price calculation gives the "$50 - $100" value (which is incorrect).

I've opened a PR with a suggested fix.

**Comment by alexgran** [comment]
Hi,
I just got hit by that bug as well. The code has more issues.
a.) Tax helper should use sub_products tax class, not products tax class. Easy fix.
$taxHelper->getPrice($sub_product, $sub_product->getFinalPrice(), $with_tax,
b.) The min-max range is not taking into account group specific prices of the sub products. As such, someone logged in will see the not logged in price range. I'm working on a fix, but this is more of a redo.

**Comment by alexgran** [comment]
I guess you can ignore b, that might be because we use the price of simple products for the configurable  children. Got that working nevertheless.
