### ISSUE TITLE
Category page exclude

### ISSUE THREAD

**Issue by badev-ajay** [algolia/algoliasearch-magento#1083]
Hi Team,

I have a different type of category pages. I want to render some category page with Algolia and some category pages need to be the default. How I can exclude some category page.

**Comment by JanPetr** [comment]
Hello @badev-ajay,

sorry for the late reply!

To remove instant search from some categories, you'll need to use back-end hook: [`algolia_after_create_configuration`](https://community.algolia.com/magento/doc/m1/backend/#algoliaaftercreateconfiguration).
In this hook, you can modify front-end configuration of the extension. You can get an ID of currently loaded category and based on that you can turn off search functionality. If it's turned off, the front-end Algolia won't be triggered and category page will be rendered "normally".
