### ISSUE TITLE
Products on category page gone after installing Algolia

### ISSUE THREAD

**Issue by Tjitse-E** [algolia/algoliasearch-magento#1085]
**Bug: What is the current behavior?**
I've installed the latest version of Algolia on Magento 1.9.3.9 and the categories are empty after installing Algolia:
![haarverzorging - menu 2018-11-20 12-09-06](https://user-images.githubusercontent.com/14849044/48770025-70307c80-ecbd-11e8-9326-2c1e14059829.png)

- There aren't any Algolia related errors in the log
- After disabling the Algolia module the products are back again.
- The search is working correctly by the way, and Algolia is done reindexing.
- I've disabled 'Replace categories page'

**Bug: What is the expected behavior?**
Products appear on the category page after installing the Algolia module

**Bug: What is the proposed solution?**
I'm still searching for a solution.

**Comment by JanPetr** [comment]
Hello @Tjitse-E, thank you for filing the issue.

Would you be able to give me access to your website (can be staging) where I could see the bug live? Thank you!

**Comment by Tjitse-E** [comment]
Hi @JanPetr . Sure, no problem. Can I send you the details via email? How can I contact you?

**Comment by JanPetr** [comment]
Hello @Tjitse-E,

yes, you can send it to support+magento(at)algolia.com, thanks!

And at the same time, can you disable "Make SEO request" in Algolia configuration in Magento (Advanced panel). Thanks!
