### ISSUE TITLE
Facet left sidebar is not loading   some time in magento 1.13 enterprices version 

### ISSUE THREAD

**Issue by badev-ajay** [algolia/algoliasearch-magento#1086]
Hi Algolia Team,

Some time Facet filter is not working. it hides from the live server. when I submit the setting page of algolia configuration without any change it comes again.

please parameter 

 ```
{hits: [,…], nbHits: 2384, page: 0, nbPages: 84, hitsPerPage: 12, processingTimeMS: 3, facets: {},…}
exhaustiveFacetsCount: true
exhaustiveNbHits: true
facets: {}
hits: [,…]
hitsPerPage: 12
index: "BrandAlleydefault_products"
nbHits: 2384
nbPages: 84
page: 0
params: "query=blue&hitsPerPage=12&maxValuesPerFacet=10&page=0&ruleContexts=%5B%22magento_filters%22%2C%22%22%5D&facets=%5B%22available_immediately%22%2C%22product_type%22%2C%22gender%22%2C%22brand%22%2C%22size%22%2C%22colour%22%2C%22price.GBP.default%22%5D&tagFilters=&filters=&numericFilters=visibility_search%3D1"
processingTimeMS: 3
query: "blue" 
```
![image](https://user-images.githubusercontent.com/42803285/48778204-91638e00-ecfa-11e8-9dc6-8fd1deddd506.png)

**Comment by badev-ajay** [comment]
HI Algolia Team,

Is anyone take care of it is a mazer issue in Magento module

**Comment by JanPetr** [comment]
Hello @badev-ajay,

sorry for the late reply.
You need to set Attributes for faceting in Algolia configuration in Magento (Instant search tab). Have you set it up?

I'm closing the issue now as it's been a while since it was reported. Feel free to re-open if you have more information on that. Thank you!
