### ISSUE TITLE
Handling too big record

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#109]

**Comment by aphroz** [comment]
I think this issue may be related to grouped products

**Comment by aphroz** [comment]
Indexing only simple products seems to fix this issue.

**Comment by maxiloc** [comment]
Ok. I am keeping this open as we want to handle every types of product

**Comment by aphroz** [comment]
Sure, it was just to update you on this issue

**Comment by maxiloc** [comment]
Thanks :smile:
