### ISSUE TITLE
how to add image for color facet instead of color text magento 2 instant search

### ISSUE THREAD

**Issue by dev9-ki5** [algolia/algoliasearch-magento#1092]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**

**Bug: What is the expected behavior?**

**Bug: What is the proposed solution?**

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

**Comment by dev9-ki5** [comment]
![1](https://user-images.githubusercontent.com/43980985/50445473-c7ff7a80-0930-11e9-8e34-9c7d3f017794.png)

**Comment by dev9-ki5** [comment]
@JanPetr @BanyuUrip @dudusotero

**Comment by dudusotero** [comment]
Hi @dev9-ki5, how are you?

I think that's your problem can be asked in algolisearch-magento-2 page, https://github.com/algolia/algoliasearch-magento-2.
Try to ask here while I look for something to help you ;)

**Comment by dev9-ki5** [comment]
Hi @dudusotero , I am fine , Hope so you are also well.
 
Yes i am putting request in algoliasearch-magento-2 , 
Thanks for your reply 👍  <3
