### ISSUE TITLE
Algolia Bundle Size

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#1093]
Does Algolia really need to load 150+ kb of javascript initially? I'm assuming a large portion of this JS could be split between the site wide search, search homepage, and category pages. We aren't using algolia for category pages, so there may be some reduction there

**Comment by JanPetr** [comment]
Hello @davids101,

thank you for the report. We are aware of the issue and we have it on our roadmap.
But to be very honest, it's not our top priority right now, but we'll get to work on that in the next months probably.

I'm closing the issue now, but feel free to re-open if you have more information or if you have anything else to add. Thank you!
