### ISSUE TITLE
Indexing Queue > 404 not found error

### ISSUE THREAD

**Issue by joell67** [algolia/algoliasearch-magento#1095]
Installed Algolia 1.15.0 in Magento 1.9.3.4 and 1.9.2.3.
Reindexed, cached, logged out etc. as usual.

Logged back in, navigated to System > Algolia Search > Configurations, entered all credentials in the fields, saved.

Then went to System > Algolia Search > Indexing Queue to reindex my catalog, but page is resulting in 404 not found.
Below is the path generated https://mysite.com/index.php/admin/algoliasearch_indexingqueue/index/key/abcdefghijkl123456789/ 

Same issue applies when navigating to Reindex SKU(s) - 404 error.
https://mysite.com/index.php/admin/algoliasearch_reindexsku/index/key/abcdefghijkl123456789/ .
Only Configurations page would load without issues.

To reproduce the issue, install the extension, navigate to either Indexing Queue or Reindex SKU(s) - there will be an error of 404 page not found.

Your help is appreciated.

**Comment by joell67** [comment]
What do you mean by classes, where is that located?

I did rename the files to IndexingqueueController.php and ReindexskuController.php, also the block files were renamed in app/code/community/Algolia/Algoliasearch/Block/Adminhtml.

No more 404's! - Reindex SKU(s) is showing just fine, but Indexing Queue still shows a blank page in admin, nothing there. I must be missing something.

Thinking now maybe to change server settings to ignore capitalization, not sure what impact this will have globally though. I might be better off just renaming this extension files/folders.

Rgds,

**Comment by jaystacey** [comment]
Algolia\Algoliasearch\Block\Adminhtml\IndexingQueue\Grid.php ~line 68

$this->addColumn('data', array(
            'header' => Mage::helper('algoliasearch')->__('Data'),
            'index' => 'data',
            'renderer' => 'Algolia_Algoliasearch_Block_Adminhtml_IndexingQueue_Grid_Renderer_Json'
        ));

to

$this->addColumn('data', array(
            'header' => Mage::helper('algoliasearch')->__('Data'),
            'index' => 'data',
            'renderer' => 'Algolia_Algoliasearch_Block_Adminhtml_Indexingqueue_Grid_Renderer_Json'
        ));

**Comment by joell67** [comment]
This helped loading the page properly.
Thank you.

**Comment by JanPetr** [comment]
Thank you for the report and the PR 🙌 I have just merged it and it will be released as a stable release soon.

**Comment by tomekjordan** [comment]
Updated to 1.16. and instead of 404 I'm getting empty page - despite there are some jobs - in notification bar at the top...
weird
![Screenshot_54](https://user-images.githubusercontent.com/8250276/56827812-1fbadd80-6860-11e9-98b2-33df1495a6d1.png)

**Comment by jaystacey** [comment]
See my comment above, that is your solution.
