### ISSUE TITLE
Redirecting 404 to search result page

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#1099]
Hi there,

This is more an feauture request for the following;

At this moment i'm using Mirasvit Sphinx Search extension ONLY for the function: when 404 - > sent to search result page.

Is there an way to implement this feature in Algolia Search extension? So I can remove the sphinx extension?

Thanks!

**Comment by JanPetr** [comment]
Hello @HRR1337,

thank you for submitting the feature request.
Could you elaborate a bit more on how it's done in Sphinx?

Does it display search on search results page?
Or 404 redirects customers to search results page? What query is searched for?

**Comment by HRR1337** [comment]
Hi there,

We have removed the Mirasvit Sphinx Search extension now completely, and used the Amasty XML sitemap extension (which also has an feature that if url gives 404, it redirects to search results). And works perfectly.

Example: If you have an url called 'red-hammer-tool'

it makes the search with: 

https://www.url.com/catalogsearch/result/?q=red-hammer-tool

Workes perfectly, though would be better to have it directly with Algolia.

Thanks,

HRR

**Comment by parramattacameras** [comment]
Any update on this? As it's exactly what we are looking for with Algolia.

**Comment by AlexEven** [comment]
Hello, 

Thank you both for your feedback and explaining what you'd like to see in our extension.
I'm adding this to our roadmap for consideration, and we'll get back to you when we have more visibility on its implementation.

Thank you!

**Comment by bsuravech** [comment]
Hi there! 

I hope you are doing well. As we have ported your feedback over to our product board, we are going to close out the issue. If you have any questions or new feedback for us, please feel free to send them to us at [support@algolia.com](mailto:support@algolia.com).
