### ISSUE TITLE
1.15.0 - Algolia Search > Indexing Queue & Reindex SKU(s) gives 404

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#1105]
**Do you want to request a *feature* or report a *bug*?**
BUG

**Bug: What is the current behavior?**

Admin area with latest 1.15.0
MENU > Algolia Search > Indexing Queue
MENU > Algolia Search > Reindex SKU(s) 
BOTH gives 404

**Bug: What is the expected behavior?**
Open desired pages

**Bug: What is the proposed solution?**
check urls

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia 1.15.0
Magento 1.9.3.1 & Magento 1.9.4.0

**Comment by collymore** [comment]
Any news on this? 
We've got the same issue.

**Comment by damcou** [comment]
Hello,

Thanks for reaching out.

This issue has been fixed on the develop branch : https://github.com/algolia/algoliasearch-magento/commit/4af31f016bcd20e0b79eede9feebb968ce187f82

And will be part of the next release.
We will keep you updated on this thread.

Best.
