### ISSUE TITLE
1.15.0 not compatible with PHP 7.2

### ISSUE THREAD

**Issue by dverkade** [algolia/algoliasearch-magento#1108]
**Bug: What is the current behavior?**

Have PHP 7.2 installed with Magento 1.9.4.0 and AlgoliaSearch module for Magento 1. Magento 1.9.4.0 supports PHP 7.2 fully. Enabling AlgoliaSearch will result in a PHP Fatal error: 

```
[Thu Feb 21 09:26:09.929855 2019] [php7:error] [pid 17750] [client 141.101.105.39:21622] PHP Fatal error:  Uncaught Error: Call to undefined function mcrypt_module_open() in /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/lib/Varien/Crypt/Mcrypt.php:74\nStack trace:
#0 /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/app/code/core/Mage/Core/Model/Encryption.php(120): Varien_Crypt_Mcrypt->init('1b19f1d2c72e904...')
#1 /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/app/code/core/Mage/Core/Model/Encryption.php(144): Mage_Core_Model_Encryption->_getCrypt()
#2 /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/app/code/core/Mage/Core/Helper/Data.php(243): Mage_Core_Model_Encryption->decrypt('RXvMZA0eiHeEsiK...')
#3 /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/app/code/community/Algolia/Algoliasearch/Helper/Config.php(424): Mage_Core_Helper_Data->decrypt('RXvMZA0eiHeEsiK...')
#4 /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php(45): Algolia_Algoliasearch_Helper_Config->getAPIKey()
#5 /home/han in /home/hansvwijk/domains/webshop.hansvanwijk.nl/public_html/lib/Varien/Crypt/Mcrypt.php on line 74
```

**Bug: What is the expected behavior?**

Magento installation works fine, no PHP Fatal error is thrown. 

**Bug: What is the proposed solution?**

Do not depend on the mcrypt functions anymore, these are no longer available in PHP 7.2

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Version 1.15.0

**Comment by damcou** [comment]
Hello,
Thanks for reaching out.
Magento 1.9.4 should include some patches to make PHP 7.2 compatible : https://inchoo.net/magento/magento-1-official-php-7-2-patches/

Could you please make sure that everything is ok on your side, especially regarding the lib/mcrypt_compat/mcrypt.php file ?

Hope this would help.
Best.

**Comment by dverkade** [comment]
Hi @damcou,

As per release notes of Magento 1.9.4.0 (the version we are using) says that it's PHP 7.2 compatible: 
https://devdocs.magento.com/guides/m1x/ce19-ee114/ce1.9_release-notes.html#ce19-1940

However the Agolia module is not. When we disable the module everything works as expected also see error log in the issue description. Please replicate this on your side.

**Comment by JanPetr** [comment]
Hello @dverkade,

we are not able to reproduce. The error you sent here refers to Magento's `decrypt()` method. Could you make sure this method is PHP 7.2 compatible on your side?

**Comment by dverkade** [comment]
Dubble checked on our side. This project was still running 1.9.3.10 instead of the mentioned 1.9.4.0. Thanks for the feedback.
