### ISSUE TITLE
Product save event

### ISSUE THREAD

**Issue by kerlama** [algolia/algoliasearch-magento#1110]
Hi,

I have installed latest module on magento 1.9.2.1 and I am trying to figure out how product is added to algolia queue.

`<catalog_product_save_before>
                <observers>
                    <algolia_stockupdate>
                        <class>algoliasearch/observer</class>
                        <method>saveProduct</method>
                    </algolia_stockupdate>
                </observers>
            </catalog_product_save_before>`

This is not firing, when some custom module calls $product->save() but still, product is added to queue.

Thanks

**Comment by JanPetr** [comment]
Hello @kerlama,

Indexers have it's own events mechanism: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Indexer/Algolia.php#L67-L205
