### ISSUE TITLE
Feature request - Related Products on productpage

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#1112]
Hi there,

I'm using atm: Algolia search on M 1.9.4 and am really happy with it. The speed is really awesome!

Wondering about the following:

Is it possible to have an 'related products' section on the homepage with the lightning speed of Algolia?

For example that we configure in Algolia which related products we want to show on which products (or with some search queries) and that it then show?

Would really love it! 

Thanks,

HRR

**Comment by damcou** [comment]
Hello @HRR1337 ,

Thanks a lot for your kind feedbacks, we really appreciate it ;) .
About your request, it is unfortunately not currently possible with the extension, but adding the possibility to add Magento widgets with some products on CMS pages is in our backlog and could be added in our roadmap in the future. We'll take your request into account to decide that ;)

Thanks again !

**Comment by HRR1337** [comment]
Hello @damcou ,

Hopefully this will be added! (Or is there an party who can create this for me?)

Thanks!

HRR

**Comment by damcou** [comment]
I don't any precise party to recommend but you can try to find some help from the community on our [forum](https://discourse.algolia.com/). 

Hope that helps.
Best.

**Comment by HRR1337** [comment]
Placed an question on the forum here:

https://discourse.algolia.com/t/magento-1-9-productpage-related-product-s/7379

If anyone can make something like this/that. Please contact me!

**Comment by JanPetr** [comment]
Hello @HRR1337,

thank you for the initiative! We noted it internally and you did it on forum, so I'll close the issue for now.
Let's be in touch on Discourse, thanks! 🙌
