### ISSUE TITLE
Autocomplete different then searchpage

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#1114]
Hi there,

I have the following issue.

The searchpage of Algolia in Magento 1.9 works not as the autocomplete.

Example product: T-shirt 1234 blue/black

I'm typing in autocomplete: T-shirt 1234 blue/black  -> result - > I see the product(s).
I hit ENTER to go to the search page:

I see T-shirts with: OR blue, OR black, not: blue/black.  

When I search on the Searchpage for: T-shirt 1234 blue/blac  (mark, i dont write the k of black) -> Result - > I see products with blue/black 

Question: How can I solve this issue? 

Thanks!

**Comment by bsuravech** [comment]
Hi @HRR1337,

Would it be possible to see a live example of this? We would like to try and reproduce the issue in your environment. 

Let us know about that. Thanks!

**Comment by HRR1337** [comment]
Have e-mailed you :-)

**Comment by bsuravech** [comment]
Hey @HRR1337,

Thanks for sending the example over. We were able to reproduce your issue there and would like to look at your index configuration. Can you perhaps send an email over to support@algolia.com with the example you provided to me? You can reference this issue as well in it. 

Thanks!

**Comment by HRR1337** [comment]
Have done it. thanks!

**Comment by bsuravech** [comment]
Received! We're handling this through the support portal. Closing out here. Thanks!
