### ISSUE TITLE
sql resource mismatch in develop

### ISSUE THREAD

**Issue by rbrown** [algolia/algoliasearch-magento#1123]
Hello, I'm not sure if it's intentional or not, but 50405da572be0cd371f47f71c6111f0c77610e8f added an sql migration for 1.15 to 1.16 without updating config.xml to the new version, leaving the develop branch broken (Algolia Search Queue Runner can't run because the locked_at column doesn't exist)

**Comment by bsuravech** [comment]
Hey @rbrown, we're aware of the issue on develop currently due to PR1117.  Thanks for letting us know! A bump in version will be added prior to the release.
