### ISSUE TITLE
How to index custom product options?

### ISSUE THREAD

**Issue by leonardovilarinho** [algolia/algoliasearch-magento#1134]
Hello, I was looking at the module settings, I did not find any option to be able to index the Algolia custom options of the products. Is there any way to do such indexing? I need the fields of the product to go to the Algolia index.

Sample of options:

![Sample](https://www.mag-manager.com/wp-content/gallery/custom-options-VS-configurable/custom-options-settings.png)

**Comment by bsuravech** [comment]
Hi @leonardovilarinho! Our apologies for the delay in response. To index any additional data outside of product attributes set in configuration, our extension does offer a backend event that allows you to add additional data to your product record in the index. I would look into the event `algolia_after_create_product_object` which you can learn more about here:

https://www.algolia.com/doc/integration/magento-1/customize/custom-back-end-events/?language=php#algolia_after_create_product_object

You can see where this is dispatched in the code here:

https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L1068

Please let us know if you have any questions regarding the above. Thanks!

**Comment by bsuravech** [comment]
Hi @leonardovilarinho ! 

I hope the recommendation above helped resolved your issues. If you have any new questions or issues, please feel free to reach us at [support@algolia.com](mailto:support@algolia.com).
