### ISSUE TITLE
Reindex attempts to add product twice to collection causing pages to be skipped

### ISSUE THREAD

**Issue by bjornsnoen** [algolia/algoliasearch-magento#1137]
Using module version 1.16.0
Magento version 1.14.2.1 enterprise

Expected behavior: All products indexed
Actual behavior: Several products not indexed because db page can't be loaded

Stack trace:
```
ERROR: Exception: Item (Mage_Catalog_Model_Product) with the same id "636" already exist in /home/vita/domains/vita.kunder.trollweb.no/public_html/lib/Varien/Data/Collection.php:373
#0 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(265): Varien_Data_Collection->addItem(Object(Mage_Catalog_Model_Product))
#1 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1055): Mage_Eav_Model_Entity_Collection_Abstract->addItem(Object(Mage_Catalog_Model_Product))
#2 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#3 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/community/Algolia/Algoliasearch/Helper/Data.php(565): Mage_Eav_Model_Entity_Collection_Abstract->load()
#4 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/community/Algolia/Algoliasearch/Model/Observer.php(249): Algolia_Algoliasearch_Helper_Data->rebuildStoreProductIndexPage('1', Object(Mage_Catalog_Model_Resource_Product_Collection), 2, '100', NULL, Array, true)
#5 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/community/Algolia/Algoliasearch/Model/Queue.php(150): Algolia_Algoliasearch_Model_Observer->rebuildProductIndex(Object(Varien_Object))
#6 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/community/Algolia/Algoliasearch/Model/Queue.php(116): Algolia_Algoliasearch_Model_Queue->run('1000')
#7 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliaqueuerunner.php(75): Algolia_Algoliasearch_Model_Queue->runCron()
#8 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/core/Mage/Index/Model/Process.php(212): Algolia_Algoliasearch_Model_Indexer_Algoliaqueuerunner->reindexAll()
#9 /home/vita/domains/vita.kunder.trollweb.no/public_html/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#10 /home/vita/domains/vita.kunder.trollweb.no/public_html/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#11 /home/vita/domains/vita.kunder.trollweb.no/public_html/shell/indexer.php(216): Mage_Shell_Compiler->run()
```
Proposed solution:
Ensure that product ids are unique before attempting to load collection.

**Comment by damcou** [comment]
Hello @bjornsnoen ,

Thanks for reaching out.
Could you be more precise about this issue ? Cause I can't reproduce it on my own .
When does it occur exactly?

I searched for a similar issue in the past, and the only one I found is this one (from May 2017) : https://github.com/algolia/algoliasearch-magento/issues/823 but it has been fixed since then.

What you could try maybe is the advice on the last message , adding
` $collection->getSelect()->group('entity_id');`

exactly there : https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Data.php#L564

to see if it may solves your issue.

hope that helps.
Best.
Damien

**Comment by bjornsnoen** [comment]
Hello @damcou 

I forgot I opened this issue after we discovered that it was indeed caused by reviews as in the issue you referenced. Thank you for the suggested fix, we will look into implementing it, however we are always hesitant to override 3rd party modules, as we need to be able to quickly roll out updates to a large number of clients.

**Comment by bsuravech** [comment]
Hi @bjornsnoen, 

I hope you were able to implement the update for your clients! If you have any questions or issues with your update, please feel free to reach us at [support@algolia.com](mailto:support@algolia.com).
