### ISSUE TITLE
Add a robots.txt on the demo website

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#1138]
Hey 👋,

we're working on improving the SEO of our `algolia.com` domain and we would like to fine-tune the URLs that are currently indexed by Google on your https://magento.algolia.com/ domain.

Could you create a `https://magento.algolia.com/robots.txt` file with the following content (we allow the crawl of the home-page but nothing else):

```
User-agent: *
Allow: /$
Disallow: /
```

Thank you so much for your help!

**Comment by 0livier** [comment]
Do we want to do so in order to ensure that the [allocated crawling budget](https://webmasters.googleblog.com/2017/01/what-crawl-budget-means-for-googlebot.html) on *.algolia.com is being used on contentful/important pages rathers than demo stores?
