### ISSUE TITLE
Can not save magento CMS page

### ISSUE THREAD

**Issue by alex-magebinary** [algolia/algoliasearch-magento#1140]
When save the CMS page, one of the function count is expecting an array, but string is given.
For example:
The wrong one:
`Algolia_Algoliasearch_Helper_Entity_Pagehelper->getPages('1', '10')`

The right one:
`Algolia_Algoliasearch_Helper_Entity_Pagehelper->getPages('1', array('10'))`

The error:
`2019-11-06T03:41:04+00:00 DEBUG (7): Exception message: Warning: count(): Parameter must be an array or an object that implements Countable  in /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Helper/Entity/Pagehelper.php on line 32
Trace: #0 /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Helper/Entity/Pagehelper.php(32): mageCoreErrorHandler(2, 'count(): Parame...', '/var/www/html/....', 32, Array)
#1 /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Helper/Data.php(203): Algolia_Algoliasearch_Helper_Entity_Pagehelper->getPages('1', '10')
#2 /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Model/Observer.php(163): Algolia_Algoliasearch_Helper_Data->rebuildStorePageIndex('1', '10')
#3 /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(49): Algolia_Algoliasearch_Model_Observer->rebuildPageIndex(Object(Varien_Object))
#4 /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(105): Algolia_Algoliasearch_Model_Resource_Engine->addToQueue('algoliasearch/o...', 'rebuildPageInde...', Array, 1)
#5 /var/www/html/.modman/algoliasearch/app/code/community/Algolia/Algoliasearch/Model/Observer.php(126): Algolia_Algoliasearch_Model_Resource_Engine->rebuildPages('1', '10')
#6 /var/www/html/app/code/core/Mage/Core/Model/App.php(1374): Algolia_Algoliasearch_Model_Observer->savePage(Object(Varien_Event_Observer))
#7 /var/www/html/app/code/core/Mage/Core/Model/App.php(1353): Mage_Core_Model_App->_callObserverMethod(Object(Algolia_Algoliasearch_Model_Observer), 'savePage', Object(Varien_Event_Observer))
#8 /var/www/html/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('cms_page_save_b...', Array)
#9 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('cms_page_save_b...', Array)`

**Comment by bsuravech** [comment]
Hi @alex-magebinary! Thanks for reporting the issue regarding the CMS Page save event. We have investigated and opened PR##1141 to address the issue and added some changes for optimisation. Please feel free to review the changes and let us know if you have any feedback. We will be including this in the next release.

**Comment by alex-magebinary** [comment]
Hi How far away for this to be merge to master?

**Comment by bsuravech** [comment]
HI @alex-magebinary, 

My apologies for the delay in response. We have merged and released the PR for CMS indexing in our [1.17.0](https://github.com/algolia/algoliasearch-magento/releases/tag/1.17.0) release. Please feel free to upgrade to the latest version if you haven't already. If you have any further questions or issues, please feel free to reach out to us at [support@algolia.com](mailto:support@algolia.com).
