### ISSUE TITLE
Multi websites with multi accounts problem

### ISSUE THREAD

**Issue by magegirl** [algolia/algoliasearch-magento#1148]
Hi,
I have 4 websites and i configure on each store view different accounts.
But when it's reindex all datas go on the first account only and 3 others are empty.

**Comment by bsuravech** [comment]
Hi @magegirl, 

My apologies on the delayed response. The extension currently isn't compatible with using multiple application IDs. It is only looking at the default configuration. As storeviews have a unique identifiers, all your stores for your separate websites will have their own index within the first account. If you have any further questions, please feel free to shoot us a email at [support@algolia.com](mailto:support@algolia.com).
