### ISSUE TITLE
Ability to filter customer groups

### ISSUE THREAD

**Issue by arjanfrans** [algolia/algoliasearch-magento#1159]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**

We have a store with over 10000 products, 28 customer groups and currently 1 store view. We share the Algolia account for a test and production system. We have over a million objects and exceed our limit every month. We now plan to add a second store view, which would result in twice the amount of objects.

Of our 28 customer groups, only 3 are relevant. Algolia creates indexes for each customer group. 

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

As a workaround I modified the code so that a filter can be configured. In the places where the 'customer groups enabled' is checked I added another check to see if the group should be indexed.

![image](https://user-images.githubusercontent.com/3588470/81048480-b632cd80-8ebc-11ea-8bc6-e5ea63dab7a3.png)

It would be nice if this functionality would be built in so that we can avoid exceeding our limits and run into lots of extra costs.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Algolia 1.17.0
Magento 1.9.4.1

**Comment by bsuravech** [comment]
Hi @arjanfrans! 

Thanks for your feedback. We're forwarded your suggestion over to our product board for feedback on future improvements as we mentioned in your support ticket. 

We're going to close the issue. Please feel free to reach us at [support@algolia.com](mailto:support@algolia.com) if you have any further issues or feedback. Thanks!
