### ISSUE TITLE
Handle grouped price

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#116]

**Comment by redox** [comment]
I've no idea how often/much groups are used in Magento. Storing 1 price per group per record will probably not scale and having 1 index per store per group is probably over-kill.

Do you guys have an idea how popular the Magento "price groups" are? Also, what is the average number of groups you're used to deal with? cc @sergeykalenyuk @colinmollenhour @zainengineer @andrew-dwyer @dlobb

**Comment by colinmollenhour** [comment]
I assume you mean Customer Groups? I don't think they are used often. However, if someone did use them then I would think one index per store/customer group would make sense.

One way to implement this without losing efficiency would be to map all customer groups to a prefix in the config. This way all of the default customer groups could map to the same prefix by default (empty string), and if someone needed multiple indexes they could map to new prefixes.

**Comment by maxiloc** [comment]
Ok will not be implemented for now. Lets close this one and re-open it if needed by someone.

**Comment by maxiloc** [comment]
Let's tackle it !!!
