### ISSUE TITLE
Comment /** */ code coming in search

### ISSUE THREAD

**Issue by vipin12117** [algolia/algoliasearch-magento#1164]
https://www.ustrailersupplies.com/

Do keyword search and check.

**Comment by bsuravech** [comment]
Hi @vipin12117,

Thanks for reaching out. Can you please elaborate more in your issue request? Please include  steps for reproduction like a keyword to enter to find this said comment code? Please send this request through [support@algolia.com](mailto:support@algolia.com) so that we can better assist you. Thanks!

**Comment by vipin12117** [comment]
https://www.ustrailersupplies.com/catalogsearch/result/?q=tarp

**Comment by bsuravech** [comment]
@vipin12117 it seems like your template for `instantsearch/stats.phtml` has been modified to include the comment to remove the section. If you need to remove this statistics, please remove the line instead of commenting it out as our javascript library will render it.

**Comment by vipin12117** [comment]
We did not modified anything in your plugin.

**Comment by bsuravech** [comment]
Please confirm that template or any theme templates for:

`app/design/frontend/base/default/template/algoliasearch/instantsearch/stats.phtml`

Does not contain any comments as I see it rendered on your frontend:

![Screenshot 2020-06-08 at 14 34 45](https://user-images.githubusercontent.com/7048136/84031009-3e613280-a995-11ea-8416-5bd9c0e61e1c.png)

Let us know. Thanks!

**Comment by vipin12117** [comment]
<script type="text/template" id="instant-stats-template">
    {{#hasOneResult}}
        <strong>1</strong> <?php echo $this->__('result found'); ?>
    {{/hasOneResult}}

    {{#hasManyResults}}
        {{^hasNoResults}}
            {{first}}-{{last}} <?php echo $this->__('out of'); ?>
        {{/hasNoResults}}
        <strong>{{#helpers.formatNumber}}{{nbHits}}{{/helpers.formatNumber}} <?php echo $this->__('results found'); ?></strong>
    {{/hasManyResults}}

    <?php echo $this->__('in'); ?> {{seconds}} <?php echo $this->__('seconds'); ?>
</script>

**Comment by vipin12117** [comment]
![image](https://user-images.githubusercontent.com/7281181/84031303-0ff25000-a9b3-11ea-82b0-0a5004e74129.png)

**Comment by bsuravech** [comment]
Hi @vipin12117,

I am reviewing the view-source of the catalogsearch page and am noticing that all of our html script templates that have HTMl have a `*<![CDATA[*/` wrap. As you have confirmed, our templates do not have comments added to our templates.

This says to me that there is something automatically being added on your templates. Can you confirm with that is in your Magento instance adding this?  Thank you.

**Comment by vipin12117** [comment]
Not sure. I just installed your plugin. You need to check how other Magento
files can change your code.

**Comment by vipin12117** [comment]
how we can fix this error ?

**Comment by bsuravech** [comment]
Hi @vipin12117 - I am reviewing your site again and do not see the comment blocks. Did you manage to figure out your issue? 

As I said before, there is something being automatically being added in your Magento instance. You will have to exclude our templates from what it is adding the comment CDATA blocks. Thank you.
