### ISSUE TITLE
Number of product categories to display

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#121]
By default we put "in category 1, category 2, ..." under the product name on the autocomplete.

Maybe we can display a fixed number to display (like 2 or three with ... at the end) and/or Maybe we can put an option in UI

@redox What do you think

**Comment by redox** [comment]
Yeah, putting an option in the UI is probably the way to go because we'll not be able to determine the good value for all stores.

**Comment by maxiloc** [comment]
We put a text-ellipsis instead
