### ISSUE TITLE
The slider doesn't shows up

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#125]
The slider doesn't shows up on attributes like price:

![image](https://cloud.githubusercontent.com/assets/261406/8425568/4adbba76-1f07-11e5-82d6-6272c084a079.png)

**Comment by maxiloc** [comment]
Works fine on  last version [here](https://magento.algolia.com/catalogsearch/result/?q=madison&instant=1#q=madison&page=0&refinements=[]&numerics_refinements={%22price_with_tax%22%3A{%22%3C%3D%22%3A510}}&index_name=%22magento_default_products%22).

Can you check for js errors ?

**Comment by aphroz** [comment]
My bad,

Refreshed the cache and it works fine.

Thank you
