### ISSUE TITLE
AJAX spins forever on instant search results page

### ISSUE THREAD

**Issue by MDowdal** [algolia/algoliasearch-magento#126]
Hello, the AJAX appears to spin forever on my instant search results page.  How can I fix this?

http://www.factorydirectfilters.com/catalogsearch/result/?q=20%20x%2020%20x%206&instant=1#q=20 x 20 x 6&page=0&refinements=%5B%5D&numerics_refinements=%7B%7D&index_name=%22magentonew_fdf_products%22

**Comment by maxiloc** [comment]
Hi,

You have this js error : Uncaught [Algolia] Invalid instant-search selector: #content

You need to configure you instant selector with .main instead like the screenshot bellow :

![selector](https://cloud.githubusercontent.com/assets/1689007/8456875/7bfdef86-200e-11e5-8f65-305065eaf4c1.png)
