### ISSUE TITLE
Change chunk size when not using the queue

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#127]
We cannot change the chunk size of the index building process in the backend when the queue is disabled.

**Comment by maxiloc** [comment]
@aphroz Can you give me a bit more details why you need this option to be available when the queue is disabled ? Is it to avoid memory limit issue ?

**Comment by aphroz** [comment]
I would like to define the number of products sent to the Algolia server at each call.

**Comment by maxiloc** [comment]
@aphroz I am not going to release on magento connect right away. But as it is only a 1 line modification you can reproduce the change on your instance.

Good for you ?

**Comment by aphroz** [comment]
Sure, thanks
