### ISSUE TITLE
Multiselect attributes displayed as a string

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#128]
Multiselect attributes are displayed as a string:

![image](https://cloud.githubusercontent.com/assets/261406/8482608/1367117c-20eb-11e5-9f5f-390c2a7ea0b8.png)

![image](https://cloud.githubusercontent.com/assets/261406/8482760/ed6ce644-20eb-11e5-9e92-703baec69139.png)

![image](https://cloud.githubusercontent.com/assets/261406/8482600/031ad6a0-20eb-11e5-8209-7bd8c29a8b4a.png)

**Comment by redox** [comment]
Good catch @aphroz, we're gonna have a look at that one!
