### ISSUE TITLE
Value "No" is sent when the attribute is not available

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#131]
When an attribute is set as a facet and is not available in the product data, the value "No" is sent:

In the search result:

![image](https://cloud.githubusercontent.com/assets/261406/8522138/5a8097f6-23eb-11e5-9542-d101ad9643ca.png)

In Algolia:

![image](https://cloud.githubusercontent.com/assets/261406/8521908/12288330-23e9-11e5-9552-bd38d7e36652.png)

**Comment by maxiloc** [comment]
Hi,

Yes fixed this morning with 0775f25.

Thanks for reporting

**Comment by aphroz** [comment]
Should I clear the index and re-index then?

**Comment by maxiloc** [comment]
You can just reindex once you made the change.
