### ISSUE TITLE
algoliasearch_run_queue running very long

### ISSUE THREAD

**Issue by MDowdal** [algolia/algoliasearch-magento#132]
It's been running today for times well over what I expected, clogging my cron queue.  The current process has been running for over twenty minutes!

**Comment by MDowdal** [comment]
I had to kill the cronjob as it was causing Cron.php to have severe issues.  It ran so long that I actually had to restart cron.php after it looped for over 40 minutes on output like this: 

open("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", O_RDONLY) = 12 fstat(12, {st_mode=S_IFREG|0644, st_size=292714, ...}) = 0
lseek(12, 0, SEEK_CUR)                  = 0
lseek(12, 0, SEEK_SET)                  = 0
fcntl(12, F_GETFL)                      = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fstat(12, {st_mode=S_IFREG|0644, st_size=292714, ...}) = 0 mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc65ae81000
lseek(12, 0, SEEK_CUR)                  = 0
read(12, "\377\330\377\340\0\20JFIF\0\1\2\1\0H\0H\0\0\377\341\31\366Exif\0\0II"..., 32768) = 32768 read(12, "\322S\242IQ\34\323\315<4\7\355\251\243\222\235\325\344p\21YJ\226\7\217v\10\344\5\323\237\313"..., 32768) = 32768 read(12, "W\223\253Uv\222\225)\250\236$y\344\223@\367\266Q\246\240wuMD\327\3024\36\247\"\277g"..., 32768) = 32768 read(12, "Q#\2128\337\304\220@\343^\274A\222\256\330P)\307?\347\374\272Pbs\230\375\207\231\335\33?"..., 32768) = 32768 read(12, "(\252r\230\332*,\355]e\6Iq\371LT\364Tx9b\236\245\246\232X\340\220\351\216\213\367"..., 32768) = 32768 read(12, "\25\24_d\225\30\225H\310GD\235|Z\322\37V\262Eq\345\237\362\217\330~\336\233\16Pi\0"..., 32768) = 32768 read(12, "\3321\374\372\363+i@\313QJW\316\236\276\237o\16\236j\361\230lV\27\1\267\366\376\317\312\234"..., 32768) = 32768 read(12, "Q\27\215\216\257{\311\325\245\vS\205\177\313QC\366`\365mz(\35@\4w\21\344~^\237\225"..., 32768) = 32768 read(12, "\264\261:\raM\10\1\217\360\220\225\373K\325\217\373Z|\207[\0048,EB\340j\5\350\177\243"..., 32768) = 30570
read(12, "", 32768)                     = 0
read(12, "", 32768)                     = 0
close(12)                               = 0
munmap(0x7fc65ae81000, 32768)           = 0
access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/cache/1/thumbnail/75x75/9df78eab33525d08d6e5fb8d27136e95/v/4", W_OK) = 0 open("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/cache/1/thumbnail/75x75/9df78eab33525d08d6e5fb8d27136e95/v/4/v40xl_108.jpg", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 12 fstat(12, {st_mode=S_IFREG|0666, st_size=0, ...}) = 0 mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc65ae81000 write(12, "\377\330\377\340\0\20JFIF\0\1\1\0\0\1\0\1\0\0\377\376\0;CREATOR:"..., 1954) = 1954
close(12)                               = 0
munmap(0x7fc65ae81000, 32768)           = 0
access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", F_OK) = 0 access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", F_OK) = 0 lstat("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", {st_mode=S_IFREG|0644, st_size=292714, ...}) = 0 open("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", O_RDONLY) = 12 fstat(12, {st_mode=S_IFREG|0644, st_size=292714, ...}) = 0
lseek(12, 0, SEEK_CUR)                  = 0
read(12, "\377\330\377\340\0\20JFIF\0\1\2\1\0H\0H\0\0\377\341\31\366Exif\0\0II"..., 8192) = 8192
lseek(12, 14042, SEEK_SET)              = 14042
read(12, "\377\341\32\250http://ns.adobe.com/xap/1.0/"..., 8192) = 8192
lseek(12, 24030, SEEK_SET)              = 24030
read(12, "\377\356\0\16Adobe\0d@\0\0\0\1\377\333\0\204\0\1\1\1\1\1\1\1\1\1\1\1"..., 8192) = 8192
close(12)                               = 0
access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", F_OK) = 0 access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", F_OK) = 0 access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", F_OK) = 0 lstat("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", {st_mode=S_IFREG|0644, st_size=292714, ...}) = 0 open("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", O_RDONLY) = 12 fstat(12, {st_mode=S_IFREG|0644, st_size=292714, ...}) = 0
lseek(12, 0, SEEK_CUR)                  = 0
read(12, "\377\330\377\340\0\20JFIF\0\1\2\1\0H\0H\0\0\377\341\31\366Exif\0\0II"..., 8192) = 8192
lseek(12, 14042, SEEK_SET)              = 14042
read(12, "\377\341\32\250http://ns.adobe.com/xap/1.0/"..., 8192) = 8192
lseek(12, 24030, SEEK_SET)              = 24030
read(12, "\377\356\0\16Adobe\0d@\0\0\0\1\377\333\0\204\0\1\1\1\1\1\1\1\1\1\1\1"..., 8192) = 8192
close(12)                               = 0
access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/v/4/v40xl_108.jpg", F_OK) = 0 access("/chroot/home/conairin/conairindustries.com/html/media/catalog/product/cache/1/image/265x/9df78eab33525d08d6e5fb8d27136e95/v/4/v40xl_108.jpg", F_OK) = 0 poll([{fd=3, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout) write(3, "\31\3\0\0\3SELECT SUM(order_items.qty_"..., 797) = 797 read(3,

**Comment by aphroz** [comment]
I experience the same issue, here is my queue configuration:

![image](https://cloud.githubusercontent.com/assets/261406/8564012/af281cd2-2546-11e5-878c-650f2db343cd.png)

Actual execution duration is 9-10 minutes.

**Comment by maxiloc** [comment]
@MDowdal @aphroz Hi, can you try to lower down the configuration to 2 and 10 for the two last config and check if the algoliasearch_queue table size is decreasing after the cron job has been started

**Comment by aphroz** [comment]
It takes now 10 seconds:

[image: Inline image 1]

But it will index only 20 products every 5 minutes, right?

**Comment by maxiloc** [comment]
@aphroz @MDowdal

It is kind of impossible to evaluate which are the right settings. It depends a lot on your stores and the server running it.

I added these settings to be able to fine tune the indexing. You will need to find the settings that make you instance able to process for max 4/5 minutes by cron run.

**Comment by MDowdal** [comment]
I applied the changes you've suggested but am watching my 32GB of server memory suddenly double in usage after running the Algolia queue cron job as a single job.  (from 20% to 61.6%) as of this moment.  Seems pretty severe with only 1000 lines in the mySQL table.

**Comment by MDowdal** [comment]
Here's what I got back from server after executing this (Memory usage is now at 66.1% by the way):

"Host "mce138-fs1.nexcess.net" has not been available for a while now to update the status of this task and the task is not reporting back by itself"  

Looks like an issue with the search queue cronjobs in this version.  I'm going to go ahead and leave this disabled for now without a resolution @maxiloc
