### ISSUE TITLE
Category count and products display inconsistent

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#133]
When a category that contains 175k+ products is clicked only 2 products are found, and only 1 is displayed.

![image](https://cloud.githubusercontent.com/assets/261406/8570095/4e33c45c-257e-11e5-8fcd-9ad7cf7abb08.png)

![image](https://cloud.githubusercontent.com/assets/261406/8570105/6133ab26-257e-11e5-90da-141d6b4acd4a.png)

**Comment by aphroz** [comment]
Related to this config:

![image](https://cloud.githubusercontent.com/assets/261406/8570213/384dc8ee-257f-11e5-80c8-f901f2a46d4d.png)

**Comment by maxiloc** [comment]
@aphroz Yes it expected. Why are you using dinstinct ?

**Comment by aphroz** [comment]
I was experimenting ;)

I thought it would not behave like that, however this functionnality will be very useful for us.

**Comment by maxiloc** [comment]
Ok. The implementation of the distinct feature is going to change in a few days to handle grouping of results. The facets count will be computed differently.

**Comment by redox** [comment]
> Ok. The implementation of the distinct feature is going to change in a few days to handle grouping of results. The facets count will be computed differently.

Yeah indeed, right now the counts are computed from the distinct hits (so only from the one kept). We'll change that in the next few days to be computed from all matching hits before the distinct application.
