### ISSUE TITLE
Instant Search only doesn't work on home page

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#135]

**Comment by maxiloc** [comment]
@aphroz Fixed :). Will be available with next release. By the end of the week

**Comment by aphroz** [comment]
Great! thanks

**Comment by arpandevluk** [comment]
I have same problem with this extension. i have properly installed this extension ( version : 1.5.2 ) and it is working for product page and category page but whey i'm trying to search by instant search on home pageit doesn't giving any response.
Can you please help me.
Thanks.

**Comment by maxiloc** [comment]
@arpandevluk Do you have a link where I can see the issue ?

**Comment by arpandevluk** [comment]
Yes
Home page link : http://dkdev1.dollskill.com/ ( here it is not working )
Product page link where it is working fine : http://dkdev1.dollskill.com/minkpink-as-if-top.html

**Comment by maxiloc** [comment]
@arpandevluk It seems that it's not related to Algolia you have javascript errors in the home page, I think when those will be fixed the search will work as expected.

**Comment by arpandevluk** [comment]
ok i'lll try to solve it and if it's work then i let you know..
Thanks.
