### ISSUE TITLE
Slider tolerance

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#137]
Would it be possible to allow a tolerance to non-numeric data in slider facet attributes?

I encounter this error when non-numeric data is stored in slider attributes:
<i>Uncaught Bad facet function for 'slider'</i>

And the search result is not displayed.

The best option would be to remove all non-numeric characters (in, cm, m, etc.).

Otherwise, log the error and display the page result anyway.

**Comment by maxiloc** [comment]
@aphroz Yes the error is expected. I think we are gonna keep it like that for now. We want the developer to see there is something wrong when putting slider for a non numerical attribute
