### ISSUE TITLE
Result page is not responsive

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#138]
The result page is not displayed nicely on mobile devices:
![image](https://cloud.githubusercontent.com/assets/261406/8593337/044ce1ca-2637-11e5-86b4-9c20698e7318.png)

**Comment by Yoshizmo** [comment]
Additionally, jQuery UI sliders do not function on most mobile devices.

**Comment by maxiloc** [comment]
@Yoshizmo point out this link on #156  https://github.com/furf/jquery-ui-touch-punch

**Comment by redox** [comment]
> @Yoshizmo point out this link on #156 https://github.com/furf/jquery-ui-touch-punch

It seems to be a nice quick-win before our `instantsearch.js` widgets suite.

**Comment by Yoshizmo** [comment]
For touch-punch to work jQueryUI needs mouse, draggable, and maybe widget.
I'm having difficulty adding these on top of bundle.min.js
Could they be added into: https://github.com/algolia/algoliasearch-extensions-bundle ?
