### ISSUE TITLE
Filter navigation: No results found matching

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#139]
When I filter the search result and no matches are found I have to go back using the browser button because the filter navigation disappears and there is only the message 'No results found matching""'.

I'd like to keep the filter navigation even if there are no results in the instant search.

**Comment by maxiloc** [comment]
You should have a Clear button see => http://magento.algolia.com/catalogsearch/result/?q=ade&instant=1#q=adezdez&page=0&refinements=%5B%5D&numerics_refinements=%7B%7D&index_name=%22magento_default_products%22

**Comment by aphroz** [comment]
Yes, but it will clear all the filters and search terms.

**Comment by maxiloc** [comment]
@redox What do you think ?

**Comment by redox** [comment]
Yeah I think it makes sense. We should be able to display the sidebar even if there are no results with the help of the underlying helper.
