### ISSUE TITLE
Associated Group Products

### ISSUE THREAD

**Issue by shurhold** [algolia/algoliasearch-magento#140]
We as many people do use group products to show a group of similar products.  In our case a brush that comes in 4 stiffnesses.  We have the group visible and the individual products not.  This forces people to shop from the group page.  The issue is when we want to rank by units sold these group pages are ignored.  This page should be ranked based on its associated products within.

**Comment by maxiloc** [comment]
@shurhold Yes it's done on the latest version :smile:

**Comment by redox** [comment]
@maxiloc It's only available since the non-published 1.3.5, isn't it?

**Comment by maxiloc** [comment]
No this one was handle before 1.3.4. Still I fixed other issues regarding grouped products in 1.3.5

**Comment by redox** [comment]
:+1:

**Comment by shurhold** [comment]
@maxiloc  Should I wait for 1.3.5 (When?) or install 1.3.4

**Comment by redox** [comment]
@shurhold we cannot publish the 1.3.5 to the Magento Connect store right now because of an issue on their side while trying to upload the zip :/ You can already install it from the archive if you want, the 1.3.5 is ready: https://github.com/algolia/algoliasearch-magento/tree/master/releases

**Comment by maxiloc** [comment]
You just need to check your settings and save them (even if everything was good) and reindex the data. Same when 1.3.5 will be available
