### ISSUE TITLE
Allow to exclude stores from indexing

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#141]

**Comment by maxiloc** [comment]
@redox Is that something we want ?

**Comment by redox** [comment]
What would the use-case be? One single Magento instance with multiple stores and you don't want to add the search feature on one of them?

**Comment by maxiloc** [comment]
I am not sure exactly sure. It was ask by a client by email. I am gonna ask him

**Comment by maxiloc** [comment]
I am closing this for now. Since I have no news from the customer
