### ISSUE TITLE
Disjunctive facets not working on page reload

### ISSUE THREAD

**Issue by Yoshizmo** [algolia/algoliasearch-magento#146]
This commit breaks disjunctive facets on page reload:
https://github.com/algolia/algoliasearch-magento/commit/b0a799455734f551e41e44f71cff591b54ab7aa3

In the updateUrl() function disjunctive facets are being added to the URL in a different way then conjunctive. Adding both types to the URL in the same way fixes the issue for me.

/** Get refinements for disjunctive facets **/
            for (var refine in helper.state.disjunctiveFacetsRefinements)
            {
                var r = {};

                r[refine] = helper.state.disjunctiveFacetsRefinements[refine];

                refinements.push(r);
            }

**Comment by maxiloc** [comment]
@Yoshizmo yes I am fixing it right now

**Comment by Yoshizmo** [comment]
Thanks, I was on your chat with someone and I can hear the beeps that they are talking to me but it shows chat is offline so I couldn't continue with them.
