### ISSUE TITLE
Ability to disable the automatic-indexing

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#147]
You sometimes just want to disable the automatic indexing (add/update/removal of products) for a while. We could add an (Advanced) option that if enabled would just `return` instead of building the indexing jobs.

**Comment by namamai** [comment]
The issue stems from if you are using a Data Feed to automatically update your product's on a regular basis, a product might be saved, updated & indexed multiple times per day. With over 30,000 products this can quickly lead to a rather large number of operations taking place. Alternatively an option might be to limit the number of times a product can be queued/indexed with Algolia per day/week especially when only the product quantity has been updated.

**Comment by maxiloc** [comment]
@namamai I think we are gonna go with the option in the advanced panel, because limiting the number of time a product can be queued can resolve in issues regarding synchronization between magento database and algolia indices.

**Comment by maxiloc** [comment]
This is already possible by setting the "Algolia Search" indexer mode to manual.

**Comment by maxiloc** [comment]
This can be done in System > Index Management

**Comment by redox** [comment]
@maxiloc If the queue is enabled; are we sure we're not gonna queue all jobs in there even if the indexer is disabled? So even if it will not index because the indexer is disabled, we may have a hard time when we enable again afterward.

**Comment by maxiloc** [comment]
@redox yes It is stop way before by magento

**Comment by redox** [comment]
:+1:

**Comment by namamai** [comment]
Unfortunately manually re-indexing a couple of times a day actually leads to a rather large number of operations (more then before). As it is re-indexing the entire collection instead of just what's changed.

**Comment by maxiloc** [comment]
@namamai I get your point. I am gonna check what we can do to avoid that.
