### ISSUE TITLE
no results on catalogsearch

### ISSUE THREAD

**Issue by ZayLong** [algolia/algoliasearch-magento#148]
I get no results whenever I try to search. 

No errors.

The instant search works. 

Search engine is set to Mysql Fulltext .

What am i missing here?

**Comment by redox** [comment]
Hi @ZayLong,

what do you mean by "try to search" if "the instant search works"? Could you provide us an URL to test? Could you check if you have some Javascript errors in your console? Also, do you see generated AJAX calls when you search?

**Comment by ZayLong** [comment]
Catalogsearch returns zero results.

URL: http://staging.theindustrysource.com/

I see no generated AJAX and there are no javascript errors in the console.

**Comment by ZayLong** [comment]
the instant "search while you type" works.

but the actual catalogsearch results page does not.

**Comment by redox** [comment]
Oh, from what I understand the search results page is just not enabled with Algolia; you need to enable it from here:

<img width="633" alt="screen shot 2015-07-17 at 11 32 27" src="https://cloud.githubusercontent.com/assets/29529/8754323/9282fe52-2c77-11e5-876e-2cea93c32601.png">

**Comment by ZayLong** [comment]
Trying that but wound up with a 500 internal error. Weird. 
Thanks for the prompt replies btw

**Comment by redox** [comment]
Interesting, are you using our last 1.3.5 release? Are you able to get the exceptions in the logs?

**Comment by ZayLong** [comment]
Using version 1.3.5

Managed to turn it on, still no results, However I DO get this error in the log when typing

Uncaught TypeError: Cannot use 'in' operator to search for 'length' in []
isArraylike @ bundle.min.js?version=23:13207.jQuery.extend.map @ bundle.min.js?version=23:13getSuggestionsHtml @ bundle.min.js?version=23:20render @ bundle.min.js?version=23:20render @ bundle.min.js?version=23:20(anonymous function) @ ?q=polish:1005(anonymous function) @ bundle.min.js?version=23:9

**Comment by redox** [comment]
I'll need more help from Magento gurus now :) cc @maxiloc ?

**Comment by ZayLong** [comment]
Also on certain product pages I get this error

Failed to load resource: the server responded with a status of 400 (Bad Request)
bundle.min.js:10 Uncaught AlgoliaSearchError: String not allowed outside of params near line:1 column:276

**Comment by maxiloc** [comment]
Ok I'll look into it

**Comment by maxiloc** [comment]
@ZayLong
So I see two things:
- First you have this error in your console "Uncaught [Algolia] Invalid instant-search selector: .daemon"
 you probably want to set it to .main
- From the looks of your indices it seems your are on the last version, but I am not able to see the right user agent. Did you install it from the magento connect store ?

It will be easier to debug via the live chat, you can access it via the https://algolia.com there is a need help button. You can start a conversation and ask for me.

**Comment by ZayLong** [comment]
I changed that just to see what would happen. It doesn't relate to the issue as far as I can tell. I changed it back to main

I installed the extension manually without magento connect.

Ill do that now.

**Comment by redox** [comment]
> Failed to load resource: the server responded with a status of 400 (Bad Request)
> bundle.min.js:10 Uncaught AlgoliaSearchError: String not allowed outside of params near line:1 column:276

OK, so that one is related to https://github.com/algolia/algoliasearch-extensions-bundle/issues/1

**Comment by ZayLong** [comment]
The issue is partially fixed however the main search still doesn't return any results.

I think this 500 internal server error is related, whenever I try to save a configuration

2015-07-17T23:00:03+00:00 ERR (3): Warning: flock() expects parameter 1 to be resource, boolean given  in /mnt/magento/app/code/core/Mage/Index/Model/Process.php on line 479

**Comment by ZayLong** [comment]
Ah the issue seemed to be alot more simple than I thought

2015/07/17 19:54:41 [warn] 2050#0: *1338 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000168, client: 68.60.67.48, server: staging.theindustrysource.com, request: "POST /index.php/admin/system_config/save/section/algoliasearch/key/337db7ccc36a439a6d397b3c2e666d68694a9aa83ef18172cd894c054af759d4/ HTTP/1.1", host: "staging.theindustrysource.com", referrer: "http://staging.theindustrysource.com/index.php/admin/system_config/edit/section/algoliasearch/key/382e51abef0500b98a2923782feb53ea1fd66e02a20c52e6bb72aceaacfbb43d/"
2015/07/17 19:54:41 [crit] 2050#0: *1338 pwrite() "/var/lib/nginx/tmp/client_body/0000000168" failed (28: No space left on device), client: 68.60.67.48, server: staging.theindustrysource.com, request: "POST /index.php/admin/system_config/save/section/algoliasearch/key/337db7ccc36a439a6d397b3c2e666d68694a9aa83ef18172cd894c054af759d4/ HTTP/1.1", host: "staging.theindustrysource.com", referrer: "http://staging.theindustrysource.com/index.php/admin/system_config/edit/section/algoliasearch/key/382e51abef0500b98a2923782feb53ea1fd66e02a20c52e6bb72aceaacfbb43d/"
2015/07/17 19:54:50 [warn] 2050#0: *1345 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000169, client: 68.60.67.48, server: staging.theindustrysource.com, request: "POST /index.php/admin/system_config/save/section/algoliasearch/key/337db7ccc36a439a6d397b3c2e666d68694a9aa83ef18172cd894c054af759d4/ HTTP/1.1", host: "staging.theindustrysource.com", referrer: "http://staging.theindustrysource.com/index.php/admin/system_config/edit/section/algoliasearch/key/382e51abef0500b98a2923782feb53ea1fd66e02a20c52e6bb72aceaacfbb43d/"
2015/07/17 19:54:50 [crit] 2050#0: *1345 pwrite() "/var/lib/nginx/tmp/client_body/0000000169" failed (28: No space left on device), client: 68.60.67.48, server: staging.theindustrysource.com, request: "POST /index.php/admin/system_config/save/section/algoliasearch/key/337db7ccc36a439a6d397b3c2e666d68694a9aa83ef18172cd894c054af759d4/ HTTP/1.1", host: "staging.theindustrysource.com", referrer: "http://staging.theindustrysource.com/index.php/admin/system_config/edit/section/algoliasearch/key/382e51abef0500b98a2923782feb53ea1fd66e02a20c52e6bb72aceaacfbb43d/"
2015/07/17 19:56:04 [warn] 2050#0: *1347 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000170, client: 68.60.67.48, server: staging.theindustrysource.com, request: "POST /index.php/admin/system_config/save/section/algoliasearch/key/337db7ccc36a439a6d397b3c2e666d68694a9aa83ef18172cd894c054af759d4/ HTTP/1.1", host: "staging.theindustrysource.com", referrer: "http://staging.theindustrysource.com/index.php/admin/system_config/edit/section/algoliasearch/key/382e51abef0500b98a2923782feb53ea1fd66e02a20c52e6bb72aceaacfbb43d/"
2015/07/17 19:56:04 [crit] 2050#0: *1347 pwrite() "/var/lib/nginx/tmp/client_body/0000000170" failed (28: No space left on device), client: 68.60.67.48, server: staging.theindustrysource.com, request: "POST /index.php/admin/system_config/save/section/algoliasearch/key/337db7ccc36a439a6d397b3c2e666d68694a9aa83ef18172cd894c054af759d4/ HTTP/1.1", host: "staging.theindustrysource.com", referrer: "http://staging.theindustrysource.com/index.php/admin/system_config/edit/section/algoliasearch/key/382e51abef0500b98a2923782feb53ea1fd66e02a20c52e6bb72aceaacfbb43d/"

**Comment by maxiloc** [comment]
@ZayLong Have you try to clean the directory /var/lib/nginx/tmp ?

**Comment by ZayLong** [comment]
in an older version of this extension that I used I could select Algolia under Configuration > Catalog >Search Engine

In this new version I cannot and only have Mysql fulltext as an option. 

I'm running magento enterprise 1.12.0.2

Is this supported?

**Comment by maxiloc** [comment]
So for the record. GroupsCatalog2 (and possibly other extension) also rewrites the Mage_CatalogSearch_Model_Resource_Fulltext_Collection. Magento without any warning just choose one (I do not know if it's random or not) which make the algolia rewrite uncallable.

One way to fix it is to extends one of the two rewrites from the other
```
class Netzarbeiter_GroupsCatalog2_Model_CatalogSearch_Resource_Fulltext_Collection
extends Algolia_Algoliasearch_Model_Resource_Fulltext_Collection
```

**Comment by ZayLong** [comment]
@maxiloc 

Helped me in resolving this issue;

there was a conflict with another extension *Netzabeiter_GroupsCatalog2* that was still pulling from mysqlFulltext,

having this extension extend its class from
 ```php Algolia_Algoliasearch_Model_Resource_Fulltext_Collection ```

instead of the default ```php Mage_CatalogSearch_Model_Resource_Fulltext_Collection ```
solved the problem

Thanks!

**Comment by redox** [comment]
:+1:
