### ISSUE TITLE
"One or more of the indexes are not up to date" warning message when an existing product is updated

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-magento#149]
When an existing product is updated via the admin panel, the a warning message remains displayed on every screen of admin UI.

![image](https://cloud.githubusercontent.com/assets/1101220/8775850/7f1b7c3c-2eec-11e5-9b24-a4085e730725.png)

That doesn't seem to have any bad impact on indexing, all updates seem properly indexed on the Algolia side.

**Comment by maxiloc** [comment]
Exepected to avoid reindexing categories on product update. The count is false so a reindexing is needed
