### ISSUE TITLE
Replace categories without HTTP redirect

### ISSUE THREAD

**Issue by Yoshizmo** [algolia/algoliasearch-magento#151]
It's possible to replace categories without using the PHP HTTP redirect header('Location: '.$url); in Observer.php (Should be nicer for page load speed, SEO, and Bots)

- Comment out the if statement in Observer.php in function controllerFrontInitBefore `if (Mage::app()->getRequest()->getControllerName() == 'category' && Mage::app()->getRequest()->getParam('category') == null)`
- Replace:
 `$isSearchPage = Mage::app()->getRequest()->getParam('instant') != null || Mage::app()->getRequest()->getParam('category') != null;`
in topsearch.phtml with something like:

```php
// Get selected category path
if($config->replaceCategories()) {
	$category = Mage::registry('current_category');
}

$isSearchPage = Mage::app()->getRequest()->getParam('instant') != null || $category != null;

if($config->replaceCategories() && $category) {
	$category->getUrlInstance()->setStore(Mage::app()->getStore()->getStoreId());

	$path = '';
	
	foreach ($category->getPathIds() as $treeCategoryId) {
		if ($path != '') {
			$path .= ' / ';
		}
	
		$path .= $product_helper->getCategoryName($treeCategoryId, Mage::app()->getStore()->getStoreId());
	}
	
	$indexName = $product_helper->getIndexName(Mage::app()->getStore()->getStoreId());
	$hash_path = '#q=&page=0&refinements=%5B%7B%22categories%22%3A%5B%22'.$path.'%22%5D%7D%5D&numerics_refinements=%7B%7D&index_name=%22'.$indexName.'%22';
}
```
- Right before `algoliaBundle.$(function($) {` in topsearch.phtml add:
```php
<?php
		if($config->replaceCategories() && $hash_path != null)
		{
			echo "if(!location.hash) { document.location.hash = '".$hash_path."'; }";
		}
	?>
```

**Comment by maxiloc** [comment]
@Yoshizmo Yes I agree it would be better to avoid the header() call. The thing is with your solution I am not sure on how you define $hash_path in the topsearch.phtml.

**Comment by Yoshizmo** [comment]
the $hash_path only needs $path (category path) and $index (which comes from the helper, already loaded in topsearch.phtml line 5)
So you can just generate it on page load instead of on the Observer. It's set at the bottom of this IF: `if($config->replaceCategories() && $category) {` from the post above

**Comment by Yoshizmo** [comment]
@maxiloc Oh I tweaked my category paths to use ' / ' instead of ' /// ', you might need to change that in the code above

**Comment by maxiloc** [comment]
@Yoshizmo Thanks

**Comment by maxiloc** [comment]
In case of conflict with other extensions rewriting fulltext_collection and/or fulltext (like in #148) we will have a working extension. We will not be able to have the backend implementation behind for seo but at least it will work :smile: @redox

**Comment by Yoshizmo** [comment]
Sorry @maxiloc it seems upon testing this patch I made breaks product pages, I'm looking at a fix and I'll let you know what I come up with.

**Comment by maxiloc** [comment]
@Yoshizmo Works fine for me

**Comment by maxiloc** [comment]
@Yoshizmo oh yes not always. I am on it too

**Comment by Yoshizmo** [comment]
@maxiloc try this:
`// Get selected category path
if($config->replaceCategories() && !Mage::registry('current_product')) {
	$category = Mage::registry('current_category');
}'

**Comment by maxiloc** [comment]
@Yoshizmo Yes almost the same :smile:

**Comment by Yoshizmo** [comment]
I like yours better ;)
