### ISSUE TITLE
I want to remove left navigation of algoliasearch and i want to add my custom left block....

### ISSUE THREAD

**Issue by rajansahota** [algolia/algoliasearch-magento#152]
I want to remove left navigation of algoliasearch and I want  to add my custom left block.
How to do it. I tried in  algoliasearch.xml also topsearch.phtml but not working. 
Also when i am trying disable the module in magento admin panel "system->configuration->advance" but not disabling the module. 
please suggest.

**Comment by maxiloc** [comment]
To remove the left navigation. You just need to remove all facets value in System > Configuration > AlgoliaSearch > Instant Search Results Page Configuration > Facets
