### ISSUE TITLE
Browser incompatibility with IE8 in bundle.min.js

### ISSUE THREAD

**Issue by Yoshizmo** [algolia/algoliasearch-magento#154]
SCRIPT438: Object doesn't support property or method 'isFrozen'
File: bundle.min.js, Line: 5, Column: 22974

**Comment by vvo** [comment]
Thanks @Yoshizmo for reporting this, we are going to fix asap.

**Comment by vvo** [comment]
This was fixed in the helper: https://github.com/algolia/algoliasearch-helper-js/commit/e9898f97d2ab06e7fc7c6e19c4e7a4825be03d13

Now waiting for a helper release.
