### ISSUE TITLE
Entering nothing into the top search and pressing enter brings you to the same page instead of catalogsearch/result/

### ISSUE THREAD

**Issue by Yoshizmo** [algolia/algoliasearch-magento#155]

**Comment by maxiloc** [comment]
@Yoshizmo Yes that's not an issue with the extension but with Magento. Do you have a way to fix that ?

**Comment by maxiloc** [comment]
Because the request does not go through the "hook" if the query is empty

**Comment by Yoshizmo** [comment]
@maxiloc I didn't realize it was a magento "feature" I'll see what I can find

**Comment by maxiloc** [comment]
@Yoshizmo Found a way :smile:
