### ISSUE TITLE
jQuery UI Sliders do not function on mobile devices

### ISSUE THREAD

**Issue by Yoshizmo** [algolia/algoliasearch-magento#156]
jQueryUI sliders do not function on mobile devices.
It is possible to use this workaround https://github.com/furf/jquery-ui-touch-punch

It requires jQueryUI Draggable and Mouse. Can you add these to bundle.min.js?

Or do you have advice on adding individual jQueryUI components? I can't seem to get it to work.

**Comment by maxiloc** [comment]
Let's put it with #138
