### ISSUE TITLE
Product sale does not trigger rebuild

### ISSUE THREAD

**Issue by Yoshizmo** [algolia/algoliasearch-magento#158]
Product sale does not seem to be adding a rebuild action into the algoliasearch_queue.
Product stock_qty needs to be updated as well as in_stock

In my particular use-case I need products that become out of stock to be removed from the index all together.

**Comment by maxiloc** [comment]
@Yoshizmo I have no idea how the sale event is handle by the magento backend. Do you have an idea how to handle this ?

**Comment by Yoshizmo** [comment]
I'll take a look on Monday.

**Comment by Yoshizmo** [comment]
I think our best bet is to observe this event, and not the sale
cataloginventory_stock_item_save_after

I'll work on it and let you know what I come up with.
