### ISSUE TITLE
Deleted products stays in the index

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#159]
I deleted ~40'000 products and re-indexed (twice), the products are still present in the index.

**Comment by maxiloc** [comment]
@aphroz You should clear the index before reindexing

**Comment by aphroz** [comment]
Ok, so every time I delete a product I have to clear the index?

**Comment by maxiloc** [comment]
No I have just tried it (via the magento admin backend), it is supposed to get deleted automatically. But it case it do not work you need to clear the index.
