### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'AlgoliaSearch/Version.php'

### ISSUE THREAD

**Issue by mkumar11** [algolia/algoliasearch-magento#160]
I installed algolia search from magento connect and run compilation from admin and getting "Fatal error: require_once(): Failed opening required 'AlgoliaSearch/Version.php".

**Comment by maxiloc** [comment]
@mkumar11 It seems that you didn't install the extension correctly. Did you install it from magento connect ?

**Comment by mkumar11** [comment]
yes. when compilation is disable its working fine

**Comment by maxiloc** [comment]
@mkumar11 Indeed I am going to fix this asap

**Comment by mkumar11** [comment]
ok thanks.

**Comment by maxiloc** [comment]
Fixed with :
- 07c53853e004c2f409136396f052b90bf48e75bf
- c0c6cf403276cc06bfdd75ccacda7705284cf771
- 5dac9f966e606714bbe2785cfbc6e7fb16205474
- 92d35c9ed36b4ebfe1b3acf8105bfa2f74efdf82

@mkumar11 Will be available with today's release
