### ISSUE TITLE
Have a staging mode when number of product reindex is limited

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#162]

**Comment by redox** [comment]
I'm not convinced by such approach; we don't do that in any of our integrations. It's complex to implement and source of a lot of potential issues.

 * If that's to "save" Algolia operations I think it's the wrong way to deal with it.
 * If that's to speed up the staging environment, I would rather recommend to either disable the indexing or decrease the number of records.

**Comment by maxiloc** [comment]
The issue for the client who ask for it was about number of records not operations. And I think it can make sense, if you have an dev instance and a prod instance with both around 20k products. With slaves you will reach the 100k and need to change the plan. But if you have a limit of products for the dev instance that can be indexed something like 200 or 300 you can stay bellow 100k.

What I was thinking was just to put the limit when you reindex everything. Saving a product will index it anyway.

@redox What do you think ?

**Comment by redox** [comment]
I would not implement anything special for that. It doesn't make sense to index only a part of the catalog. If the number of operations is the problem, they should decrease the catalog size.

**Comment by maxiloc** [comment]
Ok closing this
