### ISSUE TITLE
Date type attribute

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#164]
It would be nice to have a date facet type with a calendar

**Comment by maxiloc** [comment]
@aphroz What is your use case ?

**Comment by aphroz** [comment]
I am trying to sort by creation date

**Comment by maxiloc** [comment]
Sorting on date is already possible and does not require facets.

If you want a facet yes you will need a new facet type.

Do you have an idea how you want it to be displayed ?

**Comment by aphroz** [comment]
You mean by creating an index? I would need not only to sort by date but also to select a specific date range.

I imagine that a good solution would be to use a calendar like in the magento advanced search:

![image](https://cloud.githubusercontent.com/assets/261406/8986082/c01b185a-36da-11e5-97d3-34f7d68aa790.png)

**Comment by maxiloc** [comment]
@aphroz Ok will see what we can do about that

**Comment by maxiloc** [comment]
We are working on an instansearch.js library, and waiting for it to be available to develop the date facet as a widget.

**Comment by maxiloc** [comment]
Duplicate of #206
