### ISSUE TITLE
Improve analytics tracking by adding tags

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-magento#166]
Would be great to be able to track more precisely search usage using [AnalyticTags](https://www.algolia.com/doc/ruby#analyticsTags)

We could for instance track if the search is used
* source => "instant-search" | "autocomplete"
* deviceType => "desktop" | "tablet" | "mobile" (could be based on the screen with or some JS http://www.abeautifulsite.net/detecting-mobile-devices-with-javascript/)
* ...

**Comment by bobylito** [comment]
Yep I think that's great! We were thinking of something similar in the client and helper with @vvo. But more based on the header sent by the client. A way to let libraries that use the client to enhance the string sent to algolia. What do you think, @seafoox ?

**Comment by redox** [comment]
I don't think we need to add a new header for that, especially if it's "only" to combine our tags and the user's ones.

I'm happy with the analytics tags but I would not go for any `deviceType` tags -> that should be based on the user-agent. OK for the `source`, do you see something else @seafoox ?

**Comment by maxiloc** [comment]
So we have instant-search, autocomplete, backend-search
