### ISSUE TITLE
Exclude categories

### ISSUE THREAD

**Issue by refueledinc** [algolia/algoliasearch-magento#167]
Can you please add the ability to exclude certain categories from search, similar to what you've done with pages?

**Comment by maxiloc** [comment]
@refueledinc With pages magento has by default pages that are not for the end user, for categories it is not the case. Can you give me a bit more detail about your use case ?

**Comment by refueledinc** [comment]
For example, we currently have a category page that is set to "static block only" and the search box is showing on this page, when it really doesn't make sense to have it on that page. Being able to exclude certain categories would be a nice feature to have.

**Comment by refueledinc** [comment]
It looks like I may have resolved my issue by changing the default layout template and targeting a different container class, but it would still be nice to exclude categories, if at all possible.

**Comment by maxiloc** [comment]
@refueledinc Ok, I need to check the impact this could have. I will keep you posted.

**Comment by baltechies** [comment]
:+1:

**Comment by maxiloc** [comment]
@refueledinc @baltechies It's done will be available by the end of the week with 1.4.1 release. There will be no need to configure anything. We will not replace categorie that have a display mode of static block.

For static block + product. We add the static block at the top of the instant search.

Should be good :smile:

**Comment by refueledinc** [comment]
@maxiloc Thank you!

**Comment by davis2125** [comment]
@maxiloc I would be nice to exclude certain categories. My example is I have some products that are in multiple categories. I'd like to be able to exclude, for example, Shop By Brand category as it would be redundant. Hope this makes sense.
