### ISSUE TITLE
Special price is displayed even after reindexation

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#170]
I have never set any special price, however the value "special_price" is present in the index of Algolia. I reindexed and special prices are still there.

Is there a way to fix this without clearing the index?

**Comment by maxiloc** [comment]
@aphroz If there a special price it means somehow magento find a different price applicable to the product. If you do not use it at all, you can modify the template here https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L164-L171 to not display the special price.

**Comment by aphroz** [comment]
I may use them at some point, but I have searched the whole database and this value may have been the old price value. However this value doesn't seem to be updated after reindexation.

**Comment by maxiloc** [comment]
The computation is done by magento directly, so I do not have a clear idea about what could be the cause. If you find a way to reproduce it on a clean magento instance I will be happy to investigate.

**Comment by aphroz** [comment]
This is the Algolia index:
![image](https://cloud.githubusercontent.com/assets/261406/9247033/6425a57a-41b0-11e5-9515-a1947d0ce115.png)

You mean that Magento is sending these values to Algolia at every re-index? If these values become null, the index of Algolia will be aware of it?

One solution to would be clear the Algolia index, and then reindex to see if these values come back.

**Comment by maxiloc** [comment]
Yes the record is recreated at each update so clearing the index won't change anything

**Comment by aphroz** [comment]
I cleared the index and re-indexed and now the prices are correct.

**Comment by maxiloc** [comment]
Are you using partilalUpdates ? This would explain why.

**Comment by aphroz** [comment]
Yes indeed. But it doesn't seem logical.

**Comment by maxiloc** [comment]
Yes the special price is set only if there is a special price found. So in case of a partial update it will not remove the old value. I can fix it

**Comment by maxiloc** [comment]
ac338f83f194d9ff9b8ad2f7d0123d6682f57d39 This one should fix the issue.
