### ISSUE TITLE
Customer groups and indices

### ISSUE THREAD

**Issue by refueledinc** [algolia/algoliasearch-magento#172]
Is there a better way of indexing price for customer groups rather than creating an index for each customer group?

For example, we have a magento multi-store. Store 1 has 120,000 products. Store 2 has 30,000 products. Each store has 5 customer groups and several sorts.

In total, Algolia is showing 50 indices and we stopped sync at nearly 700,000 records which is probably only a small fraction of the total records needed.

From a financial point of view, the way customer group data is stored seems to be inefficient. Is there another way to do this without creating so many records/indices? 

We currently have a "Growth" subscription, but it's possible we might discontinue use of Algolia if we can't find a way around the record count issue. 

As a note, we are considering removing a few sort indices, but that only makes a small dent in the total record count.

**Comment by halley124** [comment]
Hello there,

We perfectly understand your issue issue. The fact is that to allow such a speed, we have to compute and include directly in the index part of the relevance score. Think of it as pre-computing the relevancy score. That imposes to have one index per ranking logic (so one per sort). 

That being said we're working on an optimization for the customer groups on Magento that should lower this multiplier effect.

Stayed tune on this back, it's back to high priority!

**Comment by refueledinc** [comment]
Thanks for the feedback! We're looking forward to optimization. In the meantime, we're going to remove a few sorts and one redundant customer group and see how much this helps.

**Comment by maxiloc** [comment]
@refueledinc I made the changes. It will be available in tomorrow's release.

I am at the minimum possible of record possible to handle the group price feature which is:

1 index/store/product
+ 1 index/price sort/group/store/product
+ 1index/non price sort/store/product

Which means that for a store with:
- 100 products
- 5 customer groups
- 2 sorts on price (asc, desc)
- 2 sorts on date (asc, desc)

You have 100 + 2*5*100 + 2*100 = 1300

**Comment by refueledinc** [comment]
@maxiloc Excellent work and thank you! We'll download and test when available along with making a few changes on our end. Thanks for getting this done!
