### ISSUE TITLE
Disable Algolia per store

### ISSUE THREAD

**Issue by refueledinc** [algolia/algoliasearch-magento#175]
Is there a way to disable Algolia on a per store basis?

We have a magento multi-store setup and don't have a need for Algolia on one of the stores since it only has a few products. Being able to disable Algolia for that store would be great.

**Comment by maxiloc** [comment]
Right now you can disable autocomplete and instant search on your specific store. But it will still index the data of this store, just not displaying it.

**Comment by refueledinc** [comment]
Yes, exactly. We were hoping to disable the indexing, since it's not necessary to run.

**Comment by maxiloc** [comment]
Ok I letting this open, I will do it for the next release

**Comment by maxiloc** [comment]
@refueledinc I have taken a look at this issue, in fact it is a bit more complicated than I expected.

Why do you need do disable Algolia for some store ? Is it because there is no search ?

**Comment by refueledinc** [comment]
It's not so much that there is no search, it's simply because we don't need anything more than the default magento search as the product line is simple and we don't need to be generating indices (and using up records and operations) on a store where Algolia is not being utilized.

**Comment by maxiloc** [comment]
I am closing this. #185 is more relevant for this issue.
