### ISSUE TITLE
Run cron outside of magento

### ISSUE THREAD

**Issue by refueledinc** [algolia/algoliasearch-magento#176]
Is it possible to run the extension on it's own cron rather than using the magento cron?

We've had issues in the past with long running crons within the magento cron system. Running them outside of magento always fixed the issue.

This would be especially helpful for the initial sync of large stores.

**Comment by maxiloc** [comment]
You can schedule a cron to run magerun => https://github.com/netz98/n98-magerun
You can check how we run it for our dev env here => https://github.com/algolia/algoliasearch-magento/blob/master/dev/bin/start.sh#L22-L24

**Comment by refueledinc** [comment]
@maxiloc is there a way to run the algolia queue via magerun?

**Comment by maxiloc** [comment]
@refueledinc No you need to disable the queue and then run the magerun command => n98-magerun --root-dir=/var/www/htdocs index:reindex algolia_search_indexer

**Comment by refueledinc** [comment]
@maxiloc  Yep, did exactly that. That doesn't seem to sync to Algolia though, does it?
