### ISSUE TITLE
CSS elements too broad - breaks other items on the page

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#178]
Some of the CSS items in algoliasearch.css are a little overly broad, and then end up breaking a bunch of other things in my theme. (My theme isn't based on the RWD/madison island theme either.)

I'm mostly fine in that I'm fixing this for myself. But if I could make a recommendation, it might be helpful to someone else in the future. 

It'd be nice if, where possible, make the IDs/classes such that they're only going to apply to elements in the algolia blocks, etc. 

For example, I've got a variety of box-sizing elements in my theme. So I changed this: 
```
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
*:before,
*:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

to this:

```
#algolia_instant_selector, #algolia_instant_selector *,
#search_mini_form, #search_mini_form * {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
#algolia_instant_selector:before, #algolia_instant_selector:after,
#algolia_instant_selector *:before, #algolia_instant_selector *:after,
#search_mini_form:before, #search_mini_form:after,
#search_mini_form *:before, #search_mini_form *:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

**Comment by maxiloc** [comment]
@sam327 Thanks for reporting.

Yes your are right this would be better, I will do it for the next release. In the meantime if you have any other issue with the default css, feel free to add it to the issue

**Comment by sam327** [comment]
I will do so, thanks. 

I've got some other things I'm working through which I might kick upwards, but I want to make sure the things I ask for are useful to for everyone, and not just personal/site-specific items. 

Though, FWIW, re-skinning to fit my theme's been relatively easy - good stuff overall.

**Comment by refueledinc** [comment]
:thumbsup:

**Comment by vvo** [comment]
@maxiloc where does this reset comes from do you think? I thought we already had namespaced everything, maybe only jquery ui css bundle

**Comment by maxiloc** [comment]
@vvo It's when I made the responsive layout I think

**Comment by maxiloc** [comment]
Will be release in next version. @sam327 Thanks
