### ISSUE TITLE
W3C validation

### ISSUE THREAD

**Issue by aivoris** [algolia/algoliasearch-magento#179]
The module generates lots of errors for W3C validation.
Doctype:	XHTML 1.0 Strict

**Comment by maxiloc** [comment]
@aivoris Yes there is a lot of errors, but most of them are in the Hogan templates which are expected because the validator does not handle that. Do you see any major issue ?

**Comment by maxiloc** [comment]
I think the html produced is ok. Let's close this and re-open it if needed
