### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by aivoris** [algolia/algoliasearch-magento#180]
After installing module i was getting a javascript error. 
File bundle.min.js:
    ...this.id="ui-id-"+ ++uuid...
should be
    ...this.id="ui-id-"+ (++uuid)...

The problem is probably with server gzipping the files and eliminating spaces.

**Comment by redox** [comment]
Hi @aivoris,

thank you for reporting us that. From what I understand, those parenthesis are optional and even if they are in the [original source](https://github.com/jquery/jquery-ui/blob/8bf46a46ad3207c62bcee305ddff50bd13a8ca51/ui/unique-id.js#L34) of JQuery-ui sortable (one of our dependency) our minifier removes it.

That's weird because it looks like valid JS. Can you provide the exact error message + version of the navigator?

**Comment by redox** [comment]
> The problem is probably with server gzipping the files and eliminating spaces.

Oh OK, now I get it -> indeed if you remove the spaces here it will be an issue. Let me check if we can remove the parenthesis removal in uglifyjs.

**Comment by redox** [comment]
So the quick-fix would be to distribute the non-minified version as well.

@vvo any idea?

**Comment by vvo** [comment]
I am not sure to understand.

When does the space removal happens?

Gzip does not removes anything, it only compress things.

Maybe a magento module does that?

**Comment by redox** [comment]
> Maybe a magento module does that?

Yes, that's what I understood :/

**Comment by vvo** [comment]
We can definitely provide the non minified versions in the bundle.

What is the standard way to deliver magento modules using JS? If the recommended way is to deliver them unminified and let magento minify them then we should stop delivering minified versions and let our magento users deal with it.

**Comment by aivoris** [comment]
Hello,
The error: "Uncaught ReferenceError: Invalid left-hand side expression in postfix operation".
Yes it was due to JS minification, not gzipping.

The thread: http://stackoverflow.com/questions/11174170/js-invalid-left-hand-side-expression-in-postfix-operation helped to fix the problem, i thought it was gzip as it was stated in the answer. Just checked it was JS minification problem.

**Comment by vvo** [comment]
@aivoris so how did you fix the problem?

**Comment by maxiloc** [comment]
No news I am closing this, let's re-open it if needed.
I have seen this a couple time and usually it can be fixed by putting a rule to not cache/minify certain file.
