### ISSUE TITLE
Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by refueledinc** [algolia/algoliasearch-magento#183]
This change https://github.com/algolia/algoliasearch-magento/commit/8eeac2b9682ab8f49e341dba6b684acbe49360c8#diff-0f0ec783f20591abcdca6a6d7508f4ebR623 is causing the following error on our site. `Uncaught ReferenceError: Invalid left-hand side in assignment`

**Comment by maxiloc** [comment]
@refueledinc Do not have any error on my side. Do you have 1.4.2 installed ?

**Comment by refueledinc** [comment]
Yes, 1.4.2 is installed.

**Comment by maxiloc** [comment]
Do you have a link where I can see the issue ?

>

-- 

[image: Algolia] <https://www.algolia.com/>

[image: Twitter] <https://twitter.com/maxiloc> [image: Linkedin]
<https://www.linkedin.com/in/maximelocqueville> [image: github]
<https://github.com/maxiloc>

Maxime Locqueville
Full-stack Software Engineer

Website: https://www.algolia.com/
<https://www.algolia.com/#millisecond-matter>
[image: htmlsig.com] <https://www.algolia.com/#milliseconds-matter>

We are hiring! <https://www.algolia.com/jobs#milliseconds-matter>

**Comment by refueledinc** [comment]
Sorry, it looks like it was an update gone bad. I was able to fix it manually. Not really sure how it happened.
