### ISSUE TITLE
Failed opening required after upgrading to 1.4.2

### ISSUE THREAD

**Issue by andrewlynch** [algolia/algoliasearch-magento#184]
Fatal error: require_once(): Failed opening required '/var/www/html/magento/app/code/community/Algolia/Algoliasearch/Helper/AlgoliaSearch/ClientContext.php' (include_path='/var/www/html/magento/app/code/local:/var/www/html/magento/app/code/community:/var/www/html/magento/app/code/core:/var/www/html/magento/lib:.:/usr/share/php:/usr/share/pear') in /var/www/html/magento/app/code/community/Algolia/Algoliasearch/Helper/Data.php on line 7

**Comment by maxiloc** [comment]
How do you update the extension ? Because even if the commit I made fix a potential error, it should work without the fix.

Should be fix with eb9538b10b87afb9c363924929cb46b71f71bf3a
