### ISSUE TITLE
On install - disable everything until index is complete

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#185]
Apologies if this is long...  

When you install the algolia search and put in your various api keys, it instantly takes over the search results. The problem is that none of the indexes have been built yet. This means that for a little bit of time, we have blank search results. 

So I suggest adding a toggle to turn off the search results - so while I'm getting the plugin started, my site continues to use the regular magento catalog search while I get algolia configured and the indexing done. 

Then I can switch on the components manually when the index is ready.

My preferred setup configuration would be something like: 
1. install plugin 
2. add license / api keys
3. configure search options 
4. configure indexing
5. run indexing (all at once or via cron)
6. enable search results
7. enable other features as desired

Didn't really notice while doing development, as I'd installed, then spent a bunch of time doing design stuff... But when I rolled it up to the production environment, I had about 20 minutes of blank search results.

**Comment by maxiloc** [comment]
@sam327 Yes that is link to the #175 issue. To do that we need to find a way to disable Algolia. The thing is the extension goes deep into magento indexing and event system and I didn't yet find a way to handle that correctly.

**Comment by maxiloc** [comment]
We will work on this one for the next release. We have some path to explore. cc @Floddy

**Comment by Floddy** [comment]
Dunno if you've found a way yet, but the solution I've seen the most is:
1. config option, enble, yes/no
2. a helper function that responds true/false if enable is yes, and api key isn't empty
3. for every event observer, start with something like:
public funtion meepevent(Varien_Event_Observer $observer)
{
if(!$helper->isEnabled()) {
    return;
}
4. for blocks, etc, an override of _toHtml:
protected function _toHtml()
{
    if(!$helper->isEnabled()) {
        return '';
    }
    return parent::_toHtml;
}
5. for controllers, pretty much:
public function myAction()
{
    if(!$helper->isEnabled()) {
        parent::myAction();
        return;
    }
}

etc etc. :)

**Comment by maxiloc** [comment]
@Floddy Thanks will have a look at that

**Comment by maxiloc** [comment]
Implemented with 3a87884.

@sam327 Everything will be enabled by default but can easily be disabled afterwards.
You will then be able to do have the exact workflow you described

**Comment by maxiloc** [comment]
Will be available with next release
