### ISSUE TITLE
Showing [object] instead of a price

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#186]
When I enabled the instant search & the autocomplete on my production site, I'm seeing *[object]* instead of the price.

Any idea what might cause this?

**Comment by sam327** [comment]
Found the problem in the index...

in my devsite_default_products, the price field is indexed as *40* 

in my productionsite_default_products, the price field is indexed as *"default": 40*  

So.... how do fix the formatting in the index?

**Comment by maxiloc** [comment]
@sam327 "default": 40 is the new formatting of products that I changed 9 days ago with 1.4.1 release

Two things possible:
- You do not have the same version of the extension installed on both instances
- You might not have done a full reindex when updating the extension to 1.4.1+

**Comment by sam327** [comment]
Yup... It was the latter. 

In my dev site, I'd installed 1.4.0 originally, then upgraded to 1.4.2.  In my production site, I pushed the latest version (1.4.2) up. 

And I missed the force-the-reindex step on dev after the update. Assumed it would do it automatically.
