### ISSUE TITLE
Compatibility with product updates via external sources

### ISSUE THREAD

**Issue by refueledinc** [algolia/algoliasearch-magento#188]
We have a very large store and managing products via magento admin doesn't work for our needs.

We use https://www.mag-manager.com/ to manage products, but it seems your extension does not detect the changes made by the Store Manager.

Prior to Algolia, we were using Sphinx and didn't have any issue with changes from Store Manager becoming available to the search index. 

When making a change in the magento admin I see a record added to  the `algoliasearch_queue` table. When making changes via the Store Manager, no records are added.

Is there a way for the extension to detect changes made to products via external sources? Even doing a full reindex of the store (which takes several hours) doesn't seem to help.

Any ideas?

**Comment by maxiloc** [comment]
We are using the default magento hooks. I can not check if they are triggered correctly by Store Manager simply because I do not have it.

Any help on that will be appreciated

**Comment by refueledinc** [comment]
@maxiloc Can you please clarify what hooks you are using so I can verify with them?

**Comment by maxiloc** [comment]
All hooks and overrides are defined in this file => https://github.com/algolia/algoliasearch-magento/blob/master/code/etc/config.xml

**Comment by Jarchik** [comment]
Is there some ability to run algolia reindex and synchronization via command line?

**Comment by redox** [comment]
> Is there some ability to run algolia reindex and synchronization via command line?

Sure thing @Jarchik, we do it using `n98-magerun` tool while setuping our development environment: https://github.com/algolia/algoliasearch-magento/blob/master/dev/bin/start.sh#L22-L25

**Comment by Jarchik** [comment]
Ohh, thx a lot. :)  But which exactly command runs synchronization with algolia cloud?
As I can see commands above do only reindex of Magento tables. Am I wrong?

**Comment by redox** [comment]
Yes @Jarchik those commands will reindex (re-sync) the whole Algolia indices. We do not have any way to sync only what has been updated since a specific date from the command line.

**Comment by Jarchik** [comment]
Ok, I understand. Is it possible to run re-sync from simple php file?

**Comment by redox** [comment]
> Ok, I understand. Is it possible to run re-sync from simple php file?

n98-magerun is done in PHP, so definitely there must a way but I don't know how to do it. (not sure if it's complex to setup the Magento environment and call the indexers).

**Comment by maxiloc** [comment]
With next release it will be possible to set indexer mode is "Manual update" and then run:

```
php -f indexer.php --reindex algolia_search_indexer
```

It's implemented with 8a76752a61b05309643c24f7d60bc5908ebadb61
