### ISSUE TITLE
How do I handle ampersands?

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#189]
I've got my store set up to include brand names in the search, and I've got a brand with an ampersand in its name, e.g. "Rum & Coke" 

It works in the autocomplete, but if go to the instant search results page, I get blank results.

The URL looks something like this: mysite.com/catalogsearch/result/?q=rum & coke&refinement_key=brand&refinement_value=rum & coke#q=&page=0...

Is it possible to URL-Encode the ampersand in the search term? e.g. "rum%20%26%20coke"

**Comment by sam327** [comment]
Think I've figured this out. A little out of my depth here, so let me know if there's a more preferable way to do this. 

In topsearch.phtml, find the *hit.value*, and wrap it in a encodeURIComponent(). (line 1258 or so)

OLD:
```
hit.url = '<?php echo $base_url; ?>/catalogsearch/result/?q=' + hit.value + '&refinement_key=' + algoliaConfig.autocomplete.additionnalSection[i].attribute + "&refinement_value=" + hit.value;
```
NEW:
```
hit.url = '<?php echo $base_url; ?>/catalogsearch/result/?q=' + encodeURIComponent(hit.value) + '&refinement_key=' + algoliaConfig.autocomplete.additionnalSection[i].attribute + "&refinement_value=" + encodeURIComponent(hit.value);
```

**Comment by maxiloc** [comment]
It's already the case on 1.4.4
