### ISSUE TITLE
Show alternate (secondary) product images on results page

### ISSUE THREAD

**Issue by WesMage** [algolia/algoliasearch-magento#190]
Hello 
To match the ux of the rest of our site, it is possible on search results to show the secondary product image on mouse hover. Please help. 
Thanks

**Comment by redox** [comment]
Hi @WesMage,

the current version of the extension doesn't support it but feel free to update the [PHP code](https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L348-L367) to add more images; and then the Hogan.js [template](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L169-L171) to handle the hover effect.

**Comment by WesMage** [comment]
Hi @redox 
Thanks for the response. I'm not a developer so I'm hoping this can be listed as a feature request and included in future versions of the product? 
Many thanks

**Comment by maxiloc** [comment]
So the secondary images indexing will be available with the new release.
Only thing to do is add 'images' to the attributes.
Then the ui remains to be done and will wait instantsearch.js to be part of the extension.

**Comment by maxiloc** [comment]
As I said the backend code is done. @redox do you think we should do that by default or let the user do it ?

**Comment by redox** [comment]
> As I said the backend code is done. @redox do you think we should do that by default or let the user do it ?

Like Amazon, I would go for a single image in the results list by default + share the code snippet to use if we want to display multiple of them.

**Comment by maxiloc** [comment]
Ok works for me

**Comment by maxiloc** [comment]
Let's close this the documentation task is reference in #238
