### ISSUE TITLE
Image URLs from different website/store

### ISSUE THREAD

**Issue by Floddy** [algolia/algoliasearch-magento#191]
I've seen a lot of the product images getting the URL for the admin store - supposedly when they are indexed from backend, since some images seem to have the correct URL.

Example:
//www.defaulturl.com/media/catalog/product/cache/0/image/265x/9df78eab33525d08d6e5fb8d27136e95/3/1/31766m_l.jpg
Should be:
//www.mystoreviewsurl.com/media/catalog/product/cache/<storeId>/image/265x/9df78eab33525d08d6e5fb8d27136e95/3/1/31766m_l.jpg

A multi site install, which have different URLs for different stores, gets the image URLs built from the default config's baseurl, not the store's baseurl. Also, they're stored in /media/catalog/product/cache/0/... - which is the cache for storeid 0 - the 'admin storeId'.

Same thing for thumbnails.

Possible solution is to emulate the store you're indexing:
http://inchoo.net/magento/emulate-store-in-magento/
A tip on this is to turn the URLs into strings before exiting the emulation, because _toString in the image helper is used in building the image URL.

**Comment by redox** [comment]
Thank you for those valuable informations @Floddy.

We're using `$product->getThumbnailUrl();` (https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L348-L367) to get the URL of an image/thumbnail.

I understand it can be confusing to load images from another domain, but does it have any impact at rendering time? The images are loading, right? Or is your baseURL some kind of "fake" URL and that should never be used?

**Comment by maxiloc** [comment]
@floddy Thanks. We already use emulation on the store but not sure it still an emulation when we generate images. I will check that 
@redox that might be one of the issue we have with thumbnail not generating correctly on some instance. I think we need to set the store before calling the function

**Comment by Floddy** [comment]
@redox that function uses the catalog/image helper :)

I don't think it's that much of a performance issue, other that you get the cache filled up with another copy of the images - but you'll still get that if you're caching images in another size than what's displayed elsewhere. The bigger issue I think is that if you have two somewhat 'unrelated' shops in the same installation, and someone looks at the url for the images (or links it somewhere), you'll see the first store's url in it. You can also have a separate admin url like admin.mysetofstores.com, which the thumbnails would be built from, which would probably break stuff if you are a bit paranoid and uses IP restriction and stuff for that domain name, but I don't think that's very common...

@maxiloc Ah, ok! From what I see you have written your own emulation function, otherwise Magento has a built-in one (as linked above). Setting the stores is a bit risky since that goes 'across the whole board' on that execution and could make other stuff run in the wrong store, if not careful.
