### ISSUE TITLE
Call to a member function initIndex() on null in Magento Version:1.9.1, algoliasearch-magento version: 1.4.4

### ISSUE THREAD

**Issue by PrakashThapa** [algolia/algoliasearch-magento#193]
I got this error when try to reindex  ``index.php/admin/process/reindexProcess/process/7/``

```Fatal error: Call to a member function initIndex() on null in /var/www/html/magento191/.modman/algoliasearch-magento/code/Helper/Algoliahelper.php on line 31```

**Comment by maxiloc** [comment]
@PrakashThapa It just mean that you are trying to reindex without credentials.

I just improve the error handling to avoid such issue in the future.
