### ISSUE TITLE
Create a "popular searches" block that appears on "no results found" pages.

### ISSUE THREAD

**Issue by WesMage** [algolia/algoliasearch-magento#196]
[feature request]
Create a "popular searches" block that appears on "no results found" pages. 
Here is an example from another search product. 
http://search.surfstitch.com/search#w=arkansaw

[I do not know how to add label] please add label "enhancement"

**Comment by WesMage** [comment]
Here is another example of a best practice "no results" page for your consideration/inspiration
http://www.topshop.com/webapp/wcs/stores/servlet/CatalogNavigationSearchResultCmd?langId=-1&storeId=12556&catalogId=33057&Dy=1&Nty=1&beginIndex=1&pageSize=20&Nrpp=20&pageNum=1&Ntt=telescope

**Comment by redox** [comment]
Thank you for contributing @WesMage, we're working on a new UI and will try to take your recommandations into account.

**Comment by maxiloc** [comment]
fixed with ed14ff4. There will be an option to enable the feature
