### ISSUE TITLE
Ability to add the "Add to cart button" in the autocomplete menu

### ISSUE THREAD

**Issue by MrYogi** [algolia/algoliasearch-magento#199]
even after enabling add to cart button option in algolia settings in magento add to cart button not showing. what could be issue, plz help

**Comment by redox** [comment]
Hi @MrYogi,

any chance you changed the hit template? (https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L416-L428) Or maybe it is out of stock -> just look at that Mustache template, you'll see that it's only displayed if in stock.

Feel free to modify it!

**Comment by MrYogi** [comment]
no i didn't changed .and products are in stock.
it is not showing "add to cart" button in instant search suggestions.
my store: http://orderjoy.com/

**Comment by redox** [comment]
Can you do a screenshot? If you're speaking about the dropdown menu that is displayed below the searchbar, it's expected: we don't have the button there.

**Comment by MrYogi** [comment]
ok , then how can this be implemented in drop down product suggestion. like this:
![1234](https://cloud.githubusercontent.com/assets/1777354/9955006/211f1d34-5e0b-11e5-9b72-8a41fc5adff1.jpg)

**Comment by redox** [comment]
Unfortunately, that's not possible right now, the auto-completion menu is not designed to handle such fields/interactions :/

Let's keep this issue open and discuss about it after releasing v1.5

**Comment by maxiloc** [comment]
I am closing this, let's re-open if needed

**Comment by tur-ing** [comment]
Is it already possible to implement the "Add to cart" button in the Algolia search results dropdown?

**Comment by maxiloc** [comment]
cc @redox

**Comment by redox** [comment]
You can already do it by copy/pasting [this code](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L339-L347) somewhere next to [here](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L190); isn't it?

**Comment by valuehaat** [comment]
Hello @redox ,

Is this facility available to add add to cart button in live search ?

**Comment by JanPetr** [comment]
Hello @valuehaat,

as today it's possible to add "Add to cart" button to the results on instant search page.
The extension doesn't support the button on autocomplete results and you need to change [product template](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/autocomplete/product.phtml) to add "Add to cart" button.

**Comment by valuehaat** [comment]
And it will not disturb anything. am i right ?

and i have a question also . is this free or premium , my website is valuehaat.com and i am asking for this site.

**Comment by ProxiBlue** [comment]
Hi @JanPetr 

Adding in teh Add to cart to the autocomplete is fairly easy, but I am struggling with the click on the resulting product info. Basically I cannot seem to prevent that click from also being actioned.

The end result is that the add to cart works, but then the page location also browses to the product in question.
Suggestion how to prevent the click through to the product from being actioned?

**Comment by JanPetr** [comment]
Hello @ProxiBlue,

yes, you've found the right line. It should be enough to just comment it out. Did you try that?

**Comment by bnymn** [comment]
@redox the links are dead. I would like to add add to cart button to instant search results. How can I do this?

**Comment by JanPetr** [comment]
@bnymn That's possible directly from configuration: 
<img width="1258" alt="screenshot 2017-08-08 17 38 52" src="https://user-images.githubusercontent.com/1058144/29095886-87f98722-7c60-11e7-9865-de877646ad1b.png">

**Comment by ProxiBlue** [comment]
@JanPetr 

Yep, all good.
Rather than editing teh module code, I naturally moved teh file to the site skin folder, and laoding the edited version there
```

<algolia_search_handle>
        <reference name="content">
            <remove name="algolia-beforecontent"/>
        </reference>
        <reference name="head">
            <action method="removeItem"><type>js</type><name>algoliasearch/autocomplete.js</name></action>
            <action method="addItem">
                <type>skin_js</type>
                <name>js/build/algoliasearch/common.js</name>
            </action>
            <action method="addItem">
                <type>skin_js</type>
                <name>js/build/algoliasearch/autocomplete.js</name>
            </action>
        </reference>
    </algolia_search_handle>
```

**Comment by bnymn** [comment]
@JanPetr I actually would like to implement something like this image. I am using Magento 2.1. When I enable the feature you mentioned, it does not add `add to cart` button to autocomplete part.

![image](https://user-images.githubusercontent.com/3506402/29121530-435e1526-7ce5-11e7-99ab-0e7dedc16078.png)

**Comment by muthali** [comment]
Hi you could use [expertrec](expertrec.com) search extension to put an add to cart button in your search. You have to request them to enable this as this is a add on feature
![crop](https://user-images.githubusercontent.com/22095803/33983331-d0ff70b6-e0d9-11e7-8b0f-fb18bd040e85.png)

**Comment by chakravarthykalyan90** [comment]
I believe provide configuration is only for instant search page but not for auto-suggestions dropdown.
