### ISSUE TITLE
New facet types

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#206]
Would it be possible to have two more facet types:
- boolean (yes/no)
- date (calendar)

**Comment by maxiloc** [comment]
@aphroz Yes ! We are working on integrating instantsearch.js that should bring those facet types. More info on that coming soon

**Comment by maxiloc** [comment]
- priceRanges added

for boolean and data, I am not yet sure how to expose it in the admin panel since it require a bit of configuration

**Comment by maxiloc** [comment]
- date facet will be able to be done with the numericRefinementList (https://community.algolia.com/instantsearch.js/documentation/#numericrefinementlist)
it's not really a calendar but will be able to handle dates

- boolean will be able to be done with the toggle widget https://community.algolia.com/instantsearch.js/documentation/#toggle

This is already available on develop it just need to be documented and planned here => https://github.com/algolia/algoliasearch-magento/issues/238

So I am closing this
