### ISSUE TITLE
Sort by price doesn't include special price

### ISSUE THREAD

**Issue by andrew-dwyer** [algolia/algoliasearch-magento#208]
Sorting by price currently ignores the special price of a product. This leads to products that are on special being ranked lower than products that aren't, even if their special price is lower.  E.g.

```
{
  name: a
  price: 10
  special:
},
{
  name: b
  price: 15
  special: 5
},
{
  name: c
  price: 20
  special: 2
},

```

**Comment by maxiloc** [comment]
@andrew-dwyer I am currently working on how the extension handles prices. It will be fixed very soon

**Comment by WesMage** [comment]
Hello - this issue also affects filtering by price filter slider.

**Comment by maxiloc** [comment]
@WesMage Yes that will also be fixed

**Comment by maxiloc** [comment]
Fixed on develop, will be release today
