### ISSUE TITLE
Config option to disable tyhe module

### ISSUE THREAD

**Issue by Floddy** [algolia/algoliasearch-magento#212]
When the module is installed, but nothing has been configured, product saving craches because the save event is triggered, and algolia tries to update the index, which fails since there is no API key. So, in order to have even have the module installed, you pretty much have to have an account, and sync the products.

An on/off option, plus a check for an existing API key, sould solve this.

**Comment by maxiloc** [comment]
@Floddy Thanks for reporting this. Actually it's a duplicate issue of #185. So I am closing this.
