### ISSUE TITLE
Order facets

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#214]
It would be great to be able to reorder the facets in the backend using drag and drop or with arrows to move the facet in the facets list.

We have a large number of facets and it's a nightmare to reorder it.

**Comment by redox** [comment]
Hey @aphroz, yes that's an awful limitation of the default Magento configuration panels. Do you have any experience with a module that is allowing that so we can inspire from their code?

**Comment by aphroz** [comment]
I have seen something like that in Unirgy RapidFlow, it seems to
usecriptaculous/dragdrop.js:
http://madrobby.github.io/scriptaculous/draggable/

**Comment by maxiloc** [comment]
Will be available with next release
