### ISSUE TITLE
Price with tax disappeared

### ISSUE THREAD

**Issue by rbrown** [algolia/algoliasearch-magento#222]
Hello, is it intentional in 0c45fa9ddef594f58410f4df25bea3f3ec65923b to stop having the price available in the results page both with and without tax?

**Comment by maxiloc** [comment]
Yes we now better handle price to take the magento configuration into account when generating the price. So no matter what is your configuration it should be good

**Comment by rbrown** [comment]
Hi, sorry, my configuration shows prices with and without tax, I'm not sure how I can do that with the new data?

**Comment by maxiloc** [comment]
If you updated the extension to last version (1.4.7), you can put price in attributes in the configuration, reindex the data. If you have made some customization of topsearch.phtml file you need to update it as well. Last version of the file can be found here https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml
