### ISSUE TITLE
instantsearch.js branch => original price when customer group enabled

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#223]
Need to make this fix 2c904ff233e5a5f59a11bc81f1d21b40b30d8e4d on instantsearch.js branch

**Comment by vvo** [comment]
? Is it an issue for you to track smg? git cherry-pick :dancer:

**Comment by maxiloc** [comment]
No I can not do that it is not handled in the same way with the new version. Otherwise I would have merge develop into instantsearch.js directly

**Comment by vvo** [comment]
But do I need to do smg? Or this is a task for you

**Comment by maxiloc** [comment]
Just for me :smile:
