### ISSUE TITLE
Very large JS packed with Algolia - everything required?

### ISSUE THREAD

**Issue by royandre** [algolia/algoliasearch-magento#227]
Could you elaborate a bit on whether everything in the bundle.min.js that comes with the module is indeed required? The JS is very large and we see some performance issues with this.

**Comment by maxiloc** [comment]
Yes everything is used except jquery-ui sortable (~=20kb)
The bundle is currently 118kb which is not a lot. I think it's ok for what it does.

Can you give me a bit more details regarding your performance issue ?

**Comment by royandre** [comment]
![algoliatimeline](https://cloud.githubusercontent.com/assets/533020/10561782/f02f01e4-7539-11e5-8246-796c982abfb7.png)

After some brief investigation we see the browser spends most of the time rendering the page to handle this particular JS. You can see it in the attached screenshot (example from www.floyd.no), however it can be seen easily on any of (at least) our Magento-installations running Algolia.

When we moved the JS to the bottom of the page we somewhat fixed the issue, as can be seen on www.linio.no as an example.

**Comment by vvo** [comment]
Cool! Thanks for the tip, we have a new magento update coming soon that also have th JS of algolia at the bottom by default
