### ISSUE TITLE
AvS_FastSimpleImport and catalogsearch_resource

### ISSUE THREAD

**Issue by rbrown** [algolia/algoliasearch-magento#228]
If I import products using [AvS_FastSimpleImport](https://github.com/avstudnitz/AvS_FastSimpleImport) it fires of an [event](https://github.com/avstudnitz/AvS_FastSimpleImport/blob/master/src/app/code/community/AvS/FastSimpleImport/Model/Import/Entity/Product.php#L538) to rebuild the catalogsearch index for the affected products. It looks like this extension is [deliberately doing nothing](https://github.com/algolia/algoliasearch-magento/blob/develop/code/Model/Resource/Fulltext.php#L53) to avoid index twice, but because AvS_FastSimpleImport has used ImportExport, no other events that algolia is watching have been fired. Is there an obvious way around that?

**Comment by maxiloc** [comment]
@rbrown Yes I understand the issue. If we remove this condition everytime you update a product both Algolia indexer and catalog search will index, which is not good.
What I would do is listen for "fastsimpleimport_reindex_products_before_fulltext" event and then run Algolia indexer from it
Does that makes sense for you ?

**Comment by rbrown** [comment]
Sort of. And the call the Observer->rebuildProductIndex. Does this miss the point where it checks to see fi a product has parents?

**Comment by maxiloc** [comment]
Yes you will need to add this logic https://github.com/algolia/algoliasearch-magento/blob/master/code/Model/Indexer/Algolia.php#L313-L321 in the event

**Comment by rbrown** [comment]
Great, thanks
