### ISSUE TITLE
1.5.0 Release tasks

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#238]
Quick list of what need to be done (Feel free to update)

### Dev
- [x] No result on instant search page
- [x] Clear configuration

### UX 
- [x] cross when there is a query

### UI
- [x] Make sure the UI is responsive
- [x] Make sure IE>9 is usable

### Documentation
- [x] Document how to update the extension
- [x] Document how to use other widget for a specific attribute
- [x] Explain that insertion/deletion without magento will not trigger updates
- [x] Add a section "when is a full reindex needed" is the documentation
- [x] Make sure the faq is up to date

### Admin panel
- [x] Review wording of admin panel
- [x] Remove the tutorial link and add the FAQ, the changelog, migration guide 
- [x] Add a comment on how to configure the cron job on the queue section

### Dev
- [x] Have a backend bundle for jquery + jquery-ui + angular.js

**Comment by vvo** [comment]
Do you need something from us here @maxiloc?

**Comment by maxiloc** [comment]
@vvo For now it's ok, if you think about something missing outside of development (like marketing things) you can add it here

**Comment by eddyparkinson** [comment]
I have the same issue but with shopify and alogolia.
Any ideas?

**shopify  image**
 I want to use this image

`{{ product.images[0].src }}`

but algolia is using 
`{{ product.images[1].src }}`

e.g.
in  algolia_instant_search_product.hogan.liquid

`  <div class="ais-hit--picture" style="background-image: url('[[# helpers.mediumImage ]][[/ helpers.mediumImage ]]')"></div>`
 
`helpers.mediumImage ` returns product.images[1].src

**Comment by Jerskouille** [comment]
Hi Eddy, could you post your question here : https://discourse.algolia.com/shopify/ ? :)
