### ISSUE TITLE
Customer group and special prices do not get along

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#239]
When 'Customer groups' is enabled, special prices does not work.

How to reproduce:
* Have a product with special price
* Index
    * Special price will show in any search
* Enable 'Advanced'->'Customer groups'
* Index
    * Special price does not show in any search

**Comment by aude** [comment]
'_original_formated' is not set, that's why frontend does not show special price.

Why does it not get set?
Producthelper.php sets data for products. After debugging, it turns out the `// If fetch special price for groups` block (:271-:293) affects $product; $special_price (:295) is not the same whether that block runs or not.

More debugging has to belief that :278 is at the core of the problem. `getPriceModel()->getFinalPrice(1, $product)`, `getPriceModel()->getGroupPrice($product)`, I don't know.

From here, I need assistance from more experienced developers :smile:

**Comment by maxiloc** [comment]
@aude Indeed there was an issue. https://github.com/algolia/algoliasearch-magento/commit/3a2f8f27797d65c73b20bfa2b38e6b617172ea11 should fix it. Can you try it and tell me how it goes.

**Comment by aude** [comment]
It seems to fix the issue. Thanks!
