### ISSUE TITLE
"Min - max" conflicts with special price

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#244]
Given the following situation:

* A configurable product has a price $100
* The associated products have prices $50
* There is a valid special price at $40

An Algolia search will show ~~$100~~ $40. The product view page will show the same.

---

Now, given this other situation:

* A configurable product has a price $100
* The associated products have prices $30 - $50
* There is a valid special price at $40

An Algolia search will show $30 - $50. The product view page will show ~~$100~~ $40.

---

I think the product view page is showing correct price in the latter case. Feel free to notify if not.

The relevant code could be around https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L336 also, [:352](https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L352)

**Comment by maxiloc** [comment]
@aude Thanks for reporting this. It will be available with next release
