### ISSUE TITLE
Rendering Twice Due to Off-Canvas Menu, Not Using Algolia Results Page

### ISSUE THREAD

**Issue by adderob** [algolia/algoliasearch-magento#249]
I've done as much as I can to try to figure out what is going on here to no avail. 

I installed Algolia, as per the instructions, on my local development instance of a client website. After disabling Elasticsearch, I can inspect element and see that the algolia-searchbox div shows up properly. However, it does not work as it is supposed to. It seems to be using the magento search functionality even though that search is within the algolia searchbox.

I dug a little deeper. I found out that the topsearch was being rendered twice on the page due to the off-canvas menu. When I shrink my window down to the appropriate size for show-for-small-only to render, the search is ALSO in that section, but it actually works as the Algolia search is supposed to work. 

So the first question is: what is the best way to get this to work with responsive designs utilizing the off-canvas menu functionalities? The off-canvas menu, rendered second, ends up overriding what was done to the normal topsearch area due to it rendering twice and this is a huge problem

The only way I have been able to see the correct search bar on normal header so far is to put this in the algoliasearch.xml:
   <reference name="header">
                <remove name="top.search"/>
                <block type="algoliasearch/search_form" name="top.algoliasearch" as="topSearch"/>
                <action method="setTemplate"><template>algoliasearch/topsearch.phtml</template></action>
            </reference>

This completely gets rid of my header, but it actually displays the correct search bar. I know it isn't correct syntaxt, but when troubleshooting...

The second issue I am facing is that, even when I utilize the search bar that actually shows up (via the above header xml piece or by using the smaller browser size to render the off canvas menu search), the results page I end up on is the normal Magento results page. I can see activity in the Network panel when I am typing into the search bar, but as soon as I submit, it all disappears and stays blank. 

Thanks for any help you can offer.

**Comment by maxiloc** [comment]
@adderob Do you have an url where I can see the issue. I am not sure to understand everything

**Comment by maxiloc** [comment]
I do not see your xml code. Can you send it again ?

**Comment by adderob** [comment]
<reference name="header">
       <remove name="top.search"/>
       <block type="algoliasearch/search_form" name="top.algoliasearch" as="topSearch"/>
       <action method="setTemplate"><template>algoliasearch/topsearch.phtml</template></action>
    </reference>

I have it right beneath the addJs action piece

**Comment by adderob** [comment]
http://162.243.200.245/ is the url to the development environment.

**Comment by maxiloc** [comment]
So I would replace #search in https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L546
by [id="search"]. This will bind to both inputs.

You should also change you instant selector in the algolia configuration to ".inner-wrap" to make the full result page work with Algolia.

Can you first try that and then let's see the remaining issues

**Comment by adderob** [comment]
Ok, got those changes moved up. I can see that the search bar works now, which is awesome! The results page is also a big ball of blank, but that probably means the right track has been found, at least.

**Comment by maxiloc** [comment]
Can you add this line https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L536
and this one https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L1735
This should remove the error in the console

**Comment by adderob** [comment]
That did not fix it. I get this error in the console: 
    uncaught exception: [Algolia] Invalid instant-search selector: .inner-wrap

**Comment by maxiloc** [comment]
Yes you will need to change if ($(algoliaConfig.instant.selector).length !== 1) to if ($(algoliaConfig.instant.selector).length >= 1)

**Comment by maxiloc** [comment]
My bad it's the opposite

```
if ($(algoliaConfig.instant.selector).length !== 1)
```
to
```
if ($(algoliaConfig.instant.selector).length < 1)
```

**Comment by adderob** [comment]
Changed it. That did not fix the error.

**Comment by adderob** [comment]
Sorry, new error: 

uncaught exception: [Algolia] You can't have a search input matching "[id="search"]" inside you instant selector ".inner-wrap"

**Comment by maxiloc** [comment]
Try with ".main-container" for instant selector

**Comment by adderob** [comment]
That fixed it! Thank you so much for your help!

**Comment by nareshphp1** [comment]
Getting below error when search first time
"Uncaught [Algolia] Invalid instant-search selector: .main" in console and result page show blank

**Comment by JanPetr** [comment]
Hello @nareshphp1,

that means that Algolia extension is looking for element with class "main", but this element doesn't exist in your theme.
You can change the selector to the existing one in Algolia configuration:
![screenshot 2017-06-14 09 47 10](https://user-images.githubusercontent.com/1058144/27121176-7af89770-50e6-11e7-9b42-cc72f10177c3.png)

**Comment by nareshphp1** [comment]
Hi JanPetr
Thanks for your reply!
DOM selector is already " .main "

![configuration_system_magento_admin](https://user-images.githubusercontent.com/14833512/27122806-6d5baecc-5109-11e7-9241-fa11abd63f41.png)

**Comment by nareshphp1** [comment]
When click on product page from search result then also show blank page with black background. Error as per screenshot. Error doesn't show everytime

![configuration-zylax](https://user-images.githubusercontent.com/14833512/27122986-07917cec-510a-11e7-8e2f-ea3d4e589ecc.png)

**Comment by JanPetr** [comment]
Yes it's .main. But the .main element doesn't exist on your page. So you need to change it to an existing one..

**Comment by nareshphp1** [comment]
Please check my site zylax.com.au and let me know which dom element I have to use for the algoria search

**Comment by nareshphp1** [comment]
Hi, Any solution for blank(black) screen.

**Comment by JanPetr** [comment]
Hello @nareshphp1,

I just checked your website and it works as expected. DId you manage to fix the issue?
