### ISSUE TITLE
Apply MAP pricing

### ISSUE THREAD

**Issue by davis2125** [algolia/algoliasearch-magento#252]
If a Magento item is configured to use MAP pricing the price is still being displayed in the Auto-Completion Menu

**Comment by maxiloc** [comment]
Indeed, thanks for reporting this. Will work on that for next release

**Comment by maxiloc** [comment]
@davis2125 the feature has been implemented, products with MAP enabled will not be indexed. It will be available with next release.

**Comment by davis2125** [comment]
Thanks @maxiloc
