### ISSUE TITLE
Autocomplete not showing

### ISSUE THREAD

**Issue by pattrainingserviceslimited** [algolia/algoliasearch-magento#257]
Hey,

Installed and configured the mod, but autocomplete is not showing?

It appears that no ajax calls are being made to algolia?

Thanks

**Comment by maxiloc** [comment]
@pattrainingserviceslimited Do you have a link where I can see the issue ?

**Comment by pattrainingserviceslimited** [comment]
Currently working locally, what screenshots, etc could I send to help diagnose this?

**Comment by maxiloc** [comment]
Can you send your APP ID, and screenshot of your algolia configuration in magento to "support at algolia dot com".
