### ISSUE TITLE
Unique queue entries

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#260]
I am working with a pretty large scale store, where products are constantly being updated through external systems posting in data to a Magento module.
Each product update triggers a new queue entry, and the queue grows fast here.

Reproduction:
* Open a product in Magento Admin Panel
* Click "Save and Continue Edit" once
* There are now x entries in _algoliasearch_queue_ (10 in my case)
* Now, click "Save and Continue Edit" 3 more times
* There will now be 3\*x more entries, totalling 4\*x (or in my case, 40)

Optimally, we would be left with the x first entries, no duplicate entries.

It would be extremely helpful for resource use reduction if the observers were able to look for duplicates/identical ones in the queue before inserting a new one. This has even larger effect if a whole category is reindexed. (Or if someone clicks reindex multiple times)

Is this perhaps something that is being handled by your new _intelligent queue_ idea?

**Comment by maxiloc** [comment]
Should be fix with https://github.com/algolia/algoliasearch-magento/commit/8e00869e20a9bf5e6c83e9385e032086719410fd

**Comment by aude** [comment]
Awesome. The new queue system sounds like a good idea.

**Comment by maxiloc** [comment]
It will not do a de-duplication because this is not something we want. It's going merge jobs per action and per store and reduce the time of queue processing.

**Comment by aude** [comment]
I figure, if a product is going to be updated towards the end of the queue, it doesn't make sense to reindex it any time before that final reindex?

**Comment by maxiloc** [comment]
Yes I agree. But the cost of checking that is big because the data of a job is json_encoded in the db and require to fetch all the jobs to be able to remove the duplicate.

**Comment by aude** [comment]
Okay. Maybe we can work on a fix with some time. The current situation requires deleting the queue from time to time (>6e6 entries), and running a reindex.
It would maybe be possible to create some sort of database index to enable a swift lookup, or maybe even an unique index so that the queue will refuse to add duplicate entries.

**Comment by maxiloc** [comment]
Yes sure, let's first wait for next release to see how it goes. And then if you still have issues lets try to find a good fix
