### ISSUE TITLE
bundle.min.js file size

### ISSUE THREAD

**Issue by manish172** [algolia/algoliasearch-magento#261]
currently, file size of  bundle.min.js is 0.5Mb. shouldn't bundle.min.js file be optimize?

**Comment by vvo** [comment]
Hi @manish172 the current bundle is indeed 500kb minified but 110kb gziped. It is still a big one bundle and we are trying to reduce the filesize.

We will let you know once that's the case.

**Comment by maxiloc** [comment]
I am closing this, Feel free to reopen the issue in the bundle repo https://github.com/algolia/algoliasearch-extensions-bundle

**Comment by manish172** [comment]
@maxiloc No issues. is there any way to show products as well as pages on instant search result page with filter to show pages only or show products only?

**Comment by maxiloc** [comment]
It's doable by instantiating two instantsearch object but to have the filter it will require custom code. Maybe you could create an issue in instantsearch.js repo to see if we can improve that.
