### ISSUE TITLE
Default Search

### ISSUE THREAD

**Issue by stefkosmo** [algolia/algoliasearch-magento#262]
I Have this installed and working but when i hit enter the default magento search no longer works. I dont want the algolia results page set up, but the default magento search.

Can these two work together?

Thanks

**Comment by maxiloc** [comment]
yes you can set the config in the screenshot to no:

![image](https://cloud.githubusercontent.com/assets/1689007/11565660/336ce164-99df-11e5-80da-e6dfacaaeac9.png)

**Comment by stefkosmo** [comment]
I've done that but the default magento search does not work?

**Comment by maxiloc** [comment]
Yes we fetch results from Algolia, and they are displayed by Magento to be able to have the same result in autocomplete and result page.
What is not working ? do you have any error in the log ?

**Comment by stefkosmo** [comment]
I have Enable instant search results page set to NO, so when I do a search and hit enter I should get magento's default search query. But no products are shown it just returns an empty page.

**Comment by stefkosmo** [comment]
FIXED....needed to reindex more than catalog search.

Thanks

**Comment by maxiloc** [comment]
sure
