### ISSUE TITLE
'Flush Catalog Images Cache' breaks Algolia images

### ISSUE THREAD

**Issue by ninteh** [algolia/algoliasearch-magento#263]
Hi All,

Great plugin - using it on a production website with good results so far.

One small issue - our Magento has various admins using it - occasionally someone accidently clicks 'Flush Catalog Images Cache' on the cache management page, this causes the images to be broken in Algolia, as it can't re-generate them until re-index.

Possible fix would be to either reindex algolia or add to the cron queue after the image cache has been flushed? Currently I've had to manually reindex algolia. My temporary fix was to remove the flush catalog images cache from the admin for now to stop other admin users from clicking it

**Comment by maxiloc** [comment]
@ninteh Thanks for reporting this. Unfortunately this is an issue we can not solve in the extension. I think your solution is the good one as the image cached should not be cleared often. Anyway we will add in the documentation that a reindex is needed after clearing the cache.

**Comment by jiitpiyush** [comment]
I think you should only store real path instead of cached path in algolia db. This will be a permaent solution.
