### ISSUE TITLE
Prices not right in the index after updating. (1.4.2 => 1.4.8)

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#266]
I updated from 1.4.2 to 1.4.8 - Looks like pricing got cleaned up a bit in the last couple versions. But some of my products weren't showing the price correctly on the search results page. 

What I saw in the index... 

One item has all the prices listed as separate items (this is the old way). 

```
"price_with_tax": {
    "default": 110
  },
  "special_price_from_date": {
    "default": false
  },
  "special_price_to_date": {
    "default": false
  },
```

While another has them grouped (this is the newer correct method):

```
  "price": {
    "default": 104,
    "default_formated": "$104.00"
  },
```
Reindexing the main index didn't fix all these records - To correct it, I purged the index entirely, and having it reindex from scratch.

Might not be the best solution, but it was effective...

**Comment by maxiloc** [comment]
Yes that is expected. There was a bug in the 1.4.2 that did not delete product when it should have so you might had some records with the old version that stays.

We did not document well breaking changes and we are going to improve that for future version.

Thanks for reporting

**Comment by sam327** [comment]
A ha. I've got this plugin on a couple different sites. But this particular issue was only really apparent on one of them. I'll do a flush on the other ones for good measure. 

Thanks.
