### ISSUE TITLE
Showing instant results page when referencing a page using div id

### ISSUE THREAD

**Issue by shumaise** [algolia/algoliasearch-magento#270]
I'm running on a magento store. 

if I have in any page for eg. <a href="#"></a>  or <a href="abouts.html/#custom></a>, clicking on these brings algolia instant results with products and replaces the actual content of the current page. Even if enter a link www.example.com/# brings up the instant results. Is there any way to correct this issue

**Comment by maxiloc** [comment]
@shumaise It will be fix with next release. Thanks for reporting this.
