### ISSUE TITLE
Add a css class for sale prices

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#271]
In the latest version of topsearch.phtml (v1.4.8), I can't tell whether or not the price in the after_special span is the regular price of the item or a sale price. 

Because this `{{price<?php echo $price_key; ?>_formated}}` really just says _current_ price. The only way I know something is on sale is whether or not the _original_formated_ block is there.

        <div class="algoliasearch-autocomplete-price">
            <span class="after_special">
                {{price<?php echo $price_key; ?>_formated}}
            </span>

            {{#price<?php echo $price_key; ?>_original_formated}}
                <span class="before_special">
                    {{price<?php echo $price_key; ?>_original_formated}}
                </span>
            {{/price<?php echo $price_key; ?>_original_formated}}
        </div>

So, can you add an if-check on/around the 'after_special' to determine whether or not the item's on sale? 

I think I figure out a solution easily enough, but you might have a better way.

**Comment by sam327** [comment]
This was my fix. I moved the current price inside the if-check. And then dropped the after_special class when there isn't an original price.

    <div class="algoliasearch-autocomplete-price">

        {{#price<?php echo $price_key; ?>_original_formated}}
			<span class="after_special">
				{{price<?php echo $price_key; ?>_formated}}
			</span>
		
            <span class="before_special">
                {{price<?php echo $price_key; ?>_original_formated}}
            </span>
        {{/price<?php echo $price_key; ?>_original_formated}}

		{{^price<?php echo $price_key; ?>_original_formated}}
			<span>
				{{price<?php echo $price_key; ?>_formated}}
			</span>
        {{/price<?php echo $price_key; ?>_original_formated}}

    </div>

**Comment by maxiloc** [comment]
I am not sure I get your question. What are you trying to do ?

**Comment by sam327** [comment]
Sorry, let me try to explain better. I'm trying to put a different class on the current price when it's on sale vs when it's not. 

In my design, the price is black by default. But when it's on sale, I make the price red, with the old price next to it in gray & crossed out.

So, in my updated code, I made it so it if an original price exists (i.e. the item is on sale), it uses the _after_special_ class, and if there is not an original price, it doesn't.

That make more sense?

**Comment by maxiloc** [comment]
Yes it makes sense, I will add a class to be able to customize it more easily

**Comment by maxiloc** [comment]
Implemented on the develop branch
