### ISSUE TITLE
Undefined variable causing empty result pages

### ISSUE THREAD

**Issue by technik-vitafy** [algolia/algoliasearch-magento#283]
For some search terms the result page was empty due to an undefined variable e in following map function in algoliaBundle.js. The first if statement is the patch we introduced: We just assign an empty array if e is undefined.

                map: function (e, t, n) {
                    if (!e) {
                        e = [];
                    }
                    var r, o = 0, i = e.length, s = a(e), u = [];
                    if (s)for (; i > o; o++)r = t(e[o], o, n), null != r && u.push(r); else for (o in e)r = t(e[o], o, n), null != r && u.push(r);
                    return ee.apply([], u)
                },

**Comment by maxiloc** [comment]
@technik-vitafy Do you know how to reproduce the error ?

**Comment by vvo** [comment]
This is a jQuery.map method, the issue is not really the method itself but how it was called. What is the UI behavior that triggered this error? Can you provide us a url?

**Comment by maxiloc** [comment]
Let's close this. Feel free to re-open if needed

**Comment by alamzaib** [comment]
When we press enter then it shows empty page
like http://mywebsite.com/catalogsearch/result/?q=cloth

when i press enter then it redirects above url and shows nothing, and gives one error in console that Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by vvo** [comment]
@alamzaib Since this issue is closed you will not get many response, can you contact support@algolia.com? Thanks
