### ISSUE TITLE
Can't View Search (Magento v1.9.2.2)

### ISSUE THREAD

**Issue by chrissm79** [algolia/algoliasearch-magento#290]
I've created a vagrant box via Homestead (Laravel) which installs PHP v7.0.1. I created a brand new magento store w/ v1.9.2.2. When I attempt to install the package via Magento Connect, I get an error in the output screen stating that it can't be installed because it required PHP >= v5.3.0 or <= 6.0. So I installed modman, and then ran:

```bash
$ modman init
$ modman clone https://github.com/algolia/algoliasearch-magento.git
```

I get confirmation that the package has been successfully installed and after flushing the cache I can see the setting on the backend and I enter in the credentials provided by the Algolia admin panel (currently on free trial). However, if I turn on Algolia's search, the search box (mini form) on the frontend of the website disappears. If I disable Algolia it reappears. I'm able to successfully run the indexer and the products appear in my Algolia account. 

To rule out that it's an issue with my products, I have a fresh install of Magento v1.9.2.2 using the sample data. As soon as I enter in my credentials to the settings and save the config, the search box on the frontend disappears.

Is there a step I'm missing? Thanks!

**Comment by lazyguru** [comment]
Pretty sure M1 is not supported on PHP 7.  M2 isn't even fully supported yet (it has the groundwork, but I haven't seen official support listed yet)

**Comment by chrissm79** [comment]
To rule out PHP7.0 I ran the default store locally on PHP 5.6 and converted account to community version. Same issue.

**Comment by lazyguru** [comment]
Try PHP 5.5, that is the highest I have heard of support for M1.

**Comment by chrissm79** [comment]
Yeah, same issue w/ PHP v.5.5/v5.6/v7.0

**Comment by lazyguru** [comment]
Did you ensure your homestead install has all of the appropriate PHP packages for Magento?  I think your issue is a system issue and not an issue with the extension (though I could be wrong).  I know the extension works with EE 1.14 and I'm pretty sure the demo site is a 1.9 install.

**Comment by chrissm79** [comment]
Looks like it needs to be installed via Magento Connect for it to work properly (which currently doesn't support PHP 7, but technically neither does Magento). Is there a way to install this properly via Github/modman (installed via modman but that's when it disappears on the frontend) and get it to work on a site?
