### ISSUE TITLE
Include unbundled source JavaScript

### ISSUE THREAD

**Issue by mattwellss** [algolia/algoliasearch-magento#293]
It looks like 1.5+ of this extension uses components located here: https://github.com/algolia/instantsearch.js

I'd like to add custom components to a site I'm building, and it doesn't look like that will be particularly possible without rebuilding the bundled JS.

Is it possible to include the source JavaScript used to build the bundle in this module?

**Comment by maxiloc** [comment]
@mattwellss Did you had a look at https://community.algolia.com/instantsearch.js/documentation/#customize ?
The goal of instantsearch.js is to be easily extendable and not having to rebuild from sources when you want to do a new widget
