### ISSUE TITLE
Warning: flattenChildren(...): Encountered two children with the same key

### ISSUE THREAD

**Issue by shumaise** [algolia/algoliasearch-magento#295]
Getting error in console

Warning: flattenChildren(...): Encountered two children with the same key, `.$magento_default_products`. Child keys must be unique; when two children share a key, only the first child will be used.

filename: algoliaBundle.min.js

**Comment by maxiloc** [comment]
@shumaise Do you have the stacktrace ?

**Comment by shumaise** [comment]
No.

**Comment by maxiloc** [comment]
Ok do you know how I can reproduce it ?

**Comment by shumaise** [comment]
The problem i think is with indexing. i tried a new install and there is no error.
