### ISSUE TITLE
Deleting products via mass action does not seem to remove products from index

### ISSUE THREAD

**Issue by lazyguru** [algolia/algoliasearch-magento#296]
I think this has to do with Algolia_Algoliasearch_Model_Indexer_Algolia::_registerCatalogProductEvent expecting that all deletes will come through as a Mage_Index_Model_Event::TYPE_DELETE but instead they are coming through under Mage_Index_Model_Event::TYPE_MASS_ACTION which doesn't seem to have logic to handle for the products being deleted (same for products being disabled).  I have not dug deep enough to confirm this though.  My current workaround is just adding an event observer for catalog_product_delete_after_done and calling Mage::helper('algoliasearch/algoliahelper')->deleteObjects([$product->getId()], $index)

**Comment by maxiloc** [comment]
Thanks I'll have a look tomorrow

**Comment by maxiloc** [comment]
@lazyguru Indeed, just fixed it
