### ISSUE TITLE
Common class names

### ISSUE THREAD

**Issue by byjord** [algolia/algoliasearch-magento#298]
On integration it seems that the Magento extension uses common class names that override that of a theme or development. Eg, `.row` or `.main` etc. Might be a good idea to use algolia prefixed class names (`.algolia-row` or `.algolia__main`, depending on your preferred naming schemes) as a default to enable fast setup without conflicts.

**Comment by maxiloc** [comment]
@byjord Yes this is something we need to work on, but this will need to be released with a major version as it will break most of the existing implementation

**Comment by byjord** [comment]
@maxiloc maybe a quick fix for future version 1.5.4 could be a toggle option in the admin to switch between generic and non-generic class names. (Just a suggestion to help your on-boarding efforts, we're already changing out the extension in house)

**Comment by maxiloc** [comment]
Thanks for the hint, this is definitely an option to consider.
The only thing is we are thinking about re-doing the css from scratch to use best practices including naming, so it will probably depends on how soon we are able to do this.

**Comment by byjord** [comment]
Good to know that you're already working on a resolution for it dude. :)
