### ISSUE TITLE
Use Include in Navigation Menu

### ISSUE THREAD

**Issue by dustincoates** [algolia/algoliasearch-magento#299]
Use this setting to include or exclude navigation menus from categories.

**Comment by dustincoates** [comment]
@maxiloc Is this closed because we already have it or because we don't plan on adding it?

**Comment by maxiloc** [comment]
Yes it's implemented with d7c01b74a1277eeabf0676d7a26fe39814ec113d

**Comment by dustincoates** [comment]
Thanks @maxiloc !
