### ISSUE TITLE
Categories appearing twice in autocomplete menu

### ISSUE THREAD

**Issue by pattrainingserviceslimited** [algolia/algoliasearch-magento#300]
Hey,

Getting the category block appearing twice in the autocomplete menu, any ideas why?

Thanks

![screen shot 2016-01-28 at 16 30 39](https://cloud.githubusercontent.com/assets/11092685/12650917/95a57354-c5dc-11e5-8aa9-af60c6580e79.png)

**Comment by maxiloc** [comment]
@pattrainingserviceslimited Can you send a screenshot of your autocomplete configuration

**Comment by pattrainingserviceslimited** [comment]
![screen shot 2016-01-29 at 09 12 47](https://cloud.githubusercontent.com/assets/11092685/12671592/9c9b26fe-c668-11e5-8f9f-902d8441edb0.png)

**Comment by maxiloc** [comment]
ok so no issue on this side. Do you have an url where I can see the issue live ?

**Comment by pattrainingserviceslimited** [comment]
http://www.test-meter.co.uk/

**Comment by maxiloc** [comment]
Seems like the javascript is injected twice, did you modified anything or just install via magento connect ?

**Comment by pattrainingserviceslimited** [comment]
I've added copied algoliasearch/topsearch.phtml & algoliasearch/algoliasearch.css to theme for modifications thats it. The module was installed via magento connect.

**Comment by pattrainingserviceslimited** [comment]
Also strangely enough, if you click a product result in the autocomplete, the second category disappears before redirecting to the search.

**Comment by maxiloc** [comment]
where did you copied it ?

**Comment by pattrainingserviceslimited** [comment]
from 
base/default/template/algoliasearch/algoliasearch.phtml 
to 
blueclaw/testmeter/template/algoliasearch/topsearch.phtml.

**Comment by pattrainingserviceslimited** [comment]
I've deleted all the files I copied to theme so the default files run, but same duplicate categories block is being produced.

**Comment by maxiloc** [comment]
Did you clear the cache when you did that ?

**Comment by pattrainingserviceslimited** [comment]
Yes cache was cleared

**Comment by maxiloc** [comment]
Can you try uninstalling the extension, check that you don't have any algolia file anymore, clear the cache and reinstall it ?
I quite sure copied files where the source of the issue.

**Comment by pattrainingserviceslimited** [comment]
I've uninstalled and reinstalled and cleared cache and still the same problem.

**Comment by pattrainingserviceslimited** [comment]
Alternatively could the second category display be hidden with css, what identifier could be targeted short term?

**Comment by maxiloc** [comment]
can you re-enable it, on http://www.test-meter.co.uk/, I would like to check one more thing

**Comment by pattrainingserviceslimited** [comment]
Done, my theme files have been removed so it's the module defaults.

**Comment by maxiloc** [comment]
Ok I found the issue. Your template seems to have two "top.search" block which make the extension code injected twice. The fix is to update this config 
![image](https://cloud.githubusercontent.com/assets/1689007/12675028/cbb943fc-c687-11e5-854b-6b13b71158ff.png)
in advanced with the selector of your default input.

Tell me how it goes

**Comment by pattrainingserviceslimited** [comment]
Excellent, thankyou very much.
