### ISSUE TITLE
Baseurl is taken from website level instead of store view level

### ISSUE THREAD

**Issue by technik-vitafy** [algolia/algoliasearch-magento#301]
Baseurl is taken from website level instead of store view level. Is the only workaround to create separate websites?

**Comment by maxiloc** [comment]
@technik-vitafy Indeed it's not taking it into account. I'll investigate

**Comment by maxiloc** [comment]
@technik-vitafy Are you still experiencing the issue ? If yes can you send me the config your are using regarding website, and a live example of what you have and what you would expect

**Comment by technik-vitafy** [comment]
We had to apply following patch in Producthelper.php:           
 'url'               => Mage::getBaseUrl() . $product->getRequestPath(),

You can reproduce the problem when having multiple storeviews with different base urls. The base url of the first store view seems is cached. On the otherhand this could not occure with a vanilla magento installation.

**Comment by maxiloc** [comment]
@technik-vitafy Can you give me more details on why this could not occurs with a vanilla magento installation.
With the sample data of magento you have several store views, when I changed the base url of those views they are updated fine after a full reindex (even with all cache enabled). 

(I don't know what I did 4 days ago because I am not able to reproduce it anymore)

**Comment by technik-vitafy** [comment]
@maxiloc: You can close this. We had a custom override for the Url Model implementation which cached the base url. Thanks!

On 02 Feb 2016, at 11:21, maxiloc <notifications@github.com<mailto:notifications@github.com>> wrote:


@technik-vitafy<https://github.com/technik-vitafy> Can you give me more details on why this could not occurs with a vanilla magento installation.
With the sample data of magento you have several store views, when I changed the base url of those views they are updated fine after a full reindex (even with all cache enabled).

(I don't know what I did 4 days ago because I am not able to reproduce it anymore)
