### ISSUE TITLE
Autocomplete width changes dependent on page layout.

### ISSUE THREAD

**Issue by pattrainingserviceslimited** [algolia/algoliasearch-magento#303]
Hey,

Pages with one column, the autocomplete is 71% of the page width. but on two column pages, the autocomplete is 71% of the right column, please see http://www.test-meter.co.uk and http://www.test-meter.co.uk/multifunction-testers/

thanks

**Comment by maxiloc** [comment]
Yes depending on the theme you might need to override some css rules on your side as we can't plan for every theme

**Comment by pattrainingserviceslimited** [comment]
At the moment `<div id="algolia-autocomplete-container"></div>` is being injected within `<div class="col-main"></div>` how can I change where this is inserted?

**Comment by maxiloc** [comment]
https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/layout/algoliasearch.xml#L30-L34

**Comment by maxiloc** [comment]
https://github.com/algolia/algoliasearch-magento/blob/cc7ac51831526be094bbdb2ccff4aef6edb2c48a/design/frontend/layout/algoliasearch.xml#L16

**Comment by pattrainingserviceslimited** [comment]
Sorted it thanks for your help.
