### ISSUE TITLE
Algolia not updating new products, no error messages??

### ISSUE THREAD

**Issue by ZayLong** [algolia/algoliasearch-magento#306]
Running 1.5.1 I have the Algolia queue runner successfully configured runs every 15 minutes, however new products have stopped updating.

The queue runner returns a build successful message whenever it runs. 

We don't use the suggestions or pages. We have updated to 1.5.1 about 2-3 weeks ago and things have ran relatively smoothly since.

Here's how our index manager is set up, 
Is there anything wrong with what I have setup?

<a href='http://postimg.org/image/59rrshicd/' target='_blank'><img src='http://s14.postimg.org/59rrshicd/whatswrong.jpg' border='0' alt="whatswrong" /></a>

**Comment by ZayLong** [comment]
Also the algoliasearch_queue_log.txt says it has stopped  1/6/16 If that may be indication.

**Comment by maxiloc** [comment]
Did you try a full reindex ?
Can you send your algolia.log file after a full reindex to support at algolia dot com (and an id of product that does not get indexed) ?

**Comment by ZayLong** [comment]
It seems the product has finally updated in Algolia, 
I did do a manual reindex however the algolia.log file has no new information in it (the file was last modified back in May of last year)

Every now and again we come across a situation where I see batch POST in the algolia dash, however many products are not updated.

Is it possible that the queue runner gets backed up? (Our store has thousands of products)

Would modifying the Max number of element per indexing job or the Number of jobs to run each time the cron is run help with that?

**Comment by maxiloc** [comment]
There should not be any issue once a query arrive to Algolia. Modifying Max number of element per indexing job and the Number of jobs can change something if you have low timeout or low memory on Magento side.

Ok let's close this and reopen-it if needed
