### ISSUE TITLE
typo in the instructions?  --reindex algolia_queue_runner

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#309]
I'm not sure if this is a difference in systems, or if it's a typo that needs fixing. At any rate, I wanted to call it to your attention, and have it documented in case someone else trips up on it.

In the docs, it says I should set up the cron tab like so:
``` 
*/5 * * * * php -f /absolute/path/to/magento/shell/indexer.php -- -reindex algolia_queue_runner 
```
As I understand it, that `-- -reindex` should instead be `--reindex` like so:
```
*/5 * * * * php -f /absolute/path/to/magento/shell/indexer.php --reindex algolia_queue_runner
```
Was wondering why a queue didn't run last night as I'd configured it to, and this was why.

**Comment by maxiloc** [comment]
What version of magento are you running. On 1.9.x ``` --reindex ``` fails

**Comment by sam327** [comment]
Whoops. I didn't see the notification... I'm on 1.9.1. 

- `php ... --reindex` runs correctly.
- `php -f ... -- -reindex` runs correctly.
- `php ... -- -reindex` fails.

At any rate, I'm closing this as 'user error.'
