### ISSUE TITLE
Really need a way to enable the front-end devs to style the elements

### ISSUE THREAD

**Issue by byersdesign** [algolia/algoliasearch-magento#311]
Its absolutely horrendous to try and style this extension. There is no way of stopping the inner elements from 'disappearing' after you click off the search box. Please help

**Comment by maxiloc** [comment]
Just set this to true https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L764

**Comment by byersdesign** [comment]
awesome. thank you
