### ISSUE TITLE
Configurable products with fixed prices

### ISSUE THREAD

**Issue by byersdesign** [algolia/algoliasearch-magento#313]
It looks as though configurable products that have a fixed price are having their associated products' prices showing in search results. For example: Search for "Fiona" here https://www.littlewomen.com/ and you will see that its pulling in a rage of prices however this is incorrect as the main "Fiona" configurable product has a set price.

**Comment by maxiloc** [comment]
Yes this is a issue. I just fixed it with https://github.com/algolia/algoliasearch-magento/commit/73d85643cf54d60b592f12d481854f9f8cc0fe3e
It will also be available with this week release
