### ISSUE TITLE
reindex products - high memory consumption

### ISSUE THREAD

**Issue by maximilianmikus** [algolia/algoliasearch-magento#317]
I maintain a webshop with about 20000 products, while indexing the memory consumption increases the more products are indexed. This leads to memory limit errors.

`PHP Fatal error:  Out of memory (allocated 2099249152) (tried to allocate 94208 bytes) in [..]/app/lib/Varien/Image/Adapter/Gd2.php on line 458`

**Comment by maxiloc** [comment]
Do you have the queue enable ? For this amount of product it's almost required for indexing to work properly

**Comment by maximilianmikus** [comment]
Of course not :smile: 

I guess the queue will this then.
