### ISSUE TITLE
Filtrable with more than 1 result

### ISSUE THREAD

**Issue by jrosell** [algolia/algoliasearch-magento#318]
I see many filters used because only gives one product included as a result. In these case all #ux guidelines says is better to show that filters instead of showing all oth them with 1 result.
I don't know if you currently do that or you plan to do it...

**Comment by maxiloc** [comment]
@jrosell I am not sure to understand. Can you give me a bit more details ? Maybe you could do some screenshot

**Comment by jrosell** [comment]
For example, this 2 attributes i don't think it makes sense for good #265 

![resultados de busqueda para cana](https://cloud.githubusercontent.com/assets/1544992/13015236/4a1dbc38-d1b8-11e5-85b4-177a02191ea4.png)

**Comment by maxiloc** [comment]
I guess this is the behavior we want by default, but this is definitely something you can customize

**Comment by JanPetr** [comment]
Desired functionality is tracked here: https://github.com/algolia/instantsearch.js/issues/1086

**Comment by JanPetr** [comment]
When i'll be implemented to IS, it will be usable via new custom JS hooks to modify IS behavior (#822).
