### ISSUE TITLE
hits widget emits divs

### ISSUE THREAD

**Issue by rbrown** [algolia/algoliasearch-magento#322]
Hi, the hits widget emits a couple of divs around each hit which is breaking the layout that I'm trying to do for my results page.

```HTML
<div class="ais-hits" data-reactid=".1">
<div class="ais-hits--item" data-reactid=".1.$3953752">
```

I can't see how to disable the js from doing this? I see there's a new allItems template option in  https://github.com/algolia/instantsearch.js/commit/1f3f889d4cc246c317d9b0e7b436f5d427dc6c33 but that's not in the magento extension yet. Would using the newer version be the best solution for me?

**Comment by vvo** [comment]
Yes @rbrown the new allItems option might be good for you. It will be available in magento soon, stay tuned here by subscribing to the issue (you already are subscribed in fact)

**Comment by rbrown** [comment]
Great, thanks
