### ISSUE TITLE
Full reindex seems to be missing some products

### ISSUE THREAD

**Issue by bslinger** [algolia/algoliasearch-magento#323]
We've been using the Algolia Magento plugin in production for the last week or so, and have noticed that the occasional product just doesn't seem to exist in the index, even after a full reindex. Hitting save on the product (when we discover it) successfully updates the index, so presumably there is nothing about the product itself that the indexer is getting hung up on.

Any ideas on how I might diagnose the issue?

**Comment by maxiloc** [comment]
@bslinger Are you importing your products via an external extension ?

**Comment by bslinger** [comment]
We have dataflow profiles which import products, though they all use the Magento models to do it so indexing events should be created correctly. It's come to our attention today that some of the products that we saved yesterday to force them into the index have disappeared from it again. I'll take a look at the algolia logs and see if I can figure out when that might have happened.

**Comment by chrisvanderpoel** [comment]
Make sure you have fully reindexed your site.  The collection methods for gathering up products to export to Algolia depends on the price index being up to date.  If a product has been imported but the price index is not up-to-date, you will run into a scenario where the product exists in Magento but is not showing up in Algolia.

A good place for debugging this is in the `app/code/community/Algoliasearch/Helper/Entity/Producthelper.php::getProductCollectionQuery` method.  That's the method that builds up a query of local Magento data for processing out to Algolia.  Place some logging statements in there if you'd like to determine what is actually being pulled from Magento with that query.  Things like visibility, store ID, stock and price indexes all have an effect on the set of products that is returned.

**Comment by bslinger** [comment]
So I've done some debugging today and it looks like the module is deleting configurable products from the index when their associated stock item is saved. 

We are using Embedded ERP, and whenever an order comes in, it saves the stock item for each item in the order, including the parent configurable. This triggers _registerCatalogInventoryStockItemEvent, which adds the 'catalogsearch_delete_product_id' data to the index event.

I think the issue may be that these configurable products don't manage stock, but that `$object->getData('is_in_stock')` still returns false in this case.

**Comment by maxiloc** [comment]
@bslinger Yes that might be possible. We are going to change the logic of the indexer, and adopt the same one that is being used in magento2 which is way simpler and less error prone.
When there is an update/sock update, we will delete + update. The update will create it again only if necessary

**Comment by maxiloc** [comment]
I am closing this in favor of #337
