### ISSUE TITLE
Add Google Analytics Product List Tracking for Category Pages

### ISSUE THREAD

**Issue by technik-vitafy** [algolia/algoliasearch-magento#325]
This would allow to measure conversion funnel metrics for each product listed on a category page.

**Comment by maxiloc** [comment]
I guess this is something you can do on your side no ?

**Comment by maxiloc** [comment]
Because I am not sure it makes sense to have it by default in the extension

**Comment by technik-vitafy** [comment]
Most ecommerce shops are using Google Analytics per default. So I think this would be a great feature for many algolia customers.

**Comment by maxiloc** [comment]
I am closing this, feel free to submit a Pull Request

**Comment by Mobecls** [comment]
@technik-vitafy Hi, and did you find the solution for tracking search in GA?

**Comment by JanPetr** [comment]
GA integration directly to the extension is very tricky. But we released a new instantsearch.js widget for analytics support - https://community.algolia.com/instantsearch.js/documentation/#analytics-1 Feel free to integrate it to your sites!

**Comment by Mobecls** [comment]
thanks
