### ISSUE TITLE
it is possible to add new info for query?

### ISSUE THREAD

**Issue by lzygmanski** [algolia/algoliasearch-magento#326]
hello!
We would like to and new dynamic element and some custom behavior for query result. how we can achieve that? 

it is possible to add new info for query: 

1. On the top of the container which has class name „autocomplete-wrapper” we would like have such text: „number of hits” Result for Query „query text”

2. if i have result for category and pages i want to show info before page and category list: „query text” can be found in the following pages :” then list of pages (category and page without section.label or section.name)

3. if i don’t have result for pages, categories, and product, i want to show one block with info „No result…” instead 3 blocks „Pages: No results, Category: No results, no product for query ... "

**Comment by maxiloc** [comment]
ping @redox

**Comment by redox** [comment]
Hi @lzygmanski,

the auto-completion menu of our Magento integration is based on the open-source [autocomplete.js](github.com/algolia/autocomplete.js) library and can for sure be extended.

That being said, each "sections" of the auto-completion menu is currently independent/isolated so you cannot easily control what you want to display based on the JavaScript code, especially not doing conditioning display based on the results of one of them.

That being said, I think you can achieve what you want to do with CSS rules that would show/hide the extra pieces of text you're speaking about based on the `.aa-with--<DATASET>` or `.aa-without--<DATASET>` classes that are put on the [dropdown menu](https://github.com/algolia/autocomplete.js#look-and-feel).

So I would add the pieces of text in the [dropdown menu template](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L388-L400).

And then I would add CSS rules to show/hide depending on the `with/without` classes.

For instance, here I only have results for the `products` and not for the 2 others (pages & categories) so the classes are: `aa-dropdown-menu aa-with-products aa-without-0 aa-without-1`.

![screen shot 2016-02-29 at 18 04 38](https://cloud.githubusercontent.com/assets/29529/13402099/12e714a8-df0f-11e5-865e-a8e2a8a6be9c.png)

![screen shot 2016-02-29 at 18 04 41](https://cloud.githubusercontent.com/assets/29529/13402103/16f9a394-df0f-11e5-8c4f-e51234ef9532.png)

Would that work for you?

**Comment by lzygmanski** [comment]
Yep! thanks for your help!
