### ISSUE TITLE
Clear all button not translatable

### ISSUE THREAD

**Issue by Floddy** [algolia/algoliasearch-magento#327]
The 'Clear all' button is not translatable. Is it possible to add a template for this widget, so we can translate it?

**Comment by maxiloc** [comment]
Yes you can add this. You can have a look at the currentRefinedValue widget doc for the template option list => https://community.algolia.com/instantsearch.js/documentation/#currentrefinedvalues

**Comment by Floddy** [comment]
Thanks! A colleague solved it now. :)
