### ISSUE TITLE
Autocomplete dropdown does not respond to z-index changes.

### ISSUE THREAD

**Issue by stefkosmo** [algolia/algoliasearch-magento#334]
Hey,

The autocomplete dropdown is appearing before certain elements on my page. I've changed the **z-index** of **#algolia-autocomplete-container .aa-dropdown-menu** to **9999 !important;** to no avail.

Does this need attaching to a different element?

**Comment by maxiloc** [comment]
Do you have a link where we can see the issue ?

**Comment by stefkosmo** [comment]
Hey sorry, please visit dealicious.co.uk

**Comment by maxiloc** [comment]
This is because you have an "overflow: hidden" for #content.
To be able to have a large autocomplete dropdown we need to put this dropdown in the content and not the header.
