### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by osm-dev** [algolia/algoliasearch-magento#335]
Hey there,

I'm trying to update Algolia to the newest(1.5.4) version but i'm getting this error:

PHP Fatal error:  Call to undefined method Algolia_Algoliasearch_Helper_Config::getNumberOfProductSuggestions() in [...]app/design/frontend/default/my-theme/template/algoliasearch/topsearch.phtml on line 28

**Comment by maxiloc** [comment]
it should be getNumberOfProductsSuggestions (with a "s" at product). See https://github.com/algolia/algoliasearch-magento/blob/a91de231822ce5e81849f4bcf52549da0ec6a446/design/frontend/template/beforetopsearch.phtml#L103

**Comment by osm-dev** [comment]
Tryied, but still without success: ... Call to undefined method Algolia_Algoliasearch_Helper_Config::getNumberOfProductsSuggestions() ...

I used this file: https://github.com/algolia/algoliasearch-magento/blob/master/releases/algoliasearch-1.5.4.tgz

**Comment by maxiloc** [comment]
Can you try to install it via magento connect

**Comment by osm-dev** [comment]
Unfortunatly, can't. Magento connect is closed on the server i use due to security.

**Comment by maxiloc** [comment]
I would say this is due to some files not being put at the right place and/or remaining files from the previous version.

**Comment by maxiloc** [comment]
Are you able to install using modman ?

**Comment by maxiloc** [comment]
https://github.com/algolia/algoliasearch-magento#2-modman

**Comment by osm-dev** [comment]
I removed all previous installation files and re-installed trougth modgit(default on this project instead of modman) the page renders, but now i have a js error: ReferenceError: algoliaBundle is not defined.

**Comment by maxiloc** [comment]
I never used modgit but since we don't have the configuration file it expected that is does not do all files mapped. You just need to check that you have all files that are mapped according to this https://github.com/algolia/algoliasearch-magento/blob/master/modman

Tell me how it goes

**Comment by osm-dev** [comment]
Modgit clones the entire repository, modman has a config file so you can choose to ignore something. I checked your link and i think its all mapped, as you can see on my deploy log: 

Deploying:
js/algoliasearch/algoliaAdminBundle.min.js/algoliasearch.map
js/algoliasearch/algoliaAdminBundle.min.js/algoliasearch
js/algoliasearch/algoliaBundle.min.js/algoliasearch
js/algoliasearch/admin_scripts.js/algoliasearch
js/algoliasearch/Function.prototype.bind.js/algoliasearch
js/algoliasearch/algoliaBundle.min.js/algoliasearch.map
app/code/community/Algolia/Algoliasearch/Model/System/Imagetype.php
app/code/community/Algolia/Algoliasearch/Model/System/Removewords.php
app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext/Collection.php
app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php
app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php
app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliasuggestions.php
app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliapages.php
app/code/community/Algolia/Algoliasearch/Model/Indexer/Algolia.php
app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliacategories.php
app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliaadditionalsections.php
app/code/community/Algolia/Algoliasearch/Model/Indexer/Algoliaqueuerunner.php
app/code/community/Algolia/Algoliasearch/Model/Queue.php
app/code/community/Algolia/Algoliasearch/Model/Observer.php
app/code/community/Algolia/Algoliasearch/Helper/Image.php
app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
app/code/community/Algolia/Algoliasearch/Helper/Entity/Additionalsectionshelper.php
app/code/community/Algolia/Algoliasearch/Helper/Entity/Pagehelper.php
app/code/community/Algolia/Algoliasearch/Helper/Entity/Suggestionhelper.php
app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php
app/code/community/Algolia/Algoliasearch/Helper/Entity/Categoryhelper.php
app/code/community/Algolia/Algoliasearch/Helper/Logger.php
app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php
app/code/community/Algolia/Algoliasearch/Helper/Data.php
app/code/community/Algolia/Algoliasearch/Helper/Config.php
app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-upgrade-0.1.0-1.4.8.php
app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-upgrade-1.4.8-1.5.0.php
app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-install-0.1.0.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Sections.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Custompages.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Sorts.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Customrankingproduct.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Customsortorder.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Customsortorderproduct.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Facets.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Select.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Customrankingcategory.php
app/code/community/Algolia/Algoliasearch/Block/System/Config/Form/Field/Customsortordercategory.php
app/code/community/Algolia/Algoliasearch/etc/system.xml
app/code/community/Algolia/Algoliasearch/etc/config.xml
app/code/community/Algolia/Algoliasearch/etc/adminhtml.xml
app/design/frontend/base/default/layout/algoliasearch.xml
app/design/frontend/base/default/template/algoliasearch/topsearch.phtml
app/design/frontend/base/default/template/algoliasearch/frontjs.phtml
app/design/frontend/base/default/template/algoliasearch/beforecontent.phtml
app/design/frontend/base/default/template/algoliasearch/beforetopsearch.phtml
app/design/adminhtml/default/default/layout/algoliasearch.xml
app/design/adminhtml/default/default/template/algoliasearch/adminjs.phtml
app/etc/modules/Algolia_Algoliasearch.xml
skin/frontend/base/default/algoliasearch/algoliasearch.css
skin/frontend/base/default/algoliasearch/cross.png
skin/frontend/base/default/algoliasearch/cross-circle.png
skin/frontend/base/default/algoliasearch/algolia-logo.png
skin/frontend/base/default/algoliasearch/algolia-admin-menu.png
skin/frontend/base/default/algoliasearch/images/ui-bg_gloss-wave_35_f6a828_500x100.png
skin/frontend/base/default/algoliasearch/images/ui-bg_diagonals-thick_18_b81900_40x40.png
skin/frontend/base/default/algoliasearch/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
skin/frontend/base/default/algoliasearch/images/ui-bg_glass_100_fdf5ce_1x400.png
skin/frontend/base/default/algoliasearch/images/ui-bg_glass_100_f6f6f6_1x400.png
skin/frontend/base/default/algoliasearch/images/ui-icons_ffd27a_256x240.png
skin/frontend/base/default/algoliasearch/images/ui-icons_228ef1_256x240.png
skin/frontend/base/default/algoliasearch/images/ui-icons_ffffff_256x240.png
skin/frontend/base/default/algoliasearch/images/ui-icons_222222_256x240.png
skin/frontend/base/default/algoliasearch/images/ui-icons_ef8c08_256x240.png
skin/frontend/base/default/algoliasearch/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
skin/frontend/base/default/algoliasearch/images/ui-bg_diagonals-thick_20_666666_40x40.png
skin/frontend/base/default/algoliasearch/images/ui-bg_glass_65_ffffff_1x400.png
skin/frontend/base/default/algoliasearch/images/ui-bg_flat_10_000000_40x100.png
lib/AlgoliaSearch/resources/ca-bundle.crt
lib/AlgoliaSearch/ClientContext.php
lib/AlgoliaSearch/Version.php
lib/AlgoliaSearch/Client.php
lib/AlgoliaSearch/AlgoliaException.php
lib/AlgoliaSearch/Index.php
Installation complete

**Comment by maxiloc** [comment]
Can you try with modman instead of modgit ? Also do you have an url where I can see the issue live ?

**Comment by osm-dev** [comment]
Hi! I tryied to install through modman, and the error is the same as when installed through modgit,  ReferenceError: algoliaBundle is not defined. I think there is some missing js file on my installation. Yes i do have a url, can you send me your email? (your team has my e-mail address)

**Comment by maxiloc** [comment]
just send it to support at algolia dot com. I'll have a look

**Comment by maxiloc** [comment]
It seems like this block https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/layout/algoliasearch.xml#L19 is added to your page.
You can either try to check why or import the two lines in https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/frontjs.phtml another way.

**Comment by osm-dev** [comment]
That was the problem. Thanks.
