### ISSUE TITLE
Mixed Content error in https

### ISSUE THREAD

**Issue by maximilianmikus** [algolia/algoliasearch-magento#336]
If I active https for the frontend, I get mixed content errors related to the search-form:

`Mixed Content: The page at 'https://www.beyondmedia.at/customer/account/login/' was loaded over HTTPS, but requested an insecure image 'http://www.beyondmedia.at//skin/frontend/base/default/algoliasearch/cross.png'. This content should also be served over HTTPS.`

**Comment by maxiloc** [comment]
You should be able to fix that by replacing references of Mage::getBaseUrl() by Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true)

- https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml
- https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/beforetopsearch.phtml

We'll try to work on a more permanent solution.

Just to be sure to reproduce your issue correctly, can you give me:
- the unsecure base url
- the secure base url
- which setting you are using to enable https

**Comment by maxiloc** [comment]
I am closing this feel free to re-open if needed
