### ISSUE TITLE
IE9 algoliaConfig is undefined.

### ISSUE THREAD

**Issue by stefkosmo** [algolia/algoliasearch-magento#338]
Hey, 

Getting this error in ie9. (See attached image)
![screen shot 2016-03-17 at 14 35 18](https://cloud.githubusercontent.com/assets/8162643/13849373/cb660f3e-ec4d-11e5-8092-048d608a1a05.png)

**Comment by maxiloc** [comment]
Do you have a url where we can see the issue live ?

**Comment by maxiloc** [comment]
No response I am closing this. Feel free to reopen if needed

**Comment by antoinekociuba** [comment]
Hi,

I can confirm that I have the exact same problem on a site still under development.
I will try to reproduce on you demo website and let you know, but in my opinion, this issue should not be marked as closed.

Keep you posted, thx.

**Comment by maxiloc** [comment]
Ok let's reopen it then :)

**Comment by antoinekociuba** [comment]
Have just tried on a Modern IE box (Win7 IE9) and I can reproduce on your demo website :

<img width="1025" alt="capture d ecran 2016-06-12 a 16 38 37" src="https://cloud.githubusercontent.com/assets/1146677/15991741/4af698f6-30bc-11e6-9037-52888cd293b1.png">

Thank you in advance

**Comment by JanPetr** [comment]
Thanks for comments and description. Will take a look at it. Reopening the issue.

**Comment by antoinekociuba** [comment]
Thx you guys!

**Comment by JanPetr** [comment]
You are welcome @antoinekociuba 💯 

It will be part of the next release or now it's a part of `develop` branch.
