### ISSUE TITLE
Magento site crashes when Algolia Limit is reached

### ISSUE THREAD

**Issue by spiralmedia-rupert** [algolia/algoliasearch-magento#341]
If your Algolia account has been suspended because you have hit the limit and a user tries to search your site, they are taken to a error page (There has been an error processing your request
Exception printing is disabled by default for security reasons.). Looking at the report I see the following result: "a:5:{i:0;s:62:"Operations quota exceeded, change plan to get more Operations.";i:1;s:4563:"#0 "

Now, I can understand why you don't provide results but I think its not good that it does not fall back to the original Magento search.

**Comment by maxiloc** [comment]
Fix with d69425a. It will be part of next release.

Thanks for reporting this.
