### ISSUE TITLE
Call to a member function getBackend() on a non-object in 

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#342]
Error while manually reindexing (using 1.5.4):

Fatal error: Call to a member function getBackend() on a non-object in `.../apps/magento/htdocs/app/code/core/Mage/Eav/Model/Entity/Abstract.php` on line 816

This is my line 816 it is referring to:

```php
$attrBackendStatic = $attrInstance->getBackend()->isStatic();
```

Any idea what that could mean?

**Comment by maxiloc** [comment]
Did you had any non default attribute ?

**Comment by sammarcus** [comment]
By non default attribute do you mean our own custom attributes for products?

I actually just cleared `eav_attribute` table of all attributes that had `is_user_defined` = `1`, there are only 39 attributes left (39 in admin interface but 128 in actual table), all of them are system out-of-the-box attributes that come with the platform.

FWIW, this only occurs on "Algolia Search Additional autocomplete sections" line:

![image](https://cloud.githubusercontent.com/assets/8689264/14037969/e1994bf8-f220-11e5-9446-f7ac513476aa.png)


Thank you for the help!

**Comment by maxiloc** [comment]
Can you try to remove all attributes from additional sections in "System > Configuration > Algolia Search > Autocomplete" , add them again and then try to reindex

**Comment by sammarcus** [comment]
Yes, that worked! Thanks so much! Reindex finished perfectly, everything is terrific! Thanks for the help!
