### ISSUE TITLE
URL problem

### ISSUE THREAD

**Issue by laurfx** [algolia/algoliasearch-magento#343]
Hello,

I have a problem with url what is showing in the instant search box, after url it's add a /default/ , how can i remove this?

Thanks

**Comment by maxiloc** [comment]
I am not sure to understand the issue. Can you give me a bit more details ? Do you have a url where I can see the issue live.

**Comment by laurfx** [comment]
Sorry, i can't give you the URL but i can explain you.

I use MultiStore for this site because i have multi language, so.. the default language is RO, and the url for the site was: www.mysite.com/default/ (RO store) and the English one www.mysite.com/EN/ .

I managed to hide the /default/ from the URL with a module, but the Alogia Search get the url from the default store.

**Comment by maxiloc** [comment]
Which version of the extension are you using ?

**Comment by laurfx** [comment]
This is the module - https://github.com/Knectar/Magento-Store-Codes
And i use the latest version of Algolia Search.

**Comment by maxiloc** [comment]
The url is fetch using the default magento core method here. https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L494
I don't think this is something we can fix as part of the extension as it needs to stay generic for every magento store
