### ISSUE TITLE
Multi Indices Search

### ISSUE THREAD

**Issue by manish172** [algolia/algoliasearch-magento#344]
Suggestion: Add option to search in products indices as well as pages indices on instant search result page. By default it will show both i.e. products as well as pages and there will be toggle filter to show products only/pages only

**Comment by maxiloc** [comment]
Yes we are already thinking about it. We'll keep you updated. Thanks for the suggestion

**Comment by manish172** [comment]
can you give me some high level idea to implement this? It's a must have feature for our client and I would see if i can implement this feature.

**Comment by maxiloc** [comment]
It's actually pretty simple if you do not want to do in a generic way.
You just need to instantiate several instantsearch object (https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L455-L463) with different indexName binding to the same input.

Tell me if you need more details

**Comment by manish172** [comment]
Actually, We want to search in multiple indices in single request so that we can get the combined result (pages + products). if we instantiate the another instantsearch object then we will get separate response then how can we manage the stats (number of pages, result count etc.)?

In this case, we will have to manipulate the data. Is there any way to get the search result from different indices using single request instead of instantiating multiple object?

**Comment by maxiloc** [comment]
No that's not possible. If you want it in 1 request you need to push content of both page and products in 1 index, but then you might have some issue having a good ranking, because the custom ranking of products differs a lot from the page one

**Comment by manish172** [comment]
Thanks @maxiloc!

**Comment by maxiloc** [comment]
I am closing this, we are not going to invest in this feature in the short term. Let's reopen it if needed.

**Comment by manish172** [comment]
are you planning to show the pages result on instantsearch page in generic way? we need the generic way to show the pages on instant search result page.

**Comment by maxiloc** [comment]
I don't know yet. We are going to work on getting feedback from end user regarding UI and UX + trying different way of presenting instantsearch. As soon as we do this, we will have a overview of where we gonna go with this.
