### ISSUE TITLE
Updating catalog rules discount and applying rule does not update prices in Algolia

### ISSUE THREAD

**Issue by Ilia** [algolia/algoliasearch-magento#346]
Hi,

We currently update the catalog rules ( discount percentages ) on a daily/weekly basis, which updates product prices for the customer group that are affected by the rule. The question I have is, do these prices changes flow through to algolia service. 

I have done a number of tests and don't see the prices updated in algolia, I also don't see anything in the algolia queue table when I "apply rule" with the new discount.

This is on 1.5.2 version of the module, any info on this will be very helpful. 

Cheers,
Ilia

**Comment by maxiloc** [comment]
Yes the extension does not handle this. If you create/update/delete a catalog rule you'll need to launch a full reindex manually.
I can not think of a clean way to handle it automatically. Their is two main reasons:
- The indexing in Algolia is done outside of the magento flow, and prices depends on others indexers. If we schedule it automatically, we have no guaranty that it will have picked up the new price for every product.
- I am not sure their is a way to get just impacted products of a catalog rule.

**Comment by Ilia** [comment]
Thanks for that info, is there a way to do a full reindex? we are thinking to bypass this, we would do a nightly/weekly scheduled full reindex

**Comment by maxiloc** [comment]
Sorry for the small delay.
Yes you can set the indexer to manual update. and launch a reindex once per day/week.
You might also want to clear the index from time to time because deleted products won't be deleted in that case.
Maybe this PR https://github.com/algolia/algoliasearch-magento/pull/355 once merge can solve this issue.
