### ISSUE TITLE
Error while doing indexing in Magento 1.9.2.4

### ISSUE THREAD

**Issue by algadgets** [algolia/algoliasearch-magento#348]
I am getting some error while indexing algolia search indexers 
![magento_indexing error](https://cloud.githubusercontent.com/assets/18314912/14330405/86dae556-fc51-11e5-9e42-924a2be9648a.JPG)

Please review the error picture to assist

thanks

**Comment by maxiloc** [comment]
I quite sure this is not related to the extension. The error mean that the currencies fetch with the magento core method => https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L291
are not valid.
What you can do to investigate is to wrap this line => https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L308 with a try catch, and see what is wrong with the $currency_code value
