### ISSUE TITLE
Sort by position

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#356]
Why is it impossible to sort result by position ? (And why this attribute is on the $excludedAttributes array Algolia_Algoliasearch_Helper_Entity_Producthelper line 41 function getAllAttributes)

**Comment by maxiloc** [comment]
Because we never had a use-case for it.
I think if you remove it from excluded attributes you should be able to add it to the list of attributes and then sort on it

**Comment by bastienlm** [comment]
Alright thanks, It's important to sort product by position for many user. I think it's a good idea to add this attribute. I think send a PR soon for that.

**Comment by maxiloc** [comment]
:+1:  we'll be happy to merge it :smile:

**Comment by maxiloc** [comment]
It seems to be more complicated that what I expected. I am not sure which position to take for search, since position are only relative to a category.

Feel free to submit a PR, I am closing this in the meantime.
