### ISSUE TITLE
Disabled products not removed on reindexing

### ISSUE THREAD

**Issue by thoaionline** [algolia/algoliasearch-magento#357]
Hi Algolia team,

We run a large Magento store with an nightly product import script. Indexers are disabled/reenabled before and after this script.

At the end of the import, we run a re-index on all indices in the system, including the Algolia product index.

Observations:

* Disabled products are not removed from the Algolia index when this is run.
* Disabled products are not removed from the Algolia index when we trigger the re-indexing from CMS interface.
* They are removed from Algolia if we trigger a save in the CMS interface for each product.

Looking into the code, we found that:

* Saving a product individually triggers the event for Mage_Index_Model_Event::TYPE_SAVE, which has proper handling for `status` (see `Algolia_Algoliasearch_Model_Indexer_Algolia::_registerCatalogProductEvent()`)
* The event handler for `Mage_Index_Model_Event::TYPE_MASS_ACTION` does not account for product status and thus fails to remove the disabled products.

Could you please look into and address this issue?

**Comment by maxiloc** [comment]
Thanks for reporting this, I'll look into it

**Comment by maxiloc** [comment]
I was not able to reproduce on the latest version, the status is handled correctly even for mass action.
Anyway a0b2d1d simplies drastically this logic and it should be easier to debug in case this happen again
