### ISSUE TITLE
Adding a sales filter

### ISSUE THREAD

**Issue by davidpike7** [algolia/algoliasearch-magento#359]
We currently have a "Sale" category which we'd like to include in the hierarchical category list. The category is not a subcategory of the currently selected root category and is another top level category:

```
- Hardware
-- Cabinet Handles
-- Hinges

- Sale
```

It seems that the logic of the Algolia implementation switches out the root category based on the current page. What would be the process for adding "Sale" to allow users to on the Hardware page to view products also in the sale category. Would it be better to break this into a separate toggle widget? 

I can provide a URL to the implementation if required.

**Comment by maxiloc** [comment]
I guess the quick fix would be to change 1 by 0 here https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L516

It should include root categories

**Comment by JanPetr** [comment]
Hello @davidpike7,
I took a look on your issue and if I got it right I don't think we want to implement such a feature.
From UX point of view it does not make sense to include categories from outside the category you are browsing. It would bring a lot confusion for end-users.

However, I understand your use-case but we don't plan adding such feature into our extension. Thank you for understanding.
