### ISSUE TITLE
placeholder images get mishandled with a CDN.

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#368]
I'm using a CDN to deliver images. 

Think this is related: https://github.com/algolia/algoliasearch-magento/issues/57

The plugin is saving my urls as //www.mysite.com/skin/frontend/theme/theme/images/catalog/product/placeholder/thumbnail.jpg

And when it tries to load them later, instead of using that URL, it shows up as 
https://www.mycdn.net//media///www.mysite.com/skin/frontend/theme/theme/images/catalog/product/placeholder/thumbnail.jpg - which is obviously the wrong spot.

Suggestions?

**Comment by lazyguru** [comment]
Check your template.  We have a customizied one but I know we saw this issue and had to modify the <img> tags to remove the hostname concatenation and that fixed it for us (I haven't check to see if this was actually a bug in extension or just a bug in our template work)

**Comment by sam327** [comment]
Well, I think there's an oddity in magento about how it handles the thumbnail url variable - And the algolia plugin doesn't quite handle it right.

If I look at a product that has an image url set to 
`catalog/product/cache/1/small_image/300x400/912345ab12345d0123458d23695/m/y/myproductimage.jpg`

And then the image url for items that have a placeholder are 
`//www.mysite.com/skin/frontend/theme/theme/images/catalog/product/placeholder/thumbnail.jpg`

So when it adds the skin URL to the front of both of these, it ends up broken.

**Comment by JanPetr** [comment]
Hey @sam327,
do you still experience this issue? Which version of the extesion do you use?
I checked it since version 1.5.2 we index only the part of URL which is behind base media URL. So it should work properly.

If you are going to update remeber that you will have to reindex all your data to make it work.

**Comment by JanPetr** [comment]
OK, this issue should be fixed by PR #383. It will be part of next release. Thanks for your contributions.
