### ISSUE TITLE
Algolia.log and system.log files creating errors at alarming rate. 

### ISSUE THREAD

**Issue by L9Nick** [algolia/algoliasearch-magento#369]
We are running Algolia 1.5.2 in our Magento store, things seem to have been running fine for months now. On a routine site check I noticed that the algolia.log file and system.log file are growing at an alarming rate. Thousands of errors a day in the system.log. All the same:

**Example error from system log: **
( 2016-04-28T13:51:16+00:00 DEBUG (7): Array to string conversion/mnt/nfs/www.ourdomain.com/files/html/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php  )

**Example error from algolia.log:**  
2016-04-28T22:20:23+00:00 DEBUG (7): >>>>> BEGIN CREATE RECORD 10515 1 (Our Name)
2016-04-28T22:20:23+00:00 DEBUG (7): Product type (bundle, mapped to: bundle)
2016-04-28T22:20:23+00:00 DEBUG (7): <<<<< END CREATE RECORD 10515 1 (Our Name) (0.10094594955444sec)
2016-04-28T22:20:23+00:00 DEBUG (7): <<<<< END CREATE RECORDS 1 (Our Name) (0.10130882263184sec)
2016-04-28T22:20:23+00:00 DEBUG (7): 
2016-04-28T22:20:23+00:00 DEBUG (7): 
2016-04-28T22:20:23+00:00 DEBUG (7): >>>>> BEGIN SEND TO ALGOLIA
2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END SEND TO ALGOLIA (0.025930881500244sec)
2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END rebuildStoreProductIndexPage 1 (Our Name) page 1 pageSize 100 (0.14516186714172sec)
2016-04-28T22:20:24+00:00 DEBUG (7): 
2016-04-28T22:20:24+00:00 DEBUG (7): 
2016-04-28T22:20:24+00:00 DEBUG (7): >>>>> BEGIN STOP EMULATION
2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END STOP EMULATION (0.00031399726867676sec)

It's unclear to us if this is just a normal feature with the Algolia debug? Is there a way to turn off debug? Is there a "best debug method" to resolve these issues? It seems that thousands of repeated errors a day has to be a problem we need to fix.

**Comment by maxiloc** [comment]
Yes logs are there to debug in case of issues. We added an option in 1.5.3
to disable it and we disable them by default.

On Saturday, 30 April 2016, L9Nick <notifications@github.com> wrote:

> We are running Algolia 1.5.2 in our Magento store, things seem to have
> been running fine for months now. On a routine site check I noticed that
> the algolia.log file and system.log file are growing at an alarming rate.
> Thousands of errors a day in the system.log. All the same:
>
> **Example error from system log: **( 2016-04-28T13:51:16+00:00 DEBUG (7):
> Array to string conversion/mnt/nfs/
> www.ourdomain.com/files/html/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
> )
>
> *Example error from algolia.log:*
>
> 2016-04-28T22:20:23+00:00 DEBUG (7): >>>>> BEGIN CREATE RECORD 10515 1
> (Our Name)
> 2016-04-28T22:20:23+00:00 DEBUG (7): Product type (bundle, mapped to:
> bundle)
> 2016-04-28T22:20:23+00:00 DEBUG (7): <<<<< END CREATE RECORD 10515 1 (Our
> Name) (0.10094594955444sec)
> 2016-04-28T22:20:23+00:00 DEBUG (7): <<<<< END CREATE RECORDS 1 (Our Name)
> (0.10130882263184sec)
> 2016-04-28T22:20:23+00:00 DEBUG (7):
> 2016-04-28T22:20:23+00:00 DEBUG (7):
> 2016-04-28T22:20:23+00:00 DEBUG (7): >>>>> BEGIN SEND TO ALGOLIA
> 2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END SEND TO ALGOLIA
> (0.025930881500244sec)
> 2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END
> rebuildStoreProductIndexPage 1 (Our Name) page 1 pageSize 100
> (0.14516186714172sec)
> 2016-04-28T22:20:24+00:00 DEBUG (7):
> 2016-04-28T22:20:24+00:00 DEBUG (7):
> 2016-04-28T22:20:24+00:00 DEBUG (7): >>>>> BEGIN STOP EMULATION
> 2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END STOP EMULATION
> (0.00031399726867676sec)
>
> It's unclear to us if this is just a normal feature with the Algolia
> debug? Is there a way to turn off debug? Is there a "best debug method" to
> resolve these issues? It seems that thousands of repeated errors a day has
> to be a problem we need to fix.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-magento/issues/369>
>


-- 

[image: Algolia] <https://www.algolia.com/>

[image: Twitter] <https://twitter.com/maxiloc> [image: Linkedin]
<https://www.linkedin.com/in/maximelocqueville> [image: github]
<https://github.com/maxiloc>

Maxime Locqueville
Full-stack Software Engineer

Website: https://www.algolia.com/
<https://www.algolia.com/#millisecond-matter>
[image: htmlsig.com] <https://www.algolia.com/#milliseconds-matter>

We are hiring! <https://www.algolia.com/jobs#milliseconds-matter>

**Comment by L9Nick** [comment]
How can we disable them in 1.5.2?

On Apr 30, 2016, at 6:37 AM, maxiloc wrote:

> Yes logs are there to debug in case of issues. We added an option in 1.5.3
> to disable it and we disable them by default.
> 
> On Saturday, 30 April 2016, L9Nick <notifications@github.com> wrote:
> 
> > We are running Algolia 1.5.2 in our Magento store, things seem to have
> > been running fine for months now. On a routine site check I noticed that
> > the algolia.log file and system.log file are growing at an alarming rate.
> > Thousands of errors a day in the system.log. All the same:
> >
> > **Example error from system log: **( 2016-04-28T13:51:16+00:00 DEBUG (7):
> > Array to string conversion/mnt/nfs/
> > www.ourdomain.com/files/html/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php
> > )
> >
> > *Example error from algolia.log:*
> >
> > 2016-04-28T22:20:23+00:00 DEBUG (7): >>>>> BEGIN CREATE RECORD 10515 1
> > (Our Name)
> > 2016-04-28T22:20:23+00:00 DEBUG (7): Product type (bundle, mapped to:
> > bundle)
> > 2016-04-28T22:20:23+00:00 DEBUG (7): <<<<< END CREATE RECORD 10515 1 (Our
> > Name) (0.10094594955444sec)
> > 2016-04-28T22:20:23+00:00 DEBUG (7): <<<<< END CREATE RECORDS 1 (Our Name)
> > (0.10130882263184sec)
> > 2016-04-28T22:20:23+00:00 DEBUG (7):
> > 2016-04-28T22:20:23+00:00 DEBUG (7):
> > 2016-04-28T22:20:23+00:00 DEBUG (7): >>>>> BEGIN SEND TO ALGOLIA
> > 2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END SEND TO ALGOLIA
> > (0.025930881500244sec)
> > 2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END
> > rebuildStoreProductIndexPage 1 (Our Name) page 1 pageSize 100
> > (0.14516186714172sec)
> > 2016-04-28T22:20:24+00:00 DEBUG (7):
> > 2016-04-28T22:20:24+00:00 DEBUG (7):
> > 2016-04-28T22:20:24+00:00 DEBUG (7): >>>>> BEGIN STOP EMULATION
> > 2016-04-28T22:20:24+00:00 DEBUG (7): <<<<< END STOP EMULATION
> > (0.00031399726867676sec)
> >
> > It's unclear to us if this is just a normal feature with the Algolia
> > debug? Is there a way to turn off debug? Is there a "best debug method" to
> > resolve these issues? It seems that thousands of repeated errors a day has
> > to be a problem we need to fix.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/algolia/algoliasearch-magento/issues/369>
> >
> 
> 
> -- 
> 
> [image: Algolia] <https://www.algolia.com/>
> 
> [image: Twitter] <https://twitter.com/maxiloc> [image: Linkedin]
> <https://www.linkedin.com/in/maximelocqueville> [image: github]
> <https://github.com/maxiloc>
> 
> Maxime Locqueville
> Full-stack Software Engineer
> 
> Website: https://www.algolia.com/
> <https://www.algolia.com/#millisecond-matter>
> [image: htmlsig.com] <https://www.algolia.com/#milliseconds-matter>
> 
> We are hiring! <https://www.algolia.com/jobs#milliseconds-matter>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

 	
NICK MURDOCK
VP of IT
 	
 
M:801.671.8651 O:801-298-6425 E:nick@levelninesports.com
 
LEVELNINESPORTS.COM 1199 W 2425 S WOODS CROSS, UT 84087

**Comment by maxiloc** [comment]
You can apply this commit manually. This will add the option to disable them

**Comment by maxiloc** [comment]
I forgot the link 😄. Here it is https://github.com/algolia/algoliasearch-magento/commit/c4bacff5b5aab76dbaab00a8f47faecb80de89f9

**Comment by L9Nick** [comment]
=) thanks I wouldn't have gotten it. So we just need to add all the code in green right?

**Comment by maxiloc** [comment]
Yes that's it. Then just make sure it's set to no in the configuration
