### ISSUE TITLE
Index other content

### ISSUE THREAD

**Issue by pixel-developpement** [algolia/algoliasearch-magento#370]
Is it possible to index other content that the products, categories and pages?

I would have indexes the content of a blog that is on Magento (Neoblog), is it possible?

Thank you for your reply

**Comment by maxiloc** [comment]
Yes it's possible but we don't have a way to do it genericly in the extension.
You can have a look at this simple indexer https://github.com/algolia/algoliasearch-magento/blob/master/code/Model/Indexer/Algoliasuggestions.php
