### ISSUE TITLE
Adding 'indexed_at' to index

### ISSUE THREAD

**Issue by Floddy** [algolia/algoliasearch-magento#372]
It would be a nice feature to include the date for when a record is updated in the index - so you can see when for example a product was last indexed by Algolia, in the algolia dashboard.

Whould this be possible?

**Comment by maxiloc** [comment]
I am not sure we want this by default in the extension but you can for sure doing on your side using this hook => https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L497

**Comment by Floddy** [comment]
Just adding some comments :)

It would be nice to verify that everything has been indexed OK without testing to add whitespaces to product names etc. to see if things changes. Perhaps this data is already available somewhere in the index though - like if Algolia's API saves a date for when it receives the update? If so, it could possibly be something for the dashboard UI team?

We could use an observer and add the data - but it's a bit of repetitive work, and would be nice to have built in.
