### ISSUE TITLE
block name is missing

### ISSUE THREAD

**Issue by manish172** [algolia/algoliasearch-magento#378]
all the blocks included in layout xml should have name attribute so that it can be customized without modifying the original file. Ex.
`<block type="core/template" template="algoliasearch/beforetopsearch.phtml"/>`

**Comment by maxiloc** [comment]
Indeed, if you already done it, feel free to submit a PR otherwise we'll add this

**Comment by JanPetr** [comment]
Names to blocks were added. It will be part of next release. Thanks for your help 👍
