### ISSUE TITLE
Implement synonyms API

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#388]
_Algolia's Synonyms API feature is still in beta and not ready for production usage. We will wait until it's release._

**Comment by michaelzangerle** [comment]
Do you know approximately when the API will be released for production usage?

**Comment by JanPetr** [comment]
Hello @michaelzangerle, we start to work on that now. Unfortunately I cannot give you any ETA, but right now it's our main priority. I will let you know once we have something in test.

**Comment by JanPetr** [comment]
Implemented to `develop` branch. It will be part of the next release 💥
