### ISSUE TITLE
Hosts Unreachable

### ISSUE THREAD

**Issue by KimITAU** [algolia/algoliasearch-magento#391]
Occasionally a customer is unable to checkout and the error returned is 

`Hosts unreachable: Connection time-out,SSL: no alternative certificate subject name matches target host name 'XXXXXX-1.algolianet.com',SSL: no alternative certificate subject name matches target host name 'XXXXXX-2.algolianet.com',SSL: no alternative certificate subject name matches target host name 'XXXXXX-3.algolianet.com' `

The problem is intermittent and I'm on the latest release. (Magento v 1.8.1)

Any help appreciated

**Comment by maxiloc** [comment]
@KimITAU  what version of the extension are you using ?

**Comment by KimITAU** [comment]
I was on 0.1.0, now I'm on 1.5.5 and having the same error when trying to save the configuration in the admin

**Comment by maxiloc** [comment]
Did you install via magento connect ?

**Comment by maxiloc** [comment]
I am asking this because we had some issues with one of our dns provider today. Only old php api client are impacted. So updating to 1.5.5 should have fixed it. Maybe you have some cache or compilation enabled ?

**Comment by KimITAU** [comment]
Ok, reinstalled via connect. One issue is that my client is on php 5.3 so I've had to edit the short array syntax in some of the files. 
Still no luck.

**Comment by alexandremeunier** [comment]
@KimITAU do you mind sending an email to support@algolia.com with the application ID? thanks

**Comment by KimITAU** [comment]
I'm so sorry, I just found some overridden files in the local directory. 
Deleted and appears to be working now

thanks for your help

**Comment by alexandremeunier** [comment]
No worries, glad you found the solution !
