### ISSUE TITLE
Related products and tags

### ISSUE THREAD

**Issue by m0zziter** [algolia/algoliasearch-magento#395]
I've been experimenting with this extension over the past few days but can't figure out how to search/index related products. Is this possible? As far as I can tell it looks like I can configure Algolia to index a product's attributes. I thought about using product tags, but I can't seem to get them to show up in Algolia either.

We have a parts category (that contains all the parts we sell) and each product's "Related Products" contains the parts compatible with that product.

My use case is this: we sell replacement parts for some of our products. I would like to be able to let the customer search for replacement parts by product.  For example: say I have a product called MyProduct and I need a power cable for it but I do not know the name or sku of the part I need. To find this product I might go to a faceted search filter by the parts category then type in "MyProduct" to the search bar and at this point I would *in theory* be looking at a list of parts for MyProduct. 

Is something like this achievable? It occurs to me that I could put the product sku into the part's description to achieve this. However since the parts are already associated to the product via "related products" I was hoping we could just use that instead of having to modify each part.

Anyways, sorry to ramble, thanks for you time and effort!

**Comment by maxiloc** [comment]
@m0zziter We never had the use case, I think it's doable but I am not exactly sure how yet. We'll investigate and come back to you asap.

**Comment by JanPetr** [comment]
Hey @m0zziter,
thanks for reaching us out with your problem.

Your use-case is definitely doable but unfortunately not with standart behavior of the plugin. We have not decided yet if will implement this feature but for the start here are some tips how you can tackle your problem.

The best way would be to hook on [`algolia_product_index_before`](https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L497) custom event. In the hook you can get related products of indexed product and add it to transport data.

If you cannot or don't want to hook on event you can modify `Producthelper.php` file directly and inject your code [somewhere here](https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L515) for example. 

Snippet of the code how it could look like:

```php
foreach($product->getRelatedProductIds() as $relatedProductId) {
    $relatedProduct = Mage::getModel('catalog/product')->load($relatedProductId);

    $customData['relatedProducts'][] = [
        'name' => $relatedProduct->getName(),
        'sku' => $relatedProduct->getSku(),
    ];
}
```

**Comment by lazyguru** [comment]
@JanPetr it would be better to get a collection using the product ids rather than calling load() inside a foreach (lots of performance issues loading inside a foreach like that)

**Comment by JanPetr** [comment]
Thanks @lazyguru for correction, it would be definitelly better to use collections.

**Comment by m0zziter** [comment]
Thanks for the update! I appreciate you guys taking the time to look into this for me. I will give your suggestion regarding related products a try.
