### ISSUE TITLE
Counting and category filtering errors

### ISSUE THREAD

**Issue by schwipps** [algolia/algoliasearch-magento#401]
Algolia doen't return the correct values when counting products in my catalog.
In the results are shown  inactive products, with missing attributes.
in the category sidebar section,  when I type the name of a category, it counts way too many products / something barely equal to what's ticked in the corresponding category, disregarding what active or visible.
Finally, dropdown menu category links do not return filteredresults when clicked, and do not always display all the matching categories.
Can we get a hand here ?

Thanks.

**Comment by JanPetr** [comment]
Hello @schwipps,
we fixed the issue with products count in a category (89f8ad8) and it will be part of next release. Hopefully sometimes during next week we should release it.

About your other issues - do you update your products standart way and trigger standart Magento hooks? Or do you use some kind of automatic imports directly to Magento database?

When you do full re-index by reindex all in **System > Index management**, does it fix the data in your indices?

**Comment by schwipps** [comment]
Thanks for the fix. Are we your first clients to face this issue ?

Our products are updated with [magmi](https://github.com/dweeves/magmi-git).

I already tried many times to reindex the catalog, from the admin panel and from shell : EMPTY_QUEUE=1 php -f shell/indexer.php -- -reindex algolia_queue_runner
or with reindexall
With no luck...

**Comment by schwipps** [comment]
I tried your fix, and it didn't change anything for us, even after full magento + Algolia reindexing.
I'll see what happens after a full import process.

**Comment by JanPetr** [comment]
I've been looking around Magmi and this plugin unfortunatelly bypasses all standart Magento Model events.
That means that products are not synchronized with Algolia indices on regular basis. In this case you have to manually run full reindexes. But full reindex in this time unfortunatelly do not remove disabled products from Algolia indices. We have fix (fb2859f6830cfd34069ad95ec3790aef8cdf7074) and it will be part of the next release as well.

**Comment by schwipps** [comment]
Can I test it yet ?

**Comment by JanPetr** [comment]
Of course, it's public. By mind that it is still not released in stable, so there might be some issues eventually.

Let us know if you tried it and the results.

**Comment by schwipps** [comment]
OK ! My bad : I had to clear config cache before reindexing. Now, the product count has indeed drastically dropped !

Though, I still see inactive configurable products in results, may be because a few related simple are still active ?

I've also figured out that category links didn't work, because the request I was testing was a expression for which a redirection is set. I keep testing for now, but thanks already for these patches :)

**Comment by JanPetr** [comment]
Cool! I'm glad you figured out the issue. About configurable products - it might be because of the active related products. 

So I'm closing the issue now. Let me know if you find any other issues.
