### ISSUE TITLE
Algolia 1.5.5, empty SKU for simple product

### ISSUE THREAD

**Issue by larascasse** [algolia/algoliasearch-magento#404]
Hello,
The sku attribute is missing for simple product in the index process.

I make it working by adding this 
`else if('sku' == $attribute_name){
                        $value = $this->getValueOrValueText($product, $attribute_name, $attribute_resource);

                        if ($value)
                        {
                            $customData[$attribute_name] = $value;
                        }
                    }`

app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php on line 755

Best,
Florent

**Comment by aude** [comment]
https://github.com/algolia/algoliasearch-magento/pull/403

**Comment by JanPetr** [comment]
Fixed in #407. it will be part of 1.6.0 release.
