### ISSUE TITLE
Develop branch doesn't work with Turpentine

### ISSUE THREAD

**Issue by thaiphan** [algolia/algoliasearch-magento#411]
Hey guys,

I've switched to using the develop branch. However, I've bumped into another problem where the extension no longer works with Turpentine. I just get a blank page for the category and search pages now. I think it has to do with Algolia_Algoliasearch_Model_Observer::useAlgoliaSearchPopup().

Would you guys be able to have a look see and perhaps address the problem as well?

Regards,

Thai

**Comment by JanPetr** [comment]
Hey @thaiphan,
in develop branches we completely refactored the extension's templates (fd949ddfac21cb83c7ba08a455649d3c4a3c02). We divided the only one template into two another to make it easier to update. However it causes BC breaks if you modifed standard templates or made modifications to standart ones. Can you check that new templates are properly loaded and redered? Perhaps cache issue?

Could you check your console if it shows any errors? Thanks!

**Comment by JanPetr** [comment]
By "Turpentine" you mean this extension https://www.magentocommerce.com/magento-connect/turpentine-varnish-cache.html?
I tried to install it and everything works :-/

**Comment by thaiphan** [comment]
Hey @JanPetr,

> Can you check that new templates are properly loaded and redered? Perhaps cache issue?

Yeah I had already refactored my custom templates to work with the new changes. My development copy of my site doesn't have Varnish set up.

I'm fairly certain that it's an issue with Turpentine because I added the categories and categorysearch URL prefixes to the Turpentine whitelist and the Algolia search results started showing up again.

> I tried to install it and everything works :-/

You can't just install the extension. You have to also install Varnish and then configure Turpentine to connect to it. Is that something you have already tried?

Regards,

Thai

**Comment by JanPetr** [comment]
Hey @thaiphan,
no, I have not, I just installed the extesion. I will try to set it up in case something occurs in future.

So I close the issue now as it's not the extestion's issue. If something comes up, feel free to open it again or create a new one ;)
