### ISSUE TITLE
Suggestions are not store/website wise

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#419]
Autocomplete suggestions are "global". If 1 customer searches for product on 1 website/store view. suggestions after some time are showed on other websites/store views. If you have different product line or different language it looks bad..

**Comment by maxiloc** [comment]
@repignite  What version of the extension are you using ?

**Comment by repignite** [comment]
The latest. Should I create separate Agnolia accounts to use it on different websites? probably not.
But Autocomplete WHEN EMPTY results suggest searching for phrases from 2nd website.....

**Comment by maxiloc** [comment]
@tomekjordan I checked, It's working well on my side.
The extension is not writing any data, just fetching from the catalogsearch_query table, so yes I think search query were made before algolia search got installed
