### ISSUE TITLE
jquery conflicts

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#428]
Hi, loading jquery should have options in panel. because its conflicting with lightboxes/fancyboxes

**Comment by maxiloc** [comment]
@repignite Which version of the extension are you using. Because there should not be any conflict, we are not exposing nor changing ```$```, or ```JQuery``` in window.
It's only available inside algoliaBundle => https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L416 (at least in latest versions)

**Comment by repignite** [comment]
1.5.5 the latest. if I enable Algolia - all my Fancybox > instagram images stop to work - popup is broken, cannot close etc. No matter I change option in Instagram widget to not load jquery/fancybox. so probably there is something in Algolia that triggers this issue

**Comment by JanPetr** [comment]
@repignite Do you receive any JS errors in your browser console?

**Comment by repignite** [comment]
no.

**Comment by maxiloc** [comment]
I don't think it's jquery related. The jquery we load is loaded in a way that can not conflict with other librairies.
Did you enable the instant search feature or just the autocomplete ?
Also do you have a link where we can see the issue live ?

**Comment by JanPetr** [comment]
Hello @tomekjordan,
did you manage to make your JS work?

**Comment by tomekjordan** [comment]
yes. works. thanks. looking forward for synonims feature - this is no.1 to develop. really important for all stores

**Comment by JanPetr** [comment]
OK, good to hear that. We will work on synonyms for sure 👍
