### ISSUE TITLE
css - to fix for wide design

### ISSUE THREAD

**Issue by repignite** [algolia/algoliasearch-magento#429]
Hi. there are problems with styling col3 + col9 because content is not placed side by side. [http://prntscr.com/bbzia3](http://prntscr.com/bbzia3) also dropdown block is disapperaing on untouch - so its imposible to check css classes + this is rally hard on mobile to search - because 50% of screen takes keyboard
Recommendation: give max-width, max-height options in Algolia configuration

**Comment by JanPetr** [comment]
@repignite The CSS is not something we can secure all the time. Once when it starts to mix with your CSS there might be conflicts and you have to adjust CSS a bit to work with your design.
To check CSS you can switch `debug` option here https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L775 to `true`, so the autocomplete menu will not disappear on blur and you can investigate your issue.

**Comment by repignite** [comment]
Thanks. helped.

**Comment by JanPetr** [comment]
Cool, I'm glad ;)
