### ISSUE TITLE
Algolia load js vs Cloudflare Rocket Downloader

### ISSUE THREAD

**Issue by repignite** [algolia/algoliasearch-magento#430]
Hi. Algolia very often is not loaded correctly when Cloudflare rocket downloader is enabled. Cloudflare.
Solution is to add data-cfasync="false" to script load line.
Like:  <script data-cfasync="false" src="/javascript.js"></script>      
Where are the agnolia js loader lines located?

Thanks a lot
[Cloudflare Disabling Rocket Downloader for particular JS script](
https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-)

**Comment by JanPetr** [comment]
Hey @repignite, here: https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/frontjs.phtml

**Comment by repignite** [comment]
Fixed
https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/frontjs.phtml
with:
```
<script data-cfasync="false" src="<?php echo Mage::getBaseUrl('js'); ?>algoliasearch/Function.prototype.bind.js"></script>
<script data-cfasync="false" src="<?php echo Mage::getBaseUrl('js'); ?>algoliasearch/algoliaBundle.min.js"></script>
```
Works now with Cloudflare CDN. Thanks
