### ISSUE TITLE
Magento attributes requrements to include into navigation

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#432]
HI. What are Magento required fields for attributes to appear on navigation search? I have created some attributes like brand and age.
And despite both have the same settings. Brand attribute is not show up in results.
Checked deeply - no luck, why.
[Screenshot for attribute
![screenshot_17](https://cloud.githubusercontent.com/assets/8250276/15819710/2d689a7c-2be5-11e6-8c12-3459fb2f95ed.png)
](http://prntscr.com/bcyd7p)

**Comment by JanPetr** [comment]
Is the `brand` attribute set as indexable in **System > Configuration > Algolia Search**? And is it set as attribute for faceting (it must be set as indexable before it can be set as attribute for faceting)?

**Comment by tomekjordan** [comment]
Hi. The problem is that this attribute doesn't show up there. [Screen](http://prntscr.com/bcyj38)
Indexing, everything all done. Very strange.

**Comment by JanPetr** [comment]
Only indexed attributes can be selected as facets. Do you have brand attribute in here? 
https://www.dropbox.com/s/pyfqx4b6ivup10n/Screenshot%202016-06-06%2013.24.02.png?dl=0
https://www.dropbox.com/s/god5id4oucg5uhd/Screenshot%202016-06-06%2013.24.19.png?dl=0

**Comment by tomekjordan** [comment]
Thanks for tips. Helped. I didn't suspect it is related each other. And I was confused that Product tab is placed below Instant Page tab. Now attributes showup, and everything works. Thanks

**Comment by JanPetr** [comment]
No problem ;) I next version you will be able make facets even from attributes which are not selected in indexable attributes. Cheers!
