### ISSUE TITLE
Catalog rules prices

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#436]
Your module can't manage catalog rules prices.
For exemple:
I have customer group 'Customer club', this group have 5% discount of all product, but this price isn't indexed in algolia, so in the catalog listing , the price for this group is wrong.

**Comment by JanPetr** [comment]
Hey @bastienlm,
which version of the extension do you use? Did you re-indexed your products when you applied the price rules?

**Comment by JanPetr** [comment]
And one more thing - did you enabled customer groups in Algolia Configuration? https://www.dropbox.com/s/e0sn4zki0gg9z28/Screenshot%202016-06-09%2017.26.54.png?dl=0

**Comment by bastienlm** [comment]
Oh yes, i just see it ! I try this tomorrow, thank you !
