### ISSUE TITLE
Add option to integrate Google Analytics to extension.

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#439]
This will allow it's users to send search data to Google Analytics and have possibility to analyze them there.

**Comment by davids101** [comment]
As long as the search is completed, the parameter passes and GA will see it. If you aren't seeing completed searches in GA then you haven't set the parameter correctly

**Comment by JanPetr** [comment]
But you mean only backend search, right? This proposing is targeting mostly instatsearch pages when there is no backend search needed.

**Comment by davids101** [comment]
Thanks for clarifying, yes I'd like to see this feature as well

**Comment by davids101** [comment]
Any updates here? It would be nice to at least record product clicks as events

**Comment by JanPetr** [comment]
Hello @davids101,
sorry for getting back to you that late. Currently no ETA for out-of-box integration as it's very individual thing.
Can you write you own JS code and send custom GA events based on clicks on results? 
Or what'd be your use case for that, what information you'd like to send to GA?

**Comment by Mobecls** [comment]
Hello @davids101, I see that you had issues with GA, did you find any solution? as we would like to track search parameters in Analytics as well.

**Comment by JanPetr** [comment]
GA integration directly to the extension is very tricky and we're not sure how to implement it directly to the extension.

But we released a new instantsearch.js widget for analytics support - https://community.algolia.com/instantsearch.js/documentation/#analytics-1 Feel free to integrate it to your sites!

**Comment by Mobecls** [comment]
thanks

**Comment by JanPetr** [comment]
Won't be integrated directly to the extension because of it's complexity.
Will be available through JS hooks ( #631 ) and [IS.js analytics widget](https://community.algolia.com/instantsearch.js/documentation/#analytics-1). Closing the issue now.
