### ISSUE TITLE
Partial product index when save categories

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#444]
Hello,

When you update product categories from the product, and you save it, magento updates this product in algolia.
But, when you update products in category from the category, all new products in this category are not updated in algolia.

It's possible for you to update product when it's added or deleted from categories ?

**Comment by maxiloc** [comment]
hello @bastienlm, which version of the extension are you using ?

**Comment by bastienlm** [comment]
1.5.4

**Comment by JanPetr** [comment]
Hello @bastienlm,
if I got your issue right, it was already solved in this commit: https://github.com/algolia/algoliasearch-magento/commit/dbd417c12c38fb14a00c225bf8acfc9dccf0e1e8
It will be part of the next release of the extension.

**Comment by bastienlm** [comment]
Oh, great !
I'm gonna look that, when you think release this update ?

**Comment by bastienlm** [comment]
Oh great, Thank you ! I wait the next version now !
