### ISSUE TITLE
Facet sort alphabetically

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#455]
Hello,

Actually, all facets refinement are sorted by number of results. Do you think it's possible to sort the refinement by name ?
http://screencast.com/t/xkoqCBnxxP

Thank you !

**Comment by JanPetr** [comment]
Hello @bastienlm,

for rendering facets we use instantsearch.js library. You can update JS code of the extension and add `sortBy` option. Here is documentation of the widget with possible options: https://community.algolia.com/instantsearch.js/documentation/#refinementlist
And if you use version 1.5.5 of the extension, you should add `sortBy` option to those two widgets: https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/beforetopsearch.phtml#L212-L240
