### ISSUE TITLE
Refinement List, sort by magento attribute value position

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#465]
Hello,

I need sort my filter value by specific position, in magento I have configure the position for all my attribute values:
http://screencast.com/t/8sRVzIuuTqY

and i need retrieved this position on my algolia filter:
http://screencast.com/t/7HwlWIKZVzLu

For the moment I sort by name thanks to:

`if (facet.type === 'conjunctive') {

                    templates.item = listItemTemplate;
                    return algoliaBundle.instantsearch.widgets.refinementList({
                        container: facet.wrapper.appendChild(document.createElement('div')),
                        attributeName: facet.attribute,
                        limit: algoliaConfig.maxValuesPerFacet,
                        operator: 'and',
                        templates: templates,
                        sortBy: [
                            'name:asc'
                        ],
                        cssClasses: {
                            root: 'facet conjunctive'
                        }
                    });
                }
`
And i need make specific position for me filter 'size', and make something like that:
```
if (facet.attribute === 'size') {

                    templates.item = listItemTemplate;
                    return algoliaBundle.instantsearch.widgets.refinementList({
                        container: facet.wrapper.appendChild(document.createElement('div')),
                        attributeName: facet.attribute,
                        limit: algoliaConfig.maxValuesPerFacet,
                        operator: 'and',
                        templates: templates,
                        sortBy: [
                            'name:XL',
                            'name:L',
                            'name:M',
                            'name:S',
                            'name:XS',
                        ],
                        cssClasses: {
                            root: 'facet conjunctive'
                        }
                    });
                }
```

Do you think it's possible ? Thank you.

**Comment by JanPetr** [comment]
Hello @bastienlm,
to `sortBy` you can pass custom function you receive `a` and `b` and return -1, 0 or 1 depending on their relative order.

**Comment by JanPetr** [comment]
@bastienlm Here is great example: https://github.com/Shipow/searchstone/blob/master/src/js/searchstone.js#L193-L210

**Comment by bastienlm** [comment]
Thank you !
