### ISSUE TITLE
Integration with Configurable Swatches?

### ISSUE THREAD

**Issue by VincentMarmiesse** [algolia/algoliasearch-magento#467]
Hello,
Is it possible to enable the configurable swatches on the products listing?

We would like to add the "Add to cart" functionality with the configurable swatches on the products listing.

Thank you for your answer.

Regards,

Vincent

**Comment by JanPetr** [comment]
Hello Vincent,
to be honest I don't know exactly what are configurable swatches in Magento.

But basically if you are able to index it, you are able to retrieve the data on search page and do whatever you want with them. So when you manage to index your configurable swatches as product attribute, you can get it from Algolia when the search page is rendered. Then you just have to update JS code and hits template to render it in a right way and you are done.

**Comment by VincentMarmiesse** [comment]
Here is an exemple of how the configurable swatches work in Magento: http://www.venustheme.com/configurable-swatches-guide-for-magento-1-9-1/

**Comment by JanPetr** [comment]
Well ok, it looks it's attribute which is selectable on product listing. So the main goal is to index it. If it's Magento attribute you are able to configure Algolia Extension so the attribute gets indexed. Once it's indexed, it's also retrieved when you perform search on your frontend. So you can update instant search templates to render these attributes as swatches and add "Add to cart" button. This stuff has to be done ion your side.

**Comment by VincentMarmiesse** [comment]
Ok I will let you know if I succeed.
