### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#468]
Hello,
Everything is on the title, I need integrate the infinie scroll for Aloglia,
I look https://www.algolia.com/doc/search/infinite-scroll#file-structure but i don't know how to integrate this to Magento. Do you have an idea or a solution ? Thank you !

Regards,
Bastien

**Comment by JanPetr** [comment]
Hello @bastienlm,

here you can find initialization of instantsearch.js in Magento. 
https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml#L455-L585

This is the place, where you should inject your custom infinite scroll widget from mentioned guide. So when you will follow the guid and update the code in topsearch.phtml file, I believe you will get desired results 👍

**Comment by talha-malik** [comment]
Hi @JanPetr 
above given link is broken. Can you check please.

**Comment by JanPetr** [comment]
Hey @talha-malik,
we have done some changes in current master. Here is correct link for version 1.5.5: https://github.com/algolia/algoliasearch-magento/blob/1.5.5/design/frontend/template/topsearch.phtml#L455-L585

And here is correct link for current version: https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/instantsearch.phtml

We strongly recommend you to always use the latest version ;)
