### ISSUE TITLE
POST Bad Request for live searches

### ISSUE THREAD

**Issue by ZayLong** [algolia/algoliasearch-magento#47]
I've been tinkering with the module to use it as my default search engine in magento, but there seems to be an issue with sending requests that I can't resolve.

Whenever I type in a search bar this error ocours

**Error: String not allowed outside of params near line:1 column:432  algoliasearch.js?version=23:line 546**
*Object {message: "String not allowed outside of params near line:1 column:432"}*

 **'{"requests":"[{\"indexName\"** is getting back slashes applied to it for some reason. Is there any resolution for this issue or am I just doing something wrong?

**Comment by redox** [comment]
We just got another complain about such issue. In that case it was related to the inclusion of Protoype.js 1.6 (similar complains on SO: http://stackoverflow.com/questions/13848027/prototype-js-1-6-x-tojson-misbehaves)

**Comment by vvo** [comment]
In the JS client, we could save toJSON methods before doing JSON.stringify and then put them back.

It would make our code safe to those problems.
