### ISSUE TITLE
Adding a placeholder for broken images

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#470]
For a variety of reasons, I sometimes end up with broken images, where it's not pulling in the product image or the placeholder I defined in magento. 

So, to prevent those broken images, I'm adding in some extra code where the image loads, and if there's an error, it uses a separate placeholder. 

Using a javascript onerror check that looks like this: onError="this.onerror=null;this.src='/media/nothumb.png';" 

The extra 'onerror=null' clears the error, so if the image breaks, it doesn't loop and melt-down. 

```
    <!-- Product hit template -->
  <script type="text/template" id="autocomplete_products_template">
      <a class="algoliasearch-autocomplete-hit" href="{{url}}">
          {{#thumbnail_url}}
          <div class="thumb"><img src="<?php echo $image_base_url; ?>{{thumbnail_url}}" onError="this.onerror=null;this.src='/media/nothumb.png';" /></div>
          {{/thumbnail_url}}
       ...
```

I'm not sure if there's a better way to do this. I've added this onerror check inline, but one probably could add it to the js file and streamline a bit.

**Comment by JanPetr** [comment]
Hello @sam327,
good idea but I'm not sure we want this behaviour in the extension as it affects default browser behaviour.

This is something you can implement on your side. As you mentioned you can create a custom JS script and handle it there.
