### ISSUE TITLE
Updated 1.5.5 to 1.6 > results much worse + locales problem

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#477]
HI. I just updated from 1.5.5 to 1.6 and I can observe that results given by new 1.6 are much worse than on 1.5.5. English language is ok, but Polish now is much worse. Maybe introduced synonyms affected it?
I didn't touch any settings. just reindexed.

BTW: translation added in 1.6 is not working, besides locales by default should be en_US instead of en_GB. But I cannot see that locales are even loaded (I tried to recopy them to pl_PL) no luck.
Do you have any thoughts why 1.6 presents results that are much worse that on 1.5.5 ? especially for other than English languages?
words with suffix ending with "pies" vs "psem" are not matching too good

Thanks for help

**Comment by maxiloc** [comment]
Hi,

The search has not been updated. Do you have a live example. If yes can you give us an example of bad query and what you would expect.
The synonym feature does not change anything out of the box.

Can you explain why en_US is better than en_GB ?

If you don't have a live example feel free to send more details to support at algolia dot com, and we'll investigate

**Comment by tomekjordan** [comment]
en_US is default loaded by Magento. all extensions have en_US translation by default, and rest locales are optional.

**Comment by tomekjordan** [comment]
Hi. we can close this, after removing agnolia 1.5.5 deprecated files and install fresh 1.6 all issues gone. Thanks for awesome support.

**Comment by maxiloc** [comment]
Ok thanks for getting back to us. We'll update the default locale for the next version
