### ISSUE TITLE
doesn't load correct language for filters names in faceted navigation

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#479]
Hi. There are some problem with Faceted navigation left sidebar it loads filters in base language (used for global) instead of language used on website/store view. Example: [http://prntscr.com/boleju](http://prntscr.com/boleju)

**Comment by maxiloc** [comment]
You need to change the Label for each of your store/language, see screenshot below

![image](https://cloud.githubusercontent.com/assets/1689007/16558727/dd9b4260-41e7-11e6-888e-9e92b93d9770.png)
