### ISSUE TITLE
duplicate class in instantsearch.phtml

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#482]
On lines 156 of the instantsearch.phtml file, there's a div with a class of "result-sub-content." And nested underneath that on line 161, there's another div with the same class. 

Can we drop the class on the nested div (line 161)?

**Comment by JanPetr** [comment]
Hello @sam327,
it always depends on your theme and on your CSS. If it does not make sense for you to have the class there you can drop it for sure. But be careful to not break your instantsearch design.

**Comment by sam327** [comment]
Okay, wanted to make sure it wasn't important. I've dropped the nested class when I've upgraded a couple times now. 

Having the nest class actually makes it a royal pain the ass to add CSS to that class. You end up setting something like this:

    .result-content .result-sub-content { height:120px; }
    .result-content .result-sub-content .ratings .result-sub-content { height:auto; }

Because you have to set it for the parent, and then set it again for the child version.

If you just set result-sub-content to a fixed height, the second box sticks out of the parent.

So, if that class isn't important for anything (other than personalization), I'd recommend removing/renaming the nested class at line 161.

**Comment by JanPetr** [comment]
Classes were renames, it will be part of the next release
