### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#485]
Is there any reason why your folder structure doesn't align with Magento?

**Comment by JanPetr** [comment]
Hello @davids101,
there is no specific reason for that. Why? Would it make anything easier for you?

**Comment by davids101** [comment]
Just seems odd that it doesn't use the same folder structure. If I were to download the extension and upload it, it wouldn't work

**Comment by JanPetr** [comment]
Do you experience the "upload" issue often? Why wouldn't you use Modman or Magento Connect?

**Comment by davids101** [comment]
I generally do use Magento Connect, but extension stopped working after going from 1.5.5 to 1.6, so now I'm trying to diagnose the problem. Having an aligned folder structure would help with sorting through the files

**Comment by JanPetr** [comment]
OK, makes sense. I will keep the issue open as we might want to re-structure.

What you mean by "stopped working"? Any error? If you won't figure that out, feel free to open an issue.

**Comment by JanPetr** [comment]
Structure updated at #517, will be part of the next major release
