### ISSUE TITLE
Custom Magento Theme Documentation

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#486]
It would be great to see some general guidelines on what's required to have Algolia work with a custom theme. We're using the most popular Magento theme "Ultimo" and after upgrading to 1.6, it no longer works.

I'd like to add that if I set RWD back as the theme, it works.

**Comment by JanPetr** [comment]
Hello @davids101, I added this paragraph to docs - https://community.algolia.com/magento/documentation/#custom-theme
We are working on much more detailed documentation but it sould solve your problem for now.
