### ISSUE TITLE
No Magento products being indexed

### ISSUE THREAD

**Issue by literalltd** [algolia/algoliasearch-magento#490]
Hi

When I index my magento store, the pages and categories tables are indexed but no products ever index

No errors in any of the logs including the algolia logs, indexing is happening but just not for products?

Any ideas?

Cheers

**Comment by JanPetr** [comment]
Hey @literalltd,
do you have enabled indexing queue? If you do, products are first indexed into tmp index and then moved to production. You can find a tmp index in Algolia dashboard.
And are products which are supposed to be indexed enabled, visibile and on stock?

**Comment by literalltd** [comment]
Thanks @JanPetr, 

Yes all of those are enabled but I do not see any temp indexes. I have three store views and I get indexes created with those names just no items added? Other indexes do populate like catagories and pages

Thanks

Damian

**Comment by JanPetr** [comment]
When you hit "Reindex" button in Magento, can you check that indexing jobs are correctly added to algoliasearch_queue DB table? And then, when the queue is processed, that they are correctly deleted? Or do the jobs stay in queue table?

**Comment by literalltd** [comment]
Hi, looks like the table is still full?

|    226 | 11834 | algoliasearch/observer | moveProductsTmpIndex           | {"store_id":"2"}                                                                   |           3 |       0 |           |         1 |
|    227 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"3","product_ids":[],"page_size":"100","page":1,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    228 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"3","product_ids":[],"page_size":"100","page":2,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    229 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"3","product_ids":[],"page_size":"100","page":3,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    230 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"3","product_ids":[],"page_size":"100","page":4,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    231 |   673 | algoliasearch/observer | moveProductsTmpIndex           | {"store_id":"3"}                                                                   |           3 |       0 |           |         1 |
|    232 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"4","product_ids":[],"page_size":"100","page":1,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    233 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"4","product_ids":[],"page_size":"100","page":2,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    234 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"4","product_ids":[],"page_size":"100","page":3,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    235 |   673 | algoliasearch/observer | moveProductsTmpIndex           | {"store_id":"4"}                                                                   |           3 |       0 |           |         1 |
|    236 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"1","product_ids":[],"page_size":"100","page":1,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    237 |   673 | algoliasearch/observer | moveProductsTmpIndex           | {"store_id":"1"}                                                                   |           3 |       0 |           |         1 |
|    238 |   673 | algoliasearch/observer | rebuildProductIndex            | {"store_id":"2","product_ids":[],"page_size":"100","page":1,"use_tmp_index":true}  |           3 |       0 |           |       100 |
|    239 |   673 | algoliasearch/observer | moveProductsTmpIndex           | {"store_id":"2"}                                                                   |           3 |       0 |           |         1 |
+--------+-------+------------------------+--------------------------------+------------------------------------------------------------------------------------+-------------+---------+-----------+-----------+
239 rows in set (0.01 sec)

**Comment by JanPetr** [comment]
And `pid` column is filled, so that means the jobs were supposed to be processed but it end up with error. Can you investigate logs in folder `var/logs` in Magento?

**Comment by JanPetr** [comment]
Any updates on the issue @literalltd?

**Comment by JanPetr** [comment]
@literalltd, did you manage to reindex your data?

**Comment by literalltd** [comment]
Hi Jan
Yes sorry meant to let you know, all good now and loving it.
Cheers
Damian

Damian Rosewarne
Director

Literal Ltd
DDI:       +64 (0)4 974 5829 Mobile:  +64 (0)212 700 957NZ Toll Free:     
0800 101 558 Web:           http://literal.co.nz

Po Box 21654, Wellington 6164, New Zealand

---- Original Message ----

**Comment by JanPetr** [comment]
Super cool to hear that! Enjoy!
