### ISSUE TITLE
updating to 1.6 from 1.5.5

### ISSUE THREAD

**Issue by raqqun** [algolia/algoliasearch-magento#492]
We have followed the documentation for algolia 1.6 for magento, but since the update, the search bar autocompletion and instant search results are gone.

Do you have any idea why ? everything went well before and we didn't change anything to our layout. 

Our magento theme is based on rwd. 

When i'm changing the current theme to rwd everything works well :/

Maybe we did something bad with the configuration ? 

any help is appreciated

**Comment by JanPetr** [comment]
Hello @raqqun,
the extension tries to override `top.search` block. If the block is not present, it won't include templates.
In that case you need to change DOM selector of search input in Algolia configuration in Magento backend to match your search input. Can you try to do that?

**Comment by raqqun** [comment]
thanx @JanPetr that worked.

**Comment by JanPetr** [comment]
Great @raqqun!
