### ISSUE TITLE
cannot find infinite scroll feature

### ISSUE THREAD

**Issue by talha-malik** [algolia/algoliasearch-magento#498]
Hi,
I am unable to find infinite scroll feature in extension. Is it missing? I am very new to magento so can any one guide me how can I add this feature if not already in it.

**Comment by JanPetr** [comment]
Hey @talha-malik, I noticed you've already found #468 👍 
But it's good time to add it to docs. Will work on it 💯

**Comment by talha-malik** [comment]
Hi,
I am facing very small issue and am urgent need of guidance here. I managed to successfully run infinite scroll but I am unable to append result set on appropriate div. [Here](http://beautyrun.com/fragrance.html) is the website I am working on. You will see on scrolling call to algolia is being sent and getting response successfully. Let me share my code on topsearch.phtml please see it and guide what Id should i give to append result set on the page.

    <script type="text/template" id="instant_wrapper_template">
    {{#findAutocomplete}}
        <div id="algolia-autocomplete-container"></div>
    {{/findAutocomplete}}
    <div id="algolia_instant_selector" class="<?php echo count($config->getFacets()) > 0 ? ' with-facets' : '' ?>">

        <?php if ($title || $imgHtml || $description || $content): ?>
            <div class="row">
                <div class="col-md-12">
                    <div id="algolia-static-content">
                        <div class="page-title category-title">
                            <h1><?php echo $title; ?></h1>
                        </div>
                        <div>
                            <?php echo $imgHtml; ?>
                        </div>
                        <div class="category-description std">
                            <?php echo $description; ?>
                        </div>
                        <?php echo $content; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="">
            <div class="left-side-custome" id="algolia-left-container">
                <div id="refine-toggle" class="visible-xs visible-sm">+ <?php echo $this->__('Refine'); ?></div>
                <div class="hidden-xs hidden-sm" id="instant-search-facets-container">
                    <div id="see-all"><a href="<?php echo Mage::getBaseUrl(); ?>/catalogsearch/result/?q=__empty__">ON SALE</a></div>
                    <div id="current-refinements"></div>
                </div>
				
            </div>
 
            <div class="col-md-9 right-custome-width" id="catalog-listing" style="/* position: relative; height: 49px; */"> 
                
                <div class="">
                    <div>
						<div class="hits">
						<?php
							/* work done for infinite scrolling*
							{{#pageNo}}
							  <div class="page-no">
								Page {{pageNo}}
							  </div>
							{{/pageNo}}
							{{#hits}}
							  <div class="hit">
								<a href="{{url}}">
								  <img src="{{image}}" alt="{{name}}">
								  <p class="name">
									{{#_snippetResult}}
									  {{{_snippetResult.name.value}}}
									{{/_snippetResult}}
									{{^_snippetResult}}
									  {{name}}
									{{/_snippetResult}}
								  </p>
								</a>
							  </div>
							{{/hits}}*/
							?>							
                            <div class="infos">
                                <div class="pull-left" id="algolia-stats"></div>
                                <div class="pull-right">
                                    <div class="sort-by-label pull-left">
                                        <?php echo $this->__('SORT BY'); ?>
                                    </div>
                                    <div class="pull-left" id="algolia-sorts"></div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div id="instant-search-results-container"></div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>

                <div class="text-center">
                    <div id="instant-search-pagination-container"></div>
                </div>
            </div>
        </div>

    </div>
	<style type="text/css">
	.ais-hits:not(body) {
		display: block;
		/* margin: 0 0 36px 3.5%; */
		width: auto;
		z-index: 1;
	}
	.button-group{display:none}
	</style>
    </script>
    <script type="text/html" id="no-results-template">
     <div id="no-results-message">
    <p>We didn&rsquo;t find any results for the search <em>&ldquo;{{query}}&rdquo;</em></p>
    <a href="#" class="clear-all">Clear all</a>
     </div>
    </script>

And here is instant search script

    search.addWidget( infiniteScrollWidget({
	container: '#instant-search-results-container',
	 templates: {
		items: document.querySelector('#instant_wrapper_template').innerHTML,
	        empty: document.querySelector('#no-results-template').innerHTML
	}
	})
	);

Thanks in advance.

**Comment by JanPetr** [comment]
Hello @talha-malik, `infiniteScroll` widget replaces `hits` widget. Try to remove `hits` widget from instantsearch.js file.

**Comment by talha-malik** [comment]
@JanPetr thanks for your reply. Above didn't work. Here is what I have been able to identify yet by debugging code. First I found the template where products are being appended. Same template is being sent when initialRender is called and object being passed is the response from aloglia search call. When initial render is called (first algolia call on page load) it flows like this
instant_scroll.js (Mustache.render) -> mustache.js ->instant_scroll.js->InstantSearch.js (located at webpack...//..//instantsearch.js/src/lib/) ->bindCall.js(located at webpack...//..//instantsearch.js/~/lodash/internal...)->createBaseEach.js ->createForEach.js->InstantSearch.js->functionPrototype.bind.js->event.js->algoliasearch.helper.js->createPartialWraper.js->
AlgoliaSearch.js->jquery.js

Thats the initial flow from InitialRender. Now when appendSearchResults is called on scrolling same template and same response from algolia is passed but the flow is different. Resultantly I get empty template with data not being appended to it. flows is like following
infinite_scroll.js(appendSearchResults)->mustache.js->infinite_scroll.js->function.prototype.bind.js->algoliasearch.helper.js->algoliaSearch.js->intenso.js( js along with theme) and thats it.

You can see how desperate I am to get this thing working. Link to my site is [here]( http://beautyrun.com/skincare.html) I still have debuggers in js files can you please take a look where its falling. Am I doing wrong something or there is some fix required for extention. 

Thanks

**Comment by JanPetr** [comment]
@talha-malik We sent the respond to Rainier via e-mail.

**Comment by talha-malik** [comment]
I am sorry but what does that mean?

**Comment by JanPetr** [comment]
@talha-malik We got e-mail from your colleague, Rainier Storm, is it correct? We responded directly via e-mail to him. I suppose he will share the respond with you?

**Comment by talha-malik** [comment]
Yes, received your response from him and it solved the issue. Thanks a lot for your time and help.
