### ISSUE TITLE
Non Linear Slider

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#499]
We have many products that have attributes with large values. The current slider integration that Algolia has does not allow the user to filter effectively. When there are a few high priced items, it skews the filtering for the more popular lower priced items. Example:

Lowest Price is $15
Average product price is $75
A few products cost $5,000

The slider range will be between $15 and $5,000, with the midpoint being $2,500. The user will not be able to filter between $15 and $100 easily, since the slider steps are in much higher increments now.

Can you please create a non-linear slider? Take a look at this example. https://codepen.io/martinAnsty/pen/BCotE

**Comment by JanPetr** [comment]
Hello @davids101,
good point, thanks! The extension depends on instantsearch.js library and there we are already working on adding a support for non-linear sliders, see https://github.com/algolia/instantsearch.js/issues/1069. Once implemented, we will integrate it into the extension ;)

**Comment by davids101** [comment]
Any word on this feature?

**Comment by JanPetr** [comment]
Hey @davids101,
it should be part of instantsearch.js V2. Sorry, but we do not have any ETA now :(

**Comment by JanPetr** [comment]
When it'll be implemented to IS, it will be usable via new custom JS hooks to modify IS behavior (#822).
