### ISSUE TITLE
[docs] Explaining settings merge strategy

### ISSUE THREAD

**Issue by rayrutjes** [algolia/algoliasearch-magento#514]
It would be nice to have some details about the way we sync settings between Magento and Algolia, and maybe address best practices if any.

WDYT?

**Comment by JanPetr** [comment]
Good idea, thanks for pointing it put 👍

**Comment by JanPetr** [comment]
Right now we [have listed a settings](https://community.algolia.com/magento/doc/m1/indexing/#index-settings) which are managed and controlled by the extension.
With explanation that all other settings can be controlled in Algolia dashbord.
