### ISSUE TITLE
Hit templates use Mage::getBaseUrl instead of getting the media url.

### ISSUE THREAD

**Issue by Inwerpsel** [algolia/algoliasearch-magento#515]
You can't use a CDN for images with this extension because the url isn't the Magento media url configuration value.

**Comment by JanPetr** [comment]
Good point, we will investigate and let's see what we can do. But feel free to send a pull request 💯

**Comment by JanPetr** [comment]
Hey @Inwerpsel, can you take a look at #518 and share feedback? Extension will index the whole URL instead of just path behind the domain. So when you use CDN, CDNs URL will be indexed. Thanks!

**Comment by JanPetr** [comment]
Fixed at #518, will be part of the next release
