### ISSUE TITLE
Bundle products issue with special price and new from/to dates

### ISSUE THREAD

**Issue by michaelzangerle** [algolia/algoliasearch-magento#526]
I have a bundle product with no special price and no new from / to dates configured. In this bundle product are two other products A and B. Product A has a special price configured and product B the new from / to dates. When I take a look at the index for the bundle product it has the special price value from product A and the new from / to dates from product B.

I expected that the bundle has none of the values of product A and B. Can you confirm this issue? 

I am using version 1.5.5.

**Comment by JanPetr** [comment]
Hello @michaelzangerle,
yes I can reproduce even in the latest version. The produc's price is composed like 
`regular price from one product + special from the second one`.
And the indexed product has news dates from the first product.

Why is this an issue? Magento does the same thing. Do I miss something?

**Comment by michaelzangerle** [comment]
Hi @JanPetr 

I can't confirm that the price is composed of anything else than the price configured on the bundle product. This would be fine for my usecase. But when I take a look at our index for the bundle product it looks like this:

```JSON
...
  "price": {
    "CHF": {
      "default": 84.9,
      "default_formated": "84,90 CHF",
      "special_from_date": false,
      "special_to_date": false
    }
  },
  "short_description": "...",
  "special_to_date": [
    "2015-12-31 00:00:00"
  ],
  "special_from_date": [
    "2015-11-29 00:00:00"
  ],
  "special_price": [
    "9.9000"
  ],
  "news_from_date": [
    "2016-07-05 00:00:00"
  ],
  "news_to_date": [
    "2016-09-06 00:00:00"
  ],
  "type_id": "bundle",
  "objectID": "7447"
...
```

It seems like there is a special price and the news dates configured when in fact they are configured on a product within the bundle. I expected the index to have only the values set on the bundle itself like e.g. the price. The price of the bundle is configured as 84.90 and no matter what price or special price I configure on a product within the bundle it stays the same on the bundle product. That's the behaviour I expected also from the news dates and the special price on the bundle product itself. I think that in this case the price of a the bundled product and the bundle should be completely separated from each other as I may want to sell the product within the bundle with a special price but not the bundle itself. 

I am not sure if there is a usecase where it should behave the way it does now but as I have some logic depending on the special price and news dates values it's kind of a problem :-)

I hope it's clear now what I mean and what I expected it to do / to behave. Do you have any ideas / suggestions?

**Comment by JanPetr** [comment]
Hey @michaelzangerle,
now I see what's the issue about.
So in the end you just don't want the attributes `special_price` and news dates to be present on bundle product if they are not set to "master" product, right?

**Comment by michaelzangerle** [comment]
Yes that's what I meant.

**Comment by JanPetr** [comment]
Great, now as we are on the same page I'll leave the issue open and we will target it in upcoming version. Thanks!

**Comment by JanPetr** [comment]
Fixed, will be part of the next release
