### ISSUE TITLE
Better Facet Control

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#528]
Facets can get out of control when you have numerous product types with unique attributes. I think we need a way of grouping certain facets. Build in a feature where you can great groupings with a header, such as:

Tire Filter Options (heading)
Tire Tread (facet)
Tire Speed Rating (facet)
Tire Speed Range {facet}

Wheel Filter Options (heading)
Wheel Finish (facet)
Wheel Tire Size (facet)
Wheel Lugs (facet)

It could work as an accordion or have a button to expand/minimize

**Comment by damcou** [comment]
Added to the features list in our roadmap.
