### ISSUE TITLE
selective reindex

### ISSUE THREAD

**Issue by ZayLong** [algolia/algoliasearch-magento#53]
Is it possible to reindex just a single algolia index from magento?

Whenever I reindex from adding a product; it reindexs ALL of the algolia indexes which really wastes operations. 

is there a solution already available for this?

**Comment by ZayLong** [comment]
I had another question about this. In the READ ME it says to do a reindexing of the Catalogsearch index, and the algolia index INITIALLY.

I believe my company's site has a cronjob running that reindexes catalogsearch index every 4 hours for some reason.

Is this a bad practice for Algolia?

**Comment by redox** [comment]
Hey @ZayLong, no it's not a bad practice; you can update your index as often as you want. Every 4 hour, 1 hour, 1 minute or even in realtime :)
