### ISSUE TITLE
Add attribute to product with category levels without path

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#532]
Right now the `categories` attribute looks like this:
```json
categories: {
    "level0": ["Men"], 
    "level1": ["Men /// Suits", "Men /// Accessories"]
}
```

The idea is to add onther attribute, lets call it `main_categories`, which would contain categories like:
```json
main_categories: {
    "level0": ["Men"], 
    "level1": ["Suits", "Accessories"]
}
```
It provides more flexibility with relevancy and allow to provide more relevant results.

**Comment by maxiloc** [comment]
same here, it will probably break the hierarchical widget

**Comment by JanPetr** [comment]
It'd be added as completely new attribute (`main_categories`), so hierarchical (oh, that's hard to spell 😄) widget should be fine.

**Comment by JanPetr** [comment]
Will be part of the next release
