### ISSUE TITLE
Add possibility to index only categories where product is

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#533]
Right now when there is category path: "Men /// Blazers" and product is added only to Blazers category the extension indexes:
```json
categories: {
    "level0": ["Men"], 
    "level1": ["Men /// Blazers"]
}
```
It ends up with issue that products which are supposed to be only in Blazers category are fetched even in "Men" category.

It'd be great to add a configuration option to index only categories into which the product actually belong and not the whole category path.

**Comment by maxiloc** [comment]
We need to be careful with this, it might break the hierarchical widget, but yes makes sense

**Comment by JanPetr** [comment]
Yes, that needs to be tested well. If the product is only in "Blazers" category I think that this
should work:
```json
categories: {
    "level0": [], 
    "level1": ["Men /// Blazers"]
}
```

**Comment by JanPetr** [comment]
will be part of the next release
