### ISSUE TITLE
Add option to refine by attribute combinations

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#535]
Let's say there is a configurable product composed of two (simple) sub-products.
One has attributes Size: 40 and Length: L
The other one has Size: 50 and Length: M

Now the extension indexes it like:

``` json
size: [40, 50],
length: ["L", "M"]
```

That means that when user is filtering Size: 50, Length: M, the product is retrieved even though there is no relevant product to buy.

Let's make a configurable option when user can select attributes which correlates together in config, the extension index them as combinations and then use `searchFunction` of [instantsearch.js](https://github.com/algolia/instantsearch.js) to refine those combinations.

So in the end the record would have 3 attributes instead of just 2:

``` json
size: [40, 50],
length: ["L", "M"], 
size_length: ["40:L", "50:M"]
```

and `searchFunction` could look like this:

``` js
searchFunction: function (helper) {
    if(FIXME-if-user-is-refining-both-size-and-length) {
        this.helper.addFacetRefinement('size_length', FIXME-size-value+':'+FIXME-length-value);
    }

    helper.search();
}
```

**Comment by maxiloc** [comment]
yes makes sense, will need some good documentation 😄, in order to be clear what it does

**Comment by damcou** [comment]
Added to the features list in our roadmap.
