### ISSUE TITLE
Facet collapse

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#537]
In [instantsearch.js](https://community.algolia.com/instantsearch.js/documentation/#filters) there is an `collapsible` option. To use this I've to add this variable to the `refinementList()` functions (for conjunctive, disjunctive and slider) in the `internals/commonjs.phtml` and after that I've to add some lines of CSS to add some arrows and make it visible. Any plans to add this by default? Maybe configurable in the backend?

**Comment by JanPetr** [comment]
Hey @royduin,
thans for the catch. Definitelly something we might want to improve in upcoming versions.

**Comment by royduin** [comment]
A quick note after implementing this myself: the clear all filters function isn't working anymore. Checkboxes stay checked after clicking on reset. Any thoughts on this?

**Comment by JanPetr** [comment]
Yes, there is an issue with instantsearch.js library. Version 1.7.0 will be released with the new version instantsearch.js.
But if you want to update only library files, feel free. Here is the PR: https://github.com/algolia/algoliasearch-magento/pull/510

**Comment by royduin** [comment]
Thanks! I'll update the library files for now and I'm looking forward to the next final release!

**Comment by JanPetr** [comment]
Cool!
