### ISSUE TITLE
Choose facets by category

### ISSUE THREAD

**Issue by VincentMarmiesse** [algolia/algoliasearch-magento#539]
Hello,

Is it possible to chose which facets are displayed by category?
I know it can be configured in the Products section in admin, but is it possible by category?

**Comment by maxiloc** [comment]
@VincentMarmiesse It's not possible to do that out of the box. But I think this is definitely doable by tweaking the extension.

**Comment by davids101** [comment]
Would like to see this built in. It's extremely necessary if Algolia is going to try and become a replacement for category page filters. If Algolia stuck to search only, it wouldn't be an issue. I think Algolia should create a tab within the category that lets you edit options like this

**Comment by julienbourdeau** [comment]
Hi @VincentMarmiesse and @davids101,

I started looking into it. Without the extension, I don't think Magento has this feature natively. I played around with attributes, attributes sets and category configuration but I couldn't change the facets displayed on a category page. Did I miss something?

**Comment by VincentMarmiesse** [comment]
Hi @julienbourdeau, 

Indeed, it's not a native feature of Magento.

**Comment by damcou** [comment]
Added to the features list in our roadmap.
