### ISSUE TITLE
prevent searching by bots

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#541]
HI. I'm over quota right know and I see two reasons:

1. bots were searching for some things - like for product 4680 times - when my store has low traffic right know
How to prevent such actions to prevent algolia giving results to bots?

2. I changed from dev to production and several times - reindexed store manually - and later added cron rule. Question - is each Magento reindexing eating quota? or the reindex in magento eats quota only when new data is pushed to algolia? what is the algolia behavior for generic Magento reindexing - manual or by cron? > how it affect Algolia quota?

**Comment by JanPetr** [comment]
Hi @tomekjordan, which quota do you mean? Operations or records? For the answers I'll assume operations quota.

> bots were searching for some things

Do you have option "Make SEO request" enabled? If so, each time bot crawls search result pages it makes a request to Algolia which is considered as operation and then counted into your operations count.

> is each Magento reindexing eating quota?

Yes, everytime you are reindexing, all products are updated in Algolia indices even if there was no change with product. So every update / delete / addition is considered as one operation, that being said every reindexation produces as many operation as many products you have.
If you don't have indexing queue enabled, everytime you're reindexing even disabled / not visible products are processed and delete operations are send to Algolia.
If you have indexing queue enabled, only available products are processed so you will have lower operation count on reindexing.
Some more information are in [documentation](https://community.algolia.com/magento/documentation/#full-products-reindex).
