### ISSUE TITLE
Sorting options configurable per facet

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#542]
Currently all facet options are sorted by count. It's possible to change this to name in the code (`sortBy: ['name:asc']`) but then I've got problems with numbers and size letters, for example:

Size letter order
```
L
M
S
XL
XS
```

Size number order
```
10
11
7
8
9
```

Any thoughts on this? With SQL this can be fixed with: `ORDER BY name,ABS(name) ASC`. Maybe it's an idea to have a option in the facet configuration to configure the sorting like default possible in Magento?

**Comment by JanPetr** [comment]
Hey @royduin,
instead of `['name:asc']` you can pass your own sort function.
Example:
```js
sortBy: function(firstValue, secondValue) {
    if(firstValue < secondValue) {
        return -1;
    }

    return 1;
}
```

**Comment by royduin** [comment]
Thanks for the quick reply! But any thought on how I can get those size letters ordered? Name and size numbers is not a problem with a custom sort function, but size letters will be a little complicated I think. That's why it's possible to order those manually with default Magento.

**Comment by JanPetr** [comment]
From the top of my head, you can hardcode an sorted array of those letters into the custom function and then compare it's indices for example.

**Comment by royduin** [comment]
Thanks again! I'm going to experiment with it and share my results.
