### ISSUE TITLE
Price rounding issues in the currentRefinedValues widget

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#546]
I'm using the facet slider type for the prices which is working great but when I've selected a range the values are not rounded. This is also happening on the demo shop at: https://magento.algolia.com

![prices](https://cloud.githubusercontent.com/assets/1703233/17730099/7d62caba-6467-11e6-972d-2616ffeb46cc.png)

I've already updated `instantsearch.js`, see: https://github.com/algolia/algoliasearch-magento/issues/537#issuecomment-238875520

Any thoughts?

**Comment by JanPetr** [comment]
Hello @royduin,
thank you for reporting. We found a bug in instatsearch.js library.
It'll be fixed soon, I'll keep you posted.

**Comment by royduin** [comment]
Thank you, I'm looking forward to the fix

**Comment by JanPetr** [comment]
PR #549 created, you can grab the files directly from it and replace in your instance. Otherwise it will be part of 1.7.0 release.

**Comment by royduin** [comment]
Thank you! Don't forget to update the Algolia demo site ;)

**Comment by royduin** [comment]
I've still got this problem after updating the bundle. Create a new issue or can you reopen this one @JanPetr?

**Comment by JanPetr** [comment]
Tracking here: https://github.com/algolia/instantsearch.js/issues/1254

**Comment by vvo** [comment]
IS 1.8.8 released fixing this, thanks, new magento release coming

**Comment by royduin** [comment]
Nice! Can I download the new bundle somewhere?
