### ISSUE TITLE
Categories that appear next to suggested search terms

### ISSUE THREAD

**Issue by dovid** [algolia/algoliasearch-magento#547]
Something I am seeing that I'm not 100% sure how to deal with is when the suggested search terms show the categories next to it those categories are not always as "accurate" as we would like. The best example I can give is with "milk". The suggestion shows milk in the groceries category, but it would make a lot more sense to show it in the dairy category (see screenshot). Or at the very least show it in the dairy category first and only then it can maybe also show it in the groceries category. How can we deal with this? What is responsible for determining which category to show there?

As far as I know we did not add anything special to the Magento extension, so it would appear that the extension adds this somehow. We want to show the suggestions there, but if it's going to show the category too then it needs to be more accurate.

Thanks for your help!

![milk in groceries](https://cloud.githubusercontent.com/assets/1697677/17733044/b43eec82-6442-11e6-879e-bce26312d56e.png)

**Comment by JanPetr** [comment]
Hello @dovid,
let me exaplain how it works. While searching for suggestions the extension uses [popularIn feature](https://github.com/algolia/autocomplete.js#popularin-aka-xxxxx-in-yyyyy) of [autocomplete.js](https://github.com/algolia/autocomplete.js) library.
That means that when searching for suggestions the query is also "forwarded" to products' index and the main category (level0) with the highest number of products is fetched and displayed before other suggestions. Categories in lower levels (level1 and lower) are not considered at all right now.

In your case when you search for milk, the same query is sent to products index and as "Groceries" category is the one with highest number of results is returned and displayed.

Unfortunatelly this is not something what can be configured via UI right now. But if you want to chage it's behaviour your can do so [here in datasource of suggestions](https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/internals/commonjs.phtml#L362-L393). You can remove the categories feature completly or just modify it to fit your requirements.
