### ISSUE TITLE
Initial Indexting / Fontend Search fails

### ISSUE THREAD

**Issue by paul-siteway** [algolia/algoliasearch-magento#55]
**What ive done:**
- ive created a new index in angolia dashboard
- ive created API credentials for the index with allowed operations: 
`````
search, browse, addObject, deleteObject, listIndexes, deleteIndex, settings, editSettings, analytics	
````
- ive set the credentials in Magento Algolia configuration

**What i get:**

- Initial Indexing of the "Algolia Search Index" fails with the Error
![image](https://cloud.githubusercontent.com/assets/3603487/5839558/7c2aa2d6-a18f-11e4-8ecf-e5a24056f50b.png)

- When trying a frontend search i get the following error
`````
"Error: Index default does not exist
main.min.js:5 Object {message: "Index default does not exist"}"
`````

**Comment by redox** [comment]
Hey @paul-siteway,

could you reach me at sylvain@algolia.com with your the email you used to create the account so I can dig into the logs?
