### ISSUE TITLE
After changing a category name, the category is empty and stays empty

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#558]
When I change a category name in Magento I would expect a trigger to Algolia to run some indexes. But after changing a category name nothing happens and I've to trigger a complete reindex of categories and products. Not really efficient I think. Any thoughts on this?

**Comment by JanPetr** [comment]
Hey @royduin,
on category's name change the category should be reindexed with correct name to categories index.
However within products we store category names and products are not reindexed automatically when you change the name so it may cause that the category seems to be empty. The extension does not do that as usually the category change does not require the products' reindexation and it'd produce large amount of "useless" operations.

There is option that you can reindex affected products when you add / remove them from category on the category page:
<img width="641" alt="screenshot 2016-08-23 13 32 34" src="https://cloud.githubusercontent.com/assets/1058144/17890400/15234672-6936-11e6-99a5-8d2ef2672d99.png">

Maybe it'd be nice to have similar option and reindex all category's products on change of the category's name. Would that work for you?

**Comment by royduin** [comment]
That would be nice! Do you've time for this? It's not a high priority issue for me but it would be nice if it's fixed in the future.

**Comment by JanPetr** [comment]
I will keep the issue open and definitelly address it in future. But always feel free to send a PR, I will more than happy to merge 🙌

**Comment by JanPetr** [comment]
The issue will be sorted out with #570. Closing now as duplicate.
