### ISSUE TITLE
Add ability to use slider in decimal increments

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#561]
We have a few values that range from 0 to 2 with about 10 decimal values between, such as 1.5 and 1.7. We've modified the code to work, but I think this should be available natively

**Comment by maxiloc** [comment]
Do you mean for the rangeSlider widget https://community.algolia.com/instantsearch.js/documentation/#rangeslider ?

**Comment by davids101** [comment]
yes. Would be nice to be able to define support for decimals with specific sliders.

**Comment by JanPetr** [comment]
Will be easily doable with new JS hooks to modify the IS page. (#822)
In the end it won't be implemented to the UI.
