### ISSUE TITLE
Hide "No" Facet value is attribute is not set for product

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#562]
We have products that have colors defined and other products that don't have a color defined due to the nature of the product. Since these products do not have a color defined, if you look at the search results, you will see a "No" value. Is it possible to not output this "No" checkbox option?

If we had actually assigned the value "No" then it would make sense to output it.

**Comment by maxiloc** [comment]
I don't see a way to do that at search time, the best would be to remove "No" before it's send to algolia.
You can modify the final record there https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L908

**Comment by JanPetr** [comment]
Hello @davids101, actually this option was implemented in https://github.com/algolia/algoliasearch-magento/pull/554 and is available in `develop` branch. Will be released soon.

**Comment by davids101** [comment]
There is a difference between setting up an attribute as a Yes / No value and having an attribute with no value defined that shows up as "No". Did you make you to target this accurately?
