### ISSUE TITLE
Add input field ranges as a facet type

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#563]
We like sliders, but in some cases it's better if a user can enter the specific number range they are looking for. Is it possible to add this as a Facet Type?

**Comment by maxiloc** [comment]
The main issue is that it's difficult to have this widget configurable via the magento admin.
The best way to handle that is to add the widget manually here https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/instantsearch.phtml#L257

You can achieve that by using the price range widget https://community.algolia.com/instantsearch.js/documentation/#priceranges and setting the currency to ""
