### ISSUE TITLE
Do not show product quantity next to Facets options

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#564]
Is there a way to remove the outputting product quantities next to facet options?

**Comment by maxiloc** [comment]
Hi @davids101, yes you can do that by modifying or overriding the facet template.
Remove this line https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/instantsearch/facet.phtml#L6 should do the trick

**Comment by davids101** [comment]
I noticed this path doesn't work. Can you relink?

**Comment by JanPetr** [comment]
Sure - https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/instantsearch/refinementsItem.phtml#L6-L8
