### ISSUE TITLE
docs: Placeholder in the search input is not centered

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-magento#565]
I have the following display when doing a search: 
![image](https://cloud.githubusercontent.com/assets/283419/18166652/9ad58e98-704c-11e6-82fe-b1bb856a85d1.png)

I'm using Chromium Version 48.0.2564.82 Ubuntu 15.04 (64-bit)

**Comment by JanPetr** [comment]
Will be handled in https://github.com/algolia/magento/issues/13
