### ISSUE TITLE
What are the limitations of the free version of this repository?

### ISSUE THREAD

**Issue by JToward** [algolia/algoliasearch-magento#567]
What are the limitations of the free version of this repository?

**Comment by rayrutjes** [comment]
Hi @JToward,

In terms of features, there are no limitations.
To be able to configure the extension you will need to create yourself an Algolia account.

Then, everything is detailed on our pricing page ;)
https://www.algolia.com/pricing

Basically, if you stay on hacker plan, you are allowed 10k records and 100k operations a month.

To better understand the records part regarding this extension, please take a look here: https://community.algolia.com/magento/faq/#how-many-records-does-the-magento-extension-create

Let me know if you need further information!
