### ISSUE TITLE
Ranking by specific attribute

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#569]
Hello,

In my product index, I create new attributes position_[id_category], they have the position of product in specific category.
On magento i need get my products sort by position on current category. I find the param 'ranking' on your DOCUMENTATION but i don't know how add this param on my request. (And maybe you know a better solution for get product in specific order).

Thank you for your help.

**Comment by JanPetr** [comment]
Hello @bastienlm,
you need to add this attribute as sort attribute:
<img width="965" alt="screenshot 2016-09-07 16 34 57" src="https://cloud.githubusercontent.com/assets/1058144/18315954/13352bc0-7519-11e6-9fae-874be86d3376.png">

But beware that each attribute in sorts will duplicate your index and the number of records will grow.
And I guess you will also have to update JS code to use different sort index on different category.

**Comment by bastienlm** [comment]
With more than 100 categories, this is complicated
There is no possibility for get product of 1 index sort by specific attribute ?

**Comment by JanPetr** [comment]
Unfortunatelly not @bastienlm,
the Algolia is designed for giving results sorted by relevancy and not specific attributes. And replica indices are the only way how to sort records according specific attribute. You can find more information in our documentation: https://www.algolia.com/doc/guides/relevance/sorting#introduction and https://www.algolia.com/doc/guides/search/instant-search#multiple-sort-criteria
