### ISSUE TITLE
Replace the "http://" protocol by "//" before displaying thumbnails to handle HTTPS

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#57]

**Comment by colinmollenhour** [comment]
It might be better to just index two urls, one for secure and one for unsecure to allow more flexibility in configurations.

**Comment by redox** [comment]
Yes that could be an option as well but I'm not sure I understand the flexibility. Do you see cases where you would force a different protocol than web page protocol?

**Comment by colinmollenhour** [comment]
Not a different protocol but sometimes a different domain. So one url for (location.protocol == 'http:') and one for (location.protocol == (https:').

**Comment by paul-siteway** [comment]
Is it possible to just strip the protocol and return: 

>````image_url: "//www.das-weinkonzept.de/media/catalog/product/cache/1/image/265x/9df78eab33525d08d6e5fb8d27136e95/1/0/1080012011.png"````

instead of: 
>````image_url: "http://www.das-weinkonzept.de/media/catalog/product/cache/1/image/265x/9df78eab33525d08d6e5fb8d27136e95/1/0/1080012011.png"````

This should load the content from http or https based on the current protocol of the page.

**Comment by paul-siteway** [comment]
>It’s not exactly light reading, but section 4.2 of RFC 3986 provides for fully qualified URLs that omit protocol (the HTTP or HTTPS) altogether. When a URL’s protocol is omitted, the browser uses the underlying document’s protocol instead.

>Put simply, these “protocol-less” URLs allow a reference like this to work in every browser you’ll try it in:

>//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js

>It looks strange at first, but this “protocol-less” URL is the best way to reference third party content that’s available via both HTTP and HTTPS. [Source](http://stackoverflow.com/questions/4978235/absolute-urls-omitting-the-protocol-scheme-in-order-to-preserve-the-one-of-the)

Also: http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by colinmollenhour** [comment]
Definitely the simplest, but Magento does support different base urls for http and https in case one is using a CDN for example. That is, web/unsecure/base_media_url and web/secure/base_media_url. I actually think the best (and still extremely simple) solution would be to not store the base_media_url at all and add it in Javascript when rendering. This way only one url is stored rather than two, but full flexibility is maintained to support common CDN configurations.

**Comment by paul-siteway** [comment]
:+1: 
both simple and fast solutions to integrate. :-)

**Comment by paul-siteway** [comment]
Cloud you add a quick info on what solution you integrated and what whats needs to be done by shop owners?

**Comment by maxiloc** [comment]
I just remove the "http:" or "https:" . There is nothing to do. Once the extension is updated, at next update you will get the protocol less url in your record

**Comment by paul-siteway** [comment]
:+1:
