### ISSUE TITLE
Add option to reindex only products from specific category

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#570]

**Comment by PLNech** [comment]
This request came from [Helpscout's conversation 248545127](https://secure.helpscout.net/conversation/248545127/):

>I've created an exception for some categories which are not included in the navigation menu, I want them to be indexed in algolia. But I don't know how to tell Algolia to index the products in this categories.
>How can I reindex all algolia products but without deleting any records (only updating) ? 

Until this is fixed, the temporary workaround we advised is [manually filtering the category in getProductCollectionQuery](https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L117-L173) then doing a "full" reindex.

**Comment by JanPetr** [comment]
Implemented in #598. It'll be part of the next release
