### ISSUE TITLE
Add option to disable overriding synonyms from Magento

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#577]
There are some users who uploads CSVs or are used to set synonyms directly in Algolia dashboard. To keep their comfort it'd be nice to implement simple checkbox in Synonyms tab which would dis/enable the setting (and overriding) synonyms from Magento

**Comment by ianjs** [comment]
+1 

We upload synonyms direct from Algolia via CSV and they mysteriously vanished after we upgraded the module.

One workaround for us would have been to start uploading them from Magento instead, but it looks like CSV file import is not available. It would be nice if this was also supported in the module so our staff can stay in the Magento backend to maintain Algolia.

**Comment by JanPetr** [comment]
Will be part of the next release
