### ISSUE TITLE
Add 1.7.0 to releases/

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#587]
Noticed 1.7.0 does not include an archive of the release in releases/. Expected to find [algoliasearch-1.7.0.tgz](https://github.com/algolia/algoliasearch-magento/blob/1.7.0/releases/algoliasearch-1.7.0.tgz).

Is the releases directory still relevant?

**Comment by JanPetr** [comment]
Hello @aude, thanks for reminder, I completely forgot /o\ I just pushed it.
