### ISSUE TITLE
modifying attribute value output

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#590]
What's the best method for changing the output of an attribute in autocomplete.phtml?

Let's say I want to output manufacturer, in the template it's {{manufacturer}}. but I want to do a str.replace of certain characters in the string before output

**Comment by JanPetr** [comment]
Hello @davids101,
I'm sorry for the late answer.

The best way would be to use `transformHit` method - https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/internals/frontend/common.js#L3
Here you can see example how it's used to modify Product hit in autocomplete's data source: https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/internals/frontend/common.js#L100
