### ISSUE TITLE
Personalization data

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#591]
We are looking to add personalized data to search results, which is calculated or determined after the user has visited the website and either a cookie or session is defined. How should we handle this? An example would be calculating user distance

**Comment by JanPetr** [comment]
Hello @davids101,

you can update the data in two ways. Both are described here: https://github.com/algolia/algoliasearch-magento/issues/593#issuecomment-248839633

About GEO distance - for such a feature would be the best to use [Algolia's GEO feature](https://www.algolia.com/doc/guides/geo-search/geo-search-overview#introduction). It's not supported by extension itself and it will require some custom coding on your side.

About further personalization - it's pretty complex topic and it's really bussiness dependent. Usually it requires some duplication of your data (more records), and usage of different ranking startegies. You can drop us an e-mail on support@algolia.com with your precise use-case and we can advise you more.

**Comment by alexgran** [comment]
Hey @davids101,
 did you succeed in having personalisation for magento? If so, could you show or tell how you did that?
regards
Alex
