### ISSUE TITLE
Why run the cronjob through the indexer?

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#592]
This is a question to help understand some design decisions.

Earlier on, the cronjob that was processing the Algolia queue was run as a Magento cron job. Then there was a change in [1.5.0](https://github.com/algolia/algoliasearch-magento/releases/tag/1.5.0) to start using the Magento indexer instead.

This probably has some up sides. Though, one of the down sides is that only one Magento indexer can run at a time.
That means that if there are a lot of products, the initial Algolia indexing job will block all indexes from running. Similarly if anything else takes a long time, the Algolia indexing job will not run.

Why was this path chosen?

**Comment by maxiloc** [comment]
There was two mains reason:
- Make it easier to run it via cli especially for people using an extension to manage their cron, which make it hard to do an immediate trigger
- Be able to run it via the admin panel, for debugging purpose when people have no access to cli

I get the downside you have. We were thinking about an option to choose between cron and indexer, but we did had only 1 demand this then so we did not pursue further

**Comment by davids101** [comment]
If it was Cron, wouldn't operations be quickly capped?

**Comment by JanPetr** [comment]
@davids101 Not really, the amount of operations would be still the same. The only difference would be that cron task could process queued jobs in parallel.

**Comment by aude** [comment]
@maxiloc Thanks for the clarification.

An ideal solution would be to be able to run this as a standalone, non-blocking cronjob. The indexer has to be run through external cron anyway now, so it would be a small change. That could be a point if you work on some core changes to the indexer again.
