### ISSUE TITLE
I want to add color swatch functionality,But didn't get any way to add custom data

### ISSUE THREAD

**Issue by Vivendo** [algolia/algoliasearch-magento#593]

**Comment by JanPetr** [comment]
Hello @Vivendo,
do you have different colors set as attributes in Magento? If so, you can add those attributes as attributes for indexing here:
<img width="966" alt="screenshot 2016-09-22 10 13 42" src="https://cloud.githubusercontent.com/assets/1058144/18741036/4623e112-80ad-11e6-92e3-6c90a3461cd7.png">

If you cannot add them or you store that data beside Magento, you can turn on partial updates:
<img width="607" alt="screenshot 2016-09-22 10 14 52" src="https://cloud.githubusercontent.com/assets/1058144/18741067/6d293f1e-80ad-11e6-8ce6-53376c3bee67.png">
and then write your own script to add custom data from external source. Just be sure you are pushing the data via `partialUpdate` method and that you are using the same `objectID` (product id) in your script.

**Comment by Vivendo** [comment]
Copying shardendu 

 

 <http://www.vivendo.com/> 

 

Mail: contact@vivendo.com <mailto:contact@vivendo.com> 

UK Freephone: 0333 577 9030 

International Calls: +44 (0) 20 3289 9490

Hours of contact: 09:00 am. - 18:00 pm (GMT)

Web: www.vivendo.com <http://www.vivendo.com>

**Comment by JanPetr** [comment]
I guess it's solved. If you have any questions, feel free to re-open.
