### ISSUE TITLE
Binary files being committed to git.

### ISSUE THREAD

**Issue by moloughlin** [algolia/algoliasearch-magento#606]
Currently, a git clone takes close to 80MB due to the presence of release tarballs and source maps in the git history, and we can assume this will only get worse over time. This can cause a lot of pain in CI builds or deploys where the repository is cloned.

There's no reason for release tarballs to exist in the repo, that's exactly what git does for you...and Github will even let you download a tarball for an existing tag (release) or branch. Could you please consider pruning those from the git history?

**Comment by JanPetr** [comment]
Hello @moloughlin,
thanks for the suggestion. Binaries stored in [releases folder](https://github.com/algolia/algoliasearch-magento/tree/master/releases) are not actually tarballs of the whole repo but tarballs used by Magento Connect for serving the plugin. Some users are relying on the tarballs being present.

But you are right that it starts to be a significant overhead and we'll have to come up with a solution. I'll keep the issue open.

Thanks.

**Comment by JanPetr** [comment]
Hello @moloughlin,

we removed the `releases` from the repository (#724), but we're going to keep it in history. So only new versions won't be added to GIT.
If it still causes you problems, you can use [shallow clones](https://www.perforce.com/blog/141218/git-beyond-basics-using-shallow-clones) in you CI builds so no history is cloned.

I'm closing the issue now.
