### ISSUE TITLE
Not response on magento 1.8

### ISSUE THREAD

**Issue by Qasimkhan87** [algolia/algoliasearch-magento#61]
Hi, 
  I have installed a latest release version without any error and also set a cron on every 5 minutes. But when I search no response is showing. and on Algolia offical site there is no records but queries are counting.
Note: I am using demo account of Agolia. and magento version 1.8 and there is no js or other php error or exceptions.
thanks
http://ritzqa.matechco.com/

**Comment by redox** [comment]
The `runCron` method is not designed to reindex the products/categories without any earlier "job" pushed in the queue.

If you have disabled such job enqueuing, you can have a look at https://github.com/algolia/algoliasearch-magento/blob/master/code/Model/Resource/Engine.php#L128-L145 to see how the products are actually pushed to the queue. Calling such code before the `runCron` should probably fix your issue.

Let me know how it goes!

**Comment by Qasimkhan87** [comment]
Thank you very much now Products upload successfully and auto complete working fine but instant page result page(result on page) is not working.
Here is my admin 
![configuration system magento admin 1](https://cloud.githubusercontent.com/assets/7070593/6098060/55ae42b6-aff4-11e4-9d47-57ed6f372c49.png)
configuration screenshot

**Comment by redox** [comment]
Alright :) Beware, instant-search is not part of the module -> seems very complex to handle it in a "generic" way. For now we only recommend building it yourself with the generated indices: https://github.com/algolia/algoliasearch-magento#instant-search

**Comment by Qasimkhan87** [comment]
Hi redox, 
   I have follow as you mentioned in last comment now autocomplete is working fine. but there is one issue remaining. in autocomplete categories is not listing as in url http://www.quiksilver.com.au/
2nd can you please give me some tips how can I edit the request query and customize response for instant searching.

Thanks
Qasim

**Comment by redox** [comment]
Hi Qasim,

yeah they customized a lot their module :) I would suggest to customize the Javascript code directly in  https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/topsearch.phtml to target the index you want + display the attributes you need.

Let me know how it goes!

**Comment by Qasimkhan87** [comment]
One last thing. I have upload a records by using simple script 
$rebuildProduct = Mage::getModel('algoliasearch/Resource_Engine');
$rebuildProduct->rebuildProductIndex();
$algolia = Mage::getModel('algoliasearch/queue');
$algolia->runCron();
and it successfully upload all my 8k Products records to Agolia.
My question is that I have use a same script for categories using a  script 
$rebuildProduct = Mage::getModel('algoliasearch/Resource_Engine');
$rebuildProduct->rebuildCategoryIndex();
$algolia = Mage::getModel('algoliasearch/queue');
$algolia->runCron();
How can I verified that categories are uploded or not. or will we have to upload categories?
thanks
Qasim

**Comment by redox** [comment]
Yes that's it. Then to search for categories, you need to filter your results with the `category` tag:

```
index.search("....", jsCallback, { tagFilters: "product" }); // to search for products
index.search("....", jsCallback, { tagFilters: "category" }); // to search for categories
```
