### ISSUE TITLE
Update index not works

### ISSUE THREAD

**Issue by marcelolinhares** [algolia/algoliasearch-magento#614]
Guys,
I did a purge in large skus in my base, eliminate more then 1000 skus, but the produts shows yet in Algolia search.

How can i exclude this products in Algolia with magento plugin?

[]s

**Comment by JanPetr** [comment]
Hello @marcelolinhares,
which version of the extension are you using?
Is you are on the latest one, can you enabled indexing queue and process reindexing? It should remove all inactive/deleted products from your indices.

**Comment by JanPetr** [comment]
Hello @marcelolinhares,
as I have no respond from you I'm closing the issue.

Feel free to re-open if you still have issues.
