### ISSUE TITLE
Promotional Pricing help

### ISSUE THREAD

**Issue by jhoopes** [algolia/algoliasearch-magento#615]
Hi,

We have a very large product library ~15k products, and we do promotional pricing from time to time that affects the price of some or all of our products.  

From going through how this plugin works and how the Magento promotions work, we need to enable customer group pricing to get the promotional pricing applied to the product's price attribute and for the customer group's index.  The problem with that, is the products that the promotion applies to doesn't trigger an re-index for those products, and so we were thinking of having the index updated nightly.  Updating our indexes nightly and letting the queue runner re-index via cron is that process creates and pushes a huge amount of operations and records into Algolia indexes as there's the multiplication of customer groups as well as the number of products we have in our library.

Do you have any suggestions on how to make this work better? 

Some Ideas I've thought of are:
 - Query Magento for the price of the product when it shows up on the page by modifying the JS code, but I feel like this might defeat the purpose of using Algolia to have quick results from searching and filtering.
 - Possibly modify this plugin to also send up a pricing index that holds the pricing information of the products and have that be a slave of the default products index.  And then only have that be updated every night.

Any help you could give would be great.  Or if there's another place to ask these types of questions, please let me know.

**Comment by JanPetr** [comment]
Hello @jhoopes,
thank you for your message and I'm sorry for the late answer.

Unfortunately we don't have any better solution for you than to trigger full-reindex manually after setting the promotion. The promotion applies to all products and full reindex is needed there.

Other possibility for you is to tweak the extension and trigger full reindex automatically after saving promotion.

In those cases you won't have to reindex every night but only in case there is a change in promotions, which will save you large amount of operations.

Is it doable for you?

**Comment by JanPetr** [comment]
Hello @jhoopes,
I'm closing the issue now. If you have any more question or something else on you mind, feel free to reopen or create a new issue for different topic.
