### ISSUE TITLE
Confusing tooltip

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#617]
<img width="526" alt="screen shot 2016-10-16 at 20 15 14" src="https://cloud.githubusercontent.com/assets/29529/19419705/6678a540-93dd-11e6-9cbd-803f92921e4f.png">

Disabling the indexing should not say "fully disable the extension". We want an option disabling the automatic indexing, is that the right option?

**Comment by JanPetr** [comment]
Hello @redox, no the label was wrong. It actually disables whole extension. I just fixed it in #619 
I created a new issue for adding "Disable indexing" feature (#620)
