### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#618]
I think we could improve the documentation by:
- [x] explaining how to disable the automatic indexing and how to trigger manually a full reindexing from the command line
- [x] renaming/spliting the [Back-end](https://community.algolia.com/magento/doc/m1/backend/) section of the documentation, which includes also logging, contributings & caveats
- [x] removing the "Is it working on Magento 2" FAQ entry

What do you think @JanPetr?

**Comment by JanPetr** [comment]
For the first point we need to impletement Disable indexing feature (#620)

**Comment by JanPetr** [comment]
All done - https://community.algolia.com/magento/doc/m1/indexing/
