### ISSUE TITLE
500 Error after installation

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#629]
Right after installing on magento 1.9.0.1 I try to visit the configuration page for Algolia and I get a 500 error:

```
[21-Oct-2016 18:26:50 UTC] PHP Fatal error:  Class 'Algolia_Algoliasearch_Block_System_Config_Form_Field_ProductAdditionalAttributes' not found in /app/code/core/Mage/Core/Model/Layout.php on line 590
```

I tried clearing the cache and logging out and back in again.

We are using PHP 5.6.27

How can I fix this?

EDIT: sorry the previous error message was not correct or related. The above one is correct.

**Comment by JanPetr** [comment]
Hello @greatwitenorth,

thank you for your report. Can I ask you how you installed the plugin? From [Magento Connect](https://www.magentocommerce.com/magento-connect/search-algolia-search.html)?
On which operating system and which Magento version do you install the extension? It will help me in reproducing the issue.

Thank you for your help.

**Comment by greatwitenorth** [comment]
Magneto 1.9.0.1. OS is CENTOS 7.2 x86_64. The plugin was installed via magento connect. Also I did the same process to install on my local development copy which runs on OS X 10.11, using Laravel Valet for the webserver, and I experienced the exact same issue (OS X saw the files as directories in the finder).

**Comment by JanPetr** [comment]
Thanks for additional info @greatwitenorth, I was able to reproduce on Mac OS X \o/
It's a bug in Magento's uncompressing algorithm, when files with path longer than 100 characters are interpreted as folders - https://magento.stackexchange.com/questions/5585/long-file-names-and-magento-connect-extension-packager/45187
I will try to use different packaging tools and come back to you.

P.S. I was not able to reproduce on 1.9.3.0, so if you are able to upgrade it should work just fine :)

**Comment by JanPetr** [comment]
I didn't manage to make it work. We already use Magento's scripts for generating packages and this is Magento's issue :(
Version 1.9.0.1 is the last with the issue, I didn't manage to reproduce on newer versions, they all work fine.
Do you think you will be able to upgrade your Magento or fix it by hand?

**Comment by greatwitenorth** [comment]
Yes I just fixed by hand. Thanks for looking into it.
