### ISSUE TITLE
Re indexing issue.

### ISSUE THREAD

**Issue by Qasimkhan87** [algolia/algoliasearch-magento#63]
Hi, 
  We are reindexing Algolia from Admin Panel but not reindexing. We also try manually but same issue
$rebuildProduct = Mage::getModel('algoliasearch/Resource_Engine');
$rebuildProduct->rebuildProductIndex(1);
Thanks

**Comment by redox** [comment]
Weird :/ Could you contact support@algolia.com specifying the APPLICATION_ID you're using so we can investigate on our side?

**Comment by Qasimkhan87** [comment]
Hi redox,
  Thanks again for your quick response. I have solve this issue. It was some conflicting issue. We have almost complete But I have one small js issue. 
1- The arrow key is not working. means select a product from result using a arrow up/down key. Can you please guide.
2- second from instant searching. Is there any possibilities to select a result between min and max prices as we normally use in magento. currently there is only min price options.
Thanks

url: http://ritzdev.matechco.com/
 http://ritzdev.matechco.com/searchresults#q=canon&page=0&minPriceCount=NaN&refinements=%5B%5D

**Comment by redox** [comment]
Hi @Qasimkhan87,

You're welcome. Regarding your questions:

1. Unfortunately, the simple auto-completion menu provided in the magento module doesn't implement the key arrow navigation. You may want to switch to `typeahead.js` like in https://www.algolia.com/doc/tutorials/multi-auto-complete

2. You just need to combine another numericFilter to end up with something like: ```numericFilters= customerReviewCount>X,customerReviewCount<Y```

Let us know how it goes!
