### ISSUE TITLE
Enable Instant Search Results Page not appear on the catalog page No result 

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#635]
when i set the _**Enable Instant Search Results Page**_ to Yes category pages are not founded it doesn't link to it  and when i put  _**Enable Instant Search Results Page**_ to No its link and open but there is no category search at the top , No Input text search ?!
Note that the main search is working fine but i need to link with category pages to make a layered navigation 
**If set to Yes, the products inside the results pages will be searchable the refined results updated as-you-type. It requires your theme to expose a top.search and content block. **
do i need to change the template name or overwritten the default one ?!
Thank you

**Comment by maxiloc** [comment]
You also need to set to yes "Replace category page" in the instant search section. Did you do that ?

**Comment by rehamwael** [comment]
yes I did it before

**Comment by JanPetr** [comment]
Hello @rehamwael,
I'm not sure I understand you issue correctly. Do you have a website where I could see it? Or can you provide some screenshots with behaviour you are expecting? Thank you in advance.

**Comment by rehamwael** [comment]
sorry I'm working locally on my PC write now :(
i want to ask you is Index product and categories URL rewrites related to this issue because I'm re index it right now it take much time from me

**Comment by rehamwael** [comment]
i think i face the same issue here https://github.com/algolia/algoliasearch-magento/issues/262

**Comment by maxiloc** [comment]
@rehamwael Do you mind sending an email to "support at agolia dot com" so we can investigate further

**Comment by rehamwael** [comment]
In app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml 
if ($config->isInstantEnabled() && $isSearchPage) {
     echo '
     <script>
-        document.write(\'<style type="text/css"> ' . $config->getInstantSelector() . '{display:none}</style>\');
+         document.write(\'<'+'style type="text/css"> ' . $config->getInstantSelector() . '{display:none}</'+'style>\');
     </script>';
 }
 we change the code it wasn't closing the style tag on the browser so its become a white page because no javascript rendering its working now but stell appearing the search at the bottom of the page Thank you so much
