### ISSUE TITLE
Product<->Category relation is not indexed

### ISSUE THREAD

**Issue by dmytro-butko** [algolia/algoliasearch-magento#638]
**Product**: Bringing It All Back Home (Vinyl)
**Magento**: Assigned to 5 categories
**Algolia**: Shows as assigned only to 1 category (for most products even 0)

**Screenshot Magento**:

![image](https://cloud.githubusercontent.com/assets/8305494/19749304/cf2e10d0-9c33-11e6-9f7b-348b0636d76f.png)

**Screenshot Algolia**:

![image](https://cloud.githubusercontent.com/assets/8305494/19749317/e1c8021e-9c33-11e6-8bf1-41120510915d.png)

**Magento catalog_category_product index extract**:

```
mysql> select * from catalog_category_product where product_id = 367973;
+-------------+------------+----------+
| category_id | product_id | position |
+-------------+------------+----------+
|           2 |     367973 |        1 |
|         382 |     367973 |        1 |
|         391 |     367973 |        1 |
|         402 |     367973 |        1 |
|         417 |     367973 |        1 |
+-------------+------------+----------+
5 rows in set (0.00 sec)
```

**Algolia record extract**:

```
"hits" : [{
  "name" : "Bringing It All Back Home (Vinyl)",
  "url" : "https://<domain>/store/bob-dylan-bringing-it-all-back-home-vinyl-vinyl-5991110?SID=f043v7sne2577uvockvco7o5j7",
  "visibility_search" : 1,
  "visibility_catalog" : 1,
  "categories" : {
    "level0" : ["Music"]
  },
```

State after full reindex and after product save is the same so indexing method does not impact the result

**Comment by JanPetr** [comment]
Hello @dmytro-butko,
have those categories attribute `Include in Navigation Menu` set to `Yes`?
If not, those categories won't be indexed by default. You can enable indexing of those categories by setting `Show categories that are not included in the navigation menu` to `Yes` in Algolia's configuration in Magento:
<img width="836" alt="screenshot 2016-10-27 11 38 30" src="https://cloud.githubusercontent.com/assets/1058144/19762354/f3f081ea-9c39-11e6-9245-d252c57d63d1.png">

**Comment by dmytro-butko** [comment]
hey @JanPetr 

 That helps, thanks!
 Sorry but related question about category pages....
   - Hit Magento Category URL of type: catalog/category/view/id/424
   - Actual result: Algolia extension showing all store products
   - Expected result: Algolia extension automatically filtering to products within category 
 Any hint is appreciated.

Thanks in advance,
 Dmytro

**Comment by JanPetr** [comment]
Hey @dmytro-butko,
great that you managed to index the categories.

About the second issue - it shouldn't happen. When you are on category page, the extension should retrieve only related products. You can test it here: https://magento.algolia.com/accessories/jewelry.html

To explain you the code. First the extension checks if you are on category page and than set's category path to configuration: [here](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml#L56-L64) and [here](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml#L221).
Then when instant search starts and path is set, the extension sets the path as refinement, so only those products are retrieved. It's happening [here](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js#L289-L291).

Can you investigate what is happening and if the refinement is correctly set and that `categories` attribute is set as attribute for faceting?
Or do you have a website where I can see it?

**Comment by dmytro-butko** [comment]
thanks @JanPetr,

 The diff between demo store and my store :  

   1. version 1.7.0 on demo and 1.7.1 on mine
   2. request on demo store

    ![image](https://cloud.githubusercontent.com/assets/8305494/19841395/3c085a52-9f5f-11e6-8efc-362179be9040.png)

   3. request on my store

     ![image](https://cloud.githubusercontent.com/assets/8305494/19841401/57ea1274-9f5f-11e6-99d4-aa0625dd2b6d.png)

    for some reason tons of params are not there.

   4. page algolia config on my store

`window.algoliaConfig = {"instant":{"enabled":true,"apiKey":"NjQ1YzVmMzhjMmE0ODRlZDczN2VjMDRiNGYwMzlkYzE0MDI4ZDZkNmYzMmVkZWM0NGQ1YzVhYjhhNzY1MDcwMWZpbHRlcnM9Jm51bWVyaWNGaWx0ZXJzPXZpc2liaWxpdHlfY2F0YWxvZyUzRDE=","selector":".main","isAddToCartEnabled":true,"showStaticContent":true,"title":"Preorders","description":"","content":"","imgHtml":"","hasFacets":true},"autocomplete":{"enabled":true,"apiKey":"MzRlNDljMDQyYTNiN2M1NmQ2M2ExYTA2ZDdmODExMzI5Y2JlYjIwYjE3NWNkMzRjNmZjMmNiMzdkMWYzM2Q1YWZpbHRlcnM9","selector":".algolia-search-input","sections":[{"name":"pages","label":"Pages","hitsPerPage":"1"},{"name":"artist_label","label":"Artist","hitsPerPage":"1"}],"nbOfProductsSuggestions":"8","nbOfCategoriesSuggestions":"4","nbOfQueriesSuggestions":"2","displaySuggestionsCategories":true},"extensionVersion":"1.7.1","applicationId":"2T8U2Y32GC","indexName":"staging_getmusicau","facets":[{"attribute":"price","type":"slider","label":"Price"},{"attribute":"artist_label","type":"disjunctive","label":"Artist"},{"attribute":"categories_without_path","type":"disjunctive","label":"Category"}],"hitsPerPage":15,"sortingIndices":[{"attribute":"price","sort":"asc","label":"Price","name":"staging_getmusicau_products_price_default_asc"},{"attribute":"artist_label","sort":"asc","label":"Artist","name":"staging_getmusicau_products_artist_label_asc"}],"isSearchPage":true,"isCategoryPage":true,"removeBranding":true,"priceKey":".AUD.default","currencyCode":"AUD","currencySymbol":"AUD $","maxValuesPerFacet":20,"autofocus":true,"request":{"query":"","refinementKey":"","refinementValue":"","path":"Music \/\/\/ Preorders","formKey":"Z82wnETetXxcdQtE"},"showCatsNotIncludedInNavigation":true,"showSuggestionsOnNoResultsPage":true,"baseUrl":"https:\/\/getmusic.uma-sites.com\/store","popularQueries":[],"urls":{"logo":"https:\/\/getmusic.uma-sites.com\/store\/skin\/frontend\/base\/default\/algoliasearch\/algolia-logo.png"},"translations":{"to":"to","or":"or","go":"Go","in":"in","popularQueries":"You can try one of the popular search queries","seeAll":"See all products","allDepartments":"All departments","seeIn":"See products in","orIn":"or in","noProducts":"No products for query","noResults":"No results","refine":"Refine","selectedFilters":"Selected Filters","clearAll":"Clear all","previousPage":"Previous page","nextPage":"Next page","searchFor":"Search for products","relevance":"Relevance","categories":"Categories","products":"Products","searchBy":"Search by"}};`

 PS it looks like #647 is the same/similar issue

**Comment by JanPetr** [comment]
Hey, I checked you configs and to make it work you need to have set attribute `categories` as attribute for faceting. Right now you have only `categories_without_path` set as attribute for faceting. Can you change that?
Do you have any special reason why you don't have `categories` as attribute for faceting?

**Comment by JanPetr** [comment]
I create a PR to not force you to set categories as attribute for faceting -  https://github.com/algolia/algoliasearch-magento/pull/650
All you `categories` attribute will be set as attribute for faceting in Algolia automatically, so it will work as expected and you won't have categories widget in filters.
