### ISSUE TITLE
Fatal error: Call to a member function isComposite() on a non-object 

### ISSUE THREAD

**Issue by dmytro-butko** [algolia/algoliasearch-magento#639]
Trying to delete product:

![image](https://cloud.githubusercontent.com/assets/8305494/19754810/8978c11a-9c5c-11e6-9873-ad2bcb2277ba.png)

Results in: Fatal error: Call to a member function isComposite() on a non-object in app/code/community/Algolia/Algoliasearch/Model/Indexer/Abstract.php on line 90

**Comment by JanPetr** [comment]
Thank you for the report @dmytro-butko 👍 
I just fixed it in #640 and it will be part of the next release!
