### ISSUE TITLE
Updating a product seems to reindex the whole catalog

### ISSUE THREAD

**Issue by anbuf** [algolia/algoliasearch-magento#64]
Hi, 

First, I love algolia. The integration with Magento was really easy, the results are accurate and it was quite easy too to change the frontend. 

We change our plan 9 days ago for the Starter plan (100,000 records and 1,000,000 operations). And in 9 days I used 80% of my operations but I have only 978 records. What's happened to all the operations?

It seems that each time a change an image, or event just a product name or just add a comma in a description. Everything is re-indexed. Am I right?

I would suggest to have a option in the system panel to choose between "manual" or "automatic" re-indexing. 

Best regards,
Anthony

**Comment by redox** [comment]
Hi @anbuf,

Thank you for the positive feedback. I have good news for you :) We're currently working hard on improving the module! And while working on it, we've discovered the same issue... It seems to reindex too much things on each save -> can you please send me an email (sylvain at algolia) so I can tag your account and remove your over-quota before the next invoice?

Don't worry about the consumption, you'll pay nothing more than your starter plan.

**Comment by anbuf** [comment]
I did for the moment, I went to System > Index Management and set the mode of "Algolia Search Index" to "Manual Update" so it gonna fix temporarily the problem while waiting the next update.

**Comment by colinmollenhour** [comment]
Just a hunch, but might have to do with the Product Count option. I have this disabled and the indexer seems very efficient to me.

**Comment by anbuf** [comment]
Where can I find this option?

**Comment by Fequois** [comment]
@anbuf System / Configuration / Algolia Search

**Comment by redox** [comment]
Any news @anbuf ? Could you try with our last 1.1.0 version?

**Comment by maxiloc** [comment]
I never reproduce this issue. With the release of 1.1.5 at the end of this week it should be good. Closing this for now
