### ISSUE TITLE
Instant search result on category 

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#647]
Instant search result on category page printed the **algolia-right-container and the left** one empty (no Result) after the footer of the page ?!
but still printed the category as they are at the top without a search on specific category page 
actually i have problem with the category page searching from the beginning but the autocomplete is working on the header :)
what the things that i have to check ?!

Thanks in advance

**Comment by JanPetr** [comment]
Hello @rehamwael,
can you check you have correctly set instant search container? When it's not set correctly it won't replace your old category but will be rendered after.

**Comment by JanPetr** [comment]
Hey @rehamwael,
I didn't hear from you for a while. Did you manage to fix the issue? Let me know.

I'm closing the issue now, but feel free to reopen anytime.
