### ISSUE TITLE
search iamges

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#648]
images are shown on my local website but not appeared on the server ?

**Comment by JanPetr** [comment]
Did you reindexed your data on the server? The whole images' URLs are indexed so when you move to the server you have to reindex in order to index correct image URLs.

**Comment by rehamwael** [comment]
sorry i missed , thank you so much it's working now :)

**Comment by JanPetr** [comment]
Perfect! 👍
