### ISSUE TITLE
Is possible to add color swatches in Algolia?

### ISSUE THREAD

**Issue by dudusotero** [algolia/algoliasearch-magento#654]
Hello!
Is there any way to add color swatches on instant-search filter like Magento's default filter??

Thank you for your answer.

**Comment by JanPetr** [comment]
Hello, yes. You need to select attribute `color` as attribute for faceting in Algolia's configuration. Here:
<img width="983" alt="screenshot 2016-11-01 15 47 17" src="https://cloud.githubusercontent.com/assets/1058144/19893744/86dfade6-a04a-11e6-8c7a-cecf48dad19a.png">

Thank you will have color filter on the instant search page.

**Comment by dudusotero** [comment]
Thanks for the support.
Currently I already have this feature, I would even was able to display color samples instead of the name.

Like this: 
![capturar](https://cloud.githubusercontent.com/assets/7073199/19896112/4b928caa-a03a-11e6-8e36-2a4d257375bb.PNG)

**Comment by JanPetr** [comment]
Oh, now I see. This feature is not provided out of the box by the extension.
For that you'll have to modify styles and templates of the colors refinement list.
You can take a look look at [instantsearch.js](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js) file where everything related to instant search page is handled. And update accordingly to fit your needs.

**Comment by redox** [comment]
> You can take a look look at instantsearch.js file where everything related to instant search page is handled. And update accordingly to fit your needs.

I think it could make sense to add a small documentation section describing the code required to build such kind of refinement widget. I've the feeling it's a pretty common use-case. What do you think @JanPetr?

**Comment by JanPetr** [comment]
@redox Yes, it's definitely not the first time I see this question and the guide for this is on my roadmap. But right now we are working on adding custom events / hooks to extension's JS files (https://github.com/algolia/algoliasearch-magento/pull/642) to be able to do it without having to update the files directly.
Now we are gathering feedback on the feature from agencies we're working with. And once we have it there will be guides on how to do different modifications and tweaks for similar use cases.

**Comment by dudusotero** [comment]
Nice, I will check that.

Thanks for the support @JanPetr and @redox.

**Comment by dudusotero** [comment]
I found an example that fits exactly what I need.

https://community.algolia.com/instantsearch.js/examples/e-commerce/

Does anyone know where I can find the source code to try to apply in my environment?

**Comment by JanPetr** [comment]
Hey @dudusotero,
the source code of the demo is here: https://github.com/algolia/instantsearch.js/tree/master/docs/examples/e-commerce

And the source code of instantsearch.js in the extension is here: https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js

**Comment by dudusotero** [comment]
Thanks @JanPetr!

**Comment by JanPetr** [comment]
You're welcome. Let me know how it goes :)

**Comment by dudusotero** [comment]
@JanPetr There a way to make the variable {{name}} in file refinementsItem.phtml be lowercase?

In magento the image samples have the same name as the value of the variable {{name}}, with this, is posible to display the swatch image.

<Img src = "https://www.mywebsite.com.br/media/catalog/swatches/3/21x21/media/{{name}}.png">

Any ideas?

**Comment by JanPetr** [comment]
You can use `transformData` parameter of refinementList widget and set it function to add lowercase name variable to the item. Documentation of refinement list: https://community.algolia.com/instantsearch.js/documentation/#refinementlist

It could look something like this:
```javascript
transformData: function(item) {
    item.lowercaseName = item.name.toLowerCase();

   return item.
}
``` 

and then use `{{lowercaseName}}` in your template :)

**Comment by dudusotero** [comment]
It worked !!
I used the transformData when the facet type is "disjunctive".
It was something like this:

```javascript
if (facet.type === 'disjunctive') {
    return algoliaBundle.instantsearch.widgets.refinementList({
	    container: facet.wrapper.appendChild(document.createElement('div')),
	    attributeName: facet.attribute,
	    limit: algoliaConfig.maxValuesPerFacet,
	    operator: 'or',
	    templates: templates,
	    cssClasses: {
		    root: 'facet disjunctive'
	    },
	    transformData: function(item) {
	        item.lowercaseName = item.name.toLowerCase();
	        return item;
	    }
    });
}
```
![capturar](https://cloud.githubusercontent.com/assets/7073199/20070021/0f2f3f44-a506-11e6-8330-9b9b45cc01eb.PNG)

Now it's time to work with a little CSS.

Thanks for the support @JanPetr

**Comment by JanPetr** [comment]
No problem, I'm glad you made it work! Happy searching 🔥

**Comment by dev9-ki5** [comment]
i want to implement this feature for magento 2 , color image show instead of text on sidebar , how can i customize instantsearch.js, awaiting for your kind reply
