### ISSUE TITLE
Algolia indexing stuck

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#656]
I have disabled Indexing Queue and started Algolia Search Products via admin area. We have 6000 enabled, visible products. (35k enabled products - some are simples, part of configurable and 35k disabled). 

Algolia indexed about 90% of the products and stuck at "processing" status. But logs are stuck as well and doesn't add any new lines of reindexing...

How can I reset it and start reindex over? 

P.S. switching to queue, trying to start indexing again - didn't help.
Trying to reindex 1 specific ID via websiteurl.com/admin/process/reindexProcess/process/3031/ gives Cannot initialize the indexer process.

UPD:
trying to reset reindexing process - I have truncated algoliasearch_queue table in db, deleted locks and restarted reindex via ssh and got an error:

 php shell/indexer.php --reindex algolia_search_indexer
Algolia Search Products index process unknown error:
exception 'AlgoliaSearch\AlgoliaException' with message 'Invalid Application-ID or API key' in

Eventhough keys and ID are correct...

**Comment by JanPetr** [comment]
Hello @Mobecls,

can you go to Algolia configuration in Magento and save the configuration again? Can you check if it was saved correctly without any error or just to try to fill the APP ID and API key again?

Thanks!

**Comment by Mobecls** [comment]
yes, I have tried that. I have copy/pasted again all the API's and resaved them - and that didn't help.


Should I try and create new key?

**Comment by JanPetr** [comment]
Could you send us e-mail with you app id and version of you Magento to support+magento@algolia.com? I'll investigate more.

**Comment by Mobecls** [comment]
just have sent

**Comment by Mobecls** [comment]
The issue was connected to our internal settings where php didn't decript api key correctly.
