### ISSUE TITLE
z-index of autocomplete menu template

### ISSUE THREAD

**Issue by abepe** [algolia/algoliasearch-magento#658]
I'm having an issue where the autocomplete box appears to be under other elements of a site I'm working on, although this is only happening on the home page.

It's entirely possible the issue is with the parent Magento skin but I don't seem to be able to find any css using dev tools.

Is there a way to set the z-index for the autocomplete menu template or am I looking in the wrong place?

![screenshot 2016-11-04 10 44 52](https://cloud.githubusercontent.com/assets/1450164/19989639/f8787a04-a27b-11e6-80cb-8a6ed7e9fb6d.png)

**Comment by JanPetr** [comment]
Hello @abepe,

the z-index is not possible to set via UI, but CSS of the autocomplete are located in this file: https://github.com/algolia/algoliasearch-magento/blob/master/skin/frontend/base/default/algoliasearch/algoliasearch.css
You might not want to override the file directly so you can update the extension in future so I'd suggest you to create your own CSS file and override it from there.

If you want to inspect autocomplete menu with browser dev tools, you can switch the autocomplete to debug mode by changing [debug variable](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/autocomplete.js#L74) from `false` to `true`. It will prevent the autocomplete menu from disappearing while debugging.
Don't forget to turn it back off when you're done :)

**Comment by JanPetr** [comment]
Hello @abepe,
I didn't here anymore from you. Did you manage to fix the z-index?

I'm closing the issue now, but feel free to reopen anytime.
