### ISSUE TITLE
catalogsearch_fulltext was rewritten with algolia

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#659]
We have noticed, that when we reindex catalogsearch_fulltext  - algolia's logs are getting new and new records. And it turned out, that Magento's default catalogsearch_fulltext  was rewritten with algolia. 

So the question - what does it do? When we run php shell/indexer.php reindexall - than we got both catalogsearch_fulltext  and algolia_search_indexer indexed. Does that mean, that we are reindexing all products twice and spending some of our Operations in vain?

**Comment by JanPetr** [comment]
Hello @Mobecls,
yes, and this is expected. When you run `reindexall` it will index products to Algolia twice.
We decided to override the `catalogsearch_fulltext` as most of our customers got confused and expected `catalogsearch_fulltext` to work for Algolia.

If it's problem for you, you can disable it by calling `return parent::rebuildIndex($storeId, $productIds);` directly without condition here: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php#L46-L48
