### ISSUE TITLE
Product didn't change in category

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#660]
We have a category that updates every night via external import app. Today we have enabled Reindex Queue at algolia settings. 

And setup to reindex all the rest algolia indeces once per week. 
I have noticed 2 problems:

1. Algolia 5minute Queue Index is reindexing during the day, but no updates are sent to algolia. 
Do we have to reindex all the rest indeces each 5 minutes as well?

2. I have run Algolia Search Products manually via admin area and in DB I can see, that in algoliasearch_queue where created 100 jobs (2 batches by 50 jobs, according to settings in admin area). But non of them had any product ID.... So the changes didn't go algolia. I had manually add those changes, to push them to algolia.

So the questions are:
1. why did extension creates empty jobs?
2. why new product didn't appear in category, eventhough I have run products and categories indexes?

**Comment by JanPetr** [comment]
Hey @Mobecls,

regarding the first question - it does not create empty jobs. It creates batches jobs which does not inlclude any IDs, it updates all products regardless IDs. So when it's processed you should see all changes done.

about the second question - can you find the product in Algolia dashboard and see it's categories. Just reminder - only active categories and categories which should be included in navigation are index with products.

**Comment by Mobecls** [comment]
1. But why it creates 100 jobs, and not jost one? and if there are no IDs - it means all? 

2. yes, I did - and it wasn't there. The question is - when we update product via 3rd party extension (without editing it in admin area) - what should we do to push it to Algolia? 

We had Queue indexer enabled - and it did nothing....

**Comment by JanPetr** [comment]
1 - because for performance reasons it cannot be run all in once, that's why it's split to 100 jobs

2 - you need to run full reindex or manually call [reindexSpecificProducts](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Indexer/Abstract.php#L50) from you custom script with IDs of updated products

Queue runner only processes queue, but indexers have to fill the queue so the queue runner has something to process.

**Comment by Mobecls** [comment]
I see, thanks.

**Comment by Mobecls** [comment]
and reindexSpecificProducts - will just add products to a Queue?

**Comment by JanPetr** [comment]
If the queue is enabled - yes. Otherwise it will index them directly.
