### ISSUE TITLE
Lock tables during reindexes? 

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#661]
Why did you decide to sync products with algolia during reindexing? It locks tables and causes performance issues. I understand that you have done Indexing Queue to fix that, but still don't understand why Indexes are used at all, and not just direct transactions to algolia?

**Comment by JanPetr** [comment]
Hello @Mobecls,
we used indexers as the extension indexes data to Algolia. The process is indexing and it's used for all other Magento's indexers.

But we are open to new suggestions and you are more than welcome to open pull request with the new approach.
