### ISSUE TITLE
Price not updating in search results

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#662]
I've indexed my entire Magento store catalogue in Algolia. I then went and increased the price of a product, but the search results still show the old price.

Steps to reproduce
- I indexed my entire catalogue in algolia
- I edited a product's price in the admin, increasing the value
- I searched for the product on the store's homepage
- I saw the product with the old price
- I triggered a reindex in the admin
- I searched for the product again on the homepage
- I saw the product still showing the old price
- I searched for the product in my algolia.com dashboard, and see the old price

I expected to see the new price in the search results after updating a product's price.

Centos 7.2
Mangento 1.9.0.1
Algolia Plugin 1.7.1
PHP 5.6.27
MySQL 5.6.34

**Comment by JanPetr** [comment]
Hello @greatwitenorth,
do you have indexing queue enabled? If you do, it may take some time to send the update to Algolia as when you update the price, the update is store in queue and queue is then processed with your cron you set up while enabling queue.

Is that the case here?

**Comment by JanPetr** [comment]
Any news @greatwitenorth?
As I didn't hear from you again, I'm closing the issue. If you didn't manage to fix it, feel free to re-open anytime.
