### ISSUE TITLE
Reindex Issues Magento Algolia

### ISSUE THREAD

**Issue by ajaysolskjaer** [algolia/algoliasearch-magento#663]
I was getting an error while trying to reindex via admin and shell.
"Record Quota Exceeded, change plan or delete records."
Also we see the same thing in algolia API calls.
(Screenshots attached)
![admin reindex](https://cloud.githubusercontent.com/assets/20857170/20167082/13f2d3ac-a73f-11e6-90b2-81032b1000b2.png)
![search results bikini](https://cloud.githubusercontent.com/assets/20857170/20167084/13f7887a-a73f-11e6-8b62-7c93b5591b0d.png)
![shell reindex error](https://cloud.githubusercontent.com/assets/20857170/20167083/13f4e6c4-a73f-11e6-8333-28ad4b67c4c3.png)

dev.pescaboutique.com
When I click enter for the keyword I search, it shows no products (Screenshot attached)
![algolia api call](https://cloud.githubusercontent.com/assets/20857170/20167087/1a4165e8-a73f-11e6-89c1-87b2bac6e340.png)

Is it becuase of the index error. And why is it causing the error while indexing ?
A quick reply would be appreciated.
Thanks

**Comment by JanPetr** [comment]
Hello @ajaysolskjaer,
you are currently on Algolia's free plan. And free plan is limited to 10 000 records.

You crossed that limit: 
![screenshot 2016-11-10 14 57 22](https://cloud.githubusercontent.com/assets/1058144/20179382/2e9167ac-a756-11e6-809f-c570f87ecc01.png)

You need to either lower the number of records under 10 000 or switch to our Starter plan and enjoy quota 100 000 records / 1M operations.
