### ISSUE TITLE
Admin API Key lost when saving in Magento Configuration

### ISSUE THREAD

**Issue by antonbe** [algolia/algoliasearch-magento#665]
The Admin API Key is lost when saving in Magento Configuration after making any changes to the configuration after saving it once originally. It saves it as the dots in the DB instead.

**Comment by JanPetr** [comment]
Hello @antonbe,
I'm sorry to hear that. It's most probably because of #637 where we start to use `obscure` input type for API key in configuration so the actual Admin API key is never displayed in frontend.

Can you share with me what version of Magento do you use?

**Comment by JanPetr** [comment]
@antonbe, did you make it work? Any information about your Magento version would help us to resolve the issue.

Thanks a bunch!

**Comment by fbkaasa** [comment]
Hey JanPetr, 
We face the same issues aswell with the latest version.

`Uncaught r` in searchfield and Algolia search does not appear at all.

**Comment by adrien-louis-r** [comment]
Hi,

I don't know if it's realted, but we encounter a similar issue, sometimes we got the `"Please provide an API key. Usage: algoliasearch(applicationID, apiKey, opts)"` message in the console without any reasons, the key seems to be correctly saved in our case.

Opening a incognito chrome solve the problem. Maybe it is cache related ? (Mag. 1.9.3.0, Algolia extension 1.7.2).

**Comment by JanPetr** [comment]
@fbkaasa Can you check what API key is saved in database? Is it just starts/dots? Are you able to save Algolia configuration in Magento? Or correctly reindex data? If so, the key is saved correctly.

@adrien-louis-r Definitely can be cache related. When you open the site in standard Chrome mode and hard refresh will it resolve?

**Comment by JanPetr** [comment]
Will be fixed in 1.8.0
