### ISSUE TITLE
magento search language 

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#667]
in my website we have two different languages , for example if I type on english pages an arabic text give me not found and the opposite happens on English is there any configuration i should do to handle this or we can't ?
search on english pages is  limited to english not searching on all store 

Thanks in advance

**Comment by JanPetr** [comment]
Hello @rehamwael,
it's expected. The extension creates one index per store, so when you are on english store, only english products (text, ...) are searched and returned from Algolia. It's not easy use-case and I'd not recommend doing so as it is very confusing for your users.

Currently there is no way how to provide results from both stores, besides writing custom JS code on your side. But it's not easy to handle it properly.

**Comment by rehamwael** [comment]
@JanPetr okay thank you so much

**Comment by rehamwael** [comment]
could you help me which files that i have to edit them is it **common.js** file or **php Files** to handle this ?

its important for us because most searching brands are on other language that user use so i need to make one and whole store for both language or i can make it as an if statement for the language that customer use ?
please can you help me on this its important for our SEO 

Thanks in Advance

**Comment by ahmedfekry** [comment]
I have a similar issue. if i am searching in the arabic version i can search in both arabic and english but if i am in the english one i only can search in english.

**Comment by ahmedfekry** [comment]
@rehamwael Did you find solution for this ?
