### ISSUE TITLE
How to change attribute options on search

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#670]
We have an attribute - personalized - dropdown, with 2 options: 0 and Yes. 
We've added it in admin area to facets: http://i.imgur.com/hfgcOqv.png

But on frontend we got a block, showing 3 results...: http://i.imgur.com/GpVbB1f.png

Why do we have 3 of them? 

And another example - we have some facets, that allow only 1 option - http://i.imgur.com/pFyuBKi.png 
But if facet has only 1 option - it shouldn't be shown at all....

**Comment by JanPetr** [comment]
@Mobecls, in the attributes setting set "Index Empty Value" to "No" for these attributes and reindex your data.

Than the "No" value won't be indexed and you will have only correct values in your facets.

<img width="953" alt="screenshot 2016-11-16 10 49 11" src="https://cloud.githubusercontent.com/assets/1058144/20342385/77ff26ac-abea-11e6-82e6-352a893cc487.png">

**Comment by Mobecls** [comment]
ok, let me try

**Comment by Mobecls** [comment]
Just checked - but we don't have "Personalized" added to attributes, it was added only to Facets. And facets doesn't have that option...

**Comment by JanPetr** [comment]
I see. When you set it only to Facets, all values will be indexed. You can add it to Attributes as well and turn off empty value indexing there. It will work the same except you will have correct values in the index.

**Comment by Mobecls** [comment]
Woudn't it spend more of our allowed operations by our plan?

**Comment by JanPetr** [comment]
Setting is as attribute no, reindexing data yes. But you'll need to reindex data in order to remove wrong ("No") values from your indices.

**Comment by Mobecls** [comment]
ok, added it like that - is that correct? 

http://i.imgur.com/GIi2DNJ.png

**Comment by JanPetr** [comment]
It needs to be retrievable in order to work for faceting. So just change the value in "Retrievable?" column to Yes and you are good to go.

**Comment by Mobecls** [comment]
And what does that mean - Retrievable? I mean, how does it work?

**Comment by Mobecls** [comment]
And why do we  have some facets, that allow only 1 option - http://i.imgur.com/pFyuBKi.png
Can we make them "yes" and "no"?

**Comment by Mobecls** [comment]
For example on that page: https://goo.gl/SHAFFP - check out the "flex" attribute.

We don't have Flex at any product in that category, so we don't expect it to be shown at this page.



![flex](https://cloud.githubusercontent.com/assets/10348554/20379045/062cef16-acab-11e6-940f-3b23cdd04e4b.jpg)

**Comment by JanPetr** [comment]
You need to add Size attribute to searchable attributes table in Algolia configuration in Magento and set "Index empty values" to "No".
Then reindex your data.
