### ISSUE TITLE
Make search work for the whole website on category pages

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#671]
We have set "Enable Auto-completion Menu" and now our Top Search works as an instant search. 

But the problem is that when I visit a category, Top Search searches only inside of that category. And I would  like to be inside of a category and expect Search to provide results from the whole website. (in the same way it works on CMS pages and at home page).

is there a way we can do that?

**Comment by JanPetr** [comment]
You can remove the condition which limits the results to the particular category: https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js#L75-L77
