### ISSUE TITLE
No products for query ""

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#673]
Suddenly all the categories started showing No products for query "" - http://joxi.net/MAj9LQqUJoK62e

F12 - XHR and Console doesn't show any errors ... Eventhough magento and algolia dashboard have products there. 

Could it be connected to the fact, that we are using same account on staging and live (but indexing works only on live)

**Comment by sandrinecrozat** [comment]
+1

**Comment by Mobecls** [comment]
I have seen a similar issue, when category was renamed (and mapping of new category didn't work with products, until you reindex_  - but we didn't rename category.

**Comment by JanPetr** [comment]
Hey @Mobecls @sandrinecrozat,

would you have a website where I could see that live? Thanks!

**Comment by Mobecls** [comment]
Just have sent to an email.

**Comment by JanPetr** [comment]
@Mobecls, thanks for the email. You are querying `magento_staging_default_products` products, but this index is empty. You have to index data even on staging environment to make it work. Or use the same index prefix, but that will mess up your data. So it's not recommended.

**Comment by Mobecls** [comment]
Oh, i see, sorry. Than it's probably not related to the initial issue. Initially - we had that happened on live, but then I disabled algolia via admin area, and enabled in 5 minutes and it worked fine....

As for the staging - I had an idea to reindex everything on live, but test on staging. 

P.S.. I have changed now prefix to magento_ - but that didn't help...

**Comment by JanPetr** [comment]
I can see it works now, probably just cache issue? 
So I'm closing the issue.

**Comment by Mobecls** [comment]
It worked when I disabled/enabled extension, but we still didn't get the reason and where not able to fix that and make sure that it won't happen again. Do you have any advice for the future cases like that?
