### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by vstepanyuk** [algolia/algoliasearch-magento#675]
In [Observer.php](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Observer.php#L207):
`$collection = $this->product_helper->getProductCollectionQuery($storeId, $productIds, $useTmpIndex);
`

`$useTmpIndex` variable is passing to `getProductCollectionQuery` method as `only_visible` parameter.

`public function getProductCollectionQuery($storeId, $productIds = null, $only_visible = true, $withoutData = false)`

**Comment by JanPetr** [comment]
Hey @vstepanyuk,
that's correct. Because only visible products are indexed into tmp products. So when `$useTmpIndex` is true, so is `$only_visible` and vice versa.

But I admit it's not the best naming here.

**Comment by vstepanyuk** [comment]
Hey @JanPetr, thx for answer)
