### ISSUE TITLE
auto complete search show all products on the page not as dropdown 

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#677]
I need to make my auto complete search update all the content of the page like This  http://us.lancaster.com/
and return the products as a category page 
How can i handle this ?
Thanks in Advance

**Comment by JanPetr** [comment]
You can disable autocomplete feature and enable instant search feature.
It'll do the trick :)

<img width="612" alt="screenshot 2016-11-22 17 18 57" src="https://cloud.githubusercontent.com/assets/1058144/20562539/5f4de158-b184-11e6-8002-164c49ad935c.png">
