### ISSUE TITLE
Add product colors available below your display in the catalog.

### ISSUE THREAD

**Issue by dudusotero** [algolia/algoliasearch-magento#680]
Hello!
Does anyone have any idea how I can display the available colors of a particular product in your catalog view?
I have this data in the product:
![algolia](https://cloud.githubusercontent.com/assets/7073199/20597790/dce47d5e-b22c-11e6-9a25-9aba1780993c.PNG)
Is there any way to make the variables present in the color facet appear in the product listed in hit.phtml?

Thanks for the support.

**Comment by JanPetr** [comment]
Hello @dudusotero,

if you have set `color` as retrievable attribute it will be present as variable in `hit.phtml` template out of box.

**Comment by dudusotero** [comment]
Thanks @JanPetr,
I have solved this problem. I've created a way to display the color and size while the results.hits are displayed. When I have more time I can better detail the way it was done.

**Comment by JanPetr** [comment]
Thanks for information @dudusotero, happy you made it work!

**Comment by hungthanhtran** [comment]
Hello @JanPetr, you said "set color as retrievable attribute it will be present as variable in hit.phtml template out of box."

How I can set color as retrievable attribute, can you give me some details? I also want to show some attributes in hit.phtml, can I do this way? Thank you.

**Comment by JanPetr** [comment]
Hey, I'm not sure if I understand your question. What do you mean by "calculate retrievable attributes"? Can you describe your use-case?
Feel free to open a new issue for that.

**Comment by hungthanhtran** [comment]
Hey @JanPetr, thank for answer me . For example, I have 2 prices:
{{price<?php echo $price_key; ?>_formated}}
{{price<?php echo $price_key; ?>_original_formated}}

Now I want to make a subtraction of that. Do you know how to do it?

**Comment by JanPetr** [comment]
For that you can use `trasformData` parameter of `hits` widget. There you can transform data of the single hit, add new attributes to a hit etc. Here's the documentation of the widget: https://community.algolia.com/instantsearch.js/documentation/#hits
