### ISSUE TITLE
Native support for AW_Blog

### ISSUE THREAD

**Issue by dimitri-koenig** [algolia/algoliasearch-magento#682]
Hi guys

Thank you so much for this amazing module, and especially your continuous effort to improve it. You definittly set an example for many other developers.

May I suggest one feature: native AW_Blog support.
Out of the box this module supports products, categories and pages. AW_Blog is installed on many magento stores and thus a native support would be a huge benefit.

Is this something that could make it onto your dev roadmap?

Thx
Best
Dimitri

**Comment by JanPetr** [comment]
Hello @dimitri-koenig,

thank you for the kind words.

Integration of the extension with other popular Magento modules/extensions is definitely something we want to explore more and AW_Blog might be a hot candidate for this.

I'll keep the issue open and I will keep you posted when we start working on this.

Thanks for your suggestion and if you decide to explore or integrate it on your own, you are more than welcome to send a PR for the integration 💯

**Comment by tomekjordan** [comment]
Hi. Personally I don't see any reason to integrate AW Blog. Its very old and basic plugin Maybe 5 years ago somebody used it. Its not a good solution for blogging comparing to Wordpress (AW Blog slow downs Magento, and is really oldschool plugin. If somebody like to integrate AW Blog for searching it may be done just like any other native CMS pages are crawled by Algolia.

**Comment by JanPetr** [comment]
Hello @dimitri-koenig and @tomekjordan for your inputs. In the end we decided not to integrate AW_Blog to the extension for the reasons @tomekjordan mentioned. I believe you understand.
