### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#683]
My company is rolling out PHP 7 at the moment. We don't see any immediate incompatibilities, but trying to install the module using the `mage` tool that comes with Magento, the following error is encountered:

    Package community/algoliasearch 1.7.2: requires PHP version  >= 5.3.0 and <= 6.0.0  current is: 7.0.13-1~dotdeb+8.1

Would be great if you could state if you support PHP 7 or not, and if you can update the PHP requirement if so.

**Comment by JanPetr** [comment]
Hello @aude,
sorry for the late answer.

The extension supports PHP 7, but requirements are wrong. It'll be fixed in the very next release.
For now you can install it with force installation: `./mage install community algoliasearch —force`
