### ISSUE TITLE
Custom search weighting per product

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#684]
I'm wondering if there's an easy way to introduce some negative/positive ranking on a per product basis. Here's our use case:

- Customer searches for 'Treadmill'
- First result is 'Treadmill Lubricant'
- This result is not desirable, but I suppose Algolia picks this first since all of our actual treadmills have the word 'Treadmill' later in the title (2nd or 3rd word).

How can I add a negative weighting to the 'Treadmill Lubricant' product so that it doesn't show up first?

**Comment by JanPetr** [comment]
Hello @greatwitenorth,

I guess the best thing for you is to set `name` attribute as unordered so the order of words is not taken into account and all products with `Treadmill` in title will be considered as equals and your custom ranking will be applied. So the more business relevant products will be ranked higher.

Let me know if it helped you.

**Comment by greatwitenorth** [comment]
It looks like it already is set to 'Unordered'. So I'm wondering if the total sales is skewing the results. It'd be really nice if there was some way of demoting items on a per product basis.

**Comment by greatwitenorth** [comment]
I'm wondering if it'd be possbile for me to add a custom attribute, then assign a negative value to that and tell Algolia to take that attribute into account when searching. Does that sound like it would work?

**Comment by JanPetr** [comment]
Yes, that'd work for sure.

**Comment by greatwitenorth** [comment]
In case anyone needs a step by step this worked for me:

1. Navigate to any of your product's edit screen in the Magento admin, and under the 'General' tab click **Create new attribute**:
![new attribute](https://cloud.githubusercontent.com/assets/547583/20717938/c59fc074-b61c-11e6-806b-5c65b2062fd5.png)

2. Create a new attribute called ```search_ranking``` with the following settings:
![create attribute](https://cloud.githubusercontent.com/assets/547583/20717969/e3bae8a4-b61c-11e6-8f38-01730e0ccb82.png)

3. Navigate to the product's **General** tab which you wish to change the ranking and enter a negative value (-10 worked for my purposes):
![product search ranking](https://cloud.githubusercontent.com/assets/547583/20718068/2edce4ea-b61d-11e6-84c5-cf417391c184.png)

4. Under **System -> Configutation -> Algolia Search -> Products** add the new attribute to the Attribute panel with the following settings:
![attributes](https://cloud.githubusercontent.com/assets/547583/20718141/64f3014a-b61d-11e6-8721-97ac7074248d.png)

5. Click save, then just below that panel add the new attribute to the **Ranking** panel as well:
![ranking](https://cloud.githubusercontent.com/assets/547583/20718180/83398372-b61d-11e6-93b3-f2bb01c458f3.png)

6. Trigger a re-index on the Algolia Product search index. You may need to wait a bit if your system queues these jobs.

**Comment by JanPetr** [comment]
Thanks for step-by-step tutorial @greatwitenorth 🎉 
One thing to change though - `search_ranking` attribute should be set as first in ranking otherwise it will work only for products which have the same `ordered_qty`.

Great job besides that! 💯

**Comment by greatwitenorth** [comment]
Thanks for the tip. I've updated the steps to reflect that change.

**Comment by greatwitenorth** [comment]
@JanPetr Once I implemented the change, and put search_ranking on top, it looks like Treadmill Lubricant came back up to the top. What would be the reason for this?

**Comment by greatwitenorth** [comment]
ok never mind, looks like once the full index ran again, then it fixed itself.

**Comment by greatwitenorth** [comment]
Is there a way to get algolia to explain it's search results? I've carried out this exact process on our production environment and now it's not working. In the algolia dashboard, and our website, treadmill lubricant is now showing at the top again when searching for treadmill (despite the negative ranking). I'm finding it very hard to determine why Algolia is returning specific results.

**Comment by greatwitenorth** [comment]
Just wondering if there's any word on this or a way to contact algolia support about this (I cannot find any contact info on their site)?

**Comment by JanPetr** [comment]
Hey @greatwitenorth,
sorry for the late answer.

You can see in [Algolia explorer](https://www.algolia.com/explorer) why the products are ranked the way they are ranked. There is ranking info next to each record showing you the reason why it's happening.
Do you have all data and the search ranking indexed?

**Comment by greatwitenorth** [comment]
@JanPetr This is now not working either on our stating environment. Algolia does give some very basic ranking information, and the top result is showing the -10 custom ranking that I gave to it. But obviously simply attributing a negative number (despite selecting 'desc' order) does not help drop it's ranking. With Algolia's search algorithm being a bit of a black box, it makes it nearly impossible for me to determine how I can effect the rankings. Is there someone at Algolia we can talk to about this? I cannot find any contact information on the site (we are paying customers).
