### ISSUE TITLE
Reindexing not getting all products

### ISSUE THREAD

**Issue by andreww3** [algolia/algoliasearch-magento#685]
Reindexing Algolia Search Products from the admin panel seems to be unstable. Sometimes no update jobs are added to the queue, sometimes not all of them. What could be the reason for that? And also, when reindexing the products, should all that add all of them to the queue or does it work in a different way (before the queue gets to be executed) ?

**Comment by JanPetr** [comment]
Hello @andreww3,

might the issue be a time or memory limit? When you have that many products so time/memory limit is reached and executed script is killed and not all jobs are created in a queue?
When reindexing products from Magento administration the extension fetches the number of products and creates so many reindexing jobs as needed for reindexation of the whole catalog. That's it. Than queue is executed and processes the jobs one by one.

**Comment by JanPetr** [comment]
Hello @andreww3,
since I didn't hear from you I'm closing the issue.

If you'll have more information or if you need more help, feel free to reopen.
