### ISSUE TITLE
After some time, the catalog images are replaced by empty placeholders

### ISSUE THREAD

**Issue by dudusotero** [algolia/algoliasearch-magento#686]
Hello!
I'm using Algolia 1.7.1 in my store. After reindexing the products all the images of the catalog appear normally, but after some time, the images begin to be replaced by empty placeholders. To solve this it is necessary to reindex the catalog again (I am having to do it every 1 hour). By doing this, I am reaching the limit of my plan.
Does Algolia have some timeout for the images? Or would this be a bug?
Has anyone gone through, or is it in a similar situation?

Thanks for the support!

**Comment by JanPetr** [comment]
Hello @dudusotero,

the Algolia indexes paths of cached images. So when you delete your cached images the paths become invalid and wrong images / placeholders are shown.
Can you make sure you don't flush your image cache?

Documentation on images: https://community.algolia.com/magento/faq/#why-are-images-not-showing-up

**Comment by dudusotero** [comment]
Thanks @JanPetr 
The cache has not been cleared. The images disappear, without any interaction, they begin to disappear one by one as time passes, and come back when the indexing of algolia_search_indexer is performed.

**Comment by JanPetr** [comment]
It's weird. Can you try to investigate in [Image.php](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Image.php) if the images are correctly generated? And can you check your logs? There might be issues with generating images - memory, GD library, timeout, etc...

Thanks!

**Comment by JanPetr** [comment]
Hello @dudusotero, 
since I didn't hear from you I'm closing the issue.

If you'll have more information or if you need more help, feel free to reopen.

**Comment by dudusotero** [comment]
Sorry for the delay. I discovered how to reproduce the problem, when a product reaches 0 in stock its image in the catalog is replaced by an empty placeholder. To fix this it is necessary to reindex the Algolia catalog again, but this is not the best way. Is there any way around this?

Thanks for the support!
