### ISSUE TITLE
Disable the fulltext search index when everything from Algolia is enabled?

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#687]
The `catalog_category_product` index is useless when all functionalities from the Algolia module for Magento are enabled. Maybe it's an idea to disable it?

**Comment by JanPetr** [comment]
Hello @royduin,
sorry for the late answer, I completely missed the issue /o\

I'm not sure what you mean. `catalog_category_product` is one of Magento's default indexers, why/how would you want to disable it? You just don't have to use it, no?

**Comment by royduin** [comment]
Sorry, me bad. I meant the `catalogsearch_fulltext` index. It's indeed a default index but it's only used for the search. This one stays automatically up-to-date when it's on "real time", we've set it on "manual" which improves speed a bit. But with imports etc and when users like to reindex everything from the backend this one will be reindexed too which is useless because it's not used when all functionalities from Algolia are enabled.

It's just a suggestion; maybe it's a good idea to disable that index completely.

**Comment by JanPetr** [comment]
Hey @royduin,
that makes sense and as an option it might be useful for some customers.
However I did a small research and didn't find a way on how to disable non-Algolia indexer completely. The only thing is to put this indexer to manual mode. What should be enough for this use case.
Or do you have an idea on how to disable it?

**Comment by royduin** [comment]
It's possible to remove a index with XML, but then it will be removed when the module is installed which isn't what we want (in case a user only wants to use the autocomplete, not the instantsearch for example). Another option is to override the index class as suggested here: http://magento.stackexchange.com/questions/39946/can-i-completely-disable-an-indexer. From there we can check a module config and just not run it, with this option the indexer is still visible.

**Comment by JanPetr** [comment]
Closing the issue - duplicate to #769
