### ISSUE TITLE
Refine Toggle on iphone

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#697]
this code is working fine on browser and android devices but it doesn't work and collapse on Iphone it
Any help please ?

$('body').on('click', '#refine-toggle', function () {
$('#instant-search-facets-container').toggleClass('hidden-sm').toggleClass('hidden-xs');
	if ($(this).html()[0] === '+')
	$(this).html('- ' + algoliaConfig.translations.refine);
	else
	$(this).html('+ ' + algoliaConfig.translations.refine);
});

**Comment by JanPetr** [comment]
Hello @rehamwael,
I'm afraid it's not related to the extension.
What exactly does not work? Classes are not toggled on iPhone?

I'd suggest you to ask this kind of question on [StackOverflow](http://stackoverflow.com/) for example.
