### ISSUE TITLE
Incorrect Product Price Rendering

### ISSUE THREAD

**Issue by annapivniak** [algolia/algoliasearch-magento#699]
<img width="695" alt="screen shot 2016-12-11 at 21 56 34" src="https://cloud.githubusercontent.com/assets/2251002/21083254/cbe7de92-bfec-11e6-9a6c-5def5e379adb.png">

as you can see in the attached screenshot, if the price includes html code it doesn't render.
Expected result:
if price contains html code it should be rendered or at least there should be a possibility to specify this behaviour in configuration.

**Comment by JanPetr** [comment]
Hello @annapivniak, 
I'm not sure we want to add support for HTML code in price directly to the extension. It's definitely not the common use case. What is the reason for you for having HTML code in price?

To render it correctly you'll need to update [product's template](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/autocomplete/product.phtml#L40-L50). Just change the double curly brackets to triple curly brackets.
But be aware that it might cause a security issue, so do it only in case you are 100% sure there won't be any harmful HTML code.
And I'd suggest you removing HTML code from price and adding it directly to templates without having to change double curly brackets to triple ones.
