### ISSUE TITLE
An error occurred while saving this configuration: You cannot specify "attributesToIndex" and "searchableAttributes" at the same time. "attributesToIndex" is deprecated you should only use "searchableAttributes"

### ISSUE THREAD

**Issue by willtran** [algolia/algoliasearch-magento#700]
/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php needs to be updated to use searchableAttributes instead of attributesToIndex

Currently the module only uses attributesToIndex, but app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php:mergeSettings will fetch searchableAttributes from Algolia settings and try to merge them together. This results in the final API request object containing both attributesToIndex and searchableAttributes.

**Comment by maxiloc** [comment]
@willtran I don't manage to reproduce your issue.
Right now the extension only get and set attributesToIndex but not searchableAttributes.

Did you did update the settings outside of magento (via a script, via the dashboard, ...) ?

If you are able to, deleting all indices and launching a full reindex should fix your issue.

I'll keep the issue open as we still want to move to the new naming

**Comment by pixelastic** [comment]
Seems like we are pushing the old `attributesToIndex` here: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L265

But we are also fetching and merging whatever is in the current index settings through `getSettings`, and the current Algolia dashboard does push `searchableAttributes`.

It results in a `setSettings` sending both and getting rejected.

What we should do instead is push a key of the same name of what is already defined in `getSettings` (or revert to `searchableAttributes` if nothing is defined).

**Comment by pixelastic** [comment]
That's true, but as we have `searchableAttributes` all over our documentation, this will happen more and more often. Especially when we'll start putting `searchableAttribute` as a default in the dashboard (I checked, it's not the case yet).

What we need to do here is only pushing the key that was already defined in the `getSettings`, or revert to `searchableAttributes` if nothing was defined.

**Comment by JanPetr** [comment]
Thanks for the report and discussion guys. It's indeed a nasty bug and it's not easy to solve when it occurs.
I fixed it in #708. I'll be happy if you could review or try it our (especially @willtran) 👍

**Comment by JanPetr** [comment]
Will be part of 1.8.0
