### ISSUE TITLE
Ability to hide the Categories from autocomplete menu

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#701]
From what I understand from [that line](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/autocomplete.js#L30) you cannot remove the display of categories.

I think we should have the same logic than for queries -> if 0, then it's hidden.

**Comment by JanPetr** [comment]
Will be part of the next release. Currently it's part of 1.8.0-RC
