### ISSUE TITLE
Default autocomplete menu behavior on mobile is not perfect

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-magento#703]
Using https://magento.algolia.com/, on iPhone. When using the autocomplete menu, if I want to hide the keyboard after typing "a" to see all results and scroll, it will hide all results.

Could we maybe on the mobile experience put `debug: true` on the autocomplete menu so that on mobile it does not disappears on blur?

It was also sent as feedback on algolia support and after trying it I thought that yes it could be better.

**Comment by JanPetr** [comment]
Thanks for reporting @vvo, fixed in #709. Will be happy if you can review before merge.

**Comment by JanPetr** [comment]
It's part of the [1.8.0 release](https://github.com/algolia/algoliasearch-magento/releases/tag/1.8.0)

**Comment by vvo** [comment]
NICE

**Comment by rayrutjes** [comment]
@vvo we should probably detect mobile in autocomplete and handle this out of the box by default, is there a reason this would not apply @JanPetr ?

**Comment by vvo** [comment]
@rayrutjes Yes good idea
