### ISSUE TITLE
Hide categories from facets

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#706]
Hi, 

is there a way we could hide some categories from facets filters? 
The thing is that facets have only 1 general attribute "categories" - http://joxi.net/52aZPblCRDOVA0

And we would like to skip some specific categories, like "featured prdoucts" - http://i.imgur.com/xM1VYCM.png

is that possible?

**Comment by JanPetr** [comment]
Hello @Mobecls,
by default the extension displays only categories which are set to be "Included in Menu". So if the category has set "Included in Menu" to "No", it won't be displayed in categories widget.
To configure this behaviour you can use "Show categories that are not included in the navigation menu" setting:
<img width="836" alt="screenshot 2016-12-26 09 33 29" src="https://cloud.githubusercontent.com/assets/1058144/21478728/6ed62c32-cb4e-11e6-9b86-9d519a85dc9e.png">

But if you want to keep "Featured products" category included in menu you will need to write some custom code. You can hook your code to [algolia_subproducts_index](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L949-L952) event and there remove those specific categories from product's data. So those categories won't be indexed within the product and they won't be displayed in categories widget.

Here is a guide on how to hook your custom code to the extension's events: https://community.algolia.com/magento/doc/m1/customize-backend/

**Comment by Mobecls** [comment]
Hello @JanPetr 

thanks for your comment. 
Let me clarify please: 

1. if "show categories that are not included in the navigation menu" is set to "yes" - Algolia will reindex and show all the enabled categories, am I right? 
2. if the setting is set to "No", algolia will reindex and show on website only those categories, that have "include in menu" set to "yes"? 

The thing is that we have some categories, like Weekly Deal, which is not included in menu and can be accessible via email link only. 

If I set to No - "show categories that are not included in the navigation menu" - than this category won't be indexed at all and when users visit that category they will see empty category. Am I right?

**Comment by JanPetr** [comment]
Hey @Mobecls,

yes, you are completely right. If you set it to "No", those categories will be shown as empty.

**Comment by Mobecls** [comment]
@JanPetr  But what if I would like to make category live, but not show it in menu?

**Comment by JanPetr** [comment]
I'm afraid there is no such a solution now :(

**Comment by Mobecls** [comment]
I see. I suppose, that for us it would be easier to set it to Yes, and than hide not necessary categories in filters area. Do you have an advice for that?
