### ISSUE TITLE
Enable Search set to No, indexes doesn't work

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#707]
If you set Enable Search setting to No, you would expect, that search would be disabled, but you will be able to run indexes (according to "_If set to No, search will be done by Magento but indexing will be done by Algolia_")

But when I did that, i got a message, that indexes are disabled for all stores... 
[ALGOLIA] INDEXING IS DISABLED FOR 1
[ALGOLIA] INDEXING IS DISABLED FOR 4
[ALGOLIA] INDEXING IS DISABLED FOR 3
Algolia Search Categories index was rebuilt successfully

So I have to enable search to make indexes work?!

**Comment by Mobecls** [comment]
seemed to be server cache

**Comment by JanPetr** [comment]
Hello @Mobecls,
I'm glad you make it work!
