### ISSUE TITLE
Why not all categories are shown in facets? 

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#711]
Hi @JanPetr 

in most of our categories we can see subcategories as facets - http://i.imgur.com/TIJ14Ph.jpg - but for some reasone, almost half of the categories are not shown. 

How does the system decides, what categories to show, and what categories to skip? We have "Show categories that are not included in the navigation menu" set to Yes. And those categories are enabled and has products there. They are also indexed and I can see them in Algolia and they have Products count...

**Comment by JanPetr** [comment]
Hello @Mobecls,
the widget you're seeing is tree widget. So only categories from top level are shown. If you click to any category, you will see it's subcategories.

Or do you mean that there is even less top categories shown? In that case, can you provide me with a live website where I can investigate?

**Comment by Mobecls** [comment]
Hi @JanPetr 

sent details via email

**Comment by JanPetr** [comment]
​I found the issue. It's because those categories are not returned from Algolia because of maxValuesPerFacet limit is reached.
​You can increase the limit by putting a bigger number here:
<img width="552" alt="screenshot 2017-01-03 12 34 10" src="https://cloud.githubusercontent.com/assets/1058144/21606644/2532446c-d1b1-11e6-80d4-aacf6fd1e16b.png">

This will affect all other facet filters. If you want to change the value only for categories, you will have to do it directly in the code here:
​https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js#L273
​
​Let me know if it helped you.

**Comment by Mobecls** [comment]
But that value - is this a product amount? or amount of values in facet?

**Comment by JanPetr** [comment]
Amount of values in facet

**Comment by Mobecls** [comment]
got it, thanks.

**Comment by Mobecls** [comment]
@JanPetr and does 10 include the children subcategories? 

Becauase we had value set to 10, but in the category there were 3 subcategories shown (not even 5..., which is less than 10)

**Comment by JanPetr** [comment]
Yes, it's including subcategories. There might be fetched categories which are relevant to shown products but which are not relevant to displayed tree. That's why you can see only 3 (because the others don't belong to the tree).

**Comment by Mobecls** [comment]
@JanPetr could you, please, provide an example? as I am not sure that I understand you well.

**Comment by JanPetr** [comment]
ok, let's say one of the fetched products has categories:
```json
level0: ["Cars", "Brands"]
level1:	["Cars /// Super Cars", "Brands /// BMW"]
level2:	["Cars /// Super Cars /// Fast Cars"]
```
as you can see, the product has 5 categories.

But you're browsing "Cars" category tree, so only "Super Cars" is displayed in the left menu, but all 5 categories are fetched from Algolia. And it's filling the limit of values per facet, do you understand?

**Comment by Mobecls** [comment]
@JanPetr 

So the value of that setting - is not the value for the 1 specific category, but it is the value for the whole store? 

I mean, taking into account, that in your example Cars have only 1 subcategory (Super Cars) - that is expected, that only 1 would be shown. 

In that case - do we have to set the value for the setting to maximum amount of our categories? (we have 2500 categories)? 

Or should we check the maximum value of subcategories in 1 category and set it? 
For example - we have Category "brands", it has 100 subcategories and each subcategory has approximately 5 subcategories. So do we have to set the value of the setting to 500?
