### ISSUE TITLE
Provide unminified and separate javascript files from algoliaBundle.min.js

### ISSUE THREAD

**Issue by Inwerpsel** [algolia/algoliasearch-magento#717]
This would make it possible to leave out large parts of it if these are already available (e.g. jQuery, which is present in many themes) which would be very helpful in reducing the 600kb+ javascript size.

**Comment by rayrutjes** [comment]
Hi @Inwerpsel ,

For now we actually bundle every JavaScript dependency of the extension so that we ensure we do not run into any kind of JavaScript conflicts.

You are right that it adds some overhead, but this was a compromise we were ready to take in the past to ensure it works everywhere, regardless of the availability of other libs.

I hope that makes sense.

**Comment by Inwerpsel** [comment]
Hi Ray,

I understand that it is important to provide a solution that works out of the box, but for people that really care about their website's performance and are willing and able to do the custom coding required for it, it would be really helpful if the option was there, with the default being the bundled file.

The demo site for this extension has only about 350KB of js in total, including Magento js. Some of which isn't even minified. So surely it is possible and very helpful to cut a great deal out of the bundle.

**Comment by rayrutjes** [comment]
We are on the same page @Inwerpsel ,

For now, the best I can offer is you manually generate the bundle by excluding jQuery from it: https://github.com/algolia/algoliasearch-extensions-bundle

Let me know if that would work for you.

**Comment by robmorgan** [comment]
I'm in the same boat as @Inwerpsel. A ~600K bundle on an ecommerce site isn't going to win me any brownie points. I'm going to have a play with https://github.com/algolia/algoliasearch-extensions-bundle. @Inwerpsel did you have any luck?

**Comment by Inwerpsel** [comment]
Hi @rayrutjes and @robmorgan ,

I've been working on other things over the last month but will probably have a go at slicing away some js sometime in the next couple of weeks. I'll let you know how it goes.

**Comment by robmorgan** [comment]
@Inwerpsel I might have a play as well.

**Comment by HRR1337** [comment]
Does anyone have luck regarding creating the AlgoliaBundle.min.js WITHOUT jquery? Thanks!

**Comment by robmorgan** [comment]
@HRR1337 I gave up and moved on to other things. Best of luck!

**Comment by HRR1337** [comment]
Going to try if I can fix that

**Comment by HRR1337** [comment]
I'm sorry but I really dont know how to work with this. Tryed installing nodejs (on windows).. but this is a bit above my expertise.
