### ISSUE TITLE
Facet Indexes level0 categories when only level 1 requested

### ISSUE THREAD

**Issue by erikshosting** [algolia/algoliasearch-magento#719]
I have configured only the product name and category.level1 to be indexed via the config panel.
When indexing I see that level0 and level1 both are added to the indice. Am I mis-understanding something?
![product indexing](https://cloud.githubusercontent.com/assets/6295678/21728843/2239e4a6-d3fd-11e6-8f52-92065fdf12d8.JPG)
![index capture](https://cloud.githubusercontent.com/assets/6295678/21728880/5b186112-d3fd-11e6-8600-7acd582c8c99.JPG)

**Comment by JanPetr** [comment]
Hello @erikshosting,
yes, when you add one of `categories...` to attributes to index, the whole tree is getting indexed. Is that a problem? Why do you want to index only `level1`?

**Comment by erikshosting** [comment]
It's not a problem, I just was curious if that was as it was designed to work.
We are using organizational categories and indexing level1 would exclude the organization directories at level0. I've found a way around this by setting level0 dirs to not visible in nav, and indexing categories_without_path instead.

Why are their options to add specific levels to index if it indexes all? I think I'm just not understanding the difference between selecting 'categories' and 'categories.level1' in that option set. But, it's not stopping me from doing what I need. So this is a non issue, feel free to close it

**Comment by JanPetr** [comment]
The `level` options are there to be able to select which level you want to use as searchable attribute. So it always index the whole tree, but by selecting only `level1` you can specify, that you want only `level1` to be searchable instead of the whole tree.

I'm closing the issue now, but if you have any further questions, feel free to ask.

**Comment by erikshosting** [comment]
Awesome, thanks for the explanation.
