### ISSUE TITLE
Handle hitsperpage changing event

### ISSUE THREAD

**Issue by hungthanhtran** [algolia/algoliasearch-magento#737]
Hi all, 
In Instant search result page, I want to CSS limiter select options (it's in #hits-per-page-selector). But the select option can't be layout so I made a new limiter, and link to the old one. Now when I change the new one, the old one also change.

But there're one problem, Json string don't return and the page also not render hits per page again.

Can anyone help me to resolve this problem. I'm very appreciate.

**Comment by JanPetr** [comment]
Hello @hungthanhtran,
sorry for the late answer. To be honest I'm not sure I understand the issue. Would you mind sharing a live website where I could see and investigate the issue?

Thanks!

**Comment by JanPetr** [comment]
As I don't have any feedback, I'm closing the issue. Feel free to reopen @hungthanhtran.

**Comment by hungthanhtran** [comment]
Thanks mate.

2017-02-17 22:15 GMT+07:00 Jan Petr <notifications@github.com>:
