### ISSUE TITLE
CSS Merge issues with SVG data

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#739]
For example this line: https://github.com/algolia/algoliasearch-magento/blob/master/skin/frontend/base/default/algoliasearch/algoliasearch.css#L718 cause issues when CSS merging is enabled in Magento. That's because there is a bug in Magento (still in version 1.9.3.1), see: http://magento.stackexchange.com/questions/14973/problem-with-data-uris-and-css-file-merge

If Magento knows this I'm sure it's a low priority for them so maybe we can create a workaround in the module for this?

**Comment by JanPetr** [comment]
Thanks for the report @royduin,
definitely something we'll target. I'll keep you posted.

**Comment by royduin** [comment]
For the time being I've created a module to fix the bug: https://github.com/just-better/magento1-css-merge-data-uri-fix

**Comment by LukyVj** [comment]
I can definitely create a workaround for that!

**Comment by JanPetr** [comment]
Fixed, will be part of the next release.
Thanks for bringing it up @royduin ❤️  💯
