### ISSUE TITLE
When a product get deleted from magento, it does not remove the algolia record

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#74]

**Comment by maxiloc** [comment]
Was working but only when the queue was activated

**Comment by maximilianmikus** [comment]
We have issues with this in our shop, if products get deleted, or disabled they are not removed from the index.

**Comment by maximilianmikus** [comment]
Could this be related to:

`$result = $process->getMode() !== Mage_Index_Model_Process::MODE_MANUAL;`

if manual mode is enabled the event is not registered?

**Comment by maxiloc** [comment]
Which version of the extension are you using ?

**Comment by maximilianmikus** [comment]
1.5.3

**Comment by maximilianmikus** [comment]
just tested this, seems to work now that I enabled `update on save` for indices.

**Comment by maxiloc** [comment]
Yes indeed. Usually what we recommend is having update on save + the queue enable to process those job asynchronously (https://community.algolia.com/magento/documentation/#indexing-queue-enabled)
