### ISSUE TITLE
Adding banners to the catalog according to the selected category

### ISSUE THREAD

**Issue by dudusotero** [algolia/algoliasearch-magento#741]
Hello!

Does anyone have any tips or ideas for adding banners according to the category selected in Algolia?
I would like to add banners under the search bar according to their category (Female, Male, Child). I thought about adding the banners according to the URL, but if my category has the changed name it would already break the code :(

Thanks for the support.

**Comment by JanPetr** [comment]
Hey @dudusotero,
how about base the banner on the category ID which you can get from the [`current_category` registry](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml#L51)?

**Comment by dudusotero** [comment]
To make the catalog more dynamic, I replace the menu links at the top of the page with the Algolia category filter links, without having to use the Magento catalog any time you switch categories, using only Algolia and being very fast.
Since I can not access the category page, it is not possible to load which category I am and what your image is.

Example: https://www.useliverpool.com.br/

**Comment by JanPetr** [comment]
Oh I see. Nicely fast solution! 👍  However I'm afraid you'll have to rely on the category name to display right banner.
Algolia is based on textual values (names, ...) and not on IDs, so in this case I can't see any other solution now.

**Comment by dudusotero** [comment]
Thanks @JanPetr!

I'll keep looking for some way to present the banners.
I was thinking to make clicking on the category, get the name, put it in lowercase and concatenate in some way with the url of the image. 
Something like this: "`/media/catalog/category/{{categoryName}}.png`"

Any ideas on how to get this category name?

Thanks for your support!

**Comment by JanPetr** [comment]
Hello @dudusotero,

I'm super sorry for the late answer.
How about rendering those banners in `render` event of the instant search and do something like that?

```js
search.on('render', function() {
	console.log(search.helper.state.hierarchicalFacets[0].rootPath);
        // render banner based on the rootPath
});
```

**Comment by JanPetr** [comment]
I'm closing the issue now as it's stale for a while. Feel free to reopen.
