### ISSUE TITLE
Slow mobile device typing

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#744]
I'm not sure, if there is anything you can do, but if instant search is enabled, when you search site on mobile the letters don't show up till well after you finish typing. So it's kind of slow laggy typing....

Have you met this before and is there anything we can do about that?

**Comment by JanPetr** [comment]
Hello @Mobecls,

thanks for the report. Can you specify which mobile phone with which browser do you use? Thanks!

**Comment by Mobecls** [comment]
Android, Google Chrome.
iPhone 6, safari.

Just try to type-delete-type and you will see the lags.

**Comment by JanPetr** [comment]
Hello @Mobecls, we didn't manage to reproduce the issue. Isn't it related only to your phone / website?

**Comment by Mobecls** [comment]
That's what happens - https://drive.google.com/open?id=0B1cCPhTwji9KUGNUajJzZFg4d1k

**Comment by JanPetr** [comment]
I don't have permission to access it @Mobecls

**Comment by Mobecls** [comment]
sorry, here is the new link: https://drive.google.com/file/d/0B1cCPhTwji9KUGNUajJzZFg4d1k/view?usp=sharing

**Comment by Mobecls** [comment]
@JanPetr  do you have access now?
