### ISSUE TITLE
Clean install on Magento2 (Using Ultimo Theme)

### ISSUE THREAD

**Issue by hyesungs** [algolia/algoliasearch-magento#747]
Hi there, 

Just installed Algolia on Magento2. Added the credentials and api keys. However the search bar on homepage has gone and cannot be seen. 

The only error I can find in the browser console is this below:

![image](https://cloud.githubusercontent.com/assets/25263158/22580083/cca2fca8-ea18-11e6-989f-06e841760f9e.png)

Unfortunately I am not very techy and don't understand what it means. Please can someone advise on how to fix.

Many thanks, Paul

**Comment by JanPetr** [comment]
Hello @hyesungs,

I'm super sorry for the late answer.
We introduced fix for our Magento 2 extension to work with Ultimo theme. Feel free to update the extension via composer to `dev-master` and change your search box selector to `#search`. That'll do the trick.

**Comment by hyesungs** [comment]
Is the search selector in here?

-----------------------------------------------------------------------------

<?php
// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div id="header-search" class="skip-content skip-content--style">
    <div class="search-wrapper block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified
*/ echo __('Search'); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form"
action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>"
method="get">
                <div class="field search">
                    <?php /* <label class="label" for="search"
data-role="minisearch-label">
                        <span><?php echo __('Search'); ?></span>
                    </label> */ ?>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?php /* @escapeNotVerified */
echo $block->getUrl('search/ajax/suggest', ['_secure' =>
$block->getRequest()->isSecure()]); ?>",

"destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo
$helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo
$helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */
echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */
echo $helper->getMaxQueryLength();?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete"
class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo
$block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo
__('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div> 
</div>

**Comment by JanPetr** [comment]
Yes, it is. It's `#search`
