### ISSUE TITLE
Index catalogsearch_query to autocomplete on past queries

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#75]

**Comment by colinmollenhour** [comment]
This should definitely be optional. The catalogsearch_query table gets full of so many junk queries that using it to suggest queries in my experience is quite useless. Perhaps if it was much more selective in which queries it returned it would be ok, but with such small search volume it is still too easy for individuals to influence the results. Also you get junk appearing from bots and security scanners. Companies with massive search volume can make this work but IMO it is not worth doing on most eCommerce sites.

**Comment by redox** [comment]
Thanks for the feedback @colinmollenhour, very appreciated. Yes it will be optional. Do you think filtering on the associated `popularity` column (is that the frequency?) with a customizable threshold would be enough?

**Comment by colinmollenhour** [comment]
Yes, popularity is the number of submitted searches for the given query. I'd recommend both a minimum popularity and a maximum number of results being configurable.
