### ISSUE TITLE
Composer install, search not showing up

### ISSUE THREAD

**Issue by jlaustill** [algolia/algoliasearch-magento#750]
Today I installed this plugin with composer require algolia/algoliasearch-magento and it showed up in the back end no problem.  Added our keys, did the indexing and tried to test it out.  The problem is that when enabled it makes the default search box disappear, but nothing replaced it.  It just made our site have NO search at all.  

I'm not allowed to install via magento connect, but I can't find any documentation on installing with composer.  Can anyone point me to some?  I would love to get this installed.

I'm using Magento 1.14.2 and the rwd theme.

**Comment by JanPetr** [comment]
Hello @jlaustill,

I don't think it's installation issue, more probably it's the extension's compatibility with your theme.
Can you navigate to the Algolia settings in Magento and in Advanced tab change the search bar selector to the one of your default search bar?
Then the extension won't try to replace your default search bar, but it'll you the default one and search should work.

**Comment by jlaustill** [comment]
This was an install issue for sure.  I reverted back to my head commit, and installed with modman and now it is working fine.  This is a pita for me though as I don't have the ability to install modman on my servers.  So When I move from dev to qa and prod I am going to have to manually clone the modman repo's under /.modman/xxxx.  That being said, it is at least working.

**Comment by JanPetr** [comment]
Thanks for the explanation @jlaustill,
I will investigate and come back to you.

**Comment by JanPetr** [comment]
Hello @jlaustill,
I just checked the Composer installation and the extension was installed correctly.
I tried on multiple Magento versions (1.8, 1.9.2, 1.9.3) and all templates and files were installed correctly.

Do you think it'd be possible for you to have a live website where I could investigate the missing search bar?
Or can you check whether all the frontend templates are installed to correct locations and loaded on Magento load?

Thanks!
