### ISSUE TITLE
Google Analytics at algoliaBundle.js

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#751]
There is an article - https://community.algolia.com/instantsearch.js/documentation/#analytics-1 - saying that there is an Analytics Widget to algolia. And there is an example of the code. But the code is in  instantsearch.js - which is not used by algolia in magento. 

As I understand, magento uses algoliaBundle.js. And current version of that lib doesn't have any Analytics widget. 

We can add instantsearch.js to the page and add Analytics there, but we would have to keep old one as well, and it would be additional 0.5MB for the page. 

So the question is - do you plan to add analytics to algoliaBundle.js?

**Comment by JanPetr** [comment]
Hello @Mobecls,

yes, this is a plan. We will update algoliaBundle.js so it'll contain the latest version of instantsearch.js with analytics widget.

btw the analytics widget itself doesn't contain GA code. That code needs to be included to website by you.

**Comment by Mobecls** [comment]
Yes, we understand, Thanks. And do you know, when it will be done?

**Comment by JanPetr** [comment]
I cannot promise any date, but I'd like to work on it next week.

**Comment by Mobecls** [comment]
ok, thanks.

**Comment by JanPetr** [comment]
It's been implemented in #754, will be part of the next release.
