### ISSUE TITLE
Catalog Search Index should not be required.

### ISSUE THREAD

**Issue by colinmollenhour** [algolia/algoliasearch-magento#76]
I haven't kept up with the latest development, but the previous version did not require that the Catalog Search Index be indexed when using Algolia as a complete replacement. We run stores with this indexer disabled because the index is never needed and just slows down product saves, creates deadlocks, etc. So, if this is indeed still the case you should update the README instructions and screenshots and if it is not I would advise fixing it so that this is once again not necessary to keep this index in operation when using Algolia.

**Comment by maxiloc** [comment]
I haven't modified such thing, so we should be good :)
