### ISSUE TITLE
Category pages not updating

### ISSUE THREAD

**Issue by jlaustill** [algolia/algoliasearch-magento#766]
Hello,

We went live with the Magento Algolia plugin this week, and the search is working fantastic.  However the plugin seems to be causing our magento categories to not rebuild.  We have the settings to replace the search page, but NOT the category pages.  

[North40 sale example](https://north40.com/sale16)

This page is an example, this is a direct category but non of the products are getting added to it when we reindex.  If we disable algolia, it works fine.  I'm wondering if we have a setting wrong, or if it's just not supported to replace the search page and not the category pages?

I'm stumped on what to debug next, so any help/advice/direction at all would be great!

Thanks,
Joshua

**Comment by vvo** [comment]
Hi @jlaustill right now I can only recommend you double checking your installation follows our documentation and indexing sections: https://community.algolia.com/magento/doc/m1/indexing/.

As soon as @JanPetr is available he will be able to better help you out.

Let us know how it goes.

**Comment by JanPetr** [comment]
Hello @jlaustill,

thanks for the report.
From what I can see on your store, your config is correct. I tried various categories and all are loaded via Magento. Algolia doesn't play any role there and products are fetched directly from Magento.

But I couldn't find the category "Sale" in your menu. Is the category supposed to be included in menu? If not, that's the reason why the category is not assigned to any products in Algolia. By default, Algolia assigns only categories which should be included in menu. To change it, you switch "Show categories that are not included in the navigation menu" to "Yes":
![screenshot 2017-02-22 10 03 55](https://cloud.githubusercontent.com/assets/1058144/23204288/4020d188-f8e6-11e6-847c-bfc08eabcbfd.png)

Let me know if it works for you.

**Comment by jlaustill** [comment]
I don't think I explained very well :)  The sales are loading to our algolia indexes just fine, and show up in the search properly.

What is breaking is the "normal" standard magento category pages.  I think we've made the decision that we are just going to have to turn alogolia off :(

**Comment by JanPetr** [comment]
Hey @jlaustill,
when you have "Replace categories" disabled Algolia doesn't have any impact on the category pages. It's Magento loading those products there without Algolia.
I cannot explain why the products are not showing up there with Algolia enabled :-/

**Comment by jlaustill** [comment]
Here's an update.  We have been unable to duplicate this issue on a local install running only nginx, MySQL, redis, and php-fpm.  

The server we are having this issue on uses nginx reverse proxied to apache which then uses php 5.5.  This is a much more complicated setup than the purely nginx setup.  So we are starting to suspect that this is an issue related to either the setup or the older version of php.  

I'll update if anything new presents itself.

**Comment by JanPetr** [comment]
Thanks for the update @jlaustill, I'll be looking forward to more information from you.

**Comment by jlaustill** [comment]
Another update, we have determined that if we enable the instant search page AND the replace category pages options, everything seems to work fine, fingers crossed.  So we are hopefully going to go live with that setup with a bit more testing.  So to recap,

instant search off, category pages off = no issue
instant search on, category pages off = issue
instant search on, category pages on = no issue

This is however ONLY on our server, not our local installs, and I have dug into that quite a bit today as well.  I've discovered that our host has a different version of PHP running on our prod site than they do on our dev/stage sites.  They are also using nginx 1.11.1 which isn't even in the ubuntu repo's yet so they compiled it from source, which could be a cause of who knows how many issues.  So I'm really starting to think that this isn't an issue with your code at all.  I think your code is just using something in PHP that is bringing out an issue in the configuration of our server.

**Comment by JanPetr** [comment]
Thank you for the detailed info @jlaustill 💯 

It's really not expected as the extension doesn't run any special PHP code on category pages. There is not even any backend query sent Algolia. When you have enabled "Replace category pages", it's only front end's JavaScript which re-renders the page when it's loaded in a browser.

I'll close the issue now, but I'm really interested in your further investigation. If you'll find the real cause, I'd really appreciate if you could share it. Thanks!

**Comment by jlaustill** [comment]
I think closing is appropriate.  I have found so many other issues in debugging this I can't even remotely say I think this is an issue with your code anymore.
