### ISSUE TITLE
Magento Infinite Scroll

### ISSUE THREAD

**Issue by dmytro-butko** [algolia/algoliasearch-magento#767]
https://community.algolia.com/demo-infinite-scroll/

hi there,

  This is mostly a question, sorry if it is not a right place for it...
  But is it possible to enable infinite scroll in Magento extension?
  And if not, are there any plans for this functionality?

thanks in advance,

**Comment by JanPetr** [comment]
Hello @dmytro-butko,

the extension doesn't support infinite scroll out of the box. We plan to add it (#556), but don't have any ETA for this feature so far.

What you can do is to implement it on your own by modifying [instantsearch.js file](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js) and replace the `hits` widget by the widget from the [Infinite scroll guide](https://www.algolia.com/doc/guides/search/infinite-scroll/).
