### ISSUE TITLE
Re-indexing Search Categories & Search Pages showing "Error : 404" in Magento

### ISSUE THREAD

**Issue by wdhrudra** [algolia/algoliasearch-magento#768]
Hi,

I am using Magento 1.9.3.2 and i installed Algolia Search. However, while i was trying to re-indexing, "Algolia Search Category" and "Algolia Search Pages" showing me 'Error : 404'.

Is this a bug? or my Magento version issue? 

How can I fix this issue?

Thanks,

**Comment by JanPetr** [comment]
Hello @wdhrudra,

no, the extension is compatible with 1.9.3.2 version of Magento.
Can you see any error message besides "404"? Can you check your error logs in Magento is there is any Algolia-related error logged?

**Comment by JanPetr** [comment]
Hello @wdhrudra,

since I didn't hear from you back, I'm closing the issue. If you still have issues, feel free to reopen it.
