### ISSUE TITLE
Reindex all is running the Algolia index twice

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#769]
We've got a custom product import running which performs a reindex all at the end. Because Algolia also performs a reindex on the `catalogsearch_fulltext` index everything is running twice.

Related issue: https://github.com/algolia/algoliasearch-magento/issues/687

**Comment by JanPetr** [comment]
Hello @royduin,

I just tested to reindex with `$ php shell/indexer.php -- -reindex catalogsearch_fulltext` and the reindex was triggered only once.

Can you provide me with more information like version of the extension, version of the Magento and steps how to reproduce? Thank you!

**Comment by royduin** [comment]
That's true, but when you run reindex all with `php shell/indexer.php --reindexall` it's reindexing twice because `catalogsearch_fulltext` and `algolia_search_indexer` are running the same.

**Comment by JanPetr** [comment]
Thanks @royduin for that.

I investigated a bit and realized the extension actually already overrides the `catalogsearch_fulltext` indexer. Not the indexer itself, but [the resource model behind it](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php).

When you take a look, the original indexer "just" matches events and then [call `rebuildIndex()` and `updateCategoryIndex()` methods](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/CatalogSearch/Model/Indexer/Fulltext.php#L363-L461) of it's resource model.

Would it work for you when I'd add a new advanced configuration directive, where you could say, that you don't want to process `rebuildIndex()` and `updateCategoryIndex()` methods, so it'd return `false` on its' very beginning?

**Comment by JanPetr** [comment]
So we don't have to rewrite the indexer, and use only the rewritten resource model which is already present.

**Comment by royduin** [comment]
Maybe it's easier to remove the `algolia_search_indexer` index because `catalogsearch_fulltext` is doing the same?

**Comment by JanPetr** [comment]
I wouldn't go that way because of backward compatibility and it gives us possibilities to edit the index as we need.

**Comment by damcou** [comment]
Added to the features list in our roadmap.
