### ISSUE TITLE
missing clearfix class

### ISSUE THREAD

**Issue by jlaustill** [algolia/algoliasearch-magento#771]
`<div class="clearfix"></div>`

This snippet appears in the wrapper.phtml file, but I don't see it defined anywhere in the algoliasearch.css file.  I'm assuming this is to cover the height of the floated elements above it, and it is probably a dependency on bootstrap?  Our site, however, doesn't contain bootstrap at all, so it's not formatting perfectly.  

I'd recommend(assuming I'm correct and not missing something, which is always possible) that the documentation either reflects a dependency on bootstrap, or the class be renamed algolia-clearfix and defined in the included css.

**Comment by JanPetr** [comment]
Great catch @jlaustill,
I made a fix in #772. Feel free to give it a try.

**Comment by jlaustill** [comment]
Wow, that was fast!  I actually did basically the exact same thing and copy and pasted the bootstrap classes into our custom AlgloliaSearch.less file and it made everything work great.  Your fix is exactly the same thing almost, so I'll test it on my next sprint for sure!  

In the meantime, I see the pull request so I think you can go ahead and close then when you see fit.  Thanks!

**Comment by JanPetr** [comment]
Thanks for the feedback. PR was merged, I'm closing the issue. The fix will be part of the next release
