### ISSUE TITLE
Is there an option to set different default sorting for Catalog and SERP? 

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#773]
Hello @JanPetr 

is there a way we could set different sorting for Catalog and Search Results page (in admin area or via code)?

**Comment by JanPetr** [comment]
Hello @Mobecls,

you can do it by creating other Algolia replice indices with custom sorting strategies and then during the search you can target the index with your custom sorting strategy.
More information about different sorting strategies here: https://www.algolia.com/doc/guides/relevance/sorting/#guides

You can define replica indices directly via Algolia configuration in Magento:
![screenshot 2017-02-27 11 03 09](https://cloud.githubusercontent.com/assets/1058144/23357022/5b67842e-fcdc-11e6-8e05-9df87bda6aa1.png)

But this will affect offered sorts on instant search page.

**Comment by Mobecls** [comment]
Hi @JanPetr 

not sure what do you mean by - create other Algolia Replice indices...
In admin area we do have several attributes to sort: http://i.imgur.com/3EdNVFN.jpg

And then - do you mean, that we have to create new index for Search Results Page and somehow use there another Attribute as default for sorting?
