### ISSUE TITLE
Unable to edit query at search results page

### ISSUE THREAD

**Issue by aude** [algolia/algoliasearch-magento#774]
When at the search results page, editing the search query is buggy. It seems the cursor is moved to the end of the input field at each key press.

## How to reproduce

1. Go to https://magento.algolia.com/catalogsearch/result/?q=shirt.
2. Click the search field.
3. Go to the start of the field, with your mouse or _Home_ button.
4. Try to write a word.

**Comment by JanPetr** [comment]
Hello @aude,

indeed. Thank you for the report. We will address it soon.

**Comment by JanPetr** [comment]
So I investigated and realized it's instantsearch.js issue. Reported here: https://github.com/algolia/instantsearch.js/issues/2012

**Comment by JanPetr** [comment]
It's been merged to `develop` branch and will be a part of the next release. Closing the issue now.
