### ISSUE TITLE
Multistore & multicurrency ranking Price issue

### ISSUE THREAD

**Issue by imso077** [algolia/algoliasearch-magento#776]
If we have a a multistore setup, and each store have different base currency is used on the sorting (When price is a sorting attribute) is simply wrong, as it just get the allowed currency code, not the base currency code for that particular store. (It could use a currency code what is not even indexed, and thats stops the sorting function working.)

You can solve this by changing these: then on sorting attributes tab it will show the correct price attribute like: price.SEK.default, or price.EUR.default dependent from what is the store base currency.

`--- www/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php	(revision 41ecd12be3d0cea2f3ee33e1088d672fe48def55)
+++ www/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php	(revision )
@@ -234,6 +234,8 @@
         /** @var Mage_Directory_Model_Currency $directoryCurrency */
         $directoryCurrency = Mage::getModel('directory/currency');
         $currencies = $directoryCurrency->getConfigAllowCurrencies();
+        $store= Mage::getModel('core/store')->load($storeId);
+        $baseCurrencyCode = $store->getBaseCurrencyCode();
 
         foreach ($facets as $facet) {
             if ($facet['attribute'] === 'price') {
@@ -340,7 +342,7 @@
                             $mergeSettings);
                     }
                 } else {
-                    $sort_attribute = $values['attribute'] === 'price' ? $values['attribute'].'.'.$currencies[0].'.'.'default' : $values['attribute'];
+                    $sort_attribute = $values['attribute'] === 'price' ? $values['attribute'].'.'.$baseCurrencyCode.'.'.'default' : $values['attribute'];
 
                     $mergeSettings['ranking'] = array(
                         $values['sort'].'('.$sort_attribute.')',`

**Comment by JanPetr** [comment]
Hello @imso077,

thanks for the report, great catch!
Would you be able to send a PR with the fix? I'd really appreciate, thank you.

**Comment by imso077** [comment]
Sure, I can. Will send it later today.

**Comment by JanPetr** [comment]
Thanks, I'm looking forward

**Comment by imso077** [comment]
Sorry @JanPetr  looks like I don't have permission to create Pull requests, or push?

**Comment by JanPetr** [comment]
Yes, you don't. You need to [fork the repository](https://help.github.com/articles/working-with-forks/), push the change to your forked repository and [create a pull request from there](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

Would that work for you?

**Comment by imso077** [comment]
Ok, done it now.

**Comment by JanPetr** [comment]
Will be part of the next release.
Thanks for bringing it up @imso077 💯
