### ISSUE TITLE
Clearing IS search input doesn't refresh the page and URL

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento#781]
When only IS is enabled, clicking on the cross in the search input clear the query but should even clear the IS page and reset the URL.

**Comment by tintutech** [comment]
Hi,

Use the following code

var search = instantsearch(/* ... */);

// bind any event with jQuery then call:
search.helper.setQuery('').search();
This should clear the query and refresh results. Thanks.

Credit to @vvo

**Comment by JanPetr** [comment]
Hey @tintutech,
thanks for the advice. I handled it a bit differently, but in the end it works the same - see #784 

The only issue is that it's not possible to "clear" URL, but results are cleared OK.

**Comment by JanPetr** [comment]
Will be part of the next release
