### ISSUE TITLE
Why old magento code is in source of the page? 

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#785]
Hi, i have noticed, that old magento code is still in the source-code of the page. 
Is this done specifically in order to let Search Bots see all the urls and the page?

**Comment by JanPetr** [comment]
What you mean by "old" Magento code? The code generated by Magento on the backend with products etc.?
Yes, this is on purpose so search engines can see products, links, the whole page ...

**Comment by Mobecls** [comment]
@JanPetr and is it possible to delete Layered Navigation from the source code? We don't want Google to index it, so we would like to delete it, also to save some page load timing. 

But would it lead to any issues with algolia?

**Comment by JanPetr** [comment]
No, when you delete it it shouldn't lead to any issue with Algolia.
But you'll have to delete / remove it from your code, I don't know what renders the layered navigation there.
