### ISSUE TITLE
Product listing description disappeared

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#788]
@JanPetr after our latest update - non of our categories have description.

Though, in sourcecode we can see that magento's part has that block... Why could that happen?

**Comment by Mobecls** [comment]
it affects our seo, so this is kind of importaint issue

**Comment by Mobecls** [comment]
@JanPetr we have tried to make a dirty-fix and get the catalog description via script, but in that case Instant-Search on CMS pages stop working...

**Comment by JanPetr** [comment]
Hello @Mobecls,
there shouldn't be any changes to instant search script which would end up in not-displaying the description.
Do you have live website where I could see the issue live?

**Comment by Mobecls** [comment]
Hello @JanPetr it seems, that this issue was connected to our template, we also deployed some fixes and it changed template, based on some settings in admin area.

**Comment by JanPetr** [comment]
OK, thanks for letting me know 👍
