### ISSUE TITLE
"strpos() expects parameter 1 to be string, array given"

### ISSUE THREAD

**Issue by GLips** [algolia/algoliasearch-magento#79]
Running into an issue updating categories where the built in Magento model function `dataHasChangedFor` is being called with an array as an argument. See the code from [line 361 of the Algolia Indexer](https://github.com/algolia/algoliasearch-magento/blob/2b0abd8738c8b300191baf50deecbe21e24ba0f3/code/Model/Indexer/Algolia.php#L361) below
```
foreach (Mage::helper('algoliasearch')->getCategoryAdditionalAttributes($category->getStoreId()) as $attribute) {
    if ($category->dataHasChangedFor($attribute)) {
        $rebuildIndex = TRUE;
        break;
    }
}
```
We can see that `$attribute` must be an array based off the code for `getCategoryAdditionalAttributes` [on  line 1135 of the algoliasearch helper](https://github.com/algolia/algoliasearch-magento/blob/2b0abd8738c8b300191baf50deecbe21e24ba0f3/code/Helper/Data.php#L1135)
```
public function getCategoryAdditionalAttributes($storeId = NULL)
{
    $attrs = unserialize(Mage::getStoreConfig(self::XML_PATH_CATEGORY_ATTRIBUTES, $storeId));
    if (is_array($attrs))
        return $attrs;
    return array();
}
```
Presumably we should be checking the returned array's `attribute` field. Example data from the `$attrs` variable in the above code:
```
Array
(
    [attribute] => name
    [searchable] => 1
    [order] => ordered
)
```

**Comment by maxiloc** [comment]
@GLips thanks for reporting this issue, should be good now
