### ISSUE TITLE
Error on loading instant search page

### ISSUE THREAD

**Issue by aschrammel** [algolia/algoliasearch-magento#799]
Hi everyone,

I'm facing the problem, when hitting enter in the autocomplete search **as long as there are any suggestions**, I receive an JS error on loading the instant search results page.
At the moment the autocomplete search returns that there are no results found, the instant search results load correctly and I'm also able to refine the search/perform a search on other terms in the searchbox on the instant results page without any issues.

I've already found out, that the problem is loading the template that is done in this line (`instantsearch.js: 28`)

    var wrapperTemplate = algoliaBundle.Hogan.compile($('#instant_wrapper_template').html());

![image](https://cloud.githubusercontent.com/assets/1203434/24284283/d4c45a3a-106a-11e7-903a-a4091f247533.png)

As long as the autocomplete search returns any results, `$('#instant_wrapper_template').html()` is undefined. From the moment on the autocomplete search has no results the correct content contained in `$('#instant_wrapper_template').html()` (defined in `algoliasearch-magento/app/design/frontend/base/default/template/algoliasearch/instantsearch/wrapper.phtml` is loaded.

I'm not sure if I'm missing something, but I hope that someone of you can help me.

**Comment by JanPetr** [comment]
Hello @aschrammel,
very sorry for the late answer. I completely missed the issue.
Would it be possible to give me an access to a live website where I could experience the issue?

It looks like the `algoliasearch-magento/app/design/frontend/base/default/template/algoliasearch/instantsearch/wrapper.phtml` template is not loaded to the page, but it should be always present. No matter if you get any results from Algolia.

**Comment by aschrammel** [comment]
Hello @JanPetr,
thanks for your reply.
Unfortunately at the moment there's no live website I can show you.

The template is present in the `app/design/frontend/base/default/template/algoliasearch/instantsearch/` folder as it should.
Do you have any idea what the reason could be, that it isn't loaded, as long as I get any result from Algolia?
This behaviour occurs every time a search URL is loaded that returns an result from Algolia.
As described above - searching a term that doesn't deliver a match loads the page and refining the search afterwards on the result page works.

**Comment by JanPetr** [comment]
Hello @aschrammel,

can you check that tbe block `before_body_end` is rendered on the page when there are no results? Maybe there's something in Magento preventing that block to render on no results and therefore the template is not rendered correctly.

**Comment by JanPetr** [comment]
Hello @aschrammel,
since I didn't hear from you for a while I'm closing the issue.
Feel free to reopen if your problem persists.
