### ISSUE TITLE
How disable Algolia for store or website?

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#800]
Hello! 

We manage several websites by magento. And for one of them we want to use default magento search. For that we disabled Algolia in admin panel for website. But default magento search not working. If we completly disable Algolia, default magento search start working. It seems like default search somewhere blocked by Algolia.

How we can solve this problem?  (we use Algolia 1.8.1 now)

**Comment by Mobecls** [comment]
Can somebody help with this problem?

**Comment by julienbourdeau** [comment]
Hi @Mobecls,

Can you upgrade the the latest version? I believe this pull request fixed the issue: https://github.com/algolia/algoliasearch-magento/pull/793

**Comment by JanPetr** [comment]
Hello @Mobecls,
did you manage to solve your issue?
I'm closing the issue, feel free to reopen if you still experience problems.
