### ISSUE TITLE
css abs path

### ISSUE THREAD

**Issue by dmytro-butko** [algolia/algoliasearch-magento#801]
app/code/community/Algolia/Algoliasearch/etc/system.xml

lines:
```css
 background: url("/skin/frontend/base/default/algoliasearch/algolia-admin-menu.svg") !important;
 background: white url("/skin/frontend/base/default/algoliasearch/algolia-admin-menu.svg") !important;
```
should be
```css
 background: url("skin/frontend/base/default/algoliasearch/algolia-admin-menu.svg") !important;
 background: white url("skin/frontend/base/default/algoliasearch/algolia-admin-menu.svg") !important;
```

**Comment by julienbourdeau** [comment]
Hi @dmytro-butko,

Can you describe the problem you are trying to fix? You don't get the logo displayed?

On my store, I only get it with `/` so can you give us more details about your configuration and which error you get if you look at the _network_ tab of your dev tools?

**Comment by julienbourdeau** [comment]
Is the error you're talking about is related to https://github.com/algolia/algoliasearch-magento/issues/739 ?

If it's not, please let me know and I will reopen this issue. :)
