### ISSUE TITLE
how to use this with a custom theme ?

### ISSUE THREAD

**Issue by wdhrudra** [algolia/algoliasearch-magento#802]
Hi,

The Algolia search is working perfectly with Magento RWD and RWD child themes. But my webstore is using Meigee "Universal" theme. And now Algolia Search is not working in my case.

**Setup taken action in my case** : 
**1**. the theme have the search input class name "form-control". I changed the Algolia "Search input DOM Selector" to ".form-control"

**Issues :** 
**1**. Algolia Search output generating blocks (i can see through browser inspection tool), but its not displaying in frontend.
**2**. The search-box dropdown also showing the magento default autocomplete suggestion with a list.

Now, If any one can help me how to modify this to work with my store.

website dev URL :: https://goo.gl/9jcj0J

Please let me know how to fix this and what is the issue.

Regards.

**Comment by JanPetr** [comment]
Hello @wdhrudra,

sorry for the late answer.
As you says, the autocomplete works but it's not visible - it's under your theme. What you need to do is to write your custom CSS to override default extension's CSS.
In your custom CSS you can specify/override different properties like `z-index` to make your autocomplete dropdown menu visible and nice.
