### ISSUE TITLE
Facets Refine by Changing the URL

### ISSUE THREAD

**Issue by alaabadran** [algolia/algoliasearch-magento#804]
I wonder if there is a URL schema that i can follow to build filtering URLs using product attributes.
For example:
**Women products**
`Gender = women `
**Women Products with Color pink**
`Gender = women & color = pink`
**Women Products with Attribute2 val2**
`Gender = women & attribute2 = val2`
Can anyone explain how to quickly build URLs from attributes?
Thanks

**Comment by JanPetr** [comment]
Hello @alaabadran,

the best way to figure it out is to go here https://magento.algolia.com/catalogsearch/result/?q=shirt and try to add some filters. You'll see how the URL changes and you'll be able to find out what to add to the URL for your specific attributes and its values.
