### ISSUE TITLE
How to add optionalWords "a, for, and" for all search requests

### ISSUE THREAD

**Issue by hungthanhtran** [algolia/algoliasearch-magento#809]
In Magento Algolia extension, is that exists a way that I can add those optionalWords? Can you tell me how to do that? Thank so much.

**Comment by JanPetr** [comment]
Hello @hungthanhtran,

you can find documentation of optionalWords here: https://www.algolia.com/doc/api-client/php/parameters/optionalWords/#optionalwords
If you want to set it once (for all search queries), you can do it via Extra settings textarea in the latest version (1.9.0) of the extension.

If you want to specify different optionalWords for each query, you'll have to tweak the frontend of the extension.
