### ISSUE TITLE
Algolia is not running on my stores, Index status is "Running" for several days now

### ISSUE THREAD

**Issue by MDowdal** [algolia/algoliasearch-magento#81]
I'm not sure really about what happened.  It was all working fine until early last week, and the credentials are accurate.  Is there a way I can troubleshoot this?

**Comment by MDowdal** [comment]
I can see successful POSTS when typing in queries but am not seeing any actual autocomplete happening.

**Comment by MDowdal** [comment]
Reindexing Algolia_SearchIndex results in the response:

object(PDOStatement)#1135 (1) {
  ["queryString"] => string(51) "UPDATE `catalogsearch_query` SET `is_processed` = ?"
}

**Comment by maxiloc** [comment]
First thing you can do, is check if you are at the last version (we release 1.1.4 yesterday). It might resolve your issue

**Comment by MDowdal** [comment]
Indexing issue was fixed but Algolia is still not showing results on my page.  Is there a good way to uninstall or reinstall?  Should I delete the indices and create new ones?  This is getting to be troublesome.  



I can see the following POSTS:


POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
5.1 KB
	
207.244.79.8:80
	
 
61ms
POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
4.8 KB
	
207.244.79.8:80
	
 
59ms
POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
5.2 KB
	
207.244.79.8:80
	
 
62ms
POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
4.9 KB
	
207.244.79.8:80
	
 
59ms
POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
4.9 KB
	
207.244.79.8:80
	
 
59ms
POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
4.9 KB
	
207.244.79.8:80
	
 
62ms
POST queries
	
200 OK
	
1nu75u1ed7-3.algolia.io
	
4.2 KB
	
207.244.79.8:80

**Comment by maxiloc** [comment]
Can you send an email to "support at algolia dot com" so that we can help you better and do a live chat or a skype call is necessary.
