### ISSUE TITLE
The deleted product still appears in the Algolia index

### ISSUE THREAD

**Issue by annapivniak** [algolia/algoliasearch-magento#811]
After the product is deleted in Magento its Algolia index is never updated. It stays in Algolia until it is deleted manually. 

Thank you for your support.

**Comment by JanPetr** [comment]
Hello @annapivniak,

what version of the extension do you use?
Do you have enabled the indexing queue?

**Comment by annapivniak** [comment]
Hi @JanPetr 
Thank you for the immediate answer. 
We use the Algolia Search 1.8.1, and I`ve just noticed that the 1.9.0 is released. Is it fixed there? 
I was testing it with the indexing queue and without. Started full Magento reindex several times. The deleted products are always shown in the search. 

Is there anything else I can try?

**Comment by JanPetr** [comment]
There shouldn't be any change regarding indexing deleted products between 1.8.1 and 1.9.0 - it works OK in 1.8.1.
Can you try to enable indexing queue, reindex products and let the queue runner to process all the queue?
With this approach, all "active" products will be indexed into a temporary index and when it's finished, the temporary index is moved to production by trashing old production index with deleted products.

You can find more information about full reindexing in documentation: https://community.algolia.com/magento/doc/m1/indexing/

**Comment by JanPetr** [comment]
Hello @annapivniak,
did you manage to fix your issue?

**Comment by annapivniak** [comment]
hi @JanPetr 
yes, the issue is fixed
Thank you!
Sorry for late answer.
