### ISSUE TITLE
The magnifier icon for the search field disappears with the Merge Css Files setting

### ISSUE THREAD

**Issue by annapivniak** [algolia/algoliasearch-magento#812]
STR:
Go to System=>Configuration=>Advanced=>Developer. Select Css Settings. Set Merge Css Files to Yes. 

With this setting enabled the icon disappears. The URL for the magnifier is broken.

**Comment by JanPetr** [comment]
Hello @annapivniak,

thanks for report. It's duplicate issue to #739, so I'm closing this one.
If I missed something, feel free to reopen.
