### ISSUE TITLE
Weee is not indexed

### ISSUE THREAD

**Issue by trosyno** [algolia/algoliasearch-magento#813]
Hello,

Weee is not added to the price when products are indexed. Is there a fix for that?

Thank you

**Comment by JanPetr** [comment]
Hello @trosyno,
maybe a stupid question, but ... what is "Weeee"? Thanks!

**Comment by trosyno** [comment]
Hello,

Weee is "Waste Electrical and Electronic Equipment Directive", a tax in Europe for electronic products. The module that handles it is Mage_Weee

Here's how it works:
![weee1](https://cloud.githubusercontent.com/assets/8102461/25619414/12703300-2f4b-11e7-8e16-5a81355eb80b.jpg)
![weee2](https://cloud.githubusercontent.com/assets/8102461/25619473/4a48f6e0-2f4b-11e7-9a85-fc7edd6e46d4.jpg)
![weee3](https://cloud.githubusercontent.com/assets/8102461/25619554/9dd89b26-2f4b-11e7-96d7-af4f766c887c.jpg)

The 0.25 tax will be included in the product final price

**Comment by JanPetr** [comment]
Thanks for explanation. I will take a look and see what can be done.

**Comment by trosyno** [comment]
Thank you. Our need is quite urgent so we may get to do it before you do. If so, the method we need to alter is handlePrice in Algolia_Algoliasearch_Helper_Entity_Producthelper, right?

**Comment by JanPetr** [comment]
Hello @trosyno,

yes, you are completely right. If you'll manage to fix it, it'll be awesome if you could send a PR with the fix :) Thanks!

**Comment by JanPetr** [comment]
Implemented in #829, it'll be part of the next release.
