### ISSUE TITLE
An error occurred while saving this configuration: Invalid API key

### ISSUE THREAD

**Issue by rehamwael** [algolia/algoliasearch-magento#815]
Hi ,
We are using the extension on production with its own API key .
I have problem with free trial API on my local machine and testing servers 
its shows to me invalid API key ? why ?

<img width="1280" alt="screen shot 2017-05-02 at 3 35 41 pm" src="https://cloud.githubusercontent.com/assets/17198176/25617885/208a3786-2f4d-11e7-9621-6aa76fa87ae2.png">

**Comment by JanPetr** [comment]
Hello @rehamwael,
can you make sure you fill in the right and valid Admin API key and Search API key?
What you mean by "own API key"?

**Comment by rehamwael** [comment]
yes sure I copy and paste them 
actually we have an paid API for production alone .
but for testing I need to sign for free but it shows this error because I don't want to mixing the API's together .

thank you

**Comment by JanPetr** [comment]
It makes sense @rehamwael, but it looks like you're not pasting there a real Admin API key. Can you dive in a code and see if output of [this method](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Config.php#L359-L367) is your admin API key?

**Comment by rehamwael** [comment]
thank you @JanPetr The issue was on the API after Algolia upgrade , also I was copied the encrypted Admin API without decryption it .

thanks always for your support 👍 :)

**Comment by JanPetr** [comment]
It's nice to hear you made it work 🚀 
You're welcome, happy searching 💥
