### ISSUE TITLE
Including a search on the bottom of the page

### ISSUE THREAD

**Issue by davids101** [algolia/algoliasearch-magento#816]
What would be the easiest way to include the search anywhere else on the page? aka having it multiple places

**Comment by JanPetr** [comment]
Hello @davids101,

interesting question. How it'd behave? When you have a search bar on the bottom of the page and you start typing there, where would you display the results? Would you jump to the top? Would you move the search bar as well? Would you switch the content to top search bar?

**Comment by davids101** [comment]
it would be great if you just had a snippet of code where we could place it
anywhere and the search results are confined to a set size box, similar to
what you have on the algolia.com homepage

**Comment by JanPetr** [comment]
Hello @davids101,
sorry for the extra late answer, I completely missed this issue.
I'm worried the extension is not intended to do such a feature. And you'll have to write a custom front end to achieve that. Is that something you can do? Or did you already manage to make it work?

Let me know. I'm closing the issue now, but feel free to re-open.
