### ISSUE TITLE
Reindex fails with many products

### ISSUE THREAD

**Issue by SergioViteri** [algolia/algoliasearch-magento#823]
Hello,

When I make a fullstext_search reindex I get this error:
I get Exception: Item (Mage_Catalog_Model_Product) with the same id "10324" already exist in /var/www/shop/lib/Varien/Data/Collection.php:373

The most of the products are well indexed but not all of them. I tried the indexing queue and it works fine but I still don't get all the products indexed.

Any clue?

Thank you,
Sergio.

**Comment by JanPetr** [comment]
Hello @SergioViteri,

I'm sorry for the late answer. I investigated the issue, but I'm not able to reproduce. Everything works OK on my side.
I have just one idea - Can you try to add `$products = $products->distinct(true);` to https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L154

It should definitely avoid duplicates in the collection. Let me know how it goes. Thanks!

**Comment by SergioViteri** [comment]
Hi @JanPetr 

thank you for your answer but I'm afraid I keep getting the same error (full stack trace below). Any further ideas?

Sergio.

Catalog Search Index index process unknown error:
Exception: Item (Mage_Catalog_Model_Product) with the same id "10324" already exist in /var/www/shop/lib/Varien/Data/Collection.php:373
Stack trace:
#0 /var/www/shop/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(265): Varien_Data_Collection->addItem(Object(Mage_Catalog_Model_Product))
#1 /var/www/shop/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1056): Mage_Eav_Model_Entity_Collection_Abstract->addItem(Object(Mage_Catalog_Model_Product))
#2 /var/www/shop/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(871): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#3 /var/www/shop/app/code/community/Algolia/Algoliasearch/Helper/Data.php(541): Mage_Eav_Model_Entity_Collection_Abstract->load()
#4 /var/www/shop/app/code/community/Algolia/Algoliasearch/Model/Observer.php(213): Algolia_Algoliasearch_Helper_Data->rebuildStoreProductIndexPage('1', Object(Mage_Catalog_Model_Resource_Product_Collection), 91, '100', NULL, Array, false)
#5 /var/www/shop/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(45): Algolia_Algoliasearch_Model_Observer->rebuildProductIndex(Object(Varien_Object))
#6 /var/www/shop/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(309): Algolia_Algoliasearch_Model_Resource_Engine->addToQueue('algoliasearch/o...', 'rebuildProductI...', Array, '100')
#7 /var/www/shop/app/code/community/Algolia/Algoliasearch/Model/Resource/Engine.php(202): Algolia_Algoliasearch_Model_Resource_Engine->_rebuildProductIndex('1', Array, false)
#8 /var/www/shop/app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php(63): Algolia_Algoliasearch_Model_Resource_Engine->rebuildProducts(NULL)
#9 /var/www/shop/app/code/core/Mage/CatalogSearch/Model/Fulltext.php(84): Algolia_Algoliasearch_Model_Resource_Fulltext->rebuildIndex(NULL, NULL)
#10 /var/www/shop/app/code/core/Mage/CatalogSearch/Model/Indexer/Fulltext.php(455): Mage_CatalogSearch_Model_Fulltext->rebuildIndex()
#11 /var/www/shop/app/code/core/Mage/Index/Model/Process.php(212): Mage_CatalogSearch_Model_Indexer_Fulltext->reindexAll()
#12 /var/www/shop/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#13 /var/www/shop/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#14 /var/www/shop/shell/indexer.php(216): Mage_Shell_Compiler->run()
#15 {main}

**Comment by JanPetr** [comment]
Hello @SergioViteri,

unfortunately no ideas :( I'm not able to reproduce.
Does it happen when reindexing products with the indexing queue enabled or not?

**Comment by SergioViteri** [comment]
It thoughts the error when indexing with queue disabled. With queue enabled I don't see errors but the product in the error (id 10324) is not indexed.

**Comment by mattlooby22** [comment]
Hi @JanPetr 

The fix that you suggested above , adding the distinct to the collection query works for me ($products = $products->distinct(true);)

So is this fix going to be included in the next release of the Algolia module for Magento as I have had to amend this code myself and don't want to break the upgrade path

Regards

Matt

**Comment by JanPetr** [comment]
Thanks for the feedback @mattlooby22,
that's great to hear! I'll run some tests with it and if everything is OK, you can expect it to be in the next release.
