### ISSUE TITLE
New products are only indexed if full index is processed

### ISSUE THREAD

**Issue by eonlab** [algolia/algoliasearch-magento#824]
Hello,

I can' t index new products without running: 
EMPTY_QUEUE=1 /usr/bin/php7.1 -f /public_html/shell/indexer.php -- -reindex algolia_queue_runner

All other options, Re-Index on Magento admin or even using a cronjob job, do not work.

I also noticed that the new products show up in the categories but not in magento's search. And yes I have visibility, stock, and display on Catalog and Search setup correctly. After run the full index it shows on algolia and on magento search.

What am I doing wrong?

Thanks
LD

**Comment by JanPetr** [comment]
Solved via Algolia support

**Comment by PascalBrouwers** [comment]
Have the same issue, would be nice to know the answer.
