### ISSUE TITLE
Back button doesn't gets user back to the filtered category, but to all products instead

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#825]
We have a "_Global Search on Category Page_" setting set to Yes and we have a problem.

if you go to any subcategory: shoes/styles/juniors (https://goo.gl/CFSl0a) , select any filter, like "size = 5" - you will see the filtered by size products. That's correct. 

After that try to hit Back button at browser and you will be back to shoes/styles/juniors page, but instead of seeing the products from that subcategory you will see the whole catalog, eventhough URL is correct...

I would expect, that we will see products from shoes/style/juniors - and now all the products.

**Comment by drant-t** [comment]
Any news on this issue?

**Comment by JanPetr** [comment]
@Mobecls @drant-t I created a fix for that - #852. Could you give it a try and confirm that it works for you?

**Comment by Mobecls** [comment]
We will test it on next week, after extension update.

**Comment by JanPetr** [comment]
Thanks @Mobecls,
I'm looking forward to your feedback.

**Comment by JanPetr** [comment]
Fix will be part of the next release
