### ISSUE TITLE
What are the needed configurations to show facets (filters)?

### ISSUE THREAD

**Issue by alaabadran** [algolia/algoliasearch-magento#833]
Hello,

I have added some facets (from attributes), but i still can't see changes on Front End. Is there any kind of configuration or options to set to show facets?
Please note:
- I have these Attributes working.
- I did multiple re-indexing.
- I see the attributes on Algolia indices, in product information.

Looking forward for an answer, while i am confused about this.
Thank you

**Comment by JanPetr** [comment]
Hello @alaabadran,

you did everything right. Could you share with me a live website where I could see and investigate the issue?

Thanks!

**Comment by alaabadran** [comment]
I found a way to apply them.
The problem was: 
i set facets for specific store view. While i should work on Website level.
Once i set the facets for all, things worked fine as expected

**Comment by JanPetr** [comment]
👍 I'm happy you made it work. Happy searching!
