### ISSUE TITLE
Displaying price_with_tax on autocomplete menu

### ISSUE THREAD

**Issue by 87pancakes** [algolia/algoliasearch-magento#835]
I can't find an option to show the tax price in the autocomplete menu.

The price_with_tax is being indexed, there's just not an option to show it in the frontend, instead of the price without tax.

**Comment by JanPetr** [comment]
Hello @87pancakes,

the displayed price is depended on Tax -> Price Display Settings:
![screenshot 2017-05-22 11 29 17](https://cloud.githubusercontent.com/assets/1058144/26301612/00131a1e-3ee2-11e7-98b8-e15b333d1b98.png)

The extension respects the global settings of the store and displays the same price.

**Comment by 87pancakes** [comment]
I have updated these settings but it still isn't reflecting in the algolia frontend unfortunately.

See attached screenshots;

![configuration___system___magento_admin3](https://cloud.githubusercontent.com/assets/11280589/26305222/59c29540-3ee6-11e7-8b16-9c98ad63403c.jpg)
![megaman_14w_cfl_spiral_-_daylight_es_e27](https://cloud.githubusercontent.com/assets/11280589/26305221/59c10b94-3ee6-11e7-9484-8f5b8be1b9f2.jpg)
![megaman_14w_cfl_spiral_-_daylight_es_e272](https://cloud.githubusercontent.com/assets/11280589/26305223/59c94516-3ee6-11e7-8209-c1ccbd76b339.jpg)

**Comment by JanPetr** [comment]
When you change this settings, you need to reindex products. Can you do that?

**Comment by 87pancakes** [comment]
All fixed thank-you

**Comment by JanPetr** [comment]
No problem :) Happy you made it work! 👍  🚀
