### ISSUE TITLE
Error on saving configuration

### ISSUE THREAD

**Issue by 87pancakes** [algolia/algoliasearch-magento#836]
I'm receiving the following error when attempting to save the configuration;

`An error occurred while saving this configuration: Invalid ranking parameter: "()", you should use typo,geo,words,filters,proximity,attribute,exact,custom or asc(attribute),desc(attribute) near line:1 column:455`

Also, I'm unable to add additional attributes in the configuration panel; See attached screen shot.

![configuration___system___magento_admin](https://cloud.githubusercontent.com/assets/11280589/26304037/c8eb9958-3ee1-11e7-9719-17a66d52b312.jpg)

**Comment by JanPetr** [comment]
Hello @87pancakes,

thanks for the report. It's very weird, that this is happening. You should have select boxes there.
What version of Magento do you use please?

**Comment by 87pancakes** [comment]
We're using Magento version 1.8.1.0

**Comment by 87pancakes** [comment]
I've fixed this. The extensions output was disabled within the Advanced section of Magento.

Thank-you for your help.

**Comment by JanPetr** [comment]
Thank you for coming back to me!
I'm glad you sorted it out and everything works now 👍
