### ISSUE TITLE
Custom product type not being reindexed

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#841]
Our system contains a custom product type named 'Brochure'. When I edit a brochure product and click save, Algolia's magento module correctly send the item's information to Algolia's servers and I'm able to search for the product. But if I trigger a full reindex on the command line (php 0f indexer.php reindexall) and wait for the algolia queue to fully empty of jobs, all of my brochure products are removed from the index and become unsearchable.

Do I need to explicitly tell the Algolia module to index the custom product type? If so, how do I tell Algolia, and why does it work when I visit and individual item and click save?

I'm currently running magento 1.9.3.1 and algolia plugin 1.9.0.

**Comment by JanPetr** [comment]
Hello @greatwitenorth,

the logic behind indexing should be the very same for both single product indexing and full reindex.
I'll investigate and come back to you.

**Comment by greatwitenorth** [comment]
ok thanks. I wasn't sure if the issue was being caused by the fact that we have a custom product type.

**Comment by JanPetr** [comment]
Hello @greatwitenorth,

I'm sorry for coming back to you that late, but I finally found time to work on that.
Can I ask you - do you use any custom extension for creating a new product types in Magento?

**Comment by greatwitenorth** [comment]
The custom product type was initially created via a module we developed. It was created via the module's install script. Would this be part of the issue?

**Comment by damcou** [comment]
hi @greatwitenorth ,

Hi, I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
