### ISSUE TITLE
Is it possible to add product count to the price ranges widget?

### ISSUE THREAD

**Issue by Inwerpsel** [algolia/algoliasearch-magento#842]

**Comment by JanPetr** [comment]
Hello @Inwerpsel,

unfortunately it's not possible right now, this is the Algolia limitation for now.

**Comment by Inwerpsel** [comment]
Thanks for the quick answer.

Is this a feature that will be added? And, if so, do you know when?

I ask this because I might try a workaround with fixed ranges and then indexing these as attributes on the products.

And just out of curiosity: what is the reason for the limitation?
