### ISSUE TITLE
With this extension enabled on Magento 1x, it exponentially increases the time needed to save cataloginventory/stock_item

### ISSUE THREAD

**Issue by aliomattux** [algolia/algoliasearch-magento#843]
On a Magento instance before this extension installed it takes 3.5 minutes to update 1,000 products stock by this method I wrote,

$stockItem = Mage::getModel('cataloginventory/stock_item')->loadByProduct($productId);
$stockItem->addData($data);
$stockItem->save();

With Algolia search extension just installed, this takes more than 10 minutes.

It must be that this extension either forces load of a product in cataloginventory save, or it does some type of index action.

This causes serious performance problems when updating the stock directly.

This method is used via API connection, but currently we can not use it because this extension prevents it from working in a reasonable time frame

**Comment by JanPetr** [comment]
Hello @aliomattux,

the extension listens on event `catalog_product_save_before` which is triggered when you save the item. Each time it's saved the extension reindexes complete product to Algolia which causes the delay.
For you the way to go is to enable the indexing queue so the indexing operation is "only" queued in database and then processed by a queue runner. It should radically decrease the amount of time needed to update products.

More information about the queue you can find in documentation of the extension: https://community.algolia.com/magento/doc/m1/indexing/

**Comment by aliomattux** [comment]
I saw the observer definition in the config.xml, but i'm confused why that observer would fire when im saving stock item.

In my code, I do not load or save a product, only the stock item. This allows my update to perform very quickly, being able to do thousands of products in a very short time.

**Comment by JanPetr** [comment]
Hello @aliomattux,

I'm very sorry for the late answer.
We need to propagate the stock availability to Algolia in order to provide the best results.

Did you try to enable the queue? Did it help you to increase the performance?

**Comment by JanPetr** [comment]
Hello @aliomattux,

as I didn't hear from you for a while I'm closing the issue. If you still experience any issues or if you have more questions, feel free to re-open or open a new issue.
