### ISSUE TITLE
Grouped Products names?

### ISSUE THREAD

**Issue by bmartus** [algolia/algoliasearch-magento#844]
I see the associated products in a grouped product in the sku attribute as an array.  Is there any way to include the names of these associated products in the grouped products data, so that when searching for the name of one of the child products, the results will show the grouped product?

**Comment by JanPetr** [comment]
Hello @bmartus,

the extension doesn't do that out of the box. But it's something you can add to your product records by hooking your code to [algolia_after_create_product_object event](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L967) and there add a new attribute with array of names.

Is it doable for you?

**Comment by bmartus** [comment]
That should be doable.  I didn't even think to look for dispatched events.
I'll reopen if I run into any trouble.
Thanks!

**Comment by JanPetr** [comment]
You are welcome.
You can find the list of all custom events here: https://community.algolia.com/magento/doc/m1/backend/#custom-events
