### ISSUE TITLE
Would you help me?

### ISSUE THREAD

**Issue by fuxing8** [algolia/algoliasearch-magento#845]
Hello,

For example, I have this Magento 1.7 site using Algolia.

I have tried to customize instantsearch.js and custom.js in algolia module.
http://vaegteeksperten.dev.magepartner.net/live/akseltryk-vaegte.html#q=&idx=dev-livedk_products&p=0&is_v=1

Here, as you can see here, there are several facets.
However let's focus to the label is "MAXIMUM".
What I want to do, is the same as following.

When I click "60g" check box, product pages should show all products that have bigger attributes than "60g".
Of course, I have defined attributes with name "MAXIMUM" in admin.
And I have created tables with positive value corresponding weight.

Would you help me?

I need to solve this problem ASAP.

Kind Regards

**Comment by JanPetr** [comment]
Hello @fuxing8,

Your use case requires a little bit of custom coding, but it's definitely doable.
First of all, you will have to modify the records you index in Algolia to index your filter attributes like:

maximum_value: "100g|10",
maximum_pos: 10

It can be done by hooking your code to algolia_after_create_product_object custom event. There you can modify the array of record which is indexed to Algolia. And you'll need to set both attribute as attributesForFaceting.

Then you'll need to modify the frontend, especially instantsearch.js file.
The you need to use transform data and a custom template on the menu widget to split maximum_value's value on "|".
Display the label 100g and keep the position value as a data attribute for instance.

When a users clicks 100g, that might be the trickiest to customize, but then you needs to filter like so: maximum_pos>=10
So you'll get the correct facet labels, and using a numeric filter he can get everything that is greater than the clicked filter position.

Is that understandable? Let me know if you need more information.

Documentations of Magento extension or instantsearch.js you can find here:
- https://community.algolia.com/magento/doc/m1/getting-started/
- https://community.algolia.com/instantsearch.js/documentation/
