### ISSUE TITLE
Amp and algolia 

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#850]
Hi @JanPetr, 

Do you have any customers using algolia along with amp?

**Comment by JanPetr** [comment]
Hello @Mobecls,

not that I'm aware of. Did you give it a try?

**Comment by Mobecls** [comment]
we will, i'll let you know.

**Comment by JanPetr** [comment]
Thanks!

**Comment by alexgran** [comment]
We would love to use that!

**Comment by oscarhandsome** [comment]
Algolia support AMP technology or not?
