### ISSUE TITLE
Hardcoded admin urls in admin_scripts.js

### ISSUE THREAD

**Issue by andrew-smart** [algolia/algoliasearch-magento#853]
The hardcoded url on https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/internals/adminhtml/admin_scripts.js#L37 means you will never see the clear queue button if you don't run under the default /admin url.

Ref: We are using v1.10.0 and Magento v1.9.3.3

**Comment by JanPetr** [comment]
Thank you for the @andrew-smart,

I'm aware of this issue. I'll deliver the fix soon. I'll keep you posted.

**Comment by JanPetr** [comment]
Hey @andrew-dwyer,
the fix is in #854, feel free to give it a try. Any feedback appreciated :) Thanks! :)
