### ISSUE TITLE
Category Replacement is not working

### ISSUE THREAD

**Issue by akshoysaha** [algolia/algoliasearch-magento#855]
We are using v1.10 of Algolia extension on Magento 1.9.2.4. We have "Replace Category" set to yes. But when we are on category page we cannot see "selected filter" option - see http://bit.ly/2skBj6O, however the category page shows the correct product.

**Instant search is not working from any category page when "replace category" is enabled.** Start typing on search box returns all products.

When clicking on any attribute, 2 consecutive AJAX call happens - 1st fetched the filtered list and 2nd calls the all product list. Hence the facet search is not working. 

After using the facet search, the URL we see on browser, returns 404 if we use the same in another window.

Also when on child (2nd) level category Ovens > Built-In Wall Gas Ovens http://bit.ly/2sJPX86,  we are getting some error in algoliabundle js library.

Instant search (on typing search box) works fine with all facets and filters from homepage or only when we have replace category set to no.

Thanks

**Comment by JanPetr** [comment]
Hello @akshoysaha,

I remember we discussed the issue with you on Algolia support and if I recall correctly you managed to fix it?
I'm closing the issue now, but if you still experience any problems, feel free to reopen.
