### ISSUE TITLE
No prices or images are visible with the autocomplete after 1.10.0 update

### ISSUE THREAD

**Issue by maaxxicarvalho** [algolia/algoliasearch-magento#858]
After applying the 1.10.0 I can only see the product name on the autocomplete search results, no prices or images are visible.

**Comment by alexgran** [comment]
I have this behaviour when I have customer groups enabled. When I disable it, stuff shows up.
Not that this is a usable workaround, but might direct someone to a solution.

**Comment by JanPetr** [comment]
Hello, this is due to a bug with retrievable attributes. It's fixed in #856, feel free to apply the code.
