### ISSUE TITLE
Extension breaks cataloging even when disabled.

### ISSUE THREAD

**Issue by alexkoepke** [algolia/algoliasearch-magento#860]
If you install the extension and do not have the Algolia credentials, the extension will break your site/prevent you from cataloging and cannot be disabled via `system > configuration > Advanced > Disable Modules Output > Algolia_Algoliasearch`.

The following is the error given when trying to catalog with the extension "disabled":
![75e5bc47-1a93-44ca-a293-acb93362f54a](https://user-images.githubusercontent.com/4930741/27637636-6d9337fe-5bde-11e7-9550-91e0ef7ba62e.jpg)

The following does not disable the extension:
![image](https://user-images.githubusercontent.com/4930741/27637680-92101322-5bde-11e7-8596-bb801ecef069.png)

**Comment by JanPetr** [comment]
Good catch @alexkoepke,
I will take a look at that and come back to you.

**Comment by JanPetr** [comment]
Hey @alexkoepke,

I fixed that in #866, feel free to give it a try.
Now when you disable the extension no indexing will be performed and no error will be thrown.

**Comment by alex-koepke** [comment]
Awesome! Thanks @JanPetr!
I'll check it out soon.

**Comment by JanPetr** [comment]
It'll be part of the next version
