### ISSUE TITLE
Development mode switcher in admin area

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#861]
Please add development switcher right into Algolia configuration tab at magento admin. Sometimes we need to make tweaks to css etc - and searching for development mode in the files is not convenient

thanks

**Comment by JanPetr** [comment]
Hello @tomekjordan,

do you mean the switch for [autocomplete's `debug: true/false`](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/autocomplete.js#L71)?
That definitely makes sense.

**Comment by tomekjordan** [comment]
yes, because very often devs needs to change somethin and check behavior for instant search block on multiple devices - like IPAD. so its easier to switch on debug via Magento panel than digging into files
thanks

**Comment by JanPetr** [comment]
Hello @tomekjordan,
it's implemented in #865, feel free to give it a try. I'll be happy for any feedback.

**Comment by JanPetr** [comment]
Will be part of the next version.
