### ISSUE TITLE
plan exhausted - default Magento searching should work

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#862]
HI. right now when Algolia plan is exhausted it stops. no searching is posssible at the store.
but why not to switch back automatically to default Magento search feature.

thanks

**Comment by JanPetr** [comment]
Hello @tomekjordan,

that's good idea. However currently Algolia doesn't have an API endpoint which would tell that the plan is exhausted.
So the extension would have to perform a "dummy" query every time the page is refreshed to see if the query returns results or not. And then display either default search functionality or the Algolia one.
But this approach would mean a huge overload to operations quota and would add another overhead to generation of the page.

So probably it's something we won't implement anytime soon.
