### ISSUE TITLE
Website specific categories are shown on other websites

### ISSUE THREAD

**Issue by maximbaibakov** [algolia/algoliasearch-magento#863]
Hi there,

We have multi website setup (3 websites).
Each of the website has own category tree (3 root categories). Some of the categories have the same name. 

When we are doing search on 1 website, we are observing categories (with the same name) from another website.

I had a look on in Indices in Algolia backend and noticed that website Indice contains records from other 2 websites.

Is there known bug / any suggestions?

Regards,
Maxim

**Comment by maximbaibakov** [comment]
Sorry, it is related to M2, created a new ticket in correct place: https://github.com/algolia/algoliasearch-magento-2/issues/275

**Comment by JanPetr** [comment]
Thanks @maximbaibakov for opening the issue on M2 repo. I'll close this one.
