### ISSUE TITLE
JS Error in Backend 🔥 

### ISSUE THREAD

**Issue by paul-siteway** [algolia/algoliasearch-magento#864]
With this Configuration:
System>Configuration>Advanced>Developer>Javascript Settings: Merge Javascript Files: Yes

Causes the Magento Backend to throw JS errors in the Algolia Konfiguration Section: 

![image](https://user-images.githubusercontent.com/3603487/27797907-a4e46342-600f-11e7-9e3b-955e9827024e.png)

Algolia Extention Version: 1.10.0
Magneto Version 1.8.1.0

**Comment by JanPetr** [comment]
Hello @paul-siteway,

I was not able to reproduce with the latest version. Do you still experience the issue?
