### ISSUE TITLE
CMS Page Synchronisation

### ISSUE THREAD

**Issue by andrew-smart** [algolia/algoliasearch-magento#867]
CMS pages are not synced on save like products are meaning you have to rebuild all of the page index each time manually. There is a function defined in the Observer.php called rebuildPageIndex along with a few others. Could that not be fired on cms_page_save_before?

**Comment by JanPetr** [comment]
Hello @andrew-smart,

that's true. The extension currently doesn't have defined listener on `cms_page_save_before`. Neither it has defined a way how reindex only one page.
But it's definitely something what can be improved. Let's keep the issue open and I'll let you know when we have something.
Or if you want, feel free to send a PR. I'll be more than happy to review 💯
