### ISSUE TITLE
Images not generated correctly when using  module "Netzarbeiter_NicerImageNames"

### ISSUE THREAD

**Issue by paul-siteway** [algolia/algoliasearch-magento#871]
We have a shop that has the Extention Nicer-Image-Names installed: 
https://github.com/Vinai/nicer-image-names/

When this module is active Algolia product indexer does not generate images correctly anymore:

![image](https://user-images.githubusercontent.com/3603487/27913225-b850e1a6-625f-11e7-94e3-e769a7fee53d.png)

Is there a way around this issue?

**Comment by JanPetr** [comment]
Hello @paul-siteway,

thanks for the report. The extension is not tested to run with this extension, however the extension gets the image URL directly from Magento's ImageHelper (https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L786-L830).

Workaround for you might be to hook your code to [`algolia_after_create_product_object` event](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L981) and fix the image URL in your code. Would that be doable for you?

**Comment by paul-siteway** [comment]
From the top of my head, i don't have any idea on how to tackle this. 

What's working for me is at the moment is disabling the _nicer-image-names_ extension while the Algolia indexer is running.
