### ISSUE TITLE
Make "Refined category is now shown in Current refinements section on replaced category page" configurable

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#872]
In 1.8.1 https://github.com/algolia/algoliasearch-magento/pull/725 fixes https://github.com/algolia/algoliasearch-magento/issues/681 but our clients don't want that. For now I'm reverting that pull request in our projects but it would be nice if this is configurable from the backend in the next version.

**Comment by JanPetr** [comment]
Good idea @royduin,
I got that feedback from multiple sides.

However ... When you land on a category page now and then use the top search - what do you and your customers expect to search at? Whole catalog or the particular category?

**Comment by royduin** [comment]
As it worked before; just in the category. So the searchbox in the headers searches the whole site the, the searchbox on a category just searches in the category currently in.

**Comment by royduin** [comment]
Any updates on this one? 👼 when updaten Algolia I've to revert this part each time

**Comment by JanPetr** [comment]
Hello @royduin,
would you mind sending a PR with the change you have to revert each time? It'd help me to implement it.

Thanks!

**Comment by royduin** [comment]
The inverse of: https://github.com/algolia/algoliasearch-magento/pull/725/files ;)

**Comment by royduin** [comment]
Any ETA on this @JanPetr?

**Comment by JanPetr** [comment]
Not for now, sorry :(

**Comment by damcou** [comment]
Added to the features list in our roadmap.
