### ISSUE TITLE
Added new magento-website/store view - algolia shows empty instant results

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#875]
HI. I just added 3rd website to my store, different domain.
The problem is that algolia is not giving any results - it shows empty autocomplete/instant search block.
The only difference from 2nd website - which works is that 3rd website view inherits category from 1st and global website. But 2nd website have its own category structure.
Some categories are disabled on this store view - but it should not affect results.
Indexing is done, every options in Algolia are inherited from global - and I dont know why 2nd website view works while 3rd is not. 
Cannot find any other differencies in config except - inherited categories and some categories are disabled.
+ there are canonical URLS to global scope domain - but Algolia is not using it.
Any option to make it work? Algolia installed 1.10.0

Category config on storeview scope
[http://prntscr.com/fvq5my](url)

Thanks for help!
Tomek

**Comment by JanPetr** [comment]
Hello Tomek,

sorry for the late answer. I wasn't online for a while.
I'll investigate your issue and come back to you. Thank you for all the information provided.

**Comment by tomekjordan** [comment]
Cool, when I added separate root category to this website searching works. but if backend has shared products adding extra root cateories is not the best solution. its multiplication for everything

**Comment by JanPetr** [comment]
Hello @tomekjordan,

I just tested it, tried to reproduce your environment and managed to reproduce the issue when nothing was indexed.
But then I realized that I didn't assign products to the new website:
<img width="265" alt="screenshot 2017-08-14 17 12 25" src="https://user-images.githubusercontent.com/1058144/29297154-ccb664d6-8113-11e7-8e78-a33652fc651c.png">

When I assigned a product to the new website, all indexing worked as expected.

Any chance it's the same issue what happened to you?

**Comment by tomekjordan** [comment]
Its not the same
1. I had products assigned to all websites
2. root category was inherited from global to website - and thats why it doesnt work, I needed to add new root category and subcategories tree to this 2nd website and them Algolia started
to provide results
But this is just not good, when you need to duplicate categories for other websites -
while you can just share them
among websites

**Comment by JanPetr** [comment]
I understand that Tomek, I created the same setup. My other website shares the same root category as my primary store and all indexing works as expected.

**My store setup:**
<img width="1404" alt="screenshot 2017-08-15 15 52 43" src="https://user-images.githubusercontent.com/1058144/29340077-1b455238-81d2-11e7-956b-0623561e7350.png">

**Category trees:**

Default / English:
<img width="240" alt="screenshot 2017-08-15 15 53 54" src="https://user-images.githubusercontent.com/1058144/29340052-020c9312-81d2-11e7-8eae-2f150624945f.png">

Olala:
<img width="227" alt="screenshot 2017-08-15 15 54 05" src="https://user-images.githubusercontent.com/1058144/29340082-233eaa84-81d2-11e7-9f39-a7b9e5ee828d.png">

Did I miss something in my setup?

**Comment by rudissaar** [comment]
after creating 2nd view for my store, none of my things get saved, what might be the problem? is it related to this issue?

**Comment by JanPetr** [comment]
Hello, probably not. Could you create a new issue with more details @rudissaar? Like what is not saved etc ... Thank you!

I'm closing the issue @tomekjordan as I didn't hear from you. Feel free to re-open if you still experience the issue 💯
