### ISSUE TITLE
Algolia index went to dead loop.

### ISSUE THREAD

**Issue by Adel-Magebinary** [algolia/algoliasearch-magento#878]
Hi guys,

Just a quick bug report here. The indexer dies when manually trigger the reindex. 

Product Attributes index was rebuilt successfully in 00:00:00
Product Prices index was rebuilt successfully in 00:00:01
Catalog URL Rewrites index was rebuilt successfully in 00:00:06
Category Products index was rebuilt successfully in 00:00:00
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/live/app/code/core/Mage/Catalog/Model/Product.php on line 2019
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

**Comment by JanPetr** [comment]
Hey @Adel-Magebinary,

thanks for the report! Can I ask you what version of Magento do you use and how many products do you have (try to index)?

**Comment by Adel-Magebinary** [comment]
@JanPetr We are running 1.9.3.2

**Comment by JanPetr** [comment]
And how many products do you have? Can you enable [indexing queue](https://community.algolia.com/magento/doc/m1/indexing/#general-information)?

**Comment by JanPetr** [comment]
Since I didn't hear from you for a while @Adel-Magebinary I'm closing the issue.
If you still experience troubles feel free to reopen.
