### ISSUE TITLE
admin URL referenced in JavaScript

### ISSUE THREAD

**Issue by 3Dgoo** [algolia/algoliasearch-magento#879]
In the `admin_scripts.js` file there are a few references to the `admin` url: 
https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/internals/adminhtml/admin_scripts.js#L37

This won't work if the Magento instance has a different admin URL.

**Comment by JanPetr** [comment]
Hello @3Dgoo,

thank you for the report! 💯 
The issue was solved in #854, and it'll be released in the next two weeks.
