### ISSUE TITLE
Analytics Search - _empty_

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#880]
Hey @JanPetr , we have enabled analytics for search and it works fine. 
But when I'm looking to analytics report, I can see _empty_ value - http://i.imgur.com/XJsaQqB.jpg

Do you know what does it mean? Is that when pages just loaded without any search?

**Comment by JanPetr** [comment]
Hello @Mobecls,

it happens when you hit "Enter" in searchbox, but the searchbox is empty. So the searchpage is loaded with `?q=__empty__`.
Is that issue for you? Can you filter it out in GA?

**Comment by JanPetr** [comment]
Do you have enabled "Trigger the push function after the initial search"?
<img width="627" alt="screenshot 2017-07-31 10 04 00" src="https://user-images.githubusercontent.com/1058144/28768353-9b7df736-75d7-11e7-9bc9-762274b7fd77.png">

**Comment by Mobecls** [comment]
@JanPetr  and do we have to enable it or disable - to get rid of _empty_? 
We have it set to "No". It takes 1.7% of all our searches... seems a a lot as it takes 3rd place in overall chart of the most popular searches.
