### ISSUE TITLE
Records quota exceeded

### ISSUE THREAD

**Issue by maximgubar** [algolia/algoliasearch-magento#884]
I'm not sure that this is the right place to submit this issue, but anyway.

I've had a trial plan, there was approx 30k records in it, now trial has ended and it switched me to community plan. and since I have to many records, it requires to switch the plan. I've tried to go to the records management and just drop most of them, but page is not working(see screenshot).

![screenshot 2017-08-04 09 35 09](https://user-images.githubusercontent.com/2241775/28959395-8f215764-78fa-11e7-95b6-3ea6a411a26a.png)

Could you please suggest how to solve this issue ?

Regards,

**Comment by JanPetr** [comment]
Hello Maxime,

I checked and you application wasn't moved to a free plan, but it was blocked. As you have more than 10k records (free plan limit), we couldn't move you automatically.

There are two ways how to solve the issue:

1. You can select a paid plan, update billing information and you'll be unblocked automatically
2. You can give me access to your account [here](https://www.algolia.com/users/edit#?tab=access-control), tell me what indices I can clear (so you'll get below 10k records) and I'll unblock your application

Tell me what fits best for you.
