### ISSUE TITLE
algoliaAnalyticsPushFunction doesn't fire on non-instant search pages with search bar

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#885]
We are currently using Algolia with instant search pages disabled. We still want to track searches through Google Analytics. It appears as though this module only fires off search events when its on an instantsearch page. I need to gather analytics from any page on the site when the search bar is present.

**Comment by JanPetr** [comment]
Hey @greatwitenorth,

the analytics feature is intended to work only on instant search pages and is tied to instant search feature. That makes sense for me as the instant search page re-renders completely on search and it's worth to track it as search page views in analytics tools.

What you're saying is that you want to track what people are searching for even on autocomplete menu?

**Comment by greatwitenorth** [comment]
Correct. I think most people would want search term analytics on both the autocomplete search bar and the instant search results. Is this possible?

**Comment by greatwitenorth** [comment]
I see that this was closed, but I'm wondering why GA is still only limited to the instant search results page. Having the analytics from our site's search bar would be valuable information.
