### ISSUE TITLE
An error occurred while saving this configuration: Invalid CustomRanking function(()), you should use asc() or desc() near line:1 column:48

### ISSUE THREAD

**Issue by u12206050** [algolia/algoliasearch-magento#889]
On clicking SAVE in the settings, I get the following error:
`An error occurred while saving this configuration: Invalid CustomRanking function(()), you should use asc() or desc() near line:1 column:48`
It does seem like the settings are saved but when trying to index Algolia, I also get:
`There was a problem with reindexing process.`

This started happening after I updated from 1.7.2 to 1.10.0

**Comment by JanPetr** [comment]
Hello @u12206050,

can you share with me a screenshot with Ranking configuration for both Products and Categories?

**Comment by u12206050** [comment]
I have none specified. Should I

**Comment by JanPetr** [comment]
If you don't have specifies any it should be OK.
Anyway, can you please specify at least one attribute for each ranking to see if it keeps happening?

**Comment by u12206050** [comment]
Hi, Sorry for the delay.

I can't seem to select attributes at all. This is quite strange since in another magento instance with "Exactly" the same Algolia code, I can see that I am suppose to have dropdown selects to select attribute. See attached image:
![screenshot](https://user-images.githubusercontent.com/6641242/29609009-26d7c57a-87f6-11e7-9475-2132564c68e4.png)

**Comment by u12206050** [comment]
Products have the same issue.

![screenshot1](https://user-images.githubusercontent.com/6641242/29609105-71186464-87f6-11e7-9f11-7e7dd6b804cc.png)

**Comment by u12206050** [comment]
Found the issue. Even though the plugin showed up etc. It wasn't activated under the Plugins list. Such a simple mistake on my my part. Hope it helps anyone else :)

**Comment by JanPetr** [comment]
Thanks for keeping it updated and I'm happy you made it work 💯
