### ISSUE TITLE
catalogsearch_fulltext table isn't getting updated anymore?

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#890]
We've got a shop with 3 stores, 2 of them are using Algolia and the 3th one is using the default Magento search. I noticed that the `catalogsearch_fulltext` table wasn't updated for a while (after the customer complained about new products not showing up in the search) so I've truncated the table, ran all indexes and noticed the table was still empty. When I disable Algolia completely and running the indexes the table gets filled again.

The shop is running on 1.8.0 with this fix applied: https://github.com/algolia/algoliasearch-magento/pull/742. I just updated to 1.10.0 just to test the index but the same issue.

**Comment by royduin** [comment]
I think we'll have to implement something like this: https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext.php#L114:L121 here: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext.php#L46:L48 and maybe on some other places where Algolia is overwriting core functions.

**Comment by JanPetr** [comment]
Hello @royduin,

nice catch. To be honest I don't have any idea why your fix doesn't work. I will take a look and investigate and come back to you what I have something.
Let me know if you'll manage to find a fix sooner.
