### ISSUE TITLE
Not displaying 0 product categories.

### ISSUE THREAD

**Issue by timothyCoxon** [algolia/algoliasearch-magento#891]
We have one site in our Magento install that we have used categories for a hierarchal CMS system, for which none have products associated with them. 
Is there a way to force this extension to index and display these categories?

**Comment by JanPetr** [comment]
Hello @timothyCoxon,

it's true that those categories are not indexed.
The solution for you would be to comment out this code: https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Data.php#L414-L416

Or better - you can hook your code to [`algolia_after_create_category_object` event](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Categoryhelper.php#L202) and set `product_count` attribute to `1`. So the category is indexed.

Would that work for you?
