### ISSUE TITLE
Autocomplete not working since update!

### ISSUE THREAD

**Issue by quadrophenianl** [algolia/algoliasearch-magento#899]
Hi there,

Since I updated the Algolia search for a client, the search bar is not working anymore. If I type a few letters, nothing at all happen. Please see the screenshot also:

![1](https://user-images.githubusercontent.com/31439621/29818538-0d541a10-8cbd-11e7-8b54-485694a6f410.png)

Downgrading also didn't work anymore because of some conflicts. Is it possible to help me out?

Thanks already!

Best wishes,

Mark

**Comment by quadrophenianl** [comment]
Maybe some more information is good to know. I updated from 1.5.4 to the newest version. Everything worked like a charm before.

It is also not possible to click on the icon within the search bar.

If you need any more information, please let me know!

**Comment by JanPetr** [comment]
Hello @quadrophenianl, would you mind sharing a live website with me where I'd be able to investigate?

Thanks!

**Comment by quadrophenianl** [comment]
No problem at all!

www.esigaret4u.nl

Hope to hear soon from you! Thanks already!

**Comment by quadrophenianl** [comment]
Hi @JanPetr,

Already have a clue? As I leave for a holiday in a few days, I'll hope I can fix this problem for my client before leaving.

Take care!

Mark

**Comment by JanPetr** [comment]
Hello Mark,

thanks for sharing the website. The issue is that for some reason the front-end config is not generated to the website. This is what is generated:

```
<script>
    window.algoliaConfig = ;
</script>
```

and it should look something like this:

```
<script>
    window.algoliaConfig = {"instant":{"enabled":true,"apiKey":"ZTJmYTE0MDUwNjM3YmVhZjU1MzFhZDk3ZWZjMWU3ZDM1MjhhZjU1NzQ5MjQ3OWRhN2NhNWY2NDg4Nzg5NzhkOGZpbHRlcnM9Jm51bWVyaWNGaWx0ZXJzPXZpc2liaWxpdHlfc2VhcmNoJTNEMQ==","selector":".main","isAddToCartEnabled":true,"showStaticContent":false,"title":"","description":"","content":"","imgHtml":"","hasFacets":true},"autocomplete":{"enabled":true,"apiKey":"MzE2OGY5MzRlODUyODAyN2MwNTY1ZjU0MzM2MTJiYzNkNTQ3YTFjZjMyYWFmZjhmMmEzNjllZjc0ZjM3ODM5YmZpbHRlcnM9","selector":".algolia-search-input","sections":[{"name":"pages","label":"Pages","hitsPerPage":"2"}],"nbOfProductsSuggestions":"6","nbOfCategoriesSuggestions":"2","nbOfQueriesSuggestions":"0","displaySuggestionsCategories":true,"isDebugEnabled":false},"extensionVersion":"1.11.0","applicationId":"latency","indexName":"magento_default","facets":[{"attribute":"price","type":"slider","label":"Price"},{"attribute":"categories","type":"conjunctive","label":"Categories"},{"attribute":"color","type":"disjunctive","label":"Colors"}],"areCategoriesInFacets":true,"hitsPerPage":9,"sortingIndices":[{"attribute":"price","sort":"asc","label":"Lowest price","name":"magento_default_products_price_default_asc"},{"attribute":"price","sort":"desc","label":"Highest price","name":"magento_default_products_price_default_desc"},{"attribute":"created_at","sort":"desc","label":"Newest first","name":"magento_default_products_created_at_desc"}],"isSearchPage":false,"isCategoryPage":false,"removeBranding":false,"priceKey":".USD.default","currencyCode":"USD","currencySymbol":"$","maxValuesPerFacet":10,"autofocus":true,"analytics":{"enabled":false,"delay":3000,"triggerOnUIInteraction":true,"pushInitialSearch":false},"request":{"query":"","refinementKey":"","refinementValue":"","path":"","level":"","formKey":"jPLX4h09XIv8mCdC"},"showCatsNotIncludedInNavigation":false,"showSuggestionsOnNoResultsPage":true,"baseUrl":"https:\/\/magento.algolia.com","popularQueries":[],"useAdaptiveImage":false,"urls":{"logo":"https:\/\/magento.algolia.com\/skin\/frontend\/base\/default\/algoliasearch\/search-by-algolia.svg"},"translations":{"to":"to","or":"or","go":"Go","in":"in","popularQueries":"You can try one of the popular search queries","seeAll":"See all products","allDepartments":"All departments","seeIn":"See products in","orIn":"or in","noProducts":"No products for query","noResults":"No results","refine":"Refine","selectedFilters":"Selected Filters","clearAll":"Clear all","previousPage":"Previous page","nextPage":"Next page","searchFor":"Search for products","relevance":"Relevance","categories":"Categories","products":"Products","searchBy":"Search by"}};
</script>
```

Would you be able to check in [configuration.phtml file](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml#L285) why the JSON is not returned to your page?

**Comment by quadrophenianl** [comment]
Hi @JanPetr ,

The config file looks fine, actually it has the same content as the one you were linking to. Any other idea wat possibly could be wrong? 

Best wishes,

Mark

**Comment by quadrophenianl** [comment]
![image 3](https://user-images.githubusercontent.com/31439621/29868150-2576e156-8d7e-11e7-84da-eb1a2a2ef1a7.png)

**Comment by quadrophenianl** [comment]
The unexpected token from above directed to the script line in the config file... Strange.

**Comment by JanPetr** [comment]
Yes, the issues from console are generated by "not-generated" config.
Can you explore in the code why it's not echoing the JSON configuration?

**Comment by quadrophenianl** [comment]
Hi @JanPetr,

In tried loads of things, but it's impossible to get it work. Can you give me more hints where to look?

Thanks!

Best wishes,

Mark

**Comment by JanPetr** [comment]
You need to look to the line I linked. The JSON is not printed to website and I have no clue why. Can you investigate there and see why it comes out empty?

**Comment by quadrophenianl** [comment]
As I got stuckin my investigation I uninstalled the plugin and deleted all entries in PHPMyAdmin. Afterwards I installed version 1.5.4 again as this was working like a charm. But now I get the following error:

An error occurred while saving this configuration: You cannot specify "attributesToIndex" and "searchableAttributes" at the same time. "attributesToIndex" is deprecated you should only use "searchableAttributes" near line:1 column:846 

Any clue?

**Comment by JanPetr** [comment]
Yes, there was a change in Algolia API where we changed the name of `attributesToIndex` setting to `searchableAttributes`. Both versions are supported, but it cannot be mixed. 
If you once set `searchableAttributes` setting to Algolia (via dashboard or via newer version of the extension), you won't be able to use `searchableAttributes` again. 
The newer version of extension have a mechanism to solve that, but version 1.5.4 was released before the change so it cannot handle it properly.

I'd recommend you to update to the latest version (today I released 1.11.0), it should work. And if it still have the same issue with configuration, can you go through your logs and try to find any config related error? It looks like the json_encode function is not handled properly.

**Comment by quadrophenianl** [comment]
Hi @JanPetr,

Unfortunately, I can't find the problem where it goes wrong. I guess it's time to find an alternative search bar. Pretty frustrating as this one is perfect.

Isn't it possible that this is because I'm running on a Hypernode server on Nginx?

**Comment by JanPetr** [comment]
Hello @quadrophenianl,

Sorry for the late answer. No, it shouldn't be an issue.
Does it still not working for you?

**Comment by quadrophenianl** [comment]
Hi @JanPetr,

Unfortunately, it still doesn't work and I was forced to use another search engine. Anyway, thanks for your help troughout this problem!

Take care!

Mark
