### ISSUE TITLE
Catalogsearch_Fulltext no longer indexes properly

### ISSUE THREAD

**Issue by MDowdal** [algolia/algoliasearch-magento#90]
This has been happening since 1.13 and 1.14, but My catalogsearch no longer indexes.  Also, search queries launched outside of algolia through /catalogsearch/ are resulting in a PDOStatement.  

http://www.factorydirectfilters.com/catalogsearch/result/?q=16+x+28+x+6

Any ideas?

**Comment by maxiloc** [comment]
Yes I fixed the issue. The fix will be available in the next release. In the meantime you can fix it on your instance like this commit https://github.com/algolia/algoliasearch-magento/commit/e989359b14e0eff6730e64d36768cb272770d117

**Comment by maxiloc** [comment]
Hi @MDowdal.

We are gonna remove the support for this functionality. It confusing for most of the users, and we want it to be as simple as possible. Installing the extension will enable indexing and search on Algolia by default and disable the magento one.

Next release will have a basic instant search available so it makes even more sense.

In case you still want to index catalogsearch. You will need to edit the plugin.

**Comment by MDowdal** [comment]
I'm experiencing an issue I was seeing when I opened this case.  http://www.factorydirectfilters.com/catalogsearch/result/?q=16x20x1 results in a SQL dump page, which stopped when you fixed the issue before.  Any thoughts?

**Comment by maxiloc** [comment]
I am not able to reproduce your issue. But we will release the new version in a few days that should fix your issue.
