### ISSUE TITLE
Magento Connect not yet updated to 1.11.0

### ISSUE THREAD

**Issue by alexbogias** [algolia/algoliasearch-magento#900]
I received the notification in configuration page but when i tried to install it to the latest version I keep getting that 1.10.0 is the latest
![screenshot-2017-8-30 magento downloader](https://user-images.githubusercontent.com/1313467/29866382-e95f60aa-8d80-11e7-8484-e6d4f2a32366.png)

**Comment by JanPetr** [comment]
Hey @alexbogias,

it looks like Magento Connect has some issues with updating. I uploaded the [new version](https://www.magentocommerce.com/magento-connect/search-algolia-search.html) to Connect before it was tagged on GitHub.

<img width="1016" alt="screenshot 2017-08-30 12 45 47" src="https://user-images.githubusercontent.com/1058144/29868935-2bbb846a-8d81-11e7-9cd7-1978a917fd26.png">

**Comment by alexbogias** [comment]
Yeah i show this already. I knew that connect has some updating issues. They are closing it anyway. I just wanted to let you know. Thanks a lot @JanPetr for your great job on this extension.

**Comment by JanPetr** [comment]
Thanks for the kind words! 
We are already in process of putting the extension on Magento Marketplace, it should be there very soon.

**Comment by alexbogias** [comment]
Sorry for commenting again but while now magento connect updated the new version I am getting another error. I know that I am able to install it manually but I just want to inform you.

![magento-downloader-algolia-version-bug](https://user-images.githubusercontent.com/1313467/30015071-d288ab40-9157-11e7-8d8a-16ceb5a27607.png)

**Comment by alexbogias** [comment]
@JanPetr Can you please reopen this and check?
