### ISSUE TITLE
Some product attributes do not go back in the ajax query

### ISSUE THREAD

**Issue by magegirl** [algolia/algoliasearch-magento#901]
I upgraded from version 1.6 to the latest.
I use the event algolia_product_index_before and therefore I add 2 data that are not attributes qty_increments and has_qty_increment.
I find them well in the index algolia but they are not reassembled via the ajax query.
Do you have an idea ?
Thanks

**Comment by JanPetr** [comment]
Hello,

most probably those attributes are not included in [`attributesToRetrieve` parameter](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml#L160-L165) of the secured API key.

Can you use [`algolia_after_create_configuration` event](https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/template/algoliasearch/internals/configuration.phtml#L281) to pass the API key with those attributes included in attributesToRetrieve?

**Comment by magegirl** [comment]
Thanks I will try on

**Comment by magegirl** [comment]
@JanPetr Not even by including them it does not work.

**Comment by magegirl** [comment]
@JanPetr Not even by including them it does not work.
