### ISSUE TITLE
weirdness on apple devices - have to click search results twice to go to a page

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#902]
I'm running into an issue with the latest version 1.11 - I updated my dev site this morning. But this also happens on algolia's test site - https://magento.algolia.com/ - so I'll show you how to recreate it there.

Go to that test site on an iPhone or iPad. Search for something, like _pants_, and the autocomplete dropdown will show up. Try clicking on one of the results.

The first click with select the result (so you'll get the gray this-item-selected background), and the second click will actually go to the result.

And the problem is _only_ on apple devices - We've got iPhones (mostly 7s) and an 1st gen iPad, and it's the same behavior on all of them. It doesn't happen at all on our android devices (a wide variety of phone versions and tablets)

Also, I've got 1.8 in a production environment, and the issue doesn't happen there.

**Comment by JanPetr** [comment]
Hello @sam327,

thank you for the report! I managed to re-produce. I'll target the issue soon and will let you know when I have fix for that.

**Comment by Haroenv** [comment]
This is because it has a `:hover` style, when you have that the first tap will apply the hover style, the second to actually apply the click.

**Comment by martinconnelly** [comment]
Has there been any movement on this? We'd like to update, but can't really can't with this broken.

**Comment by sam327** [comment]
While you're working on this - Is there some sort of dirty hack that might get this to a working state? 

I blew a couple hours trying a handful of things, such as commenting out all instances of :hover in the CSS file - which didn't work. 

Client is fine with launching with a "no hovers" behavior, but not with the "having to click twice" behavior.

I'm not using modernizr, would that be worth trying?
