### ISSUE TITLE
Images-only reindexer 

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#904]
I saw issue #704 and wanted to add a similar suggestion. If you're considering an index function to just do specific components, it'd be nice to have one to do just images.

I run into a particular annoyance on sites that use a CDN - When I go to the Cache Management and hit the "Clear Catalog Images Cache," it breaks all the images in the algolia search. And they won't fix themselves until I reindex all the algolia products. 

This isn't exactly unexpected. But it takes a little bit for the reindex to get through everything. Using the queue, it can be 15-30 min before it fixes all the images.

**Comment by JanPetr** [comment]
Hello @sam327,

thanks for the suggestion. It makes sense to do a "simple" images-only indexer. I'll will investigate what are our options here and see how much resources could this indexer save.
I'll keep you posted.

**Comment by damcou** [comment]
Added to the features list in our roadmap.
