### ISSUE TITLE
Some links to documentation in backoffice gives 404 error

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#909]
Hi there,

When I click on a link to Algolia Search Documentation via the backoffice of Magento 1.9 i get a 404 error. 

I use Algolia Search Version 1.11.0

**Synonyms:**

- https://www.algolia.com/doc/synonyms
- https://www.algolia.com/doc/synonyms#synonyms
- https://www.algolia.com/doc/synonyms#one-way-synonyms

**Advanced:**

- https://www.algolia.com/doc/api-client/default/settings/#index-settings-parameters

Thanks for the awesome extension!

**Comment by JanPetr** [comment]
Thanks for the report @HRR1337! 💯 

We'll change the links and will try to add redirects for the current ones. I'll let you know when it's done.

**Comment by JanPetr** [comment]
The redirects are live!
