### ISSUE TITLE
Disable some CMS pages from being indexed and shown in autocomplete

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#910]
Hi there,

We make alot of 'test' cms pages, or 'work in progress' cms pages. And now they are also indexed by the engine. It would be nice if there is an option to disable some CMS pages (by id?) to be indexed so it wont show up in the autocomplete. 

Or is it already here and am I missing something?

Thanks!

**Comment by JanPetr** [comment]
Hello @HRR1337,

yes, this is already in place. You can remove pages with this configuration:
<img width="705" alt="screenshot 2017-09-13 10 49 05" src="https://user-images.githubusercontent.com/1058144/30368360-390e23d4-9871-11e7-91a9-74b35fabf327.png">

You can exclude as many pages as I'd like.

**Comment by HRR1337** [comment]
Thanks! Totally overlooked it!

**Comment by JanPetr** [comment]
You're welcome, happy searching!
