### ISSUE TITLE
Incosistent indexing?

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#911]
Hello,

At this moment i'm testing Algolia Search on a dev domainname. So I'm changing configurations etc. And I know that when I change some configurations, I have to do a reindex.

The issue is, I dont know why the changes I made are not most of the time NOT visible even when I do a reindex on my queue. I only get: Algolia Search Queue Runner index was rebuilt successfully in 00:00:00

Example: 
Adding / modifying facets. 
Removing Ranking (price) for example. 

Can you please clarify if this is a feature/bug or that i'm just doing something wrong.

Thanks,

HRR

**Comment by JanPetr** [comment]
Hello @HRR1337,

did you reindex Products indexer before you run the queue indexer? If you won't run products indexer, queue won't do anything as there are no jobs in the queue.

**Comment by HRR1337** [comment]
let me try if this is the case :-)

**Comment by JanPetr** [comment]
Hello @HRR1337, does it work for you?

I'm closing the issue now. Feel free to re-open if you still experience the issue 💯
