### ISSUE TITLE
Hit template price and currency

### ISSUE THREAD

**Issue by rudissaar** [algolia/algoliasearch-magento#923]
Is it possible to have price and currency inside separate elements?

I would like to use different color for currency, but everything is inside same span.

**Comment by rudissaar** [comment]
I can see that algolia result include price_default and price_formatted, but maybe default package also should include formatted one without currency.

**Comment by JanPetr** [comment]
Hello @rudissaar,

currently it's not split, you're right.
You can split it manually by [transforming data on frontend](https://community.algolia.com/magento/doc/m1/frontend-events/) or by changing the way how data are indexed by using [backend events](https://community.algolia.com/magento/doc/m1/backend/).

Would that work for you? 

If you want to send PR to index price and currency separately, I'll be more than happy to review and merge! Thanks!
