### ISSUE TITLE
queued shell reindexing fails due to missing 'algoliasearch_queue_log' db table

### ISSUE THREAD

**Issue by weixelbaumer** [algolia/algoliasearch-magento#925]
Latest version of Magento **1.9.3.6** using latest version of Algoliasearch module **1.11.1**.
Re-running setup scripts won't help .. Queued indexing via 

`php -f /home/web/magento/shell/indexer.php -- -reindex algolia_queue_runner` 
fails and leads to following error message:

`PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table '_dev.algoliasearch_queue_log' doesn't exist in /home/web/magento/lib/Zend/Db/Statement/Pdo.php:228`

Switching off logging (within algolia config) doesn't help either.

**Comment by JanPetr** [comment]
Hello @weixelbaumer,

there is an issue with setup scripts for some reason :/ We are working on the fix.

In a meanwhile, can you apply [this fix](https://github.com/algolia/algoliasearch-magento/issues/918#issuecomment-330801701)? 

Let me know if it works for you.

**Comment by weixelbaumer** [comment]
Works just fine! Thanks for the quick support!

**Comment by weixelbaumer** [comment]
However ... it seems that no jobs are being processed. Queue is being filled up by observer .. but processed_jobs staying at 0.

![nojobsprocesse](https://user-images.githubusercontent.com/2777906/30855978-2bdec466-a2b7-11e7-8c11-a442b4fac6ab.png)

**Comment by JanPetr** [comment]
And do you have any jobs queue in `algoliasearch_queue` table? When queue is processed, but no jobs are created it still logs the run.

**Comment by weixelbaumer** [comment]
Fwiw it's a multistore setup with several thousand products per website. `algoliasearch_queue` > 5000 entries and increasing .. however in algolia backend it seems that at least tmp_ and live indexes are being updated.

**Comment by JanPetr** [comment]
Thanks for letting me know! It looks like there might be issue with counting jobs in log then. I'll investigate.
As long as Algolia indices are updated it's OK and processing is working correctly.

**Comment by JanPetr** [comment]
Will be fixed in next version

**Comment by weixelbaumer** [comment]
Indexing is NOT working fully. Many products simply don't get updatet.
Meanwhile algoliasearch_queue (>76k entries) and algoliasearch_queue_log DB tables (>5k entries) are exploding in # of entries.

**Comment by Paranoiddev** [comment]
Any solution for this?
