### ISSUE TITLE
Products are not reindexed when catalog price rules are applied

### ISSUE THREAD

**Issue by lykciv** [algolia/algoliasearch-magento#933]
Follow these steps to reproduce
* create a catalog price rule
* apply the rule
* products have a discount price on the category and product pages
* the search does not show the new price for the products

Problems
* affected products are not added to the queue for indexing
* to solve this, you could rebuild all products; however this seems overkill if the catalog price rule only applies to a couple of products
* every night the catalog price rules are reindexed; any changes during the reindex are not picked up by algolia

**Comment by JanPetr** [comment]
Hello, thank you for opening the issue! That's true, the extension currently doesn't listen on applied price rules and you have to trigger full products reindex. I'll take a look and see what can be done around this.
If you have solution for that, feel free to open a PR. I'll be more than happy to review and merge. :100:

**Comment by magegirl** [comment]
Hello,
Is it possible that the scroll automatically starts without button "show more" ?

**Comment by damcou** [comment]
Added to the features list in our roadmap.
