### ISSUE TITLE
Instant search templates and js included when it is not enabled

### ISSUE THREAD

**Issue by andrew-smart** [algolia/algoliasearch-magento#938]
Can the instantsearch.js added in the layout file...
https://github.com/algolia/algoliasearch-magento/blob/master/app/design/frontend/base/default/layout/algoliasearch.xml#L13
be removed when the instant search part of the module is not enabled. The same for the templates added specifically for the instant search.

**Comment by JanPetr** [comment]
Good idea Andrew, thanks!
I'll do that. And feel free to send a PR, I'll be more than happy to review and merge! :)
