### ISSUE TITLE
Cannot fetch items from algolia category_products index for non-default store view

### ISSUE THREAD

**Issue by maximgubar** [algolia/algoliasearch-magento#939]
I have 2 websites and each has 2 store views.
I've executed full re-index for my store already several times, and on category pages there are products only for default store, in algolia dashboard I clearly see that indexes for other stores exists and it seems that the data is correct. But anyway, all instant search ajax requests from non-default stores return empty hits. I've already submitted a ticket from algolia dashboard but there is no reaction so far.

**Comment by maximgubar** [comment]
UPD:
after debugging I've noticed that relevance sorting is the problem, for some reasons there are no problems with it on default store, but on any other store when sorting is by relevance no items are shown. If i switch to price or any other sort, then products appear.

**Comment by JanPetr** [comment]
Hello @maxigubar,

I just checked the Algolia support and didn't see your request. Is it already sorted out?

Could you tell me what is your website, please?

**Comment by maximgubar** [comment]
Hi, @JanPetr,
The issue is solved already, algolia queue was not able to save configuration. There was an issue on the algolia server, some feature was not enabled on our instances.
but now everything is fine.

**Comment by JanPetr** [comment]
Oh yes, I remember we had a call @maximgubar :) I'm glad to hear everything is fine now! Happy searching 🚀
