### ISSUE TITLE
missing table - algoliasearch_queue_log ?

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#940]
I'm attempting to update algolia (to 1.11.1) on a dev site. And when I reindex, I get an error on the index page that says "There was a problem with reindexing process."

In my exceptions.log file, it's complaining that it can't find a particular table. 

> 2017-10-23T15:33:15+00:00 DEBUG (7): Exception message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabasenamehere.algoliasearch_queue_log' doesn't exist, query was: SELECT id FROM algoliasearch_queue_log ORDER BY started DESC, id DESC LIMIT 25000, 9223372036854775807

Can you tell me what the SQL statement is that creates this table? I cannot find it.

**Comment by JanPetr** [comment]
Hello @sam327,

here you go: https://github.com/algolia/algoliasearch-magento/issues/918#issuecomment-330801701

It'll be fixed in the new version.
