### ISSUE TITLE
Un-serialization of default data broken in < 1.9.3.x with SUPEE-8788 patch

### ISSUE THREAD

**Issue by andrew-smart** [algolia/algoliasearch-magento#943]
The effect this bug has is on a fresh install of Algolia none of the default category/product attributes etc are shown in the admin.

I note a fix to get around this https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/System/Config/Backend/Serialized/Array.php#L9 but because this is a patched version and not a 1.9.3 it fails this and falls back to out the box Magento which has the same code as a 1.9.3.x

**Comment by JanPetr** [comment]
Hello Andrew, 
let me get on the same page as you - by "patched version" you mean lower Magento version than 1.9.3 with applied `SUPEE-8788` patch?

**Comment by andrew-smart** [comment]
@JanPetr That is exactly it.

**Comment by damcou** [comment]
Hi @andrew-smart ,

Hi, I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
