### ISSUE TITLE
Strange chars/coding in Autocomplete results for Pages in 1.12.0

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#950]
Hi. just update from 1.10.0 to 1.12.0 and there are some strange chars/symbols in Autocomplete > results -> PAGES > page descriptions
[http://prntscr.com/h4m91s](http://prntscr.com/h4m91s)

I have a store with Polish language - Pages titles looks ok, but description uses invalid coding or smth

Thanks for fix in next release

Tomek

**Comment by JanPetr** [comment]
Hello @tomekjordan,
thanks for the report. I'll investigate.

**Comment by JanPetr** [comment]
@tomekjordan, I pushed a fix in #957, could you give it a try?

**Comment by JanPetr** [comment]
Fixed, will be part of the next release
