### ISSUE TITLE
New CMS pages in search results - excude/include in search via CMS page directly in Meta Data tab

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#951]
Hi. I just found that very ofter pages that I create or create for tests/promos etc - appear in search results. This is a big problem - because sometimes such pages include important informations - like hidden coupons etc.
Excluding CMS pages is really hard and you always need to add them via dropdown - very inconvenient if you have couple store views and many CMS pages.
SCREENSHOT: [http://prntscr.com/h4mg85](http://prntscr.com/h4mg85)
- because you never see which pages is relate to which store (no info - just its name in dropdown).

Solution: please just add CMS > meta date > Exclude from search YES//NO
just like it is done with SEO Ultimate by Mageworx - where you can just decide to index,noindex page you are editing. 

CMS > edit page > Meta Data tab [http://prntscr.com/h4mfhk](http://prntscr.com/h4mfhk)
This will help to avoid mess and accidental showing CMS page contents.

Thanks a lot
Tomek

**Comment by JanPetr** [comment]
Hello @tomekjordan,

thanks for the suggestion. It makes sense and I'll add it to our roadmap. I cannot promise you any ETA tho. I'll keep you posted here.

**Comment by damcou** [comment]
Added to the features list in our roadmap.
