### ISSUE TITLE
DO TLD Added to all search results.

### ISSUE THREAD

**Issue by timothyCoxon** [algolia/algoliasearch-magento#952]
Bit of a weird one, and before I start hunting wanted to know if anyone has come across this before.

Basically everything is running fine expect .do tld is replacing .com on all my search results. So the search functionionality is finding www.example.com/test-page but showing the link as www.example.do/test-page.

**Comment by JanPetr** [comment]
Hello @timothyCoxon,

I've never seen this issue. The extension fetches URLs directly from Magento which uses base URLs defined in configuration. Do you have set `.com` in base URL configuration?

**Comment by timothyCoxon** [comment]
Everything was set to .com's even did a laborious search through code and DB trying to find the errant .do to no avail. 
I've since run a reindex of everything on the site and it's seeming like that has fixed the issue.

Just wanted to report this incase it occurs for anyone else.
