### ISSUE TITLE
Can I blacklist certain words from matching?

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#955]
Is there a place to black list certain words from ever matching?

I'm running into a weird error, where someone's put some styling into a description field. So, I get matches with a font name or other styling. Example: searching "velvet" matches to "helvetica"

The correct thing, obviously, is to not put styling inside the content. But I'm trying to see what my alternative options are.

**Comment by JanPetr** [comment]
Hello @sam327,

I don't thing blacklisting words is the optimal solution here as it might break your relevancy completely.
The best solution for you would be to write a small extension, hook your code to [`algolia_after_create_product_object` event](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L1006) and in the even strip tags from `description` attribute.

To strip tags you can use [`strip` method](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Helper/Entity/Helper.php#L81) of the base helper.

How to use custom events you can see in docs: https://community.algolia.com/magento/doc/m1/backend/

Would that work for you?

**Comment by sam327** [comment]
Ah. That's a good idea. I wasn't 100% sure what the best direction was with this. Thanks for the suggestion. I'll give it a go.

In the grand scheme of things, at least by how we built our stores, people shouldn't be putting in major css into a description field. I.e. this is primarily a training issue.
