### ISSUE TITLE
Algolia is trying to load some css in admin area > 404

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#966]
Hi. Algolia is trying to load some css in admin area - but the file is not provided in/adminhtml. I suspect this is css from frontend but since admin area loads files from /adminhtml it cannot be found. Algolia is not working on admin area - so it should not load the file either.

/skin/adminhtml/base/default/algoliasearch/algoliasearch.css

[http://prntscr.com/h91tdy](http://prntscr.com/h91tdy)

Best Regards
Tomek

**Comment by JanPetr** [comment]
Hello Tomek,

how did you install Algolia? Since new version, there is a CSS file in adminhtml => https://github.com/algolia/algoliasearch-magento/blob/master/skin/adminhtml/base/default/algoliasearch/algoliasearch.css

**Comment by tomekjordan** [comment]
HI. Just downloaded from github, check zip again - no adminhtml directory in it.
[http://prntscr.com/h93sdy](http://prntscr.com/h93sdy)

**Comment by JanPetr** [comment]
Yes, I found issue now /o\ Will push the fix and re-upload the archive.

**Comment by JanPetr** [comment]
@tomekjordan, feel free to download an updated package: https://github.com/algolia/algoliasearch-magento/releases/tag/1.12.0
