### ISSUE TITLE
Autocomplete disappears when a category is set to display_mode page

### ISSUE THREAD

**Issue by royduin** [algolia/algoliasearch-magento#969]
The instantsearch should not load but the autocomplete should stay. See: https://github.com/algolia/algoliasearch-magento/issues/959 and https://github.com/algolia/algoliasearch-magento/pull/960

**Comment by JanPetr** [comment]
Hello @royduin, thank you for the report.
I just tested it and I'm not able to reproduce. Would you have a link to a staging website where I could investigate?

**Comment by royduin** [comment]
Sorry, I didn't completely copied the fix to our project. Just installed the latest dev version which works great.

**Comment by JanPetr** [comment]
Thanks for letting me know! 👍
