### ISSUE TITLE
special_price_to logic

### ISSUE THREAD

**Issue by maximilianmikus** [algolia/algoliasearch-magento#974]
Hi, 

I noticed that when you index a product, and say you index it with a currently active special_price.
After this you do not touch the product. After the special_price_from/to timeframe expires, the product should be display in the autocomplete results with the normal price, since the special_price is not active anymore. This does not happen currently as far as I can tell. I have tested this with algolia 1.12.0.

If you are interessted I can look into it and add some logic to the javascript code that is responsible for rendering the autocomplete list.

kind regards, Max

**Comment by JanPetr** [comment]
Hello @maximilianmikus,

yes, you're right. The JS is not ready for that and it still displays the special price no matter what the timeframe is.
I'd really appreciate if you find some time, add the logic to JS and send PR. It'll be really cool!

Thank you!

**Comment by JanPetr** [comment]
Fixed, will be part of the next release!
Thanks @maximilianmikus 💯
