### ISSUE TITLE
Disable Instant Search on Results page

### ISSUE THREAD

**Issue by ashtonlance** [algolia/algoliasearch-magento#975]
Unless I'm overlooking it - I can't figure out a way to disable the instant search on the results page.

Could you point me in the right direction?

**Comment by JanPetr** [comment]
You can disable it in configuration:

![screenshot 2017-11-22 19 32 44](https://user-images.githubusercontent.com/1058144/33144014-01ad8a1a-cfbc-11e7-93a1-ee41b4d2814d.png)

**Comment by ashtonlance** [comment]
Disabling that setting totally breaks my layout. Is there not a way through javascript to simply stop the instant search? I want the exact page that I have now just without the instant search feature.

**Comment by JanPetr** [comment]
When you disable that, no Instant search feature is enabled and everything should look like it did before you installed Algolia.

**Comment by ashtonlance** [comment]
But I want it to look like it does with that setting enabled. Basically - the previous dev has done a lot of work with the instant search results page (style and logic wise). There's also a very important ajax call that I'm making on the widget to further narrow the results based on some Magento helpers.

Rewriting all of this isn't really a good solution as this is for a client. I realize this isn't an "issue" with the extension but something I just hoped that might have a quick solution.

**Comment by ashtonlance** [comment]
@JanPetr Got any ideas other than writing some javascript around the extension to control when search.start() runs?

**Comment by JanPetr** [comment]
What is the use case? If you need some JS to run before / after search.start(), you can use hook methods: https://community.algolia.com/magento/doc/m2/frontend-events/

**Comment by ashtonlance** [comment]
So I'm using Algolia to search my store. However, some of my products are restricted from view based on the user's location. In order to implement the restriction, I'm capturing the results JSON blob that Algoila gives, parsing it into PHP and running some checks on it and spitting it back out. This process takes 3-5 seconds.

So when I'm on the results page and I type into the search bar, the search starts immediately for every letter that I type. So what I want to do, is not have `search.start()` run until the user hits the enter key or clicks a button. I want all other functions to work as they do currently.
