### ISSUE TITLE
Dockerfile for dev purpose

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento#98]
Dockerfile specifications:
 - [x] https://github.com/alexcheng1982/docker-magento
 - [x] magento 1.9
 - [x] mysql 5.6
 - [x] phpmyadmin
 - [x] full sample data (including thumbnails)
 - [x] php.ini with enlarged limits
 - [x] modman configured with symlinks
 - [x] shared src dir to be able to edit the sources locally
 - [x] disable cache
 - [x] enable symlinks
 - [x] enable errors
 - [x] set base URI to `boot2docker ip` or equivalent
 - [x] run script with all associated environment variables

**Comment by redox** [comment]
Check also https://github.com/occitech/docker/blob/master/magento/php5.5/apache/bin/set-base-url

**Comment by redox** [comment]
@maxiloc let me know what you think about the current version. All bullet points haven't been done, but it's working fine.

**Comment by redox** [comment]
Not sure it's related to the base-url change, but the pages are now indexed with a weird URL: http://192.168.59.103/n98-magerun/reward-points (not sure why this `n98-magerun` does here :p)

**Comment by maxiloc** [comment]
Yes that expected. It is not related to magerun but to magento

**Comment by maxiloc** [comment]
Oh didn't see the all url. Yes its weird I'll have a look

**Comment by maxiloc** [comment]
@redox maybe we can host the sample data. The magento link is super slow. What do you think ?

**Comment by redox** [comment]
Sure, on it.

**Comment by maxiloc** [comment]
@redox Can we do the same for magento-1.9.1.0.tar.gz

**Comment by maxiloc** [comment]
Done with d3bba59

**Comment by maxiloc** [comment]
done with 12cbd78
