### ISSUE TITLE
Index categories with 0 products

### ISSUE THREAD

**Issue by loevgaard** [algolia/algoliasearch-magento#983]
Hi

We use algolia on [wattoo.dk](https://www.wattoo.dk/). It seems that categories with 0 products aren't indexed. Like this one for example: [LK FUGA](https://www.wattoo.dk/elartikler/lauritz-knudsen/lk-fuga).

Is there anything we can do to change this?

**Comment by JanPetr** [comment]
Hello @loevgaard,

We have a plan to add a feature to index even empty categories.
For now, you can hack it with [`algolia_after_create_category_object`](https://community.algolia.com/magento/doc/m2/backend/#algoliaaftercreatecategoryobject) event listener where you can "fake" `product_count` to be higher than 10.

**Comment by loevgaard** [comment]
Very nice @JanPetr! Thank you!

**Comment by loevgaard** [comment]
@JanPetr do you know when this commit will be included in a release? :)

**Comment by JanPetr** [comment]
Not yet, hopefully before end of January

**Comment by loevgaard** [comment]
@JanPetr Do you know when this is included in a release? It's been some months :D
