### ISSUE TITLE
Indexing no longer working

### ISSUE THREAD

**Issue by unleadedgroup** [algolia/algoliasearch-magento#986]
We have a Magento 1.9.3.7 site with Algolia that recently stopped indexing.

We noticed this because some products weren't being found in search. I've manually run the indexers, both with the queue enabled and disabled, but nothing was being added to the indexes.

I then upgraded the module to 1.13.0 (was previously on 1.10.0), and no change there.

I then finally decided to try removing the indexes and starting over, but still nothing is working.

With the queue enabled, I'm getting jobs added to the algoliasearch_queue table in the database, but when the algolia_queue_runner index is run, it just completes immediately. Nothing is pushed up to Algolia, no errors are generated, nothing is in the log files, and nothing is changed with the database tables. I just does nothing.

I'm completely at a loss as to what the issue is. Any help is appreciated to get this working again.

**Comment by tueaidup** [comment]
We're experiencing the same issues on module version 1.13.0. Magento version 1.9.0.1 on PHP7. We've tried to do the initial indexing of products, but no products are synced. The categories are synced just fine. Tried uninstalling 1.13.0 and installing 1.10.0, but the case remains the same. 

There are no errors in the log files - the cronjob generates the jobs in the database, but they are executed in 0 secs every time. The product_ids array in the data column is always empty - however I noticed that if I save a product manually from the backend, this array contains the single product id, but the product is still not synced to Algolia, and still no errors in the log file.

**Comment by Paranoiddev** [comment]
It seems that this issue is occurring on multiple websites, would be nice to get a response on this, I have upgraded, then downgraded and then truncate the queue_log and  algoliasearch_queue as well then reindexed to check if it works but it nothing has happened.

**Comment by Paranoiddev** [comment]
Do you both have multiple stores setup?

**Comment by tueaidup** [comment]
I can confirm that I have a multiple store setup. I’ve tried to disable the extension on the two other websites, but still no luck.

**Comment by Paranoiddev** [comment]
@tueaidup I have tried this and queue has started decreasing will have to check when it completely done to see if it worked, truncate algoliasearch_queue, then re-index the data after that run this command through CLI in the root folder 

EMPTY_QUEUE=1 php -f /absolute/path/to/magento/shell/indexer.php -- -reindex algolia_queue_runner 
Let me know if this helps.

**Comment by damcou** [comment]
Hi there,

I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
