### ISSUE TITLE
products not showing in autocomplete

### ISSUE THREAD

**Issue by Paranoiddev** [algolia/algoliasearch-magento#989]
Hi,
I am using magento 1.9.2.2 with algolia extension 1.13, I have updated to newest version after products stopped showing in the autocomplete but categories did, after that I reindexed everything, and then ran empty_queue=1 but the same issue remained. As this is a multi store website, it is working on one store but not the other. I have rechecked everything, but there is nothing in the log files and no error shows up in the console of browser as well.

**Comment by JanPetr** [comment]
Hello @Paranoiddev,

can you share with me your website where I could see the issue live? Thank you!

**Comment by Paranoiddev** [comment]
http://demo.thebeautyfloor.com/

Please follow this link. 

I have disabled it from the main website for now and testing it on a staging domain.

**Comment by JanPetr** [comment]
Thanks! You products indexing is not finished - you have indexed products in TMP index, but it was never moved to production for your english website. That's why you cannot see products.

Can you check if there are some jobs in indexing queue?

**Comment by Paranoiddev** [comment]
Hi, thank you for your response. 
for english index was disabled, I enabled it then re-indexed, then turncated the tables for algoliasearch_queue and re-ran the indexing and got this error below: 
Exception message: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY', query was: INSERT INTO `algoliasearch_queue` (`created`, `class`, `method`, `data`, `data_size`, `pid`) VALUES (?, ?, ?, ?, ?, ?)

This is when the table was empty.

**Comment by JanPetr** [comment]
Hello @Paranoiddev,

can you try to run `TRUNCATE algoliasearch_queue;` query and then reindex again?

**Comment by Paranoiddev** [comment]
Did it, still the same error occurred.

**Comment by JanPetr** [comment]
OK. Could you please export the structure of the table and paste it here? Thank you!

**Comment by Paranoiddev** [comment]
-- phpMyAdmin SQL Dump
-- version 4.7.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jan 04, 2018 at 01:15 AM
-- Server version: 5.6.36-82.1-log
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `thebeau9_demoCopy`
--

-- --------------------------------------------------------

--
-- Table structure for table `algoliasearch_queue_log`
--

CREATE TABLE `algoliasearch_queue_log` (
  `id` int(20) NOT NULL,
  `started` datetime NOT NULL,
  `duration` int(20) NOT NULL,
  `processed_jobs` int(11) NOT NULL,
  `with_empty_queue` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;``


-- phpMyAdmin SQL Dump
-- version 4.7.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jan 04, 2018 at 01:15 AM
-- Server version: 5.6.36-82.1-log
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `thebeau9_demoCopy`
--

-- --------------------------------------------------------

--
-- Table structure for table `algoliasearch_queue`
--

CREATE TABLE `algoliasearch_queue` (
  `job_id` int(20) NOT NULL,
  `created` datetime DEFAULT NULL,
  `pid` int(20) DEFAULT NULL,
  `class` varchar(50) NOT NULL,
  `method` varchar(50) NOT NULL,
  `data` longtext NOT NULL,
  `max_retries` int(11) NOT NULL DEFAULT '3',
  `retries` int(11) NOT NULL DEFAULT '0',
  `error_log` text NOT NULL,
  `data_size` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `algoliasearch_queue`
--
ALTER TABLE `algoliasearch_queue`
  ADD PRIMARY KEY (`job_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by damcou** [comment]
Hi @Paranoiddev , I don't know if you have still the issue. I'll close this ticket but feel free to reopen it if you're still experiencing it.
