### ISSUE TITLE
Size of AlgoliaBundle.min.js

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#998]
Hi there,

The size of the file that needs to load (algoliabundle.min.js) is in my opinion huge. I have read somewhere that its bundled also with jquery library. Is this still the case? Gziped its still 148KB (without 5xx KB). 

Question, is it possible to make this file (alot) smaller? This will improve loading speed alot!

Thanks,

HRR

**Comment by HRR1337** [comment]
To give you an example HOW big AlgoliaBundle.min.js is in comparison with the rest of my M1 javascript files i created a screenshot....

![algolia-m1](https://user-images.githubusercontent.com/4428675/35627225-90ca94a0-0698-11e8-9557-af6f3e7ff84b.jpg)

as you can see, the algolia bundle sums up the same as the rest of the js files in this screenshot. I would really like to see this improved. YES, its  the fastest search i came across and we use it with much joy, though for the sake of speed and mobile friendlyness.. please..

**Comment by royandre** [comment]
+1

**Comment by damcou** [comment]
Added to the features list in our roadmap.

**Comment by HRR1337** [comment]
Hi there, hopefully this is still on the roadmap? The size is really HUGE.. Thanks!

**Comment by 0livier** [comment]
Hi HRR1337. Yes, we're going to work on the IS integration and hopefully get noticeable improvements on the size of the output.

**Comment by HRR1337** [comment]
@0livier What exactly do you mean by IS integration? And when can we expect it ? :-)

**Comment by 0livier** [comment]
Ah, sorry for the acronym. IS is for Instant Search. But I realize this is the algoliasearch-magento repo, not the algoliasearch-magento2, which frontend will get our focus in the upcoming months. I don't think we will on this improvement on magento1 in Q3. It's still listed in our feature list and could be considered for Q4.
